### ISSUE TITLE
feature request: transclude content of all tiddlers with tag

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#121]
Title says it all.

**Comment by MaeSiuS** [comment]
unfortunately `format="wikified"` has no effect in current tiddlywiki.
Is there a way to make it work?
Cheers

**Comment by Jermolene** [comment]
Hi @MaeSiuS try `<$transclude field="description"/>` instead of `<$view field="description" format="wikified"/>`.

**Comment by sukima** [comment]
Curious, what is the technical difference between `<$transclude field="…">` and `<$view field="…" format=wikified>`?

**Comment by Jermolene** [comment]
`<$view field="…" format="wikified">` is no longer supported. It was an early inconsistency that format="wikified" was a pseudonym for transclusion. You'll notice that the remaining formats for the view widget all result in a simple string being inserted into the widget tree, not a subtree, as occurs with transclusion.

**Comment by mediacobbler** [comment]
i'm tryin to do something along these lines. been spinning my wheels for hours.. not because there's a flaw in TW per say.. it's just that i'm a janitor who thinks he can build a fusion reactor. way out of my element. 
i've got the xlxs spreadsheet importer plugin and pulling images from a folder.. so far so good. now i need to clump categories of said images into manageable segments in the hopes of creating a sort of interactive TW map  that leads to new views with each click of an icon. 
confused yet? wait there's more!
the closest i can get to achieving a sorted list of _canonical_uri's (sorting by tag) .. is to use the tag manager to get my list .. then clone that tiddler and paste the results in the new tiddler... 
i feel like there's a much simpler way to go about it and its staring me in the face. 
gonna try the above snipps you snipped and see how that works. 
I thoroughly appreciate this creation of yours/ the community.. its an addiction for me.
