### ISSUE TITLE
Double vertical scrollbar with default layout

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1282]
The default layout of TiddlyWiki gives rise to two vertical scrollbars to the right of the window:

![tiddlywiki two scrollbars in ie](https://cloud.githubusercontent.com/assets/174761/5538861/f77225b2-8ab1-11e4-8c72-f0a92c49506d.png)

Worst of all, the left hand scrollbar controls the sidebar and the right hand scrollbar controls the main story river.

The problem is not so noticeable on platforms like OS X and iPad/iPhone, where scrollbars are only rendered when in use.

**Comment by twMat** [comment]
[This demo](http://jsfiddle.net/NGLN/qndjW/6/) uses a CSS solution to make a "section specific" scrollbar only appear on hover. (ref [dicsussion](http://stackoverflow.com/questions/6887112/scroll-particular-div-contents-with-browsers-main-scrollbar?lq=1).on stackoverflow).

I like it and I think it is used (possibly by other means) in various sites such as on the google groups where the left sidebar gets a scrollbar only when hovered over.

**Comment by twMat** [comment]
[This different take](https://css-tricks.com/examples/LongDropdowns/) avoids scrollbar all together by making the list roll up as you... ah, just chkeck it out.

**Comment by sukima** [comment]
How does this work for touch devices?

**Comment by pmario** [comment]
>This different take avoids scrollbar all together by making the list roll up as you... ah, just chkeck it out.

In the early days of TW5 Jeremy did experiment with a sidebar like this. IMO with little success. I personally don't like "hidden" information. So without (the annoying) scroll bars you just don't know, that there is more info. 

I personally use a tweak for the browser (firefox) css, since I need to remove the google chrome input line at the "new tab overview" anyway. [The mechanism I use](https://support.mozilla.org/en-US/questions/957337)  ... instead of margin -14, I use margin -9. So there is still a scrollbar, but it's smaller.

I'm using this mechanism for about a year now. And it works well with "all" sites, that have a vertical scroll bar. 

The drawback is, that if you have 2 bars, on will be full size, but that's less ugly now.

**Comment by twMat** [comment]
Guys... I think this is the perfect solution:

Only have scrollbar appear if you hover over or otherwise activate the long list in question. For touch screens, I beleive the standard procedure is; touch down to activate, but then either release for clidk or swipe for scroll..
Now, to consistently have a visual indication that there is "more", i.e even when no scorllbar is visibie, use the "[fader](http://jsfiddle.net/nameanyone/3dn0qxas/)" solution (provided by @nameanyone for another issue a while back).

**Comment by pmario** [comment]
It isn't nice, and the bug is long standing, but windows users seem to be used to it. We haven't seen enough complains, to actually making the issue worth fixing it. 

So imo we should close the issue with a "wontfix" @Jermolene

**Comment by tobibeer** [comment]
I'd rather go with @twMat's [suggestion](http://jsfiddle.net/NGLN/qndjW/6/). I think it's rather elegant. There is no point to explicitly "knowing there's more" to the scrollbar. Of course there is if you see the bottom of it at the bottom of your screen.

**Comment by Jermolene** [comment]
I think @twMat's idea might be hard to implement in a way that is compatible across touch and pointer devices. I think we should close this unless/until we've got a prospective implementation to consider.

**Comment by pmario** [comment]
IMO at the moment, we simply can't fix it ... but ...

There seems to be some movement at the FF bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=77790#c214

spec draft: https://drafts.csswg.org/css-scrollbars-1/
and: https://github.com/w3c/csswg-drafts/labels/css-scrollbars-1 ... where comments could be made.
