### ISSUE TITLE
Spell checking does not work when running TW with Node.js

### ISSUE THREAD

**Issue by mardukbp** [Jermolene/TiddlyWiki5#1298]
To my surprise, Firefox's or Chrome's spell checker only works with the single-file version of TW5, but not when running TW on Node.js.

**Comment by Jermolene** [comment]
Hi @mardukbp by default, the Node.js server edition of TiddlyWiki uses the CodeMirror plugin to provide an enhanced text editor. The problem is that CodeMirror isn't compatible with the built-in spell checking facilities of browsers.

You can disable the codemirror plugin by editing the `tiddlywiki.info` file of your wiki and removing the reference to "tiddlywiki/codemirror".

**Comment by mardukbp** [comment]
Thank you!
