### ISSUE TITLE
Translate TW5.com to Spanish (es-ES) (Again)

### ISSUE THREAD

**Issue by PauDeLuca** [Jermolene/TiddlyWiki5#1299]
Hi! I think it could be interesting translating TW5.com's content to spanish. I'm still a bit unfamiliar with GitHub's workflow, so I've started on my own, translating on the browser. @xcazin, I know you've been working on the french edition. I would be more than thankful for some advice about how to proceed.

**Comment by PauDeLuca** [comment]
Hi, @xcazin. I've forked the repository, copied recursively fr-FR and fr-FR-server as es-ES and es-ES-server, modified the corresponding Tiddlywiki.info files.
I'm just getting nuts to install node.js (mon niveau de geek est carrément depassé là et je ne trouve pas d'instructions claires: Fais ça, puis ça et ça -J'utilise linux mint-). Instead of deleting the tiddlers in es-ES repository and working from node, would it be viable if I translated the tiddlers in es-ES?
Is there otherwise an EASY explanation to a not-geek-enough user of how the heck get node.js installed?

**Comment by xcazin** [comment]
Hi @PauDeLuca,

One thing that is not obvious is how node's package manager `npm` deals with a custom source code, like the one you cloned from GitHub. Normally, when you just want to use the latest public release of TW5 with node, it works with the following steps, as described in http://tiddlywiki.com/#Installing%20TiddlyWiki%20on%20Node.js:

1.  `sudo apt-get install node` # install node globally, including the package manager npm
1.  `sudo npm install -g tiddlywiki`# fetch the tiddlywiki package and install it globally. This creates a `tiddlywiki` command which is a shortcut to `node /usr/local/lib/node_modules/tiddlywiki/tiddlywiki.js`
1.  `tiddlywiki <my TW directory> --init` # creates a TW5 basic directory
1.  `tiddlywiki  <my TW directory> --server 8080` # starts TW5 on node

Your problem is that you don't want to use the public release, but the source code you just cloned and on which you'll iterate git fetch, merge, commit, push, etc. The secret here, not obvious from the npm doc, is to go to the root directory of your TW5 clone (where `tiddlywiki.js` resides) and issue a **`sudo npm link`** from here. From now on, the `tiddlywiki` command will use this `tiddlywiki.js` so that the step 6 in my first message above should work as expected.

Best,
Xavier.

**Comment by PauDeLuca** [comment]
Oh! I see. Thanks a lot! 
P.-)

**Comment by PauDeLuca** [comment]
Hi there!
I'm back after some time, but I have not forgotten my commitment to translate and build a spanish version of TiddlyWiki (now I'm a bit more proficient with GitHub and nodejs than then).

-I've translated version 5.1.12-prerelease directly on the .html file you'll find here: https://dl.dropboxusercontent.com/u/885342/Translation_ES-es_5.1.12-prerelease.html
-I've followed @xcazin 's instructions to clone and adapt fr-FR and fr-FR-server as es-ES and es-ES-server and make it run on nodejs.
-Besides the language plugin contained in the html I submitted yesterday, I'm now translating the contents and documentation of the generated wiki, including some materials borrowed from the french edition (infos pour les traducteurs, glossaire... etc), in order to make a solid and consistent edition.

I'm thinking of a TW-es edition, with several language pack plugins (es-ES, es-MX, es-AR....etc). I will try to retrieve the translation submitted in the html and get it on the wiki I'm working on.

Thank you for all help and feedback. Sorry for the absence.

Yours, 
Paulus.

**Comment by pmario** [comment]
>I'm thinking of a TW-es edition, with several language pack plugins (es-ES, es-MX, es-AR....etc). I will try to retrieve the translation submitted in the html and get it on the wiki I'm working on.

Be aware, that there may be no need, that every language "flavour", contains all the content. eg: [de-DE](https://github.com/Jermolene/TiddlyWiki5/tree/master/languages/de-DE) and [de-AT](https://github.com/Jermolene/TiddlyWiki5/tree/master/languages/de-AT) only differ a very little. 

so de-AT defines a `dependants` element in the plugin.info file https://github.com/Jermolene/TiddlyWiki5/blob/master/languages/de-AT/plugin.info#L8  So one "flavour" may only contain the differences.

This prevents you from repetitive work. IMO especially important in the future, since it reduces maintenance workload.

**Comment by PauDeLuca** [comment]
Some variations may be subtle, (as the difference between es-AR and as-UY)
and unnecessary to individualise, but the differences between central
american, south american and peninsular dialects are big enough to make,
e.g., a mexican user really uncomfortable (and terminologically wrong to
his market) when using a spanish text and viceversa. The differences are
much bigger than those between en-UK, en-US and en-AU and can be compared
to the differences between czeck, serbian, polish and russian. For
instance, the word in es-ES used for the term "link" means "marriage" in
es-MX, and the word in the latter used for the same term means "garter" in
es-ES...

Localising TW to other markets than my owns (i.e. peninsular castillian:
es-ES) should, logically enough, be done by users from those markets,
which, in my experience as technical translator and writer, will never be
done. My thoughts were more an invitation to latin american users to make
their own es-XX ports despite our mutual cultural idiosyncrasy.

Thanks for the warning!

P.-)

2016-04-28 7:57 GMT+02:00 Mario Pietsch <notifications@github.com>:
