### ISSUE TITLE
nested macro invocations

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1339]
As it is not possible to use the **$macrocall** widget within macro calls, consider...

```
<<foo <bar> >>
<<foo <bar baz> >>
<<foo bar:<baz mumble:frotz> >>
<<foo bar:<baz mumble:<frotz gronk> > >>
```

**Comment by Jermolene** [comment]
Just to be clear, the way that the basic macro syntax only permits string parameters is intentional. It was done to keep the macro syntax simple. The user can drop down to the underyling widget syntax if they want the flexibility.

Anyhow, extending the syntax is still a reasonable proposal. I think the syntax would be more consistent with the attribute syntax if we kept using double angle brackets:

```
<<foo <<bar>> >>
<<foo <<bar baz>> >>
<<foo bar:<<baz mumble:frotz>> >>
<<foo bar:<<baz mumble:<<frotz gronk>> >> >>
```

**Comment by felixhayashi** [comment]
> Anyhow, extending the syntax is still a reasonable proposal.

:+1: 

It would be great if macros could be infinitely nested. At the moment we can only nest two levels and this also requires the macrocall widget which prevents piping the input in a variable (via $set).

-Felix

**Comment by pmario** [comment]
@Jermolene  ... imo should be labeled "feature request"

**Comment by tobibeer** [comment]
I think the answer is simple: use widgets where widgets are the way to go, same for HTML markup.
