### ISSUE TITLE
tiddler aliases and auto-linking

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1342]
Enables auto-linking, auto-weaving, auto-linkification, etc...

**Note:** Rather than providing a means to [handle redirecting of dead links](http://tb5.tiddlyspot.com/#Aliases%20And%20Redirecting%20Dead%20Links) this method potentially avoids dead links altogether!

When wikified, text matching an alias definition in an alias field as described below is rendered as a link.

To implement aliasing, allow a user / designer to globally define custom alias fields, for example...
- **alias** — self-explanatory
- **master** — could be used in a language edition to allow for links in tiddlers from tw.com to point to a translated tiddler title (see https://github.com/Jermolene/TiddlyWiki5/pull/1191#issuecomment-65898754)
- **uuid** — a unique id created by plugin **xyz** which needs that kind of consistency even when tiddlers shall be renamed ...which can thus be used to have the text `REF-1` link to **Any Tiddler** with field `uuid:REF-1`, even after renaming that to **That Other Tiddler**
- etc...

The code could check for alias fields put under a namespace, e.g.
- **$:/config/AliasFields/alias**
- **$:/config/AliasFields/master**
- **$:/config/AliasFields/uuid**
- etc...

...possibly with additional configuration options in fields, e.g.  some "ignore-case" default set to `yes` / `no` (see below).

Eventually, an alias field contains a bracketed list of...
- alternative titles
- strings with modifiers
  - `Filter*` — wildcard, matches all of `Filter`, `Filters`, `Filtering`.
  - `filter\i` — ignore case, matches any `filter`, `Filter`, `FILTER`, etc...
  - `[[foo bar*]]\i` —  both of the above combined and then some
  - `\^filter\i` — match as regexp

It may be desired / desireable to optionally declare ignore-case as default; in that case, using the modifier `\i` would reverse the logic.

**Mechanism**

A global index of necessary parser rules — necessary for defined aliases — is created on startup and updated whenever...
- a tiddler with an alias field is created, updated, deleted
- an alias field config tiddler is created, updated, deleted

Alias-parser-rules should be prefixed with some identifier plus the alias-field-name so as to clearly separate them from core parser rules.

**Auto-linking matching titles**

A global switch could enable automatic alias parsers for all existing, non-system tiddlers, unless a tiddler is excluded via configuration. The following could disable auto-aliasing for the tiddlers titled **and**, **if**, and **or** and all tiddlers tagged `[tag[$:/tag/NoAlias]]` defined as a filter expression...

```
title:$:/config/AliasExclude

and if or [tag[$:/tag/NoAlias]]
```

**External Links**

To enable equivalent aliasing for external links, allow to define data tiddlers, e.g.

```
title: $:/config/AliasFields/external
type: application/json
module-type:alias
ignore-case:true

{
"http://www.tiddlywiki.com" : "tw tw.com",
"http://www.tiddlytools.com" : "Eric Shulman ELS Eric",
"http://www.google.com" : "google google.com www.google.com"
}
```

**Considerations**

Of course, aliases will only work in the context of the wiki that defines said configuration. So, a user wishing to enable this will need to import the required config tiddlers with any tiddlers he wishes auto-linkified in the same manner.

**Also compare...**

http://linkify.tiddlyspot.com

**Note on missing tiddlers**

Aliases are independent of missing tiddlers. An explicit tiddlylink or pretty-link pointing nowhere is not to be fixed by alias parsers, i.e. handling renaming is an independent issue!

**Comment by Jermolene** [comment]
Hi @tobibeer thanks.

There's a fundamental problem with this approach: it makes the parsing process be dependent upon which alias tiddlers are currently defined. That means that parsing the same block of text at different times has different results. That has fairly profound implications for the core. It means, for instance, that technically every single piece of parsed text needs to be parsed again if an alias tiddler is created, just to see if there should be any links to it.

I think the key thing to be clear about with aliases is where they are applied: are they just used during navigation, or are they full scale entries in the store? I favour just using aliases for navigation. Otherwise we risk making `wiki.getTiddler()` be slow, and scale badly with lots of tiddlers.

**Comment by tobibeer** [comment]
> It makes the parsing process be dependent upon which alias tiddlers are currently defined.

Not really. When aliases get defined, parsers are added and removed. It is not that parsers have to dynamically check some config so as to decide whether or not to kick in. In other words, we're not changing the config while any parsing is going on.

> That means that parsing the same block of text at different times has different results.

Same with any tiddler update refreshing some part of the wiki thanks to ubiquitous transclusion. In LinkifyPlugin for TWc I had a global config tiddler defining which tiddler to auto-linkify. Theoretically, it doesn't make a difference if there is an update to a single config tiddler or each tiddler changing the auto-aliasing configuration. The only difference is that a global configuration is easier to maintain, which could also be achieved with a special list ui. Anyhow, in TWc changing that config indeed was followed by a **refreshAll**.

Maybe in slow environments one could set it to lazily apply only with a full save / reload cycle. The essential thing is that it works at some point, simplifying linking.

> Are they just used during navigation, or are they full scale entries in the store?

As far as I can see sytem-parser-tiddlers are only evaluated / loaded when TiddlyWiki starts, not during runtime. This would not be true for these dynamic parsers. They are created and discarded by the aliasing handler, and not persisted in the tiddler store.

**Comment by Jermolene** [comment]
>> That means that parsing the same block of text at different times has different results.
> Same with any tiddler update refreshing some part of the wiki thanks to ubiquitous transclusion.

No, when you parse a transclusion the result doesn't depend on the target of the transclusion, that happens at rendering time.

As I say, this issue is a fundamental problem: currently parsing the same string will always have the same result, and the core implicitly takes advantage of that fact.

>> Are they just used during navigation, or are they full scale entries in the store?
> As far as I can see sytem-parser-tiddlers are only evaluated / loaded when TiddlyWiki starts, not during runtime. This would not be true for these dynamic parsers. They are created and discarded by the aliasing handler, and not persisted in the tiddler store.

My question still stands: are you proposing aliases for navigation, or at the store level?

I don't understand why aliasing needs dynamic parsers anyhow. Doesn't this ticket conflate two separate things: what other wikis call "freelinking" and aliasing. I think they are separate issues.

**Comment by tobibeer** [comment]
> Currently parsing the same string will always have the same result, and the core implicitly takes advantage of that fact.

How does the core take avantage of that fact? With parsers getting added and removed during runtime, this paradigm would indeed shift.

> My question still stands: are you proposing aliases for navigation, or at the store level?

* for navigation
    * in the sense that, once established, the parsers simply match the text like any other parsers do
* at store level
    * in the sense of the configuration being defined at either each tiddler to be aliased or a global config tiddler

> I don't understand why aliasing needs dynamic parsers anyhow.

The kind that provides auto-linking does. What other way do you see other than dynamic parsers?

> Doesn't this ticket conflate two separate things: what other wikis call "freelinking" and aliasing. I think they are separate issues.

Maybe. However, "freelinking" is a form of aliasing... albeit in a perhaps more anhanced form.

A practical example: Consider tiddler **Foo** with an "alias field" of `ticket:BAR-1`.

* freelinking, auto-linkification, auto-weaving, etc...
    * would automagically render the word `BAR-1` as a link to **Foo**
* tiddlylink-aliasing
    * would allow to render `[[BAR-1]]` as a link to **Foo**
        * unless a tiddler called BAR-1 actually exists

**Comment by Jermolene** [comment]
>  "freelinking" is a form of aliasing

I don't see that at all I'm afraid. It hugely complicates the ticket to conflate the two issues.

> A practical example: Consider tiddler Foo with an "alias field" of ticket:BAR-1.

The practical example just serves to demonstrate that these are two independent features.

By the way, why is the alias field value prefixed with "ticket:"?

**Comment by tobibeer** [comment]
> By the way, why is the alias field value prefixed with "ticket:"?

That was to indicate that there is a field `ticket` serving as an alias with the value `BAR-1`.

**Comment by twMat** [comment]
I believe he desired/intended result from the OP would be very useful.
@Jermolene do you have suggestions how this could be achieved in a way that would work?

**Comment by Jermolene** [comment]
There are really two separate issues being discussed here: aliasing and freelinking. I'd like to see aliasing in the core, although I'm not personally such an enthusiast for freelinking I'd still like it to be possible.

Freelinking is fundamentally tricky for the reason I raised with @tobibeer above: naive approaches create a dependency between the current state of the tiddler store and parsing. On the face of it, we'd have to reparse text every time we used it, and wouldn't be able to cache the results. One solution that might work is to implement it as part of the text widget. We'd still need to reparse the text widget content at each refresh cycle, in case one of the changed tiddlers were referenced within it.

Aliasing will require the tiddler store to be redesigned to allow getTiddler() to understand aliases. That bit is quite straightforward slog, but there'd be a lot more work assessing the impact of the change on other parts of the design. For example, there are places in the code where a tiddler is retrieved by title, and then something is done with the title and text. At that point in some cases we'd want to work with the post-aliasing title, not the original title. So there'd be a lot of reviewing to do to make sure that we're seeing the expected behaviour everywhere.

**Comment by tobibeer** [comment]
> we'd have to reparse text every time we used it

Same as with any other changes.

> and wouldn't be able to cache the results

the "freelinking parsers" could handle caching "freelinking aliases"

> One solution that might work is to implement it as part of the text widget.

I can see how "freelinking" is a bigger challenge than updating $link widget instances.

Some implementation of "refresh all" could fire whenever the alias configuration changed. Of course, this requires keeping and updating a cached index and handling the global refresh accordingly... so as to not fire with every changed tiddler. If one wanted to autolink tiddler titles, this would indeed need to fire with every new or renamed tiddler.

**Comment by Jermolene** [comment]
It's a bit of a rabbit hole. One alternative is to make it be part of the behaviour of the editor. It's not quite the same, because it doesn't work retrospectively, but it could still be useful.

**Comment by tobibeer** [comment]
I think I said it before, I would be fine with having any autolinking parsers, especially those for tiddler titles, only kick-in after reload ...to not dynamically update them during an editing session, as that may be overkill.

**Comment by matthias-ronge** [comment]
Is this the intended `#REDIRECT` (as in Wikipedia) function? I see two general approaches: Having “tansclusion” tiddlers (which contain nothing more than `{{MainNameOfMyConcept}}`) or having a metadata field (such as `alt`) with a list of alternate titles that shall link to that tiddler. If I am wrong and this is already implemented, please let me know.

**Comment by Jermolene** [comment]
> Is this the intended #REDIRECT (as in Wikipedia) function?

No, this is a proposal from @tobibeer; as I mentioned above I see significant problems with the approach. Aliases are on the roadmap but the implemented isn't decided yet.

**Comment by pmario** [comment]
@Jermolene .. imo should be labeled "discussion"

**Comment by tobibeer** [comment]
I'll close this and see if I will build some linkify for tw5 or not someday... based on alias fields, of course. Because aliases likely want to be defined at the tiddlers they're the alias for... while autolinking takes care that any free text is being linkified to point to that tiddler.

**Comment by pmario** [comment]
I did create 2 similar things. ... only one is public atm. [uni-link plugin](https://wikilabs.github.io/editions/uni-link/) and the 

`<<aka>> macro` is a bit hacky, that's why I didn't create a plugin yet. 

[description and code v1](https://groups.google.com/d/msg/tiddlywiki/YOj4pgiykBQ/E5621rTYAAAJ) version 2 is 
[macro code version 2](https://groups.google.com/d/msg/tiddlywiki/YOj4pgiykBQ/gwlsqib0AAAJ)

**Comment by Jermolene** [comment]
In 447cd56da9db2ee169607f32923081ac47e78354 I've created a "freelinks" plugin that uses the idea I mentioned [above](https://github.com/Jermolene/TiddlyWiki5/issues/1342#issuecomment-71869414).

**Comment by Jermolene** [comment]
See also this discussion on the mailing list:

https://groups.google.com/d/msgid/tiddlywiki/ece02188-7b35-4a80-a82e-46cdb270548a%40googlegroups.com

**Comment by linonetwo** [comment]
See Obsidian's approach https://help.obsidian.md/How+to/Add+aliases+to+note it it uses a field `aliases` to set alias of note title.

```yml
---
aliases: [AI, Artificial Intelligence]
---
```

I think we can let link/backlink indexer acknowledge this field, so backlink and freelink can use the alias from the link and backlink indexer.
