### ISSUE TITLE
Scroll focus

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1343]
Something is not behaving correctly, but without experiencing the alternatives I can't tell which is more desirable from these two scenarios.

Which part (sidebar vs river column) to scroll should be decided from:

a) Last click, either on the part or on the its scrollbar. For example; if I click+drag the sidebar scroll  then (obviously) the sidebar scrolls. But if I now use up/down keys it is the river that scrolls. I propose it should remain the sidebar scrolling until I click outside of sidebar/sidescroll.

b) Alternatively, for any of the two parts, using up/down keys should scroll the part where the mouse is currently hovering regardless of what was clicked earlier.

It may not be relevant, but just to make sure: In deciding the above, we should also consider:
* possible additional parts that bring in additional scrollbars (e.g a left menu),
* pure touch screens 
* a scenario with "up/down-keys but defective mouse"
* a scenario with "mouse but defective up/down keys"

...and maybe all of the above also for horizontal scrollbars.

**Comment by Jermolene** [comment]
Hi @twMat

TiddlyWiki doesn't customise the browser native scrolling behaviour at all. The only way we could tweak the behaviour you're seeing is to replace the browser native scroll controls with something else. I don't like to do that as it tends to make TiddlyWiki buggier and more non-standard.

My guess is that the browsers confusing behaviour is arising because of the mixture of mouse and keyboard input. Scrolling with the keyboard is likely to affect the pane that has the focus, which I think won't necessarily be affected by clicking on a scroll bar.

**Comment by twMat** [comment]
OK, then I know, thank you.
We can close the issue then.
