### ISSUE TITLE
Railroad plugin doesn't work under Node.js

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1357]
@aelocson I just noticed that the railroad plugin isn't currently working under Node.js. For example:

http://tiddlywiki.com/prerelease/static/Filter%2520Syntax.html

**Comment by aelocson** [comment]
This is caused by the patchLinks() function in railroad/wrapper.js, which adds an onclick event to each link in the SVG, to dispatch a tm-navigate event. Presumably this can't work in a static site. I don't know whether we ought to support it in other use cases of Node.js.

The easiest fix is to make patchLinks() do nothing if $tw.node is true. I will send you a pull request with this fix shortly.
