### ISSUE TITLE
Add tag in view template searchs inside the TAG tiddler

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1368]
how to reproduce

* Go to tiddlywiki.com
* Create a new tiddler
* Type hello in the add tag input box
* 3 Tiddlers without the word hello are displayed.

I think this have been fixed at #1353, but I still don't understand the current behavior. If you type hello, then only one tiddler is shown. But if you type just he there are 4 tiddlers on top of the list. What is the filter criteria? Why is not Headings in WikiText inside that list?

regards

**Comment by tobibeer** [comment]
It is fixed with #1353. The current behavior is owed to the fact that it does a search on the content, not tiddler titles.

I think, the tag-popup should only ever list existing matching titles and nothing else, listing all actual tags first, including those that are not actually tiddlers yet.

If that answered your question, you can close this one again.
