### ISSUE TITLE
tiddlywiki.com should be running SSL

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1437]
tiddlywiki.com is currently hosted with GitHub pages, which are restricted to plain http hosting.

This is means that traffic to tiddlywiki.com can be intercepted without the users knowledge, which is problematic with tiddlywiki.com being the made distribution point for TiddlyWiki. The content could also be tampered with (3G networks, hotels and public wifi have all been found to interfere with HTML traffic over HTTP in the past).

The obstacle is that https hosting and certificates are quite expensive.

**Comment by pmario** [comment]
about https certificates, this may be of interest:

https://www.eff.org/de/deeplinks/2014/11/certificate-authority-encrypt-entire-web
https://letsencrypt.org/

I saw it last year. They say it will start mid 2015. ... but not sure about the actual status.

**Comment by sukima** [comment]
Since github.com has a valid cert, could you offer a hash in a file that is part of the git repo. Then you could check the SHASUM with the `empty.html` you download from tiddlywiki.com? Maybe have a simple ajax check. The TW could hash it's own content, then run an AJAX call to `https://github.com/Jermolene/TiddlyWiki5/...OFFICIAL_SHA_HASH.txt` and check it?

I know that could be a bit much but hey, when SSL requires a static IP and $$ What ya gonna do?

**Comment by roma0104** [comment]
I agree with sukima that a checksum hosted by github through the protected connection would be a perfect stopgap.  The security minded individual would know how to sum their downloaded TiddlyWiki and verify a clean/well-formed copy.  

An AJAX call would be an interesting solution to automate it and that could be just part of the TW5.com edition build that warns if there is a problem.  Could TW hash itself without a bunch of extra code?  However, it would be at the most, a plugin.  Once a clean copy is obtained, would there be frequent need to verify itself?  And secondly, how would you remove custom content, if present so that a hash could be reliably verified?

After a cursory inspection, I don't know if you can request a text file like that directly from github without using Git.  Additionally, such a model might TOS implications that might need to be examined.

**Comment by Jermolene** [comment]
Hi @roma0104 @sukima I think for knowledgeable users downloading a release as a ZIP from GitHub is probably reasonable. But it's everyone else I'm worried about - for example, every so often we get bug reports from people with a TW that was corrupted during saving by antivirus software or ISP intervention.

This is coming to a head because I'm currently implementing a dynamic plugin library UI which connects to tiddlywiki.com to download plugins. It really needs to connect to tiddlywiki.com for downloading the components (I'd rather not have a github.com URL embedded in TW).

**Comment by Jermolene** [comment]
Fixed in #3005
