### ISSUE TITLE
filter suffix in .operator-def

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1453]
@aelocson, the suffix or any other parameters should not be capitalized in the filter documentation, it should be taken as given, so no `.doc-place {text-transform: uppercase;}`. If we want to use uppercase symbols, we should do so deliberately, not automagically.

**Comment by aelocson** [comment]
I did it that way because this was an experimental change, and it would have taken a lot longer to adjust each tiddler manually. If you recall, you gave a thumbs-up when I suggested using capitals.

But I agree with your point. I intend very soon to replace the calls to the .operator-def macro with a view template, as we've discussed before, and I'll capitalise the placeholder letters at that point.
