### ISSUE TITLE
prerelease 5.1.8: stacked view: scrolling problems

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1514]
The titles scroll at a slower pace than the river column. It happens for all the titles simultaneousely.
And, in scrolling down, when the slower title "hits" the bottom of the tiddler it sticks to, and follows, the upgoing tiddler.

FFlatest
Win 8.1

**Comment by Jermolene** [comment]
Hi @twMat you're encountering a Firefox bug with the `position: sticky` mod that we added to the tiddler titles a few weeks ago interacting with the stacked card effect. If you try it in Chrome it works fine (without the sticky titles, obviously, because they aren't implemented in Chrome). Safari is the only browser I've found that understands position: sticky and displays the stacked view correctly.

**Comment by twMat** [comment]
Thanks for your reply.

Now, with the updated prerelease, it work perfectly as far as I can tell. (FFlatest, Win8.1)
