### ISSUE TITLE
Edges of SVG buttons are clipped by some browsers

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1542]
Depending on the browser, the SVG images used for toolbar buttons are frequently clipped by one pixel on the right and bottom. Here is an example:

![screenshot 2015-02-28 10 34 12](https://cloud.githubusercontent.com/assets/174761/6425838/5bb1ddbc-bf35-11e4-8fcf-c4d055846214.png)

As far as I can tell, the problem is that the paths defining the button glyphs are sometimes at a tangent to the right hand edge of the border box. Rendering a path colours the pixels below and to the right the actual position of the path, so the pixels corresponding to those tangential lines are clipped.

One solution would be to redraw all the artwork to allow for a border around the main glyph, which would be time consuming. The quick and dirty fix is the following style definition:

```
svg.tc-image-button {
  padding: 1px;
}
```

It solves the problem but at the expense that all icons get significantly shrunk (it's particularly noticeable at small sizes, where the 1px border is a significant fraction of the width and height of the glyph).

**Comment by aelocson** [comment]
I noticed this when I was adding the macros for tips and warnings, but wrote it off as a quirk of the browser configuration I was using.

The problem seems to go away if you change the value of the viewbox attribute of the svg element in the image tiddler to be `0 0 129 129` rather than `0 0 128 128`, and this doesn't cause the icon to shrink.

**Comment by Jermolene** [comment]
Hi @aelocson maybe that would be a less intrusive fix. I'll experiment and commit shortly
