### ISSUE TITLE
ChangedTiddlers: append previous state (tiddler object) to change object

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1550]
Hi,

At the moment the changedTiddlers hashmap that is passed to the refresh handler function contains the names of the changed tiddlers as keys and for each key an object with a single property which is either `modified` or `deleted` that is set to true.

It would be of great advantage, if this would be enhanced in the following way:

    {
      modified | deleted: true,
      previous: {
        // read-only tiddler object that still contains the previous state
      }
    }

I expect this will not be possible for `modified` since the system does not know/remember the previous state. But if we could add the previous tiddler object (that existed before deletion) in read-only (as it is per default when using getTiddler()) to the change-object it could be used to do cleanup operations (I could certainly use this for tiddlymap to remove connections for nodes that pointed to the tiddlers `map.id` field, otherwise I need to iterate over all tiddlers to see if a reference is obsolete; I use ids to trace title changes). It does not break the existing api in any way to attach the previous object as another property in addition to `delete: true` so I hope it can be introduced.

Thanks
-Felix

**Comment by Jermolene** [comment]
Sorry not to have responded before @felixhayashi but I don't think this suggestion is feasible. The problem is that how would the core know what the "last" value seen was? Don't forget that tiddler change events are asynchronous, and multiple events are coalesced together. That means that by the time you get a change event for a tiddler it may actually have had it's value changed several times; how does the core know which value you saw?

**Comment by felixhayashi** [comment]
Hi @Jermolene thanks for responding

> Sorry not to have responded before @felixhayashi 

I would go crazy if I had to reply to that many issues as you do. So no problem.

> Don't forget that tiddler change events are asynchronous, and multiple events are coalesced together.

There is a refresh cycle and when changedTiddlers is passed to the widgets a tiddler title is either deleted or modified, it cannot be in two states at the same time. In case of deletion this means that at the moment it got deleted, there must have existed a corresponding tiddler object, correct? I do not understand why we cannot add this object as information to the changedTiddlers list. Whether its value was modified in the same refresh cycle doesn't matter because I am only interested in the moment it got added to the changedTiddlers list as deleted.

**Comment by Jermolene** [comment]
I'm not sure how much you know about the internals of the refresh mechanism. In the wiki object, when a modfication to a tiddler is made we don't immediately issue the change event. Instead, we call `nextTick()` (roughly equivalent to `setTimeout(fn,0)`), and register a function that sends the change event.

The reason for doing this is to prevent code that makes bulk modifications to lots of tiddlers from triggering vast numbers of change events. We temporally coalesce them.

So, the trouble is that by the time we issue the change event, it's a bit ambiguous what the previous value is. A deletion overwrites a modification. So if there's a modification and then a deletion in the queue, which value to do you record as the previous value?

I think these confusing semantics suggest that this isn't the best approach because it leads to brittle code.

> otherwise I need to iterate over all tiddlers to see if a reference is obsolete;

That doesn't sound like too much of a problem. We iterate over all tiddlers all the time.

**Comment by felixhayashi** [comment]
> I'm not sure how much you know about the internals of the refresh mechanism.

A bit, but not so sure if that is enough :) thanks for explaining.

> So if there's a modification and then a deletion in the queue, which value to do you record as the previous value?

I understand that. In any case, I am interested in the last state before a deletion, *regardless* how many modifications took place beforehand. It just requires to attach the last state as $tw.Tiddler object as property. This is useful because I can then access the fields of the tiddler in its last state before they are lost. As described in the OP, when maintaining an index (and indeces are field values) this would help to maintain the index without creating much code and runtime complexity (see below).

> That doesn't sound like too much of a problem. We iterate over all tiddlers all the time.

This means comparing EVERY index I set with EVERY tiddler in the wiki will create O(n^2) FOR EVERY changed tiddler in the changedTIddler-list just to find out which index became obsolete.

**Comment by Jermolene** [comment]
Hi @felixhayashi apologies for the delay.

I still think that there's a bit of a problem with semantics here. Imagine the following sequence of events

* Code creates a tiddler "Foo" containing "one"
* Code deletes a tiddler "Foo"
* Code re-creates the tiddler "Foo" containing "two"
* Code deletes the tiddler "Foo"
* TiddlyWiki dispatches the enqueued change events

Which value would you expect to get as the value before deletion?

**Comment by felixhayashi** [comment]
> Hi @felixhayashi apologies for the delay.

No problem, you are a busy man. Thanks for responding.

> Which value would you expect to get as the value before deletion?

I expect to get a tiddler object attached with the value "two". So only the very last state before the deletion is attached. I am only interested in the last state. I accept the fact that a tiddler might be modified in the meantime (between issues of change events) and I cannot (and don't want to) track that, what happens between changes is a blackbox for me. There must have been a reason to modify Foo and to change the value to two and delete it so it is of value for me to read the last state.

**Comment by pmario** [comment]
What if the previous state contains a 1MByte image and you have 50 of them?

**Comment by felixhayashi** [comment]
> What if the previous state contains a 1MByte image and you have 50 of them? 

Then it will exist for 1 milisecond longer in the RAM of the computer until I processed it ;)

**Comment by Jermolene** [comment]
I still think the requested behaviour has dubious semantics. The underlying problem you are trying to solve is pretty basic, and I'd rather have a solid solution.

One thing I'm not clear about: I'd have expected you to be maintaining a hashmap that maps IDs to their current title. If you did, then when you get a deletion you could reverse lookup the tiddler title to find the associated ID. I'm sympathetic to the idea of the store object being extensible so that it can manage custom indexes into the tiddler store.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> I'd have expected you to be maintaining a hashmap that maps IDs to their current title.

Correct, I do. I keep two hashmaps, one for "Title - Id" (for performance reasons) and "Id - Titlte" (to be able to access the id even when a tiddler was deleted).

> If you did, then when you get a deletion you could reverse lookup the tiddler title to find the associated ID.

Yes, you are right. A reverse lookup is possible and reduces the complexity to a simple iteration over all tiddlers: Translate deleted title to id and lookup all nodes that point to this id. I am doing that already and I now got confused why I originally started the OP. I apologize but I think I accidentally misinterpreted my original post. As said in the OP "I use ids to trace title changes" so I detect a renaming operation by checking if a new tiddler holds the same id field as a deleted title.

I think in my original post I simply wanted to express the idea, that we could attach the old state to the new state to allow users to detect renamings and to react to some field changes.

Anyhow, I'll close this issue then as you dislike the idea.

> I'm sympathetic to the idea of the store object being extensible so that it can manage custom indexes into the tiddler store.

I didn't quite get that :(

---

Just noticed its your birthday :) so I wish you a great day and as always thanks for inventing and maintining tiddlywiki. It makes the world better :+1:

**Comment by Jermolene** [comment]
Thanks @felixhayashi much appreciated!

> I didn't quite get that :(

Imagine a new method on the store: `wiki.getTiddlersByField("id","my-id-value")`. Obviously we could implement that now, but it would be slow. The idea would be to add optional indexes for specific fields. The store would automatically maintain those indexes so that they are always up to date, and the `getTiddlersByField` operation would always be fast.

Probably the best way to go would be to adopt an existing JS data store, like PouchDB or LokiJS (http://lokijs.org/). My thinking was to make the core of the store pluggable, so that using PouchDB would be an optional plugin for power users.

**Comment by felixhayashi** [comment]
> Imagine a new method on the store: wiki.getTiddlersByField("id","my-id-value")

Ahh ok, got it :)

I already created quite a lot of helper functions and bundled them in a utils module for tiddlymap. This is one of them: https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/lib.utils.js#L983

Of course what you suggest is way more sophisticated and being able to index fields is a great idea.
