### ISSUE TITLE
Inside a modal, the browser scrolls to top on various occasions which is highly unwanted.

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1575]
Tested with newest chrome/ff in linux.

To reproduce, go to tiddlywiki.com search and open "WidgetMessage: tm-modal" and enter the following into "Your message: ".

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate risus sit amet libero pellentesque porta. In hac habitasse platea dictumst. Curabitur ut vehicula erat. Sed interdum velit turpis, in gravida turpis suscipit sed. Mauris aliquam, eros ut placerat luctus, lacus nunc congue elit, in rhoncus ante arcu vel velit. Nulla est purus, scelerisque vitae urna quis, faucibus elementum nibh. Suspendisse elementum convallis tincidunt. Phasellus ante nunc, ultrices eget nulla interdum, posuere dictum dolor. Mauris imperdiet faucibus malesuada. Nullam eget lectus eu lectus lobortis porta. Phasellus sagittis viverra nisi, at malesuada enim porttitor at. Vestibulum in suscipit dolor.  Pellentesque a libero aliquam, porta leo vitae, gravida nulla. In tellus lectus, ultrices quis neque sed, consectetur imperdiet velit. Ut eu congue neque. Aenean rutrum leo nec tellus dignissim faucibus. Suspendisse lacus libero, sagittis vel erat a, pellentesque blandit arcu. Praesent elementum augue ac nisi finibus fermentum. Sed sed ante fringilla, aliquam justo pellentesque, auctor velit. Etiam sit amet augue suscipit, euismod risus congue, consectetur leo. Sed in ex ut turpis ornare egestas quis a sapien.

    <$edit-text tiddler="t1" field="f1" tag="textarea" />

    <$button>Click
    <$action-setfield tiddler="t1" f2=<<now>> />
    </$button>

1. Start the modal.
1. Make your browser's height smaller till scrollbars appear
1. Scroll down till you reach the end of the textfield. 
1. Enter something into the textfield. What happens: the browser scrolls back to the top. Same happens when clicking the button.

This behaviour prevents me from having (larger) html forms inside a modal.

Any ideas?

-Thanks

**Comment by felixhayashi** [comment]
I use forms in modals as shown here for example: https://github.com/felixhayashi/TW5-TiddlyMap/issues/48

**Comment by felixhayashi** [comment]
Actually, this happens everywhere, not just in modals. Everywhere a textbox is inside a parent element (or ancestor) that has a fixed height and `overflow: auto` it scrolls up on every keypress. I have no idea what is causing this but it is really annoying.

Here is a video: https://youtu.be/Fw-_zlJzuDg

**Comment by Jermolene** [comment]
I think the problem area is like to be this function:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/edit-text.js#L217-L241

It's purpose is to automatically resize the textarea to fit the content. It does this using a standard technique (set the height to auto, read the actual height, and then set it back). The complication comes from the need to remember and reset the scroll position; otherwise, reducing the height of the text area can cause the page to scroll.

The problem would appear to be that that scrolling mechanism isn't playing well with a parent that has `overflow: auto`.

**Comment by sukima** [comment]
Perhaps an option to `$edit-text` widget to turn off the auto sizing for times when you want a statically sized `textarea`?

**Comment by felixhayashi** [comment]
That's the point: I specifically want growing text-areas ;)

– they jusrt should not scroll back to top on keypress...

**Comment by Jermolene** [comment]
@sukima the `<$edit-text>` widget does already include an `autoHeight` attribute that allows the resizing behaviour to be controlled.

I think the scrolling behaviour can be fixed. The problem is that it currently ignores any scrollable parent, and just goes ahead and scrolls the window body. It should walk up the DOM tree and use the first scrollable parent if it exists, falling back to the window body.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> I think the scrolling behaviour can be fixed. It should walk up the DOM tree and use the first scrollable parent if it exists, falling back to the window body.

what you say makes much sense to me, this seems like a good solution!

**Comment by felixhayashi** [comment]
Hi @Jermolene,

Your description of the problem and the suggestion how to solve it were both 100% accurate! :)
Works like a charm! I'll do some polishing, create a PR and upload a demo later.

-Felix
