### ISSUE TITLE
plugin library button "open plugin library" is permanently gone

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1597]
to reproduce
- open the ControlPanel: Plugins: Get more plugins dialog
- there is a green button "open plugin library"
- if you press the button and there is an error eg: the URL path is wrong
- you get an empty interface. 
- if you close the modal dialog and
- save the file TW ... There is no way to get the green load button back. 

see the video: http://youtu.be/mhs9tiS1bXM

**Comment by Jermolene** [comment]
This is surprisingly difficult to fix. HTML doesn't let JavaScript know anything about the content of an iframe; one can't even tell whether the iframe loaded successfully or not.

We should use a timeout to trap not getting a response from the initial postMessage to the library. Then we can introduce a new UI state to represent a connection error, and provide buttons to revert.

**Comment by inmysocks** [comment]
I made a button to close a plugin library in #1718. This allows you to close and reload a plugin library if there is an error. A solution that alerts the user that there was an error instead of just showing an empty library and forcing the user to figure out that there was an error would still be a good idea, but for the moment a close library button give a way to fix the problem.

**Comment by tobibeer** [comment]
I think some "close library" button should always be displayed the moment we click the "open plugin library" button.

**Comment by pmario** [comment]
fixed with 5.1.14
