### ISSUE TITLE
Banner text is distorted in FF

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1604]
I should have brought this up long ago; for some reason the slanted banner text is "uneven" in FF (currently I have 36.0.3 which is second latest). It works well on Chrome and IE. Win8.1.

Am I the only one having this problem in FF? I can't find any mention of this on the boards or here.

![skarmklipp2](https://cloud.githubusercontent.com/assets/4534056/6769933/052d5264-d0b0-11e4-9cd3-1608a673c374.PNG)

![skarmklipp](https://cloud.githubusercontent.com/assets/4534056/6769956/f59931fa-d0b0-11e4-9a55-dad252b37a6e.PNG)

**Comment by Jermolene** [comment]
I have seen that, too - not in Firefox, but I've definitely seen it; perhaps in one of my Windows virtual machines. Anyhow, it's a browser problem where some fonts don't work well with CSS transforms.

Fiddling around with the CSS may resolve things.

Stepping back, though, the ribbon isn't necessarily the best way to highlight information; it's hard to read, and it doesn't interact well with the scrolling elements it overlaps. It was added originally to implement the GitHub ribbon, which is a readily understood signpost in the webdev community. We decided not to use it for that purpose because our audience isn't primarily developers, and then we appropriated it for the version banner. Now we're considering changing it's purpose again, and we should probably consider whether it's the best solution.

**Comment by twMat** [comment]
>CSS

I found [this](http://stackoverflow.com/questions/17321608/css-rotation-and-text-distortion) and [this](http://blog.typekit.com/2011/01/26/css-properties-that-affect-type-rendering/) (see heading: *Rotation*) that describe the issue. Seems more like an incompatability between FF and the hardware, possibly poor screen resolution or hardware acceleration. Someone suggested zooming in on the screen which does correct it. But the conclusion in one of the articles (albeit a few years old)  was that it was beyond the webdesigners control. In various places, I tried putting in the following but no change:

-webkit-backface-visibility: hidden;
backface-visibility: hidden; 



>Stepping back, though [...]

Ok, I obviously hope the "spread the word" message will be visible at front page via some other solution then.

**Comment by Jermolene** [comment]
Ah that's unfortunate, but thanks for checking it out.

**Comment by sukima** [comment]
Isn't that ribbon an image? At first I thought it was an artifact of a CSS transform but then I recalled that the [GitHub Ribbons](https://github.com/blog/273-github-ribbons) are transparent PNGs and so there is no transform. Is it a graphics rendering issue?

**Comment by twMat** [comment]
I'm pretty sure it is... or, rather, was... a CSS transform. I closed the issue because we don't use it at all anymore though so it is not relevant.

**Comment by Jermolene** [comment]
@sukima GitHub's original ribbon was indeed a transparent PNG. TiddlyWiki uses an open source CSS implementation from https://github.com/simonwhitaker/github-fork-ribbon-css/
