### ISSUE TITLE
Explore adding link panels for the front page of tiddlywiki.com

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#1609]
As discussed on earlier hangouts, the proposal is to add chunky, illustrated links to the front page of tiddlywiki.com to act as signposts for important audience groups.

The current prototype has rough edges (for example, there is an unwanted 1px padding above image link panels).

The screenshot below shows both the thumbnail strip and the single thumbnail for the introduction video. We wouldn't in fact use both features within the HelloThere tiddler.

![screenshot 2015-03-23 16 00 04](https://cloud.githubusercontent.com/assets/174761/6784121/b401b67a-d175-11e4-8442-7ae31aa4f34e.png)

**Comment by Jermolene** [comment]
By the way, I've pushed a prerelease to http://tiddlywiki.com/prerelease

**Comment by pmario** [comment]
I like the idea, but the images should not be greyed out by default. The images only look good, if you hover them. IMO they should always look good and hovering could just highlight the bottom text. 

Also the background colours should be less aggressive.

**Comment by Jermolene** [comment]
Here's the latest state of affairs (the prerelease is updated too):

![screenshot 2015-03-23 19 56 06](https://cloud.githubusercontent.com/assets/174761/6789214/b4f72d00-d196-11e4-9fd0-1e04f4198b67.png)

**Comment by twMat** [comment]
I also like the idea, it definitely gives more life to the page, partly at the expense of soberness though.

Overall, more air is needed. We'll see what it looks like when the intro-clip is removed, but because of the rather compact text I think air is needed both above and below the whole chunk segment. 

Recently I took a course on "Communication Design" (buzzwords galore to attract students). Turned out to be a fantastic course on the craft of creating presentations, including the "visuals" - images, fonts, powerpoint presentations, etc.

One of the lecturers pointed out a common mistake for beginners; we have a tendency to use unnecessary frames in slides. One example of *not* making this mistake, is Jeremys intro video where there is a clear sense of "borderless". The chunky idea, on the other hand, adds more framiness to the already framy layout. Maybe they must not be in a clinical matrix? I recall the surprise when I realized that the TW we see in the intro video, that first slide showing a bunch of tiddlers haphazardly scattered along a line, they are actually *real* tiddlers. Very cool, and would maybe be cool if we could use that somehow? More life, less production line.

**Comment by Spangenhelm** [comment]
> ...partly at the expense of soberness though.

+1

If we want it to look a bit more dynamic we may use a slideshare no?

**Comment by twMat** [comment]
>If we want it to look a bit more dynamic 

Hm, that makes me realize I don't quite know the aim with this. I am presuming it is primarily about providing accessability to key areas?

**Comment by Jermolene** [comment]
I've done some more tweaks and uploaded another prerelease: http://tiddlywiki.com/prerelease

It's still a work in progress, with lots of rough edges, but I think it's getting better slowly!

![screenshot 2015-03-26 11 18 39](https://cloud.githubusercontent.com/assets/174761/6846338/35a05d44-d3b5-11e4-93e5-f38b1b1a1591.png)

**Comment by Jermolene** [comment]
> Hm, that makes me realize I don't quite know the aim with this. I am presuming it is primarily about providing accessability to key areas?

There are several aims:

* To make the introduction video more prominent without the sledgehammer effect of the previous "big red button"
* To make the home page more visually interesting (for a long time I felt that the problem was that the "squint test" of the tiddlywiki.com homepage was that it looked like block after block of grey text)
* To provide clearer sign-posts to important external pages (eg /dev) and important calls-to-action
* To be able to get rid of the much abused "github ribbon"

**Comment by pmario** [comment]
> * To be able to get rid of the much abused "github ribbon"

But where do you show the actual version? ... I often open the TW homepage, just to have a look if the version changed. .. This takes about 2 seconds. .. With the current page I need to open a tiddler and use the <<version>> macro. IMO quite a regression :/

**Comment by Spangenhelm** [comment]
@pmario 
> ..I often open the TW homepage, just to have a look if the version changed

I was doing the same thing before i have discovered http://visualping.io, take a look it works great !

**Comment by Jermolene** [comment]
> But where do you show the actual version? ... I often open the TW homepage, just to have a look if the version changed. .. This takes about 2 seconds. .. With the current page I need to open a tiddler and use the <<version>> macro. IMO quite a regression :/

The version number is shown in control panel, and at the top of the tools tab in the sidebar (both one click away).

But I do plan to include the version number as one of the link panels, linking to the release note.

**Comment by Jermolene** [comment]
Yet another update, getting quite close to release now. There's an updated prerelease at http://tiddlywiki.com/prerelease

![screenshot 2015-04-01 14 21 15](https://cloud.githubusercontent.com/assets/174761/6941758/6e9f9b18-d87a-11e4-8ffb-addb85fd8dde.png)

@pmario you'll notice that there's now a banner for the latest version number. I can't quite think of an image to use as the background, however.
