### ISSUE TITLE
Support relative path in links

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1628]
## Summary

Currently full file path like `file:///home/reflectionalist/tiddlywiki/file` can be used as a URL to link to a file.  Relative path is supported for images, but not for other file types in general.

## Reproduction

Try `[[see this|path]]` in a tiddler, where `path` is a relative path, and if `./` is omitted should default to the directory where the whole wiki is located.

## Expectation

I expect the relative path be rendered (probobaly after an internal tranformation) as a link to the file.

## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: Firefox (36.0.4) and Chromium (41.0.2272.76)

**Comment by Jermolene** [comment]
The issue here is that the syntax `[[description|target]]` is used both for tiddler links and external links. TiddlyWiki tries to figure out which it is based on whether it looks like an URL. The word `path` in the example of `[[see this|path]]` is interpreted as a tiddler title because it doesn't look like an URL.

The solution is to explicitly mark it as an external link like this:

```
[ext[see this|path]]
```

**Comment by reflectionalist** [comment]
Ah, thanks.  Issue solved.

**Comment by danielo515** [comment]
Maybe having a dedicated tiddler called: "relative path linking" would avoid this questions in the future

**Comment by reflectionalist** [comment]
**@danielo515**:

Thanks for the suggestion.  I think a dedicated tiddler is not necessary.  It is sufficient to add some text into the section on "External Links" in the tiddler titled "Linking in WikiText".  I will contribute this part.  For the moment, I reopen the issue to wait for my fix.  :)
