### ISSUE TITLE
Provide an option to disable auto link to text in camel case

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1629]
## Summary

I understand that wikis treat text in CamelCase specially as a wiki link or to-be for convenience.  But sometimes, it is quite counterintuitive.  Currently, text like `CamelCase` is rendered as an italicized link if a tiddler so named does not exist yet.  One who is not familar with wiki may think of it as a link _emphasized_ by the author, click on it and then be surprised by a pop-up empty tiddler.  The author thus has no way to prevent some text in camel case to be presented in such a misleading way to his reader.

To completely disable this feature may be controversial for those love it and may also cause backward incompatibility.  So it would be nice to provide an option that can disable it.  Then when one really want a wiki link, he can put the camel-case text in double square brackets.

## Reproduction

Mention `Jone McCarthy` (RIP) in some text but do not want to create a tiddler named `McCarthy` to say anything about this name.

## Expectation

I expect `McCarthy` to appear as normal text.

## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: Firefox (36.0.4) and Chromium (41.0.2272.76)

**Comment by pmario** [comment]
Hi. Your summary is right. 

There are actually 3 possibilities to disable CamelCase links. 

a) use `~CamelCase` so the tilde sign will prevent automatic wiki links. 

b) use `\rules except wikilink` at the very top of the tiddler text. This will disable wikilinks for the whole tiddler.

c) disable the wikilink rule in the code

 - open the system tiddler `$:/core/modules/parsers/wikiparser/rules/wikilink.js` 
 - edit the tiddler. (There will be a warning, but that's ok)
 - at the bottom of the code is a field named `module-type` value: `wikirule`
 - either delete the field or change the value from `wikirule` to eg: `wikirule_disabled`
   - the value text isn't important, it can be anything different to wikirule. .. I choose `wikirule_disabled` because it makes sense, if someone opens it. 

You can see all the core elements if you open the `ControlPanel: Plugins: Core` plugin or the tiddler named `$:/core` 

IMPORTANT: **If you want to enable the wikilink rule again, delete your modified tiddler, so the core can take over again.** If you don't delete your tiddler, an eventual core update will not take effect, because the core still uses your modified tiddler.

**Comment by pmario** [comment]
@Jermolene 
Since this behaviour is requested relatively often, wouldn't it be possible to create a core plugin, that replaces the wikilink.js rule? So the hack in c) isn't needed?

**Comment by Jermolene** [comment]
As discussed before, my preferred approach is to extend the tiddler "type" field with an additional parameter that specifies a vocabulary (identified by URL or tiddler title). The vocabulary would stipulate which rules are to be used. A default vocabulary would be specified for new tiddlers.

The reason for taking that approach is so that content can still be exchanged between wikis and be parsed correctly.

**Comment by pmario** [comment]
You are right. The issue to track this new feature is: "Introduce vocabulary parameter to wikitext content type" #345

**Comment by reflectionalist** [comment]
**@pmario**:

Thanks for the suggested work around and hints on dealing with changes made to the core

**Comment by felixhayashi** [comment]
I agree with @reflectionalist.

@pmario 

> edit the tiddler. (There will be a warning, but that's ok)

The remark with the warning made me smile :)

**Comment by tobibeer** [comment]
Can this be closed seeing as how #345 appears to be the preferred way to handle it?

**Comment by Jermolene** [comment]
There is actually a new option in 5.1.10 to disable automatic CamelCase linking, so this can be closed.

**Comment by tobibeer** [comment]
:+1:

@reflectionalist => please close, then

**Comment by Jermolene** [comment]
Fixed in d5e690a06d523a2047eaf9b623b633bb72c18af9

**Comment by hegart-dmishiv** [comment]
Thanks for fixing this @Jermolene, I look forward to seeing v5.1.10 with this option in it. Within my own TW wiki implementation, I'm constantly waging war on Missing pages and Orphans. These auto-linkified CamelCase links generate lots of missing pages that I just don't need to create. If for no other reason, I'll be upgrading to v5.1.10 as soon as it is released. Thanks.
