### ISSUE TITLE
{{!!title}} should linkify

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1664]
It is self evident in TW that a title is a link. {{!!title}} should therefore recognize this to produce consistent results (such as when used a templates).

However - and again for getting consistent results - we should also be able to delinikfy it also, perhaps via ~{{!!title}}

**Comment by danielo515** [comment]
What you are asking will produce a link widget. If this widget is created when the {{!!title}} is used as a widget parameter we have a problem.

**Comment by pmario** [comment]
>It is self evident in TW that a title is a link.

Why? 
If the tiddler title field is: "This is a title, but no link" your assumption is wrong. 
So the rendered text would be: ~This is a title, but no link

If the tiddler title field is: CamelCaseTitle  then your assumption is true and 
the rendered text would be: CamelCaseTitle  (without a clickable link)

So this is not consistent. It just creates one more edge case. The existing behaviour is consistent. It produces 2 times a tilde and then the title text. 

There has been some discussions if the tilde sign should affect, what ever comes next. ... But imo it shouldn't follow transclusions. ... It may prevent transclusions, so that `~{{!!title}}` ... just renders as {{!!title}} and doesn't execute the transclusion. 

The tiddler title field is problematic and creates several edge cases in TW: eg: `This ]] title` can not be wiki / pretty linked using wikitext. You have to use a widget. ... 

I think the discussion about expanding the power of the tilde sign is valid. ... But your suggestion here has some room for improvements ;)

**Comment by twMat** [comment]
Ok, you guys understand a lot more about the technical reasons for and against this (and there are alternatives to achieve the same result using other means) - so I'm happy to close down the suggestion. Thanks for your input and explanations!
