### ISSUE TITLE
Discussion - Should we deprecate the CLA and replace it with something easier?

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1695]
@Jermolene 
raised his concerns about the existing CLA. see: https://github.com/Jermolene/TiddlyWiki5/pull/1692#discussion_r29556951

So the question is. Is there something easier and / or better. ...

Jeremy mentioned this article: ["Why Your Project Doesn't Need a Contributor Licensing Agreement"](http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html). Which references: ["The trouble with Harmony: Part 1"](http://opensource.com/law/11/7/trouble-harmony-part-1)

To clarify, why these articles are mentioned: TWs CLA is based on the Harmony project templates.

 - see: http://www.harmonyagreements.org/index.html
 - TW's - How to sign the CLA: https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md#how-to-sign-the-cla

The article: "Why Your Project Doesn't Need a Contributor Licensing Agreement" raises some concerns and I can follow them. ... So the question is: What's better and or easier. 

IMO [Developer's Certificate of Origin](http://web.archive.org/web/20070306195036/http://osdlab.org/newsroom/press_releases/2004/2004_05_24_dco.html) is much easier. 

This type of "sign off" is used by several big projects. eg: Docker: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

So my proposal is: Let's talk about: implementing "Developer's Certificate of Origin" or something better. 

Proposals highly welcome!

**Comment by pmario** [comment]
Implementing:  "Developer's Certificate of Origin" is as simple as adding this line to your pull request: 

```
Signed-off-by: Mario Pietsch pmariojo@gmail.com
```

---------

So what does using this signature mean? -> I did read and understand this:

```
Copyright (c) UnaMesa Association
654 Gilman St, Palo Alto, CA 94301
..... (whatever is missing here!!!)

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file (TODO link); or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it; and

(d) In the case of each of (a), (b), or (c), I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license indicated in the file.
```

**Comment by felixhayashi** [comment]
Hi @pmario Hi @Jermolene 

I read "Why Your Project Doesn't Need a Contributor Licensing Agreement".

Here are is my (harsh) critique:

---

> In practice, most CLAs in use today are deleterious overkill for that purpose. CLAs simply shift legal blame for any patent infringement, copyright infringement, or other bad acts from the project (or its legal entity) back onto its contributors.

Since this is exactly what we want to achieve I cannot see anything bad in it except bureaucracy.

> Thus, no one knows (in the general case) if the contributors' assurances in the CLA are valid.

The point is not whether we know or not but whether we tried to avoid it. It makes a difference.

> CLAs twist the empowering, community-oriented, enjoyable experience of FLOSS contribution into an annoying exercise in pointless bureaucracy

Yes, it's bureaucracy that cannot be avoided because it's about legal issues. The author keeps repeating himself numerous times and thereby spams his article.

> I've concluded quite simply: in this regard, all a project and its legal home actually need is a clear statement and/or assent from the contributor that they offer the contribution under the project's known FLOSS license. 

**Where is the benefit over CLA? The user is even forced to write a few lines himself/herself. What if he/she doesn't speak english? Even worse, what is "a clear statement and/or assent" when it comes to legal issues? Where to store this statement?**

> This is precisely why I urge projects to select a copyleft license with a strong patent clause, such as the GPLv3. With a license like that, CLAs are unnecessary.

**TiddlyWiki is not copyleft!**

> pically, developers indicate their agreement to the DCO with a specially-formed tag in their DVCS commit log.

Where is the benefit over CLA? This is just as hard as signing a CLA...

> However, most projects use the same time-honored and successful mechanism used throughout the 35 year history of the Free Software community. Simply, they publish clearly in their developer documentation and/or other key places (such as mailing list subscription notices) that submissions using the normal means to contribute to the project — such as patches to the mailing list or pull and merge requests — indicate the contributors' assent for inclusion of that software in the canonical version under the project's license.

Is this guy a lawyer, because he seems really sure that this will be enough. What is a key place? At the bottom of the GitHub readme? In the "Welcome" tiddler at tiddlywiki.com?

> Ultimately, CLAs are much ado about nothing.

The author contradics himself. At the beginning he correctly pointed out "CLAs simply shift legal blame for any patent infringement, copyright infringement, or other bad acts from the project (or its legal entity) back onto its contributors."

> The most ardent supporters of CLAs have yet to experience first-hand the arduous daily work required to manage a queue of incoming FLOSS contributions.

**The alternative? People creating their own "Developer's Certificate of Origin"; in bad english; most of the time forgetting to append it; Jeremy has to tell them how to do it.**

> Lawyers are trained to zealously represent their clients, and as such they often seek to an outcome that maximizes leverage of clients' legal rights

Creating a Harmony CLA is for free and does not involve lawyers. This does not make any sense.

---

-Felix

**Comment by Jermolene** [comment]
Thanks @pmario and @felixhayashi 

One minor point is whether we can really draw a distinction between code and documentation contributions. My concern is that in both cases we'd seem to be leaning on the same copyright laws. If we have relaxed thresholds for documentation contributions then we'd be in the odd situation that we wouldn't have the same copyright position on code and documentation.

**Comment by felixhayashi** [comment]
Hi @Jermolene

Thinking about it, I think you are right here. It is saver and more maintainable to have the same agreement for docs and code.

**Comment by pmario** [comment]
With the existing CLA we actually have 2 different licenses for code and docs. see: 
https://github.com/Jermolene/TiddlyWiki5/blob/master/licenses/cla-individual.md#23-outbound-license

I did include the CC-BY paragraph for a reason ;)

TW plugins are also an edge case. They may have there own and different license.. In general in TW every tiddler can have its own licensing if you want. 
see: https://github.com/Jermolene/TiddlyWiki5/blob/master/licenses/cla-individual.md#27-3rd-party-libraries-and-plugins

While I'm a fan of "as short as possible" licenses, I think the actual CLA isn't that bad. ... It's just way to long and IMO the "Developer's Certificate of Origin 1.1" would be a shorter option. .... but we need to discuss the TW edge cases. 

- docs
- plugins

**Comment by pmario** [comment]
... and as I wrote in my second post

>So what does using this signature mean? -> I did read and understand this: ....

Contributors need to read this short text and understand it. .. So they need to understand, eg: that if they contribute work to TW, that was written at work, that this code belongs to there employer and not to them. .. We have 2 CLA files for a reason too.

**Comment by Jermolene** [comment]
Thanks @pmario @felixhayashi 

Let's think about the immediate problem: should we accept pseudonymous contributions? I wonder if there is in fact much material difference between `@bloggo (Bloggo)` and `@joebloggs (Joe Bloggs)`. Neither is exactly a legal declaration of identity. We're basically leaning on GitHub to identify people in any case; aren't all user handles pseudonyms?

**Comment by pmario** [comment]
User handles may be pseudonyms but the proposed DCO looks like this:

```
Signed-off-by: Mario Pietsch pmariojo@gmail.com
```

If you allow

```
Signed-off-by: @bloggo
```

IMO this introduces problems. If bloggo just created an account without additional profile info, we have no immediate way to identify "it". For me it would be very disappointing to add a LGTM or +1 to a PR is signed off like this. 

I have no problems if issues are filed with anonymous names but PRs should be signed with real names.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

I agree with Mario and think for now we should stick with real names and a CLA. 

But I feel that this whole case pro and contra CLA needs a more thorough/systematic analysis. I am not an expert in this matter and therefore as far as I am concerned I need more time to reflect at least on the points below

* Why do some companies maintain a CLA, why do some ditch it or do not have one?
* What risks are involved not keeping a CLA.
* What legal disputes exist where a CLA was useful or not?

If we are not in a rush, I will take some time and report my findings back at some point so they may be helpful for our discussion

@pmario 

> Implementing: "Developer's Certificate of Origin" is as simple as adding a similar line to your pull request: 
> Signed-off-by: Mario Pietsch pmariojo@gmail.com

I did not completely understand the benefit of a DCO over a CLA yet except that the formulation is kept simpler. Does this mean I have to sign every PR I do individually? Where to put this message, in the commit message (if so, does it also count for additional commits in the same PR that are done adterwards or do we force contributers to rebase)?

-Felix

**Comment by pmario** [comment]
>I did not completely understand the benefit of a DCO over a CLA yet except that the formulation is kept simpler. Does this mean I have to sign every PR I do individually? Where to put this message, in the commit message (if so, does it also count for additional commits in the same PR that are done adterwards or do we force contributers to rebase)?

IMO You sign every PR in the first commit message. 

Quoting from the docker project:

>If you set your `user.name` and `user.email` git configs, you can sign your commit automatically with `git commit -s`.

Having a look at there pull request archive. It is possible to do automatic check against signed commits. 

I'm using docker as an example, because I follow the project since its public start. There are really big "cloud" companies involved, with strong financial interests. Most of them are business competitors. But all of them are fine with the open source signing mechanism. .. And I'm sure there lawyers had a closer look :)

There is a nice [blog post](http://blog.docker.com/2015/01/docker-project-2014-a-whirlwind-year-in-review/#more-4253) about thers PRs. On the left side the mention who joined the project. ...

**Comment by felixhayashi** [comment]
Thanks for the clarification @pmario 

> IMO You sign every PR in the first commit message. 

Ah, k.

> If you set your user.name and user.email git configs, you can sign your commit automatically with git commit -s.

I know some projects also do it like this but what if a user only uses github to create a PR, is it also signed (not sure; needs testing)?

> I'm using docker as an example, because I follow the project since its public start. 

Side note: Docker seems like a nice project.

> Most of them are business competitors. But all of them are fine with the open source signing mechanism. .. And I'm sure there lawyers had a closer look :)

Good point, I think we need some more examples like this one so we can feel comfortable with any decision we make with regards to this issue.

> There is a nice chart in the blog post about there PRs. On the left side the mention who joined the project.

My standpoint at the moment is, if other projects do not keep a CLA but make it mandatory to sign a author list, we might as well keep the CLA.

-Felix

**Comment by danielo515** [comment]
I did not read the mentioned article, but I find the CLA mechanism confortable:you sign once and forget about it. With your proposal Mario, you are forcing to everyone to use git, and maybe not everyone want to. I find myself more than once contributing directly from github. 

A bit of offtopic, could you explain me this?
 
>that was written at work, that this code belongs to there employer and not to them

They employ you, but they don't own your ideas just for being seated at you workplace

**Comment by pmario** [comment]
>> that was written at work, that this code belongs to there employer and not to them

>They employ you, but they don't own your ideas just for being seated at you workplace 

Off course, If you get you money for eg: software development, you can't make it open source, without your employer. They did pay you to program it. So all rights belong to them. ... If you get you money to have ideas, even they belong to them.

**Comment by danielo515** [comment]
Ok Mario, thanks for the clarification. But they can own the code they have asked you to program. What if you have an idea and just use your spare time at work to make it? Still belonging to them? What if they pay you for server support? Do they own your code?

**Comment by pmario** [comment]
------- may be off topic --------
I have to say, that I'm not a lawyer. And laws widely differ in different countries. .. and there are work contracts too .. so take it with a grain of salt :)

>What if you have an idea and just use your spare time at work to make it?

If you work in a "think tank" and you did write down your ideas, and store them at work. It's theirs. Same should be valid for developers. They get paid to have new ideas.

>What if you have an idea and just use your spare time at work to make it?

Spare time at work? ... ok. lunch break?  ... I personally wouldn't want to win this battle. ... Write it down in your personal phone (if you are allowed to carry it with you), and do the work at home. ... Don't use their HW, SW and don't send it with their mailserver. There are no private projects at work!

**Comment by pmario** [comment]
---- may be off topic ---------
>What if they pay you for server support? Do they own your code? 

I'm not 100% sure, if I understand this question. .. 
So hypothetically speaking: 2 possibilities. 

a) Your employer pays you for your server space, 
b) or let's you use their existing servers for your own private projects. right?

a)
If you get money from your employer and you rented the server. So your name is on the bill. It's yours. Except they have a contract that says it's theirs.  

b)
IMO it depends, on your contract. .. I Austria "a handshake" (especially with an attestor) is still a legally binding contract. ... So it depends on your contract. If it was clear, that your private project is open source and you can prove it. It's ok. .. If they don't know it, imo it's difficult.

**Comment by sukima** [comment]
I'd like to chime in with a technical perspective.

>Where is the benefit over CLA? The user is even forced to write a few lines himself/herself. What if he/she doesn't speak english? Even worse, what is "a clear statement and/or assent" when it comes to legal issues? Where to store this statement?

To answer this I'd like to break it down and compare it to the current CLA process. At the moment I've seen many discussions on PR threads complaining about the confusing CLA process. Especially for non-English speaking contributors. While the idea of the current system seems sound there isn't any technical help on the matter.

Second there is the matter of how and when to edit the main CLA file. A simple git blame on the file will yield some confusion I'm sure. While a `Signed-off-by` offers a human readable and computer understandable way of expressing the same legal agreement. Many tools can easily understand a `Signed-off-by` tag in commit messages.

Interested in knowing why Dockyard choose `Signed-off-by` instead of something else? It is because [Git itself knows about and uses that tag](http://stackoverflow.com/a/13457395/227176). In fact this process of signing your commits was well established by the Linux kernel team and the Git development team. It is the core method of contributing to these projects. It is a [well established standard](http://stackoverflow.com/a/1962112/227176) among developers.

The concept of using `Signed-off-by` lowers the barrier to entry because it is supported by all the possible workflows while Pull requests on GitHub has only one way. What I mean is with Git one could send contributions through email or on the Google groups. They could be contributed by mailing a USB stick (obviously a desperate measure for sure).

As it stand now a new contributor has to perform two actions instead of a simple `git commit -s`. Finally, it makes managing this easier on @Jermolene et al. How so? Glad you asked. Compare to the current method:

#### Scenario 1: Current method

1.  User makes a change
2.  User creates a PR
3.  A maintainer has to comment on the PR and tell them to go make another PR with their name added to the CLA file.
4.  User makes another change
5.  User creates another PR
6.  Maintainer merges both.

#### Scenario 2: Sign-off by a developer

1.  User makes a change and commits with `git commit -s`
2.  User creates a PR
3.  Maintainer merges

#### Scenario 3: Sign-off by inexperienced contributor

1.  User makes a change
2.  User creates a PR
3.  Maintainer comments on PR to verify agreement.
4.  User agrees (either with a `git commit -s --amend` or via a PR comment.
5.  Maintainer merges (optionally adding a `Signed-off-by:` to the merge commit).

Maybe the last step is still a tad time consuming but there is documentation on it. There is a large community available to explain it. And simple this is a well defined **built-in** [feature of Git](https://github.com/git/git/blob/b2c150d3aa82f6583b9aadfecc5f8fa1c74aca09/Documentation/git-commit.txt#L154-L161):

>`-s::`
>`--signoff::`
>Add Signed-off-by line by the committer at the end of the commit log message.  The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).

My last point is that by using the tools as intended it allows for more integration options. A web hook could easily check to see if a PR has a `Signed-off-by` in a commit. And if not make GitHub show a big red PR not ready message like this:

<img width="767" alt="screen shot 2016-07-18 at 23 20 48" src="https://cloud.githubusercontent.com/assets/70075/16937615/8a03464a-4d3e-11e6-8075-ec680b843608.png">

And in the case of it all working out:

<img width="773" alt="screen shot 2016-07-18 at 23 21 09" src="https://cloud.githubusercontent.com/assets/70075/16937622/927a2a6e-4d3e-11e6-91ce-fee594adbf9b.png">

https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by sukima** [comment]
Speaking of which a co-worker just showed me http://danger.systems/ which automates this very thing.

On a side note http://danger.systems/ can also be used to enforce the current CLA process so @Jermolene does not have to repeat the _Please create a separate pull request_ comment every time.

**Comment by Jermolene** [comment]
Thanks for the research @sukima. The thing I like about the current process is the symbolic impact of individuals carving their own name in the source code of TiddlyWiki, and the way that the process for doing it is itself the process they need to learn in order to contribute to the project. Signing the CLA makes a good test commit for first time GitHubbers.

Having said that, I'm also attracted to the other extreme: making the act of contributing to the project be taken as implicit agreement with the terms. It's not really possible to contribute to a project by accident, so I'd have thought all we'd need would be a sufficiently prominent warning message... I believe that there are projects that take an approach something like this.


http://danger.systems// looks like code, not a service, is that right? I don't run a server for TiddlyWiki at the moment and so would be keener on SaaS options.

**Comment by sukima** [comment]
@Jermolene danger.system is a program you run in the project directory. The intent is a CI system like Travis.CI would execute the code. What this looks like:

1.  User submits a PR
2.  GitHub sends a webhook to Travis.CI (both free)
3.  Travis `git pull` the pull request branch
4.  Travis executes the danger.system code
5.  The danger.system code checks the commits on that branch for the authors' name
6.  It opens the `licenses/cla-individual.md` and checks that the names exist.
7.  **if not** Travis fails and tells GitHub. GitHub displays a red **failed** X mark.
8.  **if so** Travis passes and tells GitHub. GitHub displays a green **passed** check mark.

**Comment by Jermolene** [comment]
Thanks @sukima 

@pmario worked on setting up Travis at the meetup. We plan to use it to build the static files for tiddlywiki.com. I'd certainly be interested in also setting up http://danger.system to enforce the CLA signature for pull requests.

I vote for closing this ticket, and sticking with the current CLA signature mechanism for the moment on the basis that it is as straightforward for contributors as their actual contribution. I'd like to avoid the workload of re-engineering things. Separately, we'll work on the Travis CI setup to automate more.

**Comment by pmario** [comment]
@sukima https://github.com/Jermolene/TiddlyWiki5/issues/1695#issuecomment-233520183 .. great post. 

I personally agree with most of it. 

I discussed it a bit with Jeremy at the eu-meetup. He made a nice summary https://github.com/Jermolene/TiddlyWiki5/issues/1695#issuecomment-233677596. 

As Jeremy pointed out, there is quite some work involved to change the whole thing, and creating PRs to contribute to the project is a necessity anyway, we should stick for the current process, until a change is really needed. ... 

I'll close the issue atm. 

----------

@Jermolene  .... slightly OT
I have had a very short look at the danger.systems site, but what burned my eyes out, was the dependencies. ... It seems to depend on a complete ruby stack. ... just to look up, if the PR creator is part of our CLA file. ... really?   ...... We probably need to open a new issue for this topic

**Comment by Jermolene** [comment]
> I have had a very short look at the danger.systems site, but what burned my eyes out, was the dependencies. ... It seems to depend on a complete ruby stack. ... just to look up, if the PR creator is part of our CLA file. ... really? ...... We probably need to open a new issue for this topic

I know! I look at that kind of thing and wonder if we shouldn't just do it within TiddlyWiki, with some ridiculously custom JS macros. The thing is that Travis CI is going to have to run TiddlyWiki up anyhow to do the builds, so it seems harmless to also do the checks under TW....
