### ISSUE TITLE
Don't use Google Material Design theme by default

### ISSUE THREAD

**Issue by rnkn** [Jermolene/TiddlyWiki5#1698]
Just a suggestion, but to my eye the default theme variations (either Snow White or Vanilla) aim to mimic Google Material Design. For those who like Google this is probably great, and I give wholehearted commendation to the huge amount of work that has obviously gone into the theme's creation, however, for those who *don't* love Google, it kinda makes TiddlyWiki feel a bit tainted.

Please don't take as a criticism, just an outside* perspective.

_\*outside the [Google dome](https://www.youtube.com/watch?v=lMChO0qNbkY)._

**Comment by pmario** [comment]
:) I'm pretty sure, that TW doesn't want to mimic anyone. IMO the default theme is more inspired by the existing Apple Mac UI than any google UI suggestions. 

IMO the default theme wants to be as simple and useful as possible. To give the users enough room to make there own modifications. 

You can have a short look at the [TW UI evolution](https://www.youtube.com/watch?v=aROD7iUM85g) on youtube. It's only 31 seconds.

**Comment by twMat** [comment]
A general thought is that it is more constructive to suggest what *to* do rather than what to *not* do.

Regardless, after doing an image search for Google Material Design, I fail to understand what you mean. I can't see any particular mimicry at all.

**Comment by Jermolene** [comment]
Hi @rnkn thanks for the feedback. I think you're right: it's a mistake for TiddlyWiki to look too slavishly like any other identifiable product. Personally, I don't enjoy Material Design when I encounter it.

The resemblance isn't intentional, but I think has the same causes: I'm not a natural visual designer, and so I've tried to develop a theme that is as unobtrusive as possible, highlighting the users' own content.

Anyhow, the "fix" is for TiddlyWiki's design to be more distinctive - something I'd love to see, but that might not be within my reach as a designer.

**Comment by rnkn** [comment]
@pmario That is a cool video. Interesting that you see more Apple than Material Design.

@Jermolene I was super surprised to find it wasn't intentional! I asked a few friends just to make sure I wasn't nuts. All subjective I guess. Looking through the CSS I really thought I'd find it was constructing on top of a Google framework a la Bootstrap.

Ideally I'd like to see something blank and stark after installation, something not unlike <http://c2.com/cgi/wiki> but I can understand that many, if not most, people would be turned off by such a bare-bones initial state.

**Comment by pmario** [comment]
>.. Looking through the CSS I really thought I'd find it was constructing on top of a Google framework a la Bootstrap.

:) you are right here. Bootstrap was part of TW some time ago. .. but it only gets in your way. So it was removed.

>Ideally I'd like to see something blank and stark after installation, something not unlike http://c2.com/cgi/wiki but I can understand that many, if not most, people would be turned off by such a bare-bones initial state.

hmmmm. 

 - In normal cases I do open several (10+) tabs with search results in one go. 
 - I read them right to left. ... 
 - If I see a page formatted like your link, I have a look at the footer and search for "last updated" or similar.
 - If I find a date less than one year old. maybe, maybe I start to read the content. 
   - imo lines that long are no pleasant reading experience.
 - If I can't find it, I close it.
   - no content read at all. Not even cross reading 
 - So this needs about 3 seconds to close the tab. 

And I'm pretty sure, I'm not the only one.

**Comment by danielo515** [comment]
So your suggestion is to make TW horribly ugly just because it reminds you too much to Google? What a poor argument. What is trend nowadays is to be minimalistic. There is no much room for identity when you try to be minimalistic (but without being an horrible blank sheet of paper). If you look at several minimalistic UIs I'm pretty sure you will see Google on them also. I would understand that you relate it to Google if we were using blue buttons and that sort of things, but that is not the case. As Mario said, I see more inspiration on Mac style rather than google

**Comment by rnkn** [comment]
@danielo515 the central idea of the web of starting with a minimal base template is to facilitate style additions from a zero point, rather than needing to first contradict someone else's aesthetic decisions. If you turn off CSS in your browser you will see the pure HTML that forms the building blocks of the web is "horribly ugly."

**Comment by danielo515** [comment]
For that purpose is better to ad a button called "download an absolute barebones wiki". Which is not a bad idea.
