### ISSUE TITLE
Feature Request: "Embed Images"

### ISSUE THREAD

**Issue by mubed** [Jermolene/TiddlyWiki5#1707]
Linking and showing external images is fine, but sometimes I need a possibility to embed/upload an image directly into wiki. I know that there are some examples for image tiddlers, but I need to be able to click on a button, get the open file dialog, select an image file and this goes inside the wiki, not copying the image content as text into a tiddler and tell wiki this is an image not a text!

**Comment by roma0104** [comment]
@mubed 
You can do that already!  With most image files, simply drag the file into the browser window so that a green bar with 'Drop Here' appears.  An import tiddler will appear, click 'Import' button and you now have an imported image.  The tiddler that contains the image can be renamed and transcluded in other tiddlers.

**Comment by sukima** [comment]
Drag and Drop is not required. Under the **tools** tab there is an **import** button. You can even check the box next to it to have it show up as an paper clip icon in the top tool bar. That button does exactly as you asked and will prompt for a file via a file open dialog.

![screen shot 2015-05-07 at 23 41 44](https://cloud.githubusercontent.com/assets/70075/7530222/adfd073c-f512-11e4-97f2-b472cc5313af.png)

**Comment by mubed** [comment]
Thank you. It's even more than what I needed :)

**Comment by danielo515** [comment]
So you can close the ticket then?

**Comment by tobibeer** [comment]
> So you can close the ticket then?

Echo.

**Comment by mubed** [comment]
Yes, you can close. Sorry for delay.
