### ISSUE TITLE
Android text input fails to generate blue movable input cursor

### ISSUE THREAD

**Issue by quantumtechnology** [Jermolene/TiddlyWiki5#1716]
When edditing tiddler in tiddlywiki on android devices no blue input cursor which is the only way to move the cursor is generated. Tiddlywiki version 5.1.8 used as server in node.js under windows 8.1.
Android Versions: 4.1.1 and 4.4.2.  (others not tested)
how to reproduce:
start windows commandline:
>tiddlywiki testwiki --init server
>tiddlywiki testwiki --server 80 $:/core/save/all text/plain text/html user password host.domain.com

use android device and go to http://host.domain.com

Also the saved document and used locally inside android has the same issue.
The saved (non node.js) file can be tested here:
http://quantenbit.de/tmp/tiddlywiki_prob.html

**Comment by inmysocks** [comment]
After a bit of poking it looks like this is caused by the code mirror plugin, which is included with the node version by default. I tested a vanilla empty.html on my android tablet and it worked as expected, installing the code mirror plugin on the wiki caused exactly the problem you are describing.

It looks like this is a code mirror problem because going to http://codemirror.net/ and trying out the demo on my tablet has the same problem.

**Comment by quantumtechnology** [comment]
Thanks for the help, so uninstalling the plugin should solve the
problem isn't it?

**Comment by pmario** [comment]
Just remove this line and restart the server.
https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com-server/tiddlywiki.info#L6

**Comment by Jermolene** [comment]
I'm wondering if we should perhaps stop having CodeMirror installed by default for the Client-Server configuration.

**Comment by pmario** [comment]
Removing it, would be an option.
