### ISSUE TITLE
Add an advanced configuration tiddler, possibly outside the control panel

### ISSUE THREAD

**Issue by inmysocks** [Jermolene/TiddlyWiki5#1727]
I think that since there are so many potential configuration options, most of which will only be useful to a few people, it may be a good idea to have an advanced configuration tiddler that gives a reasonable interface for changing less commonly used parts of tiddlywiki. The discussion in [this thread](https://groups.google.com/forum/#!topic/tiddlywiki/1cOZyZKKFrY) about changing the refresh timeout is a good example of what we could include in the advanced configuration. I think that we could target it at more advanced users and wouldn't need to have more than a table with the names, a very brief description and a field to edit the value. Since it would be targeted at advanced users it could be in a tiddler outside the control panel, maybe with a link to it from the control panel, and it wouldn't add unnecessary clutter while still giving access to more configuration options.

It would take some work changing the code around in the core to make the values editable, but I don't think that it would be a huge problem if we just use the way things in the control panel work now. I think that it this would also lower the barrier for people learning how tiddlywiki works even if it is just the psychological effect of having a field to edit instead of having to edit the line in a tiddler directly.

I don't know if this would work as a plugin because some of the modifications (like the draft tiddler timeout) would require changes to javascript in the core.

**Comment by twMat** [comment]
Instead of a separate tiddler - which would cause uncertainty as to where to look ("is it in the basic or in the advanced controlpanel?) - maybe there could be a single "mode" toggle button in the Controlpanel to show Basic or Basic+Advanced. Advanced could appear like perhaps a bottom section to the Basic, kind of like a slider, and/or add eventual new Controlpanel //tabs//. The toggle button could be part of the Controlpanel toolbar or at a "Controlpanel-global" level.

**Comment by Jermolene** [comment]
I agree with the identification of the problem. Another dimension is that each setting we add to control panel needs translation strings which means there's a lot more bloat than first appearance.

My favoured approach would be to have a list labelled "Advanced Settings" that just consists of tiddler links to the relevant configuration tiddlers.

Also, see the discussion at #1689

Anyhow, this is the sort of thing that benefits from mockups.

**Comment by pmario** [comment]
Hmmm, I'm also a fan of parameters being adjustable. ... but as Jeremy mentioned, imo there is a 3 to 1 relation for every ControlPanel parameter. .. so 3+ shadow tiddlers for 1 parameter. 

If you have a look at the ControlPanel of empty.html you'll see, that it contains 1166 shadow tiddlers. 

Most of them are used to make TW layout dynamic, which is fine. .. but the drawback for me is bloat and slow speed. 

 - TW5 empty is 1'300kByte
 - TW5 language empty is 1'500kByte
 - TWclassic empty is 393kByte

I think, playing with TW parameters is important at the very beginning, when experimenting  to needs to be easy. ... But once you found your perfect TW style, imo it doesn't change much.

So we carry a lot of overhead with every single TW. I know, that TW is much, much easier to handle than TWc. But our convenience has a price. ... 

IMO using TW as it is atm expects expensive "premium hardware" to be useful.

**Comment by twMat** [comment]
*Side note:* If I understand it right, it seems the admissability of translation then directly inflicts on decisions for usability and UI? Unfortunate. Are the things related to translations as "externalized" as possible, i.e that as much as possible of the additional code is put into the language addons rather than in core? The primary method I can think of for creating translations, which is what I'm guessing TW is using, is to use transclusion placeholders in the core, with a unique ID, that simply pulls data from some language specific added on data tiddler - but this does not sound very bloating as far as I can tell?

**Comment by Jermolene** [comment]
You can get an idea of what's involved with adding a new feature that includes additional translatable strings with @felixhayashi's recent patch for extending the navigator widget:

https://github.com/Jermolene/TiddlyWiki5/pull/1662/files

Note that the seven strings added to `core/language/en-GB/ControlPanel.multids` are each stored in separate tiddlers.

> Hm, it sounds like the admissability of translation then directly inflicts on decisions for usability and UI? Unfortunate. 

I think it's the familiar trade-off between adding new features and complexity: it's just that one of the factors in the complexity of the core is the number of translatable strings.

> Are the things related to translations as "externalized" as possible, i.e that as much as possible of the additional code is put into the language addons rather than in core? 

You should dig around and explore the translation mechanism. It's pretty much along the lines that you've speculated. It's a pretty efficient and effective arrangement. The point is that the complexity added by the introduction of new translatable strings is pretty much independent of the implementation details.

**Comment by felixhayashi** [comment]
Hi

> Hmmm, I'm also a fan of parameters being adjustable. ... but as Jeremy mentioned, imo there is a 3 to 1 relation for every ControlPanel parameter. .. so 3+ shadow tiddlers for 1 parameter. 

Maybe a solution is to bundle parameters as data tiddlers where possible instead of using one tiddler per parameter?

**Comment by pmario** [comment]
>>Hmmm, I'm also a fan of parameters being adjustable. ... but as Jeremy mentioned, imo there is a 3 to 1 relation for every ControlPanel parameter. .. so 3+ shadow tiddlers for 1 parameter.

>Maybe a solution is to bundle parameters as data tiddlers where possible instead of using one tiddler per parameter?

At the very beginning, there where some theme related data tiddlers (if I can remember right), but the drawbacks where bigger, than the win. So they are single tiddlers now. eg: If you want to overwrite one string, you basically modified them all ... update problem :/ ..

**Comment by felixhayashi** [comment]
> So they are single tiddlers now. eg: If you want to overwrite one string, you basically modified them all ... core update problem :/ ..

I had similar problems when I started developing tiddlymap. And at some point I decided to do the following:

      var shadowTObj = $tw.wiki.getSubTiddler(shadowTiddler) || {};     
      var data = $tw.utils.extend({}, shadowTObj.fields, overriddenShadowTiddler.fields);

What this example code does is it extends the shadow tiddler json-data (or in this case the fields) with the user changed data so if user changes exist, they are preferred, if not, the default is used.

This way, I can use json tiddlers and do not have to maintain a tiddler for each config.

**Comment by Jermolene** [comment]
That's correct @pmario.

As I said above, the implementation of translatable strings isn't really the issue: just the fact of adding further translatable strings makes the process of producing a translation a bit more burdensome. Another aspect is the complexity of the control panel: we can't say yes to 100 requests for specific tweaks and twizzles without making the control panel overwhelmingly complex.

**Comment by felixhayashi** [comment]
> we can't say yes to 100 requests for specific tweaks and twizzles without making the control panel overwhelmingly complex.

Maybe we could use the reveal widget to have something like "show advanced options".

**Comment by twMat** [comment]
>we can't say yes to 100 requests for specific tweaks and twizzles without making the control panel overwhelmingly complex.

How about this approach; 

Keep the Controlpanel very simple.

...and make it very easy for the *user* to configure it to show (add/remove) whatever he wants. I.e, whatever "procedure" it takes to make it appear there is made into a mechanism that the user can use to *create* his own Controlpanel items.

Maybe such a mechanism could reuse a lot from Andreas Hahns the new "plugin tiddler bundler", [Tinka](http://twguides.org/wiki/tinka.html)? That type of interface.

For example

Tab in which to place your setting: [ drowpdown menu, incl "new tab" option ]
Title for your setting:
Description: 

It would create a tiddler that, for the case of "Sizes" would look something like;
`|[[my SiteTitle size|$:/themes/...]] |<$edit-text tiddler="$:/themes/..." default="" tag="input"/> |`

...and which is transcluded into the specified location. 

(and no need for transclusion strings, other than for the mechanism itself.)

I'm would assume different settings are of different "kinds" which the mechanism would either have to handle or there could be a few different mechanisms. 

To me, something like this approach feels much more "TiddlyWikish" than the static current approach.

**Comment by pmario** [comment]
>> we can't say yes to 100 requests for specific tweaks and twizzles without making the control panel overwhelmingly complex.

>How about this approach;
>
>Keep the Controlpanel very simple.

The main problem is. If we make configurations easier for the user, we increase the complexity of TW itself. ... more shadow tiddlers to control UI visibility. ... IMO wrong approach. 

What I was proposing is: Move stuff from Vanilla TW to plugins and make the advanced possibilities more approachable. 

eg: 
 - I don't need all the different Colour Pallets. I even don't want to carry them around. 
 - For my private TWs I need one Theme only. 
 - Languages are plugins already. 
 - ControlPanel: Info: Advanced  ... IMO is only needed by developers, or if there is a problem. 
 - ...

Let me explain `ControlPanel: Info: Advanced` in more detail: 

 - I **don't** want the Advanced Tab go away. It should be there, but there can be a button. eg: "Install Advanced and Developer settings plugin" 
   - So users know, if they install it, they get settings, that may need more background information. 
 - All these plugins can be installed by default, but there should be a way to get rid of them. 

-----

Things that I want, that could link there settings into the Control panel. 
I want to have :

 - Settings that lets me define the visibility of the **Right sidebar: More**  tabs. If I found my settings, I personally don't change them for years.
 - Settings and a plugin for an "improved search" behaviour
 - A plugin and a management UI that lets me store search terms, so I can recall them faster
 - Settings and a UI to remove all popup dialogs or make them optional. 
 - Settings and a management UI for ... <you name it>

Do you really want to carry all my (not everything is phantasy) stuff around in your Control Panel. 

.... but hey, you don't need to .... It's all plugins

**Comment by twMat** [comment]
>plugins

+1, including regarding my proposed idea.

>... but there can be a button. eg: "Install Advanced and Developer settings plugin" 

Great idea! A to the plugin, or, even better, a button to go fetch and install it. This could be a recurring approach for extrax.

This is also an interesting idea generally; "meta-plugins" that merely insert an amount of such links or buttons in relevant places, that in turn lead to actual plugins. It's a bit like a bundle of plugins but providing you with the //options// rather than the actual plugins, and it could feature tooltips describing what the actual plugins would do if installed.

**Comment by Jermolene** [comment]
@twMat the control panel is already highly extensible; it's trivial to create plugins that add various tabs and individual settings to the control panel. So, we could create a plugin for "Advanced Tweaks" that just added a user interface for things like the draft tiddler typing timeout.

**Comment by twMat** [comment]
>So, we could create a plugin for "Advanced Tweaks" that just 

:+1: 
Feels like a conclusive, and I would guess "consensusitive", solution to this issue :-)

**Comment by tobibeer** [comment]
I'd also be in favor to be able to remove a ControlPanel-plugin... because, frankly, comes a time when you never need it... and with the new plugin library it's easy as pie to get it back, that is so long as I can still access that.

**Comment by hegart-dmishiv** [comment]
As a new TW user myself, I'd really appreciate an extended ControlPanel with additional configuration options. One solution I thought of, to avoid the bloat issue mentioned above, is to fork the whole project as a "TW5 Pro" version which is lean and mean, without such hand-holding namby-pamby stuff for us n00bs, then you experienced users can get a tight download that doesn't have the bloat, while we n00bs can put up with the extra overhead in our empty.html files until we're confident enough to lose the training wheels ourselves. Just a thought.

**Comment by Jermolene** [comment]
There are already configuration options in the core that we've chosen not to expose in the control panel in order to avoid bloat. I like the idea of plugins that provide additional configuration options.

@tobibeer if you mean that you want to be able to remove the standard control panel by making it a plugin, then I disagree. It's useful to be able to rely on the control panel, particularly when one is exploring a TiddlyWiki made by someone else. See [this discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tiddlywiki/m5AlE6v-4lQ/eHFb-pS_AQAJ) for more about slimming down the core plugin.

**Comment by tobibeer** [comment]
Yes and no. If I was to design a website ui based on TiddlyWiki it may make it easier for someone else to explore it by being able to access the default controlpanel, but then to me that is of no use and neiter would it be to my visitors.

**Comment by Jermolene** [comment]
Then @tobibeer you get back to trying to explain the justification for this proposal; as I keep saying, it's a lot of work and all it appears to do is to give people a slightly smaller empty.html.

**Comment by pmario** [comment]
@hegart-dmishiv 

> One solution I thought of, to avoid the bloat issue mentioned above, is to fork the whole project as a "TW5 Pro" version which is lean and mean, ..

ouch ... for an open source project a fork, really is the very last possibility, if there are unsolvable problems. ... and a discussion about the advanced configurations and the control panel are far away from an unsolvable problem :)

... I'm sure splitting the community is something we really don't want. Creating a fork, would mean double the amount of work needed, with half the human resources.

**Comment by Infurnoape** [comment]
Using developer tools, you can do anything you want to your own tiddlywiki
including plugging your own control panel. You can even see the source of
everyone's. @tobibeer <https://github.com/tobibeer>, your site was a little
challenging for awhile. You can remove any component you want. Tiddlywiki
is already exploded into over a thousand parts only put together with
shadow glue. You just have to use the right tool. I already experimented
massively and came to the conclusion that there were only a couple tiddlers
that I'm going to ultimately end up removing if they don't become options
in the future. Camel-Case which i overrode on my page and will eventually
completely remove in the end using developer tools which is on my list of
things to do for my site. I would really like to see an Auto-linking plugin
instead. And $:/core/save/all which I tweaked because I didn't want the TOC
expanded every time I open up my page. I got tired of hitting save, then
realizing everything was still expanded, closing it and then hitting save
again. Anyway, please don't be upset with me for seeming to side with
Jeremy, @tobibeer <https://github.com/tobibeer> you actually do already
have what you want, just like you made me realize, I'd like to try to help
you realize that it is already in pieces that can be manipulated any way
you want. It is the unpublished secrets that only the pros should know
because a shadow core is a safety net that has even saved me countless
times.

**Comment by tobibeer** [comment]
Yes, I can see how I can already construct a required `tiddlywiki.info` so as to construct the kind of lightweight edition I might desire from the repo. So, it's not like the core needs to come packaged to my needs. Perhaps it would be interesting to see people share different tiddlywiki.info files constructing maybe a minimal edition or something else entirely.

**Comment by pmario** [comment]
@Jermolene .. label "discussion"?

**Comment by kookma** [comment]
can be moved to discussion!

**Comment by Jermolene** [comment]
Hi @pmario @kookma what's the advantage of moving this a GitHub discussion? It seems quite an old discussion

**Comment by pmario** [comment]
I think, there is no problem having "old" discussions, but there is a big problem having issues that are not fixed after 5 years.

 - If an issue is "open", it is an issue, that needs fixing
 - A closed issue is either "fixed" or a "wont fix"
 - A closed issue is gone!!!

I personally don't read "closed" issues, to find new ideas. ... But I am reading "old" and "starred" google threads to find new and old ideas.

We do have a lot of open issues, because it could be considered rude to close "really cool ideas". They are cool ideas, but nobody did implement them yet. IMO closing good idea issues is like throwing away a lot of potential. 

Converting open issues to discussions doesn't throw them away, but makes them more accessible and doesn't pollute the "issue space"

We do have the possibility to label discussions as: "feature request" or "enhancement" or ....

**Comment by inmysocks** [comment]
For this specific issue I am just going to close it. It didn't result in any actionable things and any new input would probably be better served as a new discussion

**Comment by Jermolene** [comment]
Hi @pmario

> I think, there is no problem having "old" discussions, but there is a big problem having issues that are not fixed after 5 years.
> * If an issue is "open", it is an issue, that needs fixing

I don't think that's correct at the moment. Open issues are simply issues that haven't been closed. An issue being open could never be an indication that there is any agreement that it "needs fixing", just that the OP believes it needs fixing.

> * A closed issue is either "fixed" or a "wont fix"
> * A closed issue is gone!!!

Closed issues still show up in search results, and so I find myself coming across them all the time. Plus there is some useful information in closed issues.

> I personally don't read "closed" issues, to find new ideas. ... But I am reading "old" and "starred" google threads to find new and old ideas.

I don't read "open" issues in any methodical way; it would be impractical do so. It's issues with recent traffic that get my attention.

> We do have a lot of open issues, because it could be considered rude to close "really cool ideas". They are cool ideas, but nobody did implement them yet. IMO closing good idea issues is like throwing away a lot of potential.

Again, I'd need to understand how it benefits us to keep them open; it seems incompatible with the idea of minimising the number of open issues. In fact, it's exactly the logic that got us here -- My practice is often to leave issues open if the discussion is ongoing out of respect for the poster, even if I've already made my view clear, and opted not to take action.

> Converting open issues to discussions doesn't throw them away, but makes them more accessible and doesn't pollute the "issue space"

The trouble is that there is no "issue space"; they're indistinguishable unless you navigate via the site nav to "issues" vs. "discussion".

**Comment by pmario** [comment]
> The trouble is that there is no "issue space"; they're indistinguishable unless you navigate via the site nav to "issues" vs. "discussion".

There is a clear difference: https://github.com/notifications  ... The icons are different. 
![grafik](https://user-images.githubusercontent.com/374655/102884183-77548680-4451-11eb-9751-f73def2431e2.png)

**Comment by Jermolene** [comment]
> There is a clear difference: https://github.com/notifications ... The icons are different.

That's the point: it requires close study to distinguish them. There are no icons visible on email which is a sore point for me. I realise not everyone uses email notifications with GitHub. They literally live in the same namespace because issues, PRs and discussions all share the same ID space.

**Comment by pmario** [comment]
>... My practice is often to leave issues open if the discussion is ongoing out of respect for the poster, even if I've already made my view clear, and opted not to take action.

IMO that's a problem. No desission is worse than a "wont fix". 

If I open an issue, I do expect a yes or no. If something is an issue, that shouldn't be closed, because it needs more discussion, or it is a good idea and needs more thought, you can move it to discussion. ... 

Moving an issue is a clear decision for the poster of the issue. ... Open and "stalled" issues are only frustrating.

**Comment by Jermolene** [comment]
> > ... My practice is often to leave issues open if the discussion is ongoing out of respect for the poster, even if I've already made my view clear, and opted not to take action.
> 
> IMO that's a problem. No desission is worse than a "wont fix".

But "no decision" happens by default when discussion peters out. That's why I advocate automatically closing old issues to reflect the reality that old issues will not be actioned unless somebody takes the trouble to bump them and reopen the discussion.

> If I open an issue, I do expect a yes or no. If something is an issue, that shouldn't be closed, because it needs more discussion, or it is a good idea and needs more thought, you can move it to discussion. ...

It's clearly not as simple as that.

**Comment by pmario** [comment]
>I don't think that's correct at the moment. Open issues are simply issues that haven't been closed. An issue being open could never be an indication that there is any agreement that it "needs fixing", just that the OP believes it needs fixing.

As I wrote. If someone takes the time to create an issue, they think it needs fixing. 

Until now we didn't have the possibility to create proposals and discuss them. We needed to open issues even if they are not actionable. 

So IMO every open issue that is a proposal and _not_ actionable can be moved to discussions.

**Comment by saqimtiaz** [comment]
Considering that we have moved discussions from the TW-dev GG to Github, we really need the discussions area to be usable, easy to follow and productive. There are already concerns over how usable the discussions are, I do not see how dumping 100+ old issues into the discussions area is going to be helpful in this regard.

> But "no decision" happens by default when discussion peters out. That's why I advocate automatically closing old issues to reflect the reality that old issues will not be actioned unless somebody takes the trouble to bump them and reopen the discussion.

@Jermolene As someone that has tried to unsuccessfully review old issues I completely agree. It is not worth the effort required to wade through them all, and any issue that is still worth considering will resurface either via a bump or a re-post by another user.

**Comment by Jermolene** [comment]
Hi @pmario

> > I don't think that's correct at the moment. Open issues are simply issues that haven't been closed. An issue being open could never be an indication that there is any agreement that it "needs fixing", just that the OP believes it needs fixing.
> 
> As I wrote. If someone takes the time to create an issue, they think it needs fixing.

Indeed, but it doesn't mean anyone else agrees that it needs fixing. It's via discussion that we try to reach consensus.

> Until now we didn't have the possibility to create proposals and discuss them. We needed to open issues even if they are not actionable.

> So IMO every open issue that is a proposal and _not_ actionable can be moved to discussions.

Just to be clear, you think somebody should go through the open issues and make that call on each of them? That seems like a lot of work, and to involve a good deal of subjectivity.

And it would leave behind the issues that in somebody's opinion were actionable but hadn't been done. Why? What good are those open issues doing for us? Even if they're actionable, if they're stale, there's little value in them being open, and lots of collateral damage because it is our propensity to keep tickets open that makes the list of open tickets useless for any practical purposes.

And what good is it to clog up the discussions area with masses of 5 year old discussions with dozens of threads that are really hard to summarise now?

**Comment by saqimtiaz** [comment]
I agree completely with everything @Jermolene has stated in the previous post.

**Comment by pmario** [comment]
>Just to be clear, you think somebody should go through the open issues and make that call on each of them?

Yes

>That seems like a lot of work,

And?

> and to involve a good deal of subjectivity.

Yes

----------

I am going through many of them, from time to time starting at [page 34](https://github.com/Jermolene/TiddlyWiki5/issues?page=34&q=is%3Aissue+is%3Aopen) ... where (almost) every issue has a label.

labels are common till [page 26/27](https://github.com/Jermolene/TiddlyWiki5/issues?page=26&q=is%3Aissue+is%3Aopen) ... than they fade away. 

Especially the [bug list](https://github.com/Jermolene/TiddlyWiki5/issues?q=is%3Aissue+is%3Aopen+label%3Abug) hurts my eyes. I think many of them can be closed because they are not valid anymore. .. 

Some are still valid and hard to fix. eg: Improve experience with screenreaders #650  .. Which is labelled bug but may be better  "refactor"

If we have a look at our [bug list]((https://github.com/Jermolene/TiddlyWiki5/issues?q=is%3Aissue+is%3Aopen+label%3Abug)), it seems we had the last one 2015 6. Dec. ... That's nice, but not true.

--------

If we don't want to move issues, they should at least be labelled, so users can filter them.

**Comment by kookma** [comment]
If all old issues will be kept as now, at least I think this time forward, a policy should be made to encourage people to use discussion if they have not an actionable issue! It is admin role to decide if a new issue should be moved to discussion if it is not actionable and  other may label to help admin for such decision.
