### ISSUE TITLE
Sticky Titles: "More info" dropdown overlapped by following tiddler

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#1737]
In sticky titles mode, if a tiddler is short enough, "More info" dropdown gets obscured under the below tiddler's title.

**Comment by Jermolene** [comment]
Hi @nameanyone thanks. @pmario and I did do some investigation of this problem a few weeks ago. Annoyingly, the fix isn't as simple as giving the dropdown a z-index (you can try that using the browser dev tools).

**Comment by erwanm** [comment]
_I copy here how to reproduce a very similar bug reported under issue #2047, in order to close the other issue._

### Sticky titles cuts off dropdown box from button in edit toolbar

To reproduce on www.tiddlywiki.com:

* enable sticky titles from control panel
* edit shadow tiddler  ` $:/core/ui/Buttons/more-tiddler-actions`
* add tag `$:/tags/EditToolbar`
* save
* open any tiddler in edit mode and click the "more actions" button

**Comment by nameanyone** [comment]
I looked at it some more using browser dev tools. If I edit HTML of the tiddler and add style to the element as follows, it works.
```
    <div class="tc-tiddler-title" style="z-index:501;">
```
So, would it be possible to implement a fix for this issue by increasing z-index on dropdown and decreasing it back after the dropdown is gone?

**Comment by rubaboo** [comment]
Replaced by #2747
