### ISSUE TITLE
npm package includes build products

### ISSUE THREAD

**Issue by tomtom** [Jermolene/TiddlyWiki5#1758]
Installing via npm fails with ubuntu 14.04:

    npm --version
    => 2.10.1

    node --version
    => v2.1.0

    npm install -g tiddlywiki
    => npm ERR! ENAMETOOLONG: name too long, open '[...]/.nvm/versions/io.js/v2.1.0/lib/node_modules/tiddlywiki/editions/tw5.com/output/static/%22%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E5%88%B7%E6%96%B0%E3%80%82%E6%AC%A1%E3%81%AE25%E5%B9%B4%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99TiddlyWiki%22%20by%20Moongift.html'

**Comment by Jermolene** [comment]
Hi @tomtom thanks for that.

The file that is referenced in the error message is not supposed to be included in the TiddlyWiki package; it's one of the build products when building tiddlywiki.com. It turns out that I had misunderstood how npm publishing worked, and have been inadvertently publishing the `output` directory as part of the npm package.

I'll fix it shortly, but for the moment you could work around it by downloading the TW5 repo to a folder with a shorter path, and then using `npm link` to link it up as the handler for the `tiddlywiki` command.

**Comment by Jermolene** [comment]
It turns out that according to the docs, npm should observe the `.gitignore` file, which does exclude the `output/` folder.

Here's somebody with the same problem:

http://stackoverflow.com/questions/29793744/npm-not-ignoring-folders-specified-in-gitignore
