### ISSUE TITLE
"Save changes" downloads a blob

### ISSUE THREAD

**Issue by beingalink** [Jermolene/TiddlyWiki5#1840]
As the title says. I'm on TiddlyWiki 5.1.8 using node v0.10.38. I tried current Firefox Nightly and current stable Chrome. On Safari I get a popup "Your browser only supports manual saving." Do I misunderstand this feature?

**Comment by beingalink** [comment]
After some thinking, I guess the reason for this behavior is that I used the --password switch. Sorry for the false alarm.

**Comment by Jermolene** [comment]
Hi @beingalink by default, we save changes using HTML5's built-in ability to download files. Safari doesn't fully implement the standard, which is why we fall back to manually right-clicking on a link. It doesn't have anything to do with the `--password` switch: it is only used if you are baking a TiddlyWiki HTML file that you want to encrypt with a password.
