### ISSUE TITLE
Seems like navigation is broken in current master

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#1873]
Hi @Jermolene 

If I click on links in the recent list, the open but do not scroll to existing tiddlers...

-Felix

**Comment by Jermolene** [comment]
Whoops, thanks - if you've time to run a git bisect to track down the issue that would be much appreciated.

**Comment by felixhayashi** [comment]
Hi jeremy,

I'll do so once I am back from the supermarket.

-Felix

**Comment by Jermolene** [comment]
I've tracked it down to the changes in wiki.js in c6e48ebc2db4af895f5b3935b3f575b8aab292fe

**Comment by felixhayashi** [comment]
I tested all your changes in c6e48eb and I wish I had started from the bottom. The bug is somewhere in the code that changed wiki.js. Replacing it with the previous wiki.js code from 0206358 makes it work...

**Comment by Jermolene** [comment]
It turns out that the problem was that in some places the callers of `wiki.getTiddlerData()` were modifying the returned data structure. That wasn't a problem before, but with the caching it means that the next retrieval of the same tiddler data will return the modified data structure, and not the original that reflects the content of the tiddler.

I plan to fix it by freezing the return value of getTiddlerData() so that any existing code that attempts to modify the structure will raise an error.

**Comment by felixhayashi** [comment]
Hi @Jermolene,

This means I cannot directly manipulate the object anymore and always need to deepclone it if I want to insert an item in the data and save it again? I do this quite often and I think many plugins will break because they directly operate on the returned item. Doesn't the navigator widget also directly work with the object to update the historylist?

-Felix

**Comment by Jermolene** [comment]
Yes, the navigator widget would need to be updated.

I think it was a mistake to make the return value of the getTiddlerData API mutable; it makes it impossible to cache the value because it means that we have to give each caller their own independent copy of the data. In contrast, the tiddler object has always been immutable; that lets us return the same tiddler object for multiple calls to getTiddler.

You're probably right that it's too late to change the existing API. Perhaps we should deprecate getTiddlerData and add a new getCachedTiddlerData() method that has the required slightly different semantics.

**Comment by nameanyone** [comment]
Probably related to caching, I started seeing old copies of tiddlers again, HTTP heades don't help anymore. See https://groups.google.com/forum/#!topic/tiddlywiki/xWqZnXmYyhU for background. There is a ticket #1839 as well.

**Comment by felixhayashi** [comment]
> Perhaps we should deprecate getTiddlerData and add a new getCachedTiddlerData() method that has the required slightly different semantics.

I think this is a better idea, otherwise much will break.
