### ISSUE TITLE
readme.md is not readable in plain text

### ISSUE THREAD

**Issue by aramiscd** [Jermolene/TiddlyWiki5#1883]
At the bottom readme.md says "This readme file was automatically generated by TiddlyWiki", which is nice, but I think it's actually supposed to be readable in plain text as well.  That's the whole point of markdown.

When developers clone/fork the repo, readme.md is probably the first file they will look at. They will probably look at it in plain text and expect it to be readable this way.

It might be good for the project, to stick to this convention.

**Comment by Jermolene** [comment]
Hi @aramiscd thanks for the feedback, it's not something I'd really considered. Of course HTML tags are a valid part of Markdown; the syntax is only intended to provide a shorthand for common operations.

The only way that I can see to fix this would be to write the readme manually as a Markdown file, and stop trying to generate it automatically. I'm not keen on that because it will result in me having to maintain duplicated content.

We could  link to the actual source text of the readme, but the use of transclusion means that it is not particularly readable either:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/readme/ReadMe.tid

**Comment by aramiscd** [comment]
Hi @Jermolene,

> the syntax is only intended to provide a shorthand for common operations.

I beg to differ. It isn't intended as syntactic sugar for html. It is ["(1) a plain text formatting syntax."](http://daringfireball.net/projects/markdown/).

> HTML tags are a valid part of Markdown;

Of course, but treating outright html as markdown seems inadequate to me.  It does work though, and I understand your reluctance to duplicate content.

**Comment by Jermolene** [comment]
Thanks @aramiscd
