### ISSUE TITLE
It should be possible to display fields in local time

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#190]
Date fields are currently interpreted as UTC times, and then converted to local time for display. This causes a disparity between the value stored and the value displayed.

It should be possible to cause a tiddler to be displayed in local time.

**Comment by tobibeer** [comment]
@Jermolene, can you be more specific what you actually refer to by:

> It should be possible to cause a tiddler to be displayed in local time.

To me, with a date field we should always:

* **writte** as UTC — as that is how it's implemented now
* **read** as local time — required due to the above

If there are occurrences where we don't respect both conventions, I'd consider it a bug that needs fixing. So, let's start by listing all bugs similar to #1096. Are there others?

**Comment by Jermolene** [comment]
Consolidated in #2061
