### ISSUE TITLE
Add attribute "class" to TranscludeWidget

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#1900]
To allow for additional classes to be assigned to transcluded content's wrapper, in addition to a default "transcluded" class requested in #1899.

**Comment by pmario** [comment]
-1 .. imo there is an existing solution

**Comment by Jermolene** [comment]
Hi @nameanyone the real problem with this and #1899 is that by design the transclude widget doesn't generate any DOM nodes, so there's nothing to put the class onto. The reason it doesn't generate DOM nodes is so that you can (eg) transclude list item elements inside a list element without introducing an illegal additional element.

Generally, if you're concerned with transclusions you might want to be working with the widget tree rather than the DOM tree.

**Comment by nameanyone** [comment]
@pmario, by "existing solution" you mean the same `{{tiddler||template}}`?

**Comment by nameanyone** [comment]
I seem to recall now this has already been discussed previously, probably on the forum.

I'll check out the widget tree, thanks.
