### ISSUE TITLE
folded tiddlers - not enough visual feedback

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#1908]
commit: https://github.com/Jermolene/TiddlyWiki5/commit/ac08dc2e35d99eb563ab8c4449ce1fcfe30f3bf7 introduces fold/unfold all. The tiddlers keep the fold state, if saved. 

to reproduce

 - open several tiddlers
 - click "fold all" button
 - save and close tw
 - ... do nothing for one week :)
 - open the TW
 - now all "folded" tiddlers look, as if they are empty. 

Expected behaviour. 

- If a tiddler is folded, the tiddler body should show a visual indication, that there is content.
- may be the "unfold" icon button could be stretched to 100% width and revealed in the body. So clicking this button will show the content.

**Comment by twMat** [comment]
I just returned from having waited a week only to discover how all my tiddlers were blank! I was just going to report this serious error when I saw this thread and remembered what had happened. Lucky me ;-) But, seriously, I agree with @pmario  - there is no visual difference between empty body and folded.

>may be the "unfold" icon button could be stretched to 100% width and revealed in the body. So clicking this button will show the content. 

I 'm not sure I fully understand the "stretched" part, but I'm thinking that to discern it from an empty tiddler, how about *force-displaying* the "unfold this tiddler" button in the toolbar for all folded tiddlers? I think this is fine to do by default since those folded tiddlers are of limited use (if the user absolutely does not want to have it show in folded state he can customize it).

**Comment by pmario** [comment]
>I just returned from having waited a week only to discover how all my tiddlers were blank! 

;)

**Comment by pmario** [comment]
>I 'm not sure I fully understand the "stretched" part, 

I just want to have something, that is very prominent and visible, if a tiddler is folded. I wanted to reuse the existing icon button. ... but much wider. 

>but I'm thinking that to discern it from an empty tiddler, how about force-displaying the "unfold this tiddler" button in the toolbar for all folded tiddlers?

I think the unfold toolbar icon is not "visible" enough. IMO there should be something in the content area.

**Comment by twMat** [comment]
Ah, ok,

Maybe it would look good with an unstretched icon in the center of the blank body? Or as a "tab" sticking out down from the center of the bottom edge (a kind of "pull here"). I think the fact that the tiddler body is blank will make things visible.

**Comment by danielo515** [comment]
Putting the unfold button at the bottom of folded tiddlers it's the logical thing. It's how It works in most "web apps". And it also has another great advantage, and that is that on mobile it is very comfortable to hit a button 100%wide. I definitively love the idea.

**Comment by tobibeer** [comment]
I would show a horizontal bar at the bottom...

* at full-tiddler-width
* containing "...", centered
* displayed when hovering the tiddler
* acts exactly like the unfold button

Personally, I would likewise prefer a similar area at the top of a tiddler to fold it... only just without any "...", just a horizontal bar that is transparent by default and greyish when hovering the title.

**Comment by nameanyone** [comment]
Here, a color might be appropriate. Pick your own color, obviously. Mine appears just a bit more saturated than the rest of the buttons.
```
/* make "unfold" button more prominent */
.tc-tiddler-controls button svg.tc-image-unfold { fill: #657b83; }
```
I like my folded tiddler taking up as little vertical space as possible:
![folded](https://cloud.githubusercontent.com/assets/212368/9967850/f4521c4a-5df9-11e5-9f08-818706e15580.png)

**Comment by Jermolene** [comment]
I've pushed a new prerelease to http://tiddlywiki.com/prerelease with some experimental changes in b641cb402d320f54c6e1627d70310eb69a1b788f and cf00658ddfc2f55ea41c2681a9eac2b33d69532d.

* There's a new vertical bar at the left of each unfolded tiddler that allows it to be folded even if you've scrolled the toolbar out of reach
* There's a new horizontal bar at the bottom of each folded tiddler for unfolding it

At the moment, both the new buttons are enabled all the time, independently of the fold/unfold toolbar button. What do you think?

**Comment by nameanyone** [comment]
:-1: I think the toolbar button is sufficient, just make it visible if you intend to use it (Control Panel > Appearance > Toolbars), and add a color as I described earlier.

**Comment by tobibeer** [comment]
I am not at all a fan of (too many or secondary) toolbar buttons. So, I very much appreciate this tentative ui.

**Comment by nameanyone** [comment]
To me that's a natural placement, in the toolbar, similar to where you would find window controls in any window manager.

I'm just glad to see the new **tm-fold-tiddler** message. That's all we need in the core. The rest can be customized to taste. So, I'm fine whichever way. If it ends up adding a bit of height to each tiddler, I'll be sure to apply `display:none` to it. :)

**Comment by tobibeer** [comment]
There's always that, either way. I think a decent default that can be easily disabled is a preferable option.

**Comment by twMat** [comment]
First off, IMO this should be a plugin. 

I think the new proposed unfold now looks good with the centered arrow and it also makes sense to click anywhere in the body to open it.

At the same time I agree with @nameanyone that the folded tiddler should take up as little vertical space as possible. Maybe top- and bottom- margin could be decreased.

>There's a new vertical bar at the left of each unfolded tiddler that allows it to be folded even if you've scrolled the toolbar out of reach

-1. Especially if it is to be a default feature. While I agree it is desirable to reach the fold-up button from everywhere, this is actually desirable for so many more toolbar features.

...I really wish there was a way to make *sticky* work instead, so to have a hovering button. I recently found a solution that I think works also in Chrome, using "polyfill". Might this be a viable solution? (I don't know what "polyfills" are, I just memorized the term to read up on it eventually but just mentioning it because it was presented as a workaround for sticky.)

As reasoned in the discussion on sticky, #1203 (a bit down in the discussion),  maybe we could treat fold the same way and include it in a sticky head for the cases it does work.

**Comment by tobibeer** [comment]
A *polyfill* is simply extra js code to make up for browsers not (yet) implementing standards ...thus bloating the codebase to make things work cross-browser.

Folding could indeed be a plugin in its entirety (I missed the discussion where it was concluded core-worthy) ...that is: all toolbar buttons and (optional) in-tiddler-controls in the form of vertical or hoizontal bars... which I very much like as a new way of ui that ain't cluttering the tiddler display too much... despite the fact, that it might help to be able to also access other functions more easily, e.g. clicking on a title (or a permalink symbol next to it would ideally create that without having to search through a list of "more commands". Personally, I would style these bars so they are barely visible, as I consider them editing / managing features and not so much presentational (for your visitors).

Here is an earlier comment / idea about introducing dim, on-hover buttons in the "gutter" being the left or right margin of a tiddler: https://github.com/Jermolene/TiddlyWiki5/issues/133

**Comment by Jermolene** [comment]
I've pushed an update that makes the new "fold-bar" be switchable as though it were a toolbar button. It's on by default in the pre-release, but will be off by default in the full release. (I've also yet to make the text translateable).

@twMat says:

> First off, IMO this should be a plugin.

The main folding functionality needs to be part of the core, because the core templates for the tiddler body need to be aware of the folding mechanism.

We could make the fold/unfold toolbar button and/or the fold-bar reside in a plugin, but it seems inconsistent with the other toolbar buttons to make the former be in a plugin. There's a case to be made for the fold-bar to be in a plugin but (a) it's fairly trivial and (b) personally, I think it's really useful.

> I really wish there was a way to make sticky work instead, so to have a hovering button. I recently found a solution that I think works also in Chrome, using "polyfill". 

I agree, that would be much better.

I decided long ago not to include any polyfills in the core code. The reason is that they are brittle and frequently highly specific to specific browser versions. My goal with TW5 is for it to have a long useful life, and polyfills would provide a point where rust would accumulate.

Polyfills in plugins make sense, though.

> Folding could indeed be a plugin in its entirety (I missed the discussion where it was concluded core-worthy)

See the point above about how folding needs to be in the core for functional reasons. But the main reason for including it in the core is because we need to radically improve the smartphone experience of TiddlyWiki.

**Comment by tobibeer** [comment]
Thanks for the explanation on why folding better be in the core. Makes sense, otherwise a plugin would have to force-overwrite the corresponding core templates which is quite undesireable.

> (a) it's fairly trivial and (b) personally, I think it's really useful

Very much agree and totally ok with the "fold-bars" being turned off by default (as I would barely fold things, anyway, I imagine ...unless, perhaps, these bars would make it as easy as pie).

**Comment by pmario** [comment]
I like the new "fold button" at the left area of the tiddler. 
I also like the "unfold button". It's exactly as I proposed in  ... but I don't like the vertical space, that the new unfold button uses

I'd like to have the "fold / unfold" button both on the left side, of the tiddler

**Comment by felixhayashi** [comment]
> I like the new "fold button" at the left area of the tiddler.

Me too :) Very well done @Jermolene.

> but I don't like the vertical space, that the new unfold button uses. I'd like to have the "fold / unfold" button both on the left side, of the tiddler

I also agree on this one with Mario.

**Comment by Jermolene** [comment]
> but I don't like the vertical space, that the new unfold button uses

Ah, there was a bug in the latest prerelease that introduced additional vertical space. I've updated it here:

https://github.com/Jermolene/TiddlyWiki5/commit/90e0b6f5551071499a450bd68c3d854fb6323345

I've pushed a new prerelease. I agree that it would be better if the folded tiddlers were smaller still; at the moment the folded size is basically how the tiddler displays without the folded segments; margins and padding stay the same. So, any further fix would involve adding a `tc-folded-tiddler` CSS class so that we can adjust the padding for folded tiddlers. (And maybe the margin; perhaps folded tiddlers should abut one another).

**Comment by danielo515** [comment]
Hello @Jermolene, 

As I said on the group, I love the new implementation. It works beautifully on mobile. Thank you very much for it.

**Comment by Jermolene** [comment]
Thanks @danielo515!

**Comment by pmario** [comment]
I think the current implementation fixes the issue. The topic is quite long already. So for improvement suggestions, new issues should be better. Thx.
