### ISSUE TITLE
tc-tiddler-view-frame not defined

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1912]
I might be missing something but in playing around with the styling, I notice that 

tc-tiddler-view-frame

is found in $:/core/ui/ViewTemplate ...but that is the only occurence of it, i.e it is not mentioned/defined in any stylesheet or anywhere else AFAICT.

**Comment by pmario** [comment]
there are 3 CSS rules `.tc-tiddler-view-frame .tc-tiddler-edit-frame and .tc-tiddler-frame`
It seems there is no special rule needed for the base images, because .tc-tiddler-frame is enough atm. 

There are many classes, that have no rules assigned atm. So what do you need it for?

**Comment by twMat** [comment]
Thanks. I don't need them (...unless they are somehow related to how I can style there to be no tiddler border/shadow). I merely reported because, as you note, they are unused and I'm thinking that maybe they are forgotten leftovers from some earlier festivities.

**Comment by pmario** [comment]
You are right. Most classes, that are defined in the TW templates, may be unused atm. ... Some may even be "obsolete" or "not really usable" for styling, because they are used too often. ... But imo changing it, will be very hard, because of backwards compatibility. 

So if we want to change stuff there, we will clearly need to deprecate stuff over several versions, to be sure, that we don't break stuff.

**Comment by twMat** [comment]
Ah, that makes sense.
