### ISSUE TITLE
External tiddlers don't work for single-file TiddlyWiki: should they?

### ISSUE THREAD

**Issue by tfeb** [Jermolene/TiddlyWiki5#1917]
I'm using a traditional single-file TiddlyWiki (so not node.js or anything clever), currently 5.1.9.

I can make external images work fine via setting `_canonical_uri` for a tiddler and the appropriate content type.

I naively thought that this would work for other kinds of tiddlers: so, for instance if I had a chunk of TW markup in a file I could create a tiddler which referenced it by setting its `_canonical_uri` and content type.  This seems not to work: you just end up with a blank tiddler.  It is possible that this is finger trouble on my part but I have checked the paths &c pretty carefully.

It would be good, I think, if it could work.  But perhaps it is not possible for some reason of course.

**Comment by danielo515** [comment]
using the canonical uri just shows the file content inside the html file, like any other website would the. Tiddlers in the other hand, have to be parsed and rendered by tiddlywiky core. I think that could be part of the problem.

**Comment by Jermolene** [comment]
Hi @tfeb external text tiddlers weren't implemented but I've just done a quick implementation of the simpler parts: a204784c0c7ccc9b3ccfdb9d5230017cdcc19e90

The limitation is that the technique here is read-only; if one edits an external-text tiddler then it becomes an ordinary tiddler when changes are saved. You can create the external-text tiddler files manually, or you can create them under Node.js while creating a standalone TiddlyWiki HTML file. Annoyingly, Chrome places security restrictions that prevents the external text tiddlers from being loaded if the HTML file is on a file:// URI.

I've also pushed a new prerelease for you to check out:

http://tiddlywiki.com/prerelease/#Alice%20in%20Wonderland

**Comment by tfeb** [comment]
@Jermolene: thanks, I will try that as soon as I can

**Comment by twMat** [comment]
@Jermolene 

I figure it's too unofficial to bring up on the boards so I hope it is OK with some Qs here?

Where do I actually see the _canonical_uri for the text in your provided demo? (I find the [$:/core/templates/canonical-uri-external-text](http://tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Ftemplates%2Fcanonical-uri-external-text) but this seems to be a template). Or is it simply so that *all/any* text files (in format .tid) are pulled in (from address stated in [$:/core/templates/canonical-uri-external-text](tiddlywiki.com/prerelease/#%24%3A%2Fcore%2Ftemplates%2Fcanonical-uri-external-text))? I was expecting to click on the Alice tiddler and see a simple _canonical_uri field with a http address. Is that the intention eventually?

What is a reasonalbe ambition for displaying such tiddlers? To have them display/appear as they do in their actual location, i.e with style and wikified?

And what does this actually mean?
*Is the text wikified remotely and the result is seen from the local tiddler? Not unlike an iframe, I guess.
*Is the text wikified locally? A string reading [[mylocaltiddler]] would actually link to mylocaltiddler? And my local tiddler background color is applied.
*Or is it even a merge of remote and local? Would a list filter list remote tiddler titles or my own or both?

As usual I have the TWederation in the back of my head.  

Thanks!

**Comment by pmario** [comment]
>Where do I actually see the _canonical_uri for the text in your provided demo? 

as an example see: http://tiddlywiki.com/#Caruso%20-%20Ave%20Maria

>(I find the $:/core/templates/canonical-uri-external-text but this seems to be a template). Or is it simply so that all/any text files (in format .tid) are pulled in (from address stated in $:/core/templates/canonical-uri-external-text)?

those templates are needed to create a proper tiddler, so the core can handle it. You can't expect external text files to be formatted in the right way for TW. They can have any text format. 

>I was expecting to click on the Alice tiddler and see a simple _canonical_uri field with a http address. Is that the intention eventually?

as an example see: http://tiddlywiki.com/#Caruso%20-%20Ave%20Maria


>What is a reasonalbe ambition for displaying such tiddlers?

IMO documentation purpose. eg: I have a 'dobackup.sh' or 'dobackups.bat' file, which perform some action. ... Those files need to be formatted in a spacial way, so the work for their OSes. But I want to add some more documentation, that should show the active file and not a copy pasted, outdated version. 

>To have them display/appear as they do in their actual location, i.e with style and wikified? ...and what does this actually mean?

>-  Is the text wikified remotely and the result is seen from the local tiddler? Not unlike an iframe, I guess.

no. it's rendered by the TW core.

> - Is the text wikified locally? A string reading [[mylocaltiddler]] would actually link to mylocaltiddler? And my local tiddler background color is applied.

yes, if the external tiddler has the right mime-type. if it's eg: text/plain, no wikifikation will be done. 

> - Or is it even a merge of remote and local?

imo no merge. but I didn't read the code yet :)

> - Would a list filter list remote tiddler titles or my own or both?

Since _cannonical_uri tiddlers need to be real tiddlers, filters will show them. BUT find will not be able to search the content.

**Comment by twMat** [comment]
@pmario - thanks for yoru replies but I realize I expressed myself poorly on some of the questions:

What I mean is, where do I find the _canoncial_uri specifically for Alice in Wonderland? I can't find anything equivalent to the Caruso Ave Maria where there is a _canonical_uri field.

... or is it so that there is no exlicit field for this but instead Alice happens to be shown because *everything* in some folder, specificed via some hard coded canonical uri path, is pulled in and shown?


>>* Would a list filter list remote tiddler titles or my own or both?

>Since _cannonical_uri tiddlers need to be real tiddlers, filters will show them. BUT find will not be able to search the content. 

Hm, but you also say that it would wikify locally if if the mime-type is correct. Doesn't "wikify" mean it parses the content... and doesn't "parsing the content" imply that the content *is* searchable?

**Comment by pmario** [comment]
>Hm, but you also say that it would wikify locally if if the mime-type is correct. Doesn't "wikify" mean it parses the content... and doesn't "parsing the content" imply that the content is searchable?

There are a lot of different mechanisms involved, if you load an image from a server. Most of them have sensible defaults, that it just works.

So if you show an external tiddler, it will be cashed in the TW store. So if you do a show tiddler and then a search, imo it should be searchable. ... But if you didn't show the tiddler, the _canonical_uri is not resolved. That means that TW doesn't request the external content. So the content isn't searchable.

**Comment by pmario** [comment]
>What I mean is, where do I find the _canoncial_uri specifically for Alice in Wonderland? I can't find anything equivalent to the Caruso Ave Maria where there is a _canonical_uri field.

That seems to be a bug.

**Comment by twMat** [comment]
>That means that TW doesn't request the external content. So the content isn't searchable.

Ah, makes sense. Thanx.

>That seems to be a bug. I'll create a ticket.

Good... But how/where *does* it fetch the _canonical_uri then?

**Comment by pmario** [comment]
>But how/where does it fetch the _canonical_uri then?

try this: 

 - http://tiddlywiki.com/prerelease/
 - <f12> open dev tools
 - select console or network tab
 - search for "alice" in tw search box. 
 - open "Alice in Wonderland" tiddler. 

you'll see that the content is fetched from the server "on demand". So TW has a mechanism built in, that has a look, if there is a _canonical_uri field if there is no tiddler content. If the URI is there it will load the content and display it.

**Comment by twMat** [comment]
Thanks @pmario 

```
<div title="Alice in Wonderland" tags="external-text" _canonical_uri="./text/Alice%2520in%2520Wonderland.tid">
<pre></pre>
</div>
```

**Comment by pmario** [comment]
@tfeb ... can you close the issue, if you are OK with the provided responses?

**Comment by tfeb** [comment]
@pmario sorry, I thought I had

**Comment by Jermolene** [comment]
Thanks @pmario @tfeb
