### ISSUE TITLE
Need terms to differentiate between external content types

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1924]
In #1917 I'm happy to note @Jermolene typing "external-text tiddler " (with a hyphen) as simply typing "external text tiddler" is ambiguous; it can mean "tiddlers that are external and contain text" OR "tiddlers that are internal showing external text [unspecified if stored in a tiddler]". I interpret the included hyphen in "external-text tiddlers" to mean the latter.

But external *images* has the same ambiguity. If you're advice to "simply use an external image", it is not clear if this means you should type in `[img[http://tiddlywiki.com/favicon.ico]]`or create a new tiddler with a _canonical_uri field. (Maybe `[img[..` processes the url as a _canonical_uri but that is another matter.)

Perhaps we should introduce distinct terminology this to avoid confusion? 

(I'm not overly fond of the exotic term "canonical", not to mention "_canonical_uri", so I hope for something friendlier sounding. Frankly, I hope we eventually get a better keyword than `_canonical_uri`, or a UI that doesn't force a user to confront this term).

**Comment by pmario** [comment]
_cononical_uri is an exact term. You can look up every part of it's definition and see, what it does. 

Changing terms will only create confusion, because they are not exact enough. 

see: 
canonical link info: https://en.wikipedia.org/wiki/Canonical_link_element
official specs: https://tools.ietf.org/html/rfc6596

URI: https://en.wikipedia.org/wiki/Uniform_resource_identifier

The URI does not specify, how to deal with the content. That's what the MIME type or the protocol is used for. eg: mailto:me@example.com

**Comment by twMat** [comment]
@pmario  - thanks. I'm closing this issue for now because it confuses the other issues I've brought up. Might repoen it at some point. Thanks for your input!
