### ISSUE TITLE
How about introducing a generic _canonical_uri wikifier

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1925]
[I might not phrase the title correctly. Please improve if possilbe.]

In #1924 I propose introducing terminology to clarify what is referred to when saying "external". 

Maybe the issue can be solved by introducing wikitext for a solution instead and make for a unified solution so there aren't two different meaning concepts. I.e to make `[xxx[]]` be a generic placeholder so that you can write

`[<type>[url or uri]]`

For example

`[img[url]]` does the usual stuff. (I don't know, maybe this *does* somehow use the url as a _canonical_uri?)

`[img-image/jpeg[url]]` would somehow create, or merely store in temp memory, the equivalent of creating a tiddler with `_canonical_uri` with that url and that specified type. (...but, ideally(?) merely `[img[url]]` would be enough and would sniff out image type if needed. See also @Jermolene comments on March 21 in #1594 )

`[text[url]]` would thus deal with what we see the beginnings of in #1917 

...and eventually `[tid[url]]` (..even `[tw[url]]`? )

Does this make sense at all or do I misunderstand something fundamental?

**Comment by pmario** [comment]
I think this should not happen, since it's the wrong place to deal with the mime-type definition.  

The proposed definition is redundant and in 80% of the cases wrong too. eg: img-image/jpeg is _not_ a valid mime type. (I know this is just an example but it shows, that nobody remembers mime types correctly. Everyone has to look them up. - me too :) 

IMO if a user types '[img[any-image-in-any-format]]' she wants to display an image. she doesn't want to specify how it is stored, and how it has to be handled. ... It should just work. 

So `[img[something]]` is a high level wiki text definition, that the content of a tiddler should be shown / transcluded as an image, because `[[someting]]` would create a link.

The MIME type needs to be defined, where they belong to. At the tiddler level. 

To accomplish this, there are several possibilities: 

- The/Any server where an image is stored provides us with the right "respond header" info 
  - Most well configured servers do it in the right way for well known types. eg: jpg, jpeg, svg, bmp, png ... but if we have an exotic format they may not provide us with the right / or no info at all. So the next rule should be used
- Any tiddler should have a content-type field.
   - every tiddler actually has a type field in the edit view. 
   - if a tiddler has no content type 'text/vnd.tiddlywiki' is used as the default. 
   - That's the reason why TW works. It's a convenient function, that makes usage easier, but it hides "knowledge" from the user. 

LInks: 
see: https://en.wikipedia.org/wiki/MIME for more info about what mime types are.

**Comment by twMat** [comment]
>IMO if a user types [img[any-image-in-any-format]] she wants to display an image. she doesn't want to specify how it is stored, and how it has to be handled. ... It should just work. 

Well, I agree with this - and this is what I meant with the sniffing. The user should only have to type in `[img[...]]` and the system should itself detect mime-type. The explict "img-image/jpg" was just in case sniffing is not possible, but I'm guessing it *is* possible and it woudl be quite user friendly then.

The overall idea is to make the system "just work" instead of the user; i.e the *equivalent* of a separate tiddler with a _canonical_uri field is temporarily created in memory - or it is actually created, silently, by the system. Currently, you must manually create a tiddler, set a title for it, create a _canonical_uri field with the url, and set the type. AND then apply it in context (i.e transclude it where it should appear). My proposal is to not force the user to go through all this but only the "apply in context", perhaps using the syntax `[img[]]` and have the system do the rest. 

Actually, maybe `{img{...}}` makes more aesthetic sense as we're more or less talking about a transclusion.

...and make it generic so we have one consistent way to use it, i.e: `{text{some remote text}}, `{tid{some remote tiddler}}` etc.

Why should a user be forced to create a whole tiddler just to put a uri into it? The tiddler here is, AFAICT;

* just a placeholder
* that also specifies the mime type
* and relies on the user being on-line to function

Particularly the last bullet makes it a bit funny that you must create a *permanent* tiddler for something that might not even be usable.

We could have a cascading order making ``{{http://foobar}}` first interpret the content as a .tid, then .text, then perhaps the image types etc.

**Comment by pmario** [comment]
I think you are mixing things up here.

It's perfectly fine if you use eg: `[img[./favicon.ico]]` which is the same as: `[img[http://tiddlywiki.com/favicon.ico]`. It will load the external favicon image from http://tiddlywiki.com/favicon.ico 

The difference is, that the first image link uses a relative address, that will also work with a local TW.

The `_cannonical_uri` was introduced, that you could link to external images and tag them. Add additional fields to it and so on.. 

So the function was introduced to do something, that you want to remove now. So just don't use external images the default way and you are good to go. ... but if you image server isn't configured, in the right way to serve images propperly, you may need hardcoded tiddlers. ... or fix your server.

**Comment by twMat** [comment]
Thanks, and yes I probably do mix up a few things, but still this is limited to images. My proposal is to make the syntax generic so we can use the same syntax for using ("transcluding") external objects of other types. 

In the explicit case where you want to add *more* fields to some external _canonical_uri, then such separate tiddlers are fine. But if I just want to include a, say, an external text in the middle of a tiddler (as is hinted we'll be able to do with the Alice exmple) then what to do?

**Comment by pmario** [comment]
I think, it would be possible to add additional possibilities to the existing wikitext. But I think it is already too complicated. IMO we should try to make it simpler and not harder. 

There are some convenience functions included, for most common usecases eg: [img[]]. The other "edge cases" should be solved using the existing features. 

But you are right. We have some consistency problems, but I don't think we can remove them, in a backwards compatible way.

**Comment by twMat** [comment]
I'll "clean up" this proposal (remove my possible misunderstandings that have clarified from your input) and make a new issue and meanwhile close this one. BTW, another option is to edit the opening post here but that would make the succeeding conversation seem irrelevant, so I'm guessing the best way to go about it is to close it, right?
