### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#1946]
Reading up on #1743, I believe TiddlyWiki might benefit from a notification center where messages get logged with a type of icon that shows a count and, upon clicking, a list of messages which can be deleted easily.

There may need to be distinct alerts, those that go into the list of notifications and those that pop up right away.

**Comment by Jermolene** [comment]
@tobibeer there are several related features already in TiddlyWiki (notably "notifications" and "alerts"). How would your proposal differ or integrate with the existing functionality?

**Comment by tobibeer** [comment]
They would differ in that on mobile there would be less distractions, e.g. failed communication attempts... being logged to a hidden list and displayed when the user actively choses to see them.

**Comment by Jermolene** [comment]
Is it a new thing, or a different way of presenting existing notifications or alerts? Is the idea really at the point where a ticket is useful?

**Comment by tobibeer** [comment]
We have no notification icon / center right now indicating that there are messages wanting to tell me something, while not being so intrusive as to do it out loud via the alert ui.

We can discuss "conceptual topics" more off Github on the groups, fine with me.

**Comment by tobibeer** [comment]
So, I'll close this.

**Comment by Jermolene** [comment]
I do agree that notifications/alerts/warnings could do with reorganisation and consolidation. But I think any proposal needs to deal with the existing mechanisms; the worst thing would be to just add a new mechanism alongside all the others -- leading to the bloat issues we've been discussing elsewhere.

Right now, the situation is that notifications are ephemeral and alerts require user action to dismiss. Notifications are implemented as widget messages, while alerts are implemented as specially tagged tiddlers that overlay the main story river. There's also wizards/modals, of course, which share some characteristics and use cases.

I think notifications should stay ephemeral; they are designed to be missable. We shouldn't use them for confirmations (as we do with TiddlySpot saving). It would be better to have unambiguous visual indication of the state of being unconfirmed (ie a warning should appear if saving fails, not so much if it succeeds).

Alerts are primarily used for sync errors at the moment. As discussed in #1743, the user experience is pretty poor at the moment. Alerts are probably the wrong way to handle sync errors.

@twMat has proved to have some prowess at producing mockups; perhaps you could work together to propose something more concrete?

**Comment by felixhayashi** [comment]
@tobibeer Just to understand what you envisioned, you are talking about something like the GitHub "you have unread notifications" bell?

**Comment by tobibeer** [comment]
Yes, something that is less intrusive as having an alert or notification pop up.

**Comment by felixhayashi** [comment]
Maybe a plugin could be written that adds a tab in the sidebar (or elsewhere) and keeps track of alerts and notifications and hides them from direct display. This plugin would be for users that do not wish direct confrontation with alerts or notifications. It does not add a third way of informing the user but rather changes the way messages are displayed. But that's just an idea…

**Comment by tobibeer** [comment]
That would be a good ui, I think, an icon tab that has the messages in it... and is capable of displaying a count in the tab-name.

**Comment by twMat** [comment]
>@twMat has proved to have some prowess at producing moc

I'd be happy to help along if you think I can.

>a tab in the sidebar (or elsewhere)

While that's a nice idea *per se*, I feel there has evolved a bit of a standard for "alerts about messages" to be something like the bell icon here in Github or as seen in the google services etc. IMO this should be fine, as long as you can set what type of messages it is you want to trigger the alert icon for them.

A tab would also be tricky in that it is either permanently visible or made to pupup when there's something to show (vibes of #1066 ). Either way, this is a bit distracting in that it's not the user who triggers it, don't you think? There's not much room for sidebar tabs, even if they're icons, whereas e.g the topbar is totally underused..

For people who really don't want any messages, perhaps a tab in Ctrlpanel would make sense? That would at least be better if it is a permanent tab.

>...an icon tab that has the messages in it... and is capable of displaying a count in the tab-name, overlay style

I like the "display count" idea. Icon tabs are nice too - but deviates from current UI. However, we do have the toolbar buttons that are icons and they are also in the sidebar, if that's what one is after. It could be a button very similar to the Ctrlpanel sidebar button.

...which might also make sense if the messages are longer because it is of course not very good to display longer messages inside a sidebar tab (problems linebreaks etc). ...possibly doable with accordion type menus or text fading to show part of the alert and clicking on it opens it in full in the river column or as popup or something.

Its worth considering that in the future we might also have other messages such as update alerts, messages from other TWs/people etc.

**Comment by tobibeer** [comment]
I think hiding it in the controlpanel is not an option as "the bell" or whichever indicator needs to be visible at all times.

**Comment by twMat** [comment]
Yea, the point was if people really don't want any messages. One could imagine an *optional* bell, i.e visible at all time that when clicked opens the Ctrlpanel for the actual center - but possible to disable from showing, in which case the center is still in the Ctrolpanel.

**Comment by tobibeer** [comment]
Yes, after all, "the bell" would only be relevant for "editors" and not really for a wiki that is designed for "visitors".
