### ISSUE TITLE
Cannot delete tiddler when running Node.js server with password

### ISSUE THREAD

**Issue by tgrosinger** [Jermolene/TiddlyWiki5#1975]
```
tony@myhost:~$ tiddlywiki --version
5.1.9
tony@myhost:~$ node --version
v0.10.25
```

When I start the server I am using a command like this:

```
tiddlywiki mywiki --server --password MyPassword
```

I can then create, view, and edit tiddlers in the browser without any problems. Deleting however never seems to be successful. When a tiddler is deleted I wait for the save icon to turn grey again, then refresh the page. After decrypting I find that the tiddler has returned.

This does not happen when the server is run without a password.

**Comment by tgrosinger** [comment]
When running the server with `--verbose` I see this message go by:

```
syncer-server: Dispatching 'delete' task: Draft of 'Tesing again'
FileSystem: Deleted file /home/tony/atrium/tiddlers/Draft_of_'Tesing_again'.tid
```

Seems to indicate to me that the problem exists because the only way to delete a tiddler is by editing it first. When in edit mode however the title changes, so clicking delete removes the draft, not the actual tiddler.

**Comment by tgrosinger** [comment]
It seems to fail intermittently. I performed another test and saw this in the logs:

```
syncer-server: Dispatching 'delete' task: Draft of 'Delete Me'
FileSystem: Deleted file /home/tony/atrium/tiddlers/Draft_of_'Delete_Me'.tid
syncer-server: Dispatching 'delete' task: Delete Me
FileSystem: Deleted file /home/tony/atrium/tiddlers/Delete_Me.tid
```

And it did in fact delete both the draft and the tiddler.

**Comment by tobibeer** [comment]
It's possible — since deleting in view-mode has only been made available not too long ago — that the node side of things fell short.

**Comment by Jermolene** [comment]
Hi @tgrosinger 

The first thing is that `--password MyPassword` is only intended for producing encrypted standalone TiddlyWiki HTML files. It isn't designed to work in the client-server configuration.

There is no support for encryption with the client-server configuration because the expectation is that users needing encryption would run the server over SSL.

> Seems to indicate to me that the problem exists because the only way to delete a tiddler is by editing it first. When in edit mode however the title changes, so clicking delete removes the draft, not the actual tiddler.

If you click a tiddler into edit mode and delete it, both the draft and the original tiddler are deleted. I think some of the confusion here might be the way that changes are buffered in the browser and the server. To avoid repeatedly saving the same tiddler during typing, tiddlers are only synced if they haven't changed for a few hundred milliseconds (there is another timeout to ensure that they get synced after 10 seconds regardless).

Thus, if you perform some operations quickly in the browser, you'll never see the corresponding store operations in the console of the server. I think that's why you're seeing intermittent behaviour.

> It's possible — since deleting in view-mode has only been made available not too long ago — that the node side of things fell short.

I don't think that that has any bearing.

**Comment by tgrosinger** [comment]
Oh interesting, I misunderstood the password option. I am running under SSL, but how can I achieve password protection? Should I just use [Apache auth](http://httpd.apache.org/docs/2.2/mod/mod_auth_basic.html)?

**Comment by tgrosinger** [comment]
Ah, I found the key in the docs:

```
--server 8080 $:/core/save/all text/plain text/html MyUserName passw0rd
```
