### ISSUE TITLE
Expand getTiddlerData and setText functionality

### ISSUE THREAD

**Issue by tgrosinger** [Jermolene/TiddlyWiki5#1998]
Example data tiddler

``` json
{
    "item-1": {"value-1": 1, "value-2": 2},
    "item-2": {"value-1": 1, "value-2": 2}
}
```

Currently with `$tw.wiki.getTiddlerData` I can retrieve the whole body of the document as a javascript object. I can also set top level items with `$tw.wiki.setText`, however it would be impossibly to directly update `.item-1.value-1` directly without retrieving the full body and updating item-1 and then using `setText`.

I am not yet sure what this would look like, but it would be very nice to expand the support for data tiddlers to allow arbitrary (or at least a little more powerful) interaction. Possibly something along the lines of the selectors used by [jq](https://stedolan.github.io/jq/manual/#Basicfilters) could be used to specify what value to set or retrieve.

[impetus for this feature](https://groups.google.com/d/msg/tiddlywikidev/_w-jcVlswac/7E6AcoaaAQAJ)

**Comment by felixhayashi** [comment]
Hi @tgrosinger 

> however it would be impossibly to directly update .item-1.value-1 directly without retrieving the full body and updating item-1 and then using setText.

This sounds like you want to do a "blind write" without reading the existing property, correct? But `$tw.wiki.setText(tRef, null, prop, value);` does exactly what you want. You don't need to retrieve the object first.

E.g. try the following (notice that `sjdkfhksj` doesn't need to exist).

$tw.wiki.setText("sjdkfhksj", null, "foo", "bar");
$tw.wiki.setText("sjdkfhksj", null, "foo2", "bar");

and then look at the result.

**Comment by Jermolene** [comment]
Hi @tgrosinger are you looking for the ability to manipulate non-top level properties within a data tiddler?

One way we could accomplish that is to extend the text reference syntax. For example, `{{my-tiddler##item-1##value-1}}` would return 1 with your example data tiddler.

It's a conceptually simple change but the present implementation means that quite a few parts of the code would need to be touched.

**Comment by felixhayashi** [comment]
> Hi @tgrosinger are you looking for the ability to manipulate non-top level properties within a data tiddler?

Ok seems like I misread the question.

**Comment by tgrosinger** [comment]
@Jermolene, that's exactly what I meant. I was thinking we could use something like what jq users. 

For example:  `.key-1.value-1[0:2]` would reference just the "return-this" values in the document below.

```
{
    "key-1": {
        "value-1": [
            "return-this-0",
            "return-this-1",
            "return-this-2",
        ],
        "value-2": [
            "dont-return-this-0",
            "dont-return-this-1",
            "dont-return-this-2",
        ]
}
```

And this could be used both to reference the items that should be returned in `getTiddlerData` and the items that should be updated with `setText`.

**Comment by tobibeer** [comment]
The function could read...

`exports.getTiddlerData = function(titleOrTiddler,defaultData,path) { ...`

rather than just...

`exports.getTiddlerData = function(titleOrTiddler,defaultData) { ...`

For text references, I think a JSON query should be prefixed by something specific, rather than use hard to read namespace delimiters like `##`, e.g.:

`{{JSON=>SomeTiddler##down.the.json.namespace}}`

instead of...

`{{SomeTiddler##downt##he##json##namespace}}`

**Comment by inmysocks** [comment]
as much as I would like to have a more concise shorthand I think that remaining consistent when using the {{foo##bar}} syntax would be more important. While we may not be targeting people who have no knowledge of computers I think that it is still important that we try to make everything as understandable as possible to make the lowest barrier to entry for learning wikitext.
Adding a new delimiter would also further limit the acceptable labels for data tiddlers, but that isn't as big a concern.

I think that adding extra options and using the transclude widget would be a better way to go for supporting other data structures, or perhaps a dataread widget that sets variables according to the content being read. While it isn't as convenient, I think that a new widget would be the easiest way to add the ability to use other structures without worrying about breaking any existing code.
I can't think of any situation where you could use {{foo##bar}} that couldn't also be done using something like
<$dataread $variable=someName $value=foo.bar $type=xml>
(use the variable however you want here)
</$dataread>
where the delimiters would be whatever works well. Maybe to make things more flexible there could be an optional $deliminator='.' that lets you set it if you don't want to use the default.

There may be problems with refreshing, but it shouldn't add any problems that don't already exist.

**Comment by tobibeer** [comment]
@inmysocks, the issue is that we want to access those data via text-reference, so another widget is not the solution.

This would not introduce new delimiters, but rather just qualify how to interpret the data-accessor being defined...

```
{{SomeTiddler##down.the.json.namespace<=JSON}}
```

When anyone uses a construct like JSON, I expect them to be able to handle such a syntax rule.

**Comment by tgrosinger** [comment]
@tobibeer, your text-reference link seems to be broken. What did you mean by that?
@inmysocks, like Tobias said, I would like to be able to use this data retrieval from a javascript plugin, not just from wikitext (but I am new around here, so I could very well be just missing something).

**Comment by inmysocks** [comment]
@tobibeer I don't think there is any reason to assume that someone would need to understand complex JSON objects as anything more complex than a table of contents with sub-headings. I am not thinking in terms of if someone can handle the rule, I am thinking about making things easy for someone with no knowledge of the system to learn and apply the rules. I think that expecting a user to learn something outside the scope of tiddlywiki in order to use a feature is going to lead to features being unusable to anyone who isn't a developer.

In the context of making a plugin for a limited audience then there isn't a problem, but if this is going to be proposed as a change to the core than it should require as little knowledge and learning as possible to use or it will just be unused code taking up space.

@tgrosinger I think we are talking about different things then. I am not talking about accessing things from within a javascript plugin. I think I am talking about how what you would like to implement would be exposed when using wikitext. We have to find a solution to what you are talking about before what I am thinking about becomes relevant.

**Comment by tobibeer** [comment]
@inmysocks

>  I think that expecting a user to learn something outside the scope of tiddlywiki in order to use a feature is going to lead to features being unusable to anyone who isn't a developer.

You see, if you want to use JSON, you need to know and learn at least the basics of JSON, rather than coerce it's pretty slick semantics into something else, e.g. from

`foo.bar.baz`

into...

`foo##bar##baz`

This is gibberish to anyone who speaks JSON.. and makes implementation all the harder!

**Comment by inmysocks** [comment]
When I asked my girlfriend if she knew what JSON was she had no idea, but she makes things in tiddlywiki that use data tiddlers. JSON is very simple and easy to use and foo##bar##baz is gibberish when in the context of JSON. I am not disagreeing with any of that. My point is that any modifications to the core aren't in the context of json, they are in the context of tiddlywiki.
In tiddlywiki a text reference like {{foo##bar}} makes sense, and the extension of that which makes sense in tiddlywiki is {{foo##bar##baz}}. If we abandon that in favour of something that makes more sense for JSON and for people who have a background manipulating data structures in non-tiddlywiki contexts than there is a disconnect between existing methods that are understood by users and the new methods which, for not-tiddlywiki reasons, are better in some sense. This gives users two different competing ways of addressing data, one which fits the conventions used everywhere else in tiddlywiki and one which fits conventions used outside of tiddlywiki. Sticking to conventions used in tiddlywiki and making people who have experience or knowledge of other systems use tiddlywikis conventions puts the extra effort on the people who necessarily have some background in a developer context instead of on every user, many of whom have no developer background at all.

For things like this, if they are going to be part of the core, the primary design criteria should be if they work well with what already exists in tiddlywiki, coding and the back end has to support that, not the other way around. I am not disagreeing with you about which one makes more sense in a wider context, but for what we have now that is mostly irrelevant.

Jeremy mentioned the eventual version 5.2.0 somewhere recently. For the purposes of planning that version, maintaining a list of things like this that could be done better but require some deeper changes to tiddlywiki is a good idea. We could reference that when making changes in order to make the transition to a potential future version easier.

**Comment by felixhayashi** [comment]
In case of the syntax to access nested properties from wikitext I agree with @inmysocks when he says

> In tiddlywiki a text reference like {{foo##bar}} makes sense, and the extension of that which makes sense in tiddlywiki is {{foo##bar##baz}}.

It looks strange to write `foo#bar.x`. @tobibeer Also what if a dot is used as part of a property key `{ "foo.bar" : "hello" }`? – it would break the system :)

**Comment by tobibeer** [comment]
> Also what if a dot is used as part of a property key { "foo.bar" : "hello" }? – it would break the system :)

Not at all, that's what the suffix is for...

```
{{SomeTid##foo.bar<=JSON}}
```

**Comment by tobibeer** [comment]
To be precise, using a dot in an object key forces you to not use dot notation, so the proper way to address it would probably be something like...

```
{{SomeTid##["foo.bar"]["baz.mumble"].frotz.gronk:JSON}}
```

...evaled against a parsed JSON object tree.

**Comment by tobibeer** [comment]
I also see this in connection with #1947 as I'd like to be able to address any given field like that, rather than be required to have a(nother) data tiddler of a certain kind.

I simply want to point to some text and tell whichever new widgetry that I wish that interpreted as JSON, i.e. a list widget iterating over indexes and then another widget to pull data from that index, optimally using the data already read and parsed and cached by the outer list widget.

**Comment by tgrosinger** [comment]
> I simply want to point to some text and tell whichever new widgetry that I wish that interpreted as JSON, i.e. a list widget iterating over indexes and then another widget to pull data from that index, optimally using the data already read and parsed and cached by the outer list widget.

Ohh, this is a great idea. Having the benefits of JSON-indexed access without needing a separate tiddler.

**Comment by tobibeer** [comment]
>  optimally using the data already read and parsed and cached by the outer list widget.

Perhaps a plugin-like-multi-line-json-string could be unpacked upon access using the plugin-unpacking mechanism to make things more simple under the hood, e.g.

* `$:/temp/json/some-tiddler-title/some-multi-line-field-of-it/index-foo`
    * represents a tiddler encoded into a plugin-like-json-string unpacked to the above location
* `$:/temp/json/some-tiddler-title/some-multi-line-field-of-it`
    * holds an ordered list of all indexes in that field in its `list` field

So, we can easily iterate over those indexed shadows, perhaps with a filter that provides a shortcut to access such an extracted-from-a-json-field-tiddler with respect to `<<currentTiddler>>`, e.g.

* `filter="[json[json-field]]`
    * this **json** filter could return the above shadow tiddler as extracted from a field called **json-field** of the current tiddler at `<<currentIndex>>` being the variable generated by the list, intrisically interpreted by this **json** filter
    * we could then do something like...
        * `filter="[json[json-field]get[checked]]`
        * retrieves the field **checked** of the shadowtiddler at `<<currentIndex>>`

**Comment by pmario** [comment]
@Jermolene -- IMO This can be closed since we do have all the JSONxxx "set" and "get" operators now

**Comment by Jermolene** [comment]
Thank you @pmario
