### ISSUE TITLE
Internal JavaScript Error -  Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by leizard** [Jermolene/TiddlyWiki5#2032]
Hi,
There 's Error happen with my wiki page, how can I fix it ?

[My tiddy wiki page](http://namsoft.tiddlyspot.com/)

**Comment by pmario** [comment]
Hi @leizard 
You have a recursive dependency. The easiest way is: 

* make a backup first :)
* save / download your own wiki from your link provided above. 
   * since the tab states are not saved your wiki from the file will open with the "Open" tab selected. 
* Copy the following string: `Setask có sử dụng các ''Phím tắt" không?` to the clipboard.
* paste this string into your search input box. 
* now open the tiddler
* enter edit mode and **remove** the FAQ tag. 
* save -> done.

**Comment by pmario** [comment]
The circular tagging causes your problem. But I have some remarks too. 

Your title `Setask có sử dụng các ''Phím tắt" không?` has 2 single quotes in front of the words `''Phím tắt"` and 1 double quote after `tắt"`. ... Is that by design? 

I think this will also cause some usability trouble in the future. IMO nobody will remember how to write this title correctly.

**Comment by leizard** [comment]
@pmario sr I don't undestand clearly. The error broke down the app so I can't use any function. How can search, or open the tiddle and edit it.
About the single quotes mistake, it 's my editing fault, I definitely will fix this. But is it that easy to make the entire app break down due to some typing mistake ?

**Comment by pmario** [comment]
You need to avoid the dialog. ... If you do exactly as I posted here, it works. I did test it. -> See the second step. you need to download your tw from your own link you posed here.

**Comment by leizard** [comment]
Hi @pmario,
Does "download" mean Ctrl + S in the browser ? If so, I downloaded it to my local machine. And when I open the local file, it still crash and can't do anything with it.

**Comment by leizard** [comment]
somehow I manage to edit the tiddler directly in the tiddlyspot by enter the link to Setask có sử dụng các ''Phím tắt" không? tiddler. It seems fix the recursive issue. but now my wiki page is extremely slow, and when I use the search tool, it crashed with Stack overflow issue. What happens now ?

**Comment by tobibeer** [comment]
> Does "download" mean Ctrl + S in the browser ? If so, I downloaded it to my local machine. And when I opened the local file, it still crashed and couldn't do anything with it.

Downloaing means...

1. right click this link: http://namsoft.tiddlyspot.com/
2. save target as
3. now you have a local copy on your disk that you can edit (in a text editor)

Alternatively, see: http://tiddlywiki.com/#SafeMode

**Comment by pmario** [comment]
>somehow I manage to edit the tiddler directly in the tiddlyspot by enter the link to Setask có sử dụng các ''Phím tắt" không? tiddler. It seems fix the recursive issue. 

good :)

>but now my wiki page is extremely slow, and when I use the search tool, it crashed with Stack overflow issue. What happens now ?

For me it works quit well. ... You could do a browser page reload with a clean cache with: `<shift> reload button`

**Comment by leizard** [comment]
thank you @pmario and @tobibeer for supporting me. it works well again :)
