### ISSUE TITLE
"click button" penalty since alpha 13

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#206]
If I click a sidebar tab, more shadow tab or close tiddler button, ... , I get a penalty of about 600ms until any action happens. 

Chrome seems to add 400ms which is better, but still annoying.

**Comment by davidag** [comment]
Hello, I am suffering this problem since I upgraded to 5.1.4 from Classic.

My current environment is:

* TiddlyWiki 5.1.9
* Firefox 41.0
* OS X Yosemite

When the "Recent" tab is open, text editing has lag and quickly becomes quite annoying. If you are having this issue, just change to other tab...

Thank you for your work!
