### ISSUE TITLE
sort by evaluated filter expression

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2063]
Allow to sort items with respect to the output of a filter expression evaluated against the item title.

For that purpose, perhaps introduce a suffix / flag to all of the available sort filters that instructs them to sort by the evaluated operand, e.g.:

```
<$vars sortfilter="[<currentTiddler>tagging[]]">
{{{ [sort:eval<sortfilter>] }}}
</$vars>
```

In other words:

Sort the input elements by the output of evaluating the specified operand as a filter expression against the **currentTiddler** being iterated as the item.

Equivalently:

```
{{{ [sortcs:eval<sortfilter>] }}}
```
### Counter Use Case

This sorts by a "virtual" count that is dynamically computed rather than a field:

```
<$vars sortfilter="[<currentTiddler>tagging[]count[]]">
<<list-links filter:"[tags[]sort:eval<sortfilter>]">>
</$vars>
```

...assuming there was a count filter to begin with.
## Caching

With #2064, none of the above would possibly be necessary.
## Discussion

https://groups.google.com/d/msg/tiddlywiki/HF0wPbmY3qY/SYguYbtoAQAJ

**Comment by Jermolene** [comment]
Hi @tobibeer as you've noted, the problem with this approach is the way that it requires the re-computation of the sort filter for each item in the main list. That's quite a severe problem because parsing and processing a filter is pretty slow.

An alternative approach might be to compute the list of virtual fields first, storing them as a list in a variable, and then reference that list within the sort filter operation. For example:

```
<$set name="sortList" filter="[tags[]sort[]tagging-count[]]">
<$list filter="[tags[]sort[]sort-by-list<sortList>]" template="FooBar">
</$set>
```

The imaginary "tagging-count" operator replaces each item in the list with the count of the number of times that that item is used as a tag.

The "sort-by-list" operator would sort the values in the sort list, and then apply the same reorderings to the list of items that were passed in.

So, imagine that we've got the following tag counts:

```
alpha: 23
beta: 46
gamma: 12
```

The variable `sortList` would end up as `23 46 12`.

The processing of the main list widget would go like this:

* Start with all tags: `alpha beta gamma`
* Sort to: `alpha beta gamma`
* Sort-by-list: first we sort the values in `sortList`, giving us `12 23 46`. Then we apply the same transformation to the source list, giving us `gamma alpha beta`

**Comment by tobibeer** [comment]
> the problem with this approach is the way that it requires the re-computation of the sort filter for each item in the main list. That's quite a severe problem because parsing and processing a filter is pretty slow.

Makes sense to evaluate once against the set and not per item. I guess the `sort[]` part in your example can be skipped.

However, an individual sort-by-list or perhaps **listsort** filter requires that all the core sort algorithms are exposed as well, possibly via suffix, e.g.:

```
<$set name="sortList" filter="[tags[]tagging-count[]]">
{{{ [tags[]listsort:cs<sortList>] }}}
</$set>
```

Optimally, the filter would not implement those algorithms via its own code but rather leverage some core sort function that does the corresponding sorting, e.g.:

```
$tw.wiki.sort(list,reverse,method)
```

**Comment by saqimtiaz** [comment]
@Jermolene this can be closed thanks to the introduction of the `sortsub` operator.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
