### ISSUE TITLE
addsuffix for ] (closing square bracket)

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2080]
Allow to add a closing square bracket as a suffix or perhaps provide a generalized way to escape it in the operand, e.g. `addsuffix[\]]`.

**Comment by pmario** [comment]
Do you have an example use case?

----------------

There are some discussions already, about "a generalized way" to escape certain characters in TW. I can't find the links atm ... 

The main problem here is, that we have no character left, that can be used for our escape mechanism. TW needs to work with OS X, Linux and Windows. So a backslash `\` isn't an option, since its valid in windows and causes a lot of problems with path names. ... That's why my question about the use case.

**Comment by tobibeer** [comment]
I am only talking about being able to use a closing square bracket in a filter expression as a character.

I there is at least one issue about generally excaping characters in wikitext, but this is **not** one of them, so please don't reference any such discussion here. To me, they're unrelated.

An example would be to concatenate filder components into a big filter expression as I am trying to achieve using the [[join filter|http://joinfilter.tiddlyspot.com]] I just wrote ...which, however, faces another frequently encountered problem: that of telling a widget to update itself when there are changes to certain tiddlers, perhaps tiddlers matching a filter, or tiddlers referenced in text-references used in widget attributes (including macros).

**Comment by Jermolene** [comment]
There's already a couple of ways to include "illegal" characters in filters: transclude the operand value from a variable or a tiddler field.

**Comment by tobibeer** [comment]
@Jermolene, good point and a viable option that I forgot. However, such a variable will know nothing of the item we're currently iterating in the filter expression. That's actually why I created the **join** filter, see #2084.
