### ISSUE TITLE
refreshing widgets

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2081]
Ever so often, a user is faced the problem of widgets not refreshing as expected.

Therefore, devise a general approach by which **any** widget is automatically aware of any requirements to refresh itself, e.g.:

1. a generic **$refresh-filter** attribute could be used at any widget to specify a filter expression whereas any changes to tiddlers matching the filter triggers a refresh of the widget
2. a mechanism whereby any **text references** being used as **widget attributes** are automatically added to a "watch-list" and the widget refreshed upon changes to those text references
    1. this may possibly need to be extended to text references used in **macros** that are used as widget attributes

**Comment by tobibeer** [comment]
Good news: Just tested the above example with the prerelease version and there the list widget updates properly.

**Comment by tobibeer** [comment]
Am I correct that 2. from the issue description is already implemented for [5.1.10-prerelease](http://tiddlywiki.com/prerelease/)?

**Comment by Jermolene** [comment]
Hi @tobibeer widgets already have full control over their own refreshing, and they already track changes to attribute values to figure out if something needs refreshing.

If you're seeing different results in 5.1.10 it's because of some other change.

I'm guessing that you haven't actually looked to see how the widget refreshing process works? I'd recommend studying some of the simpler widgets; there's really not much to it, and the refreshing circuitry is pretty self-evident.

**Comment by Jermolene** [comment]
The example for your join filter is too complex for me to readily see what problem you are pointing at, can you provide a more minimal test case?

**Comment by tobibeer** [comment]
@Jermolene that example does no longer have the mentioned problem, since 5.1.10 fixes the refresh handling for the list widget.
