### ISSUE TITLE
edit-text widget refresh problem with non-existing tiddler

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2111]
The edit-text widget appears to refesh depending on whether or not the target tiddler being edited exists or not, e.g.:

```
<$tiddler tiddler="$:/temp/foo">
<$edit-text default="" placeholder=""/>
<$button>
<$action-setfield $tiddler="Foo" text={{!!text}}/>
<$action-deletetiddler $tiddler=<<currentTiddler>>/>
{{$:/core/images/new-button}}
</$button>
</$tiddler>

[[Foo]]
```

Since I am editing a temporary tiddler, this breaks the flow of writing, as the editor loses focus when the first character is entered.

**NB:** As for the example above, I would like to also instruct action-setfield to generate a unique tiddler title when actioned, rather than a fixed one, e.g.:

```
<$action-setfield $tiddler="Foo" text={{!!text}} title-suffix="unique"/>
<$action-setfield $tiddler="Foo" text={{!!text}} title-suffix="date"/>
<$action-setfield $tiddler="Foo" text={{!!text}} title-suffix="random"/>
<$action-setfield $tiddler="Foo" text={{!!text}} title-suffix="uuid"/>
```

**Comment by Jermolene** [comment]
Hi @tobibeer a useful technique to debug things like this is to insert the macro `<<now "YYYY-MM-DD hh:mm:ss">>`. You'll then be able to see when the macro is refreshed by the time changing.

In this case, if you insert the macro just before the edit-text widget you'll see that the first character typed actually causes the tiddler widget to refresh.

If you look at the [source of the tiddler widget](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/tiddler.js) you'll see that a tiddler transitioning from missing to not missing will always cause a refresh. This is done so that the variables you [see here](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/widgets/tiddler.js#L42-L45) are set correctly.

**Comment by tobibeer** [comment]
Mhhh, @Jermolene, I still would not know how I can edit a temporary tiddler without my editor being refreshed while typing. The edit-text widget in the example above appears quite separate from the button widget that uses the now macro.

**Comment by Jermolene** [comment]
Hi @tobibeer have you tried moving the edit text widget outside of the tiddler widget?

**Comment by tobibeer** [comment]
Just did, thanks:

```
<$vars temp="$:/temp/foo">
<$edit-text tiddler=<<temp>> default="" placeholder=""/>
<$button>
<$action-setfield $tiddler="Foo" text=<<temp>>/>
<$action-deletetiddler $tiddler=<<temp>>/>
{{$:/core/images/new-button}}
</$button>
</$vars>

[[Foo]]
```
