### ISSUE TITLE
Import dropzone is overly greedy

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2157]
This was "side mention" in #592 , a now closed issue, but the problem remains and I think it is not an unreasonable request because the problem occurs when the user performs a very standard procedure:
 
In editmode if I merely wish to relocate a text portion by selecting+dragging it to another place - even still within the tiddler editor - the green "Drop here" is triggered. The green also doesn't go away, but it shouldn't trigger to begin with, imo, *at least not* if the dragging is still within the editor.

In the closed #592 it was suggested to look at object origin. Judging from current behaviour I conclude this was not implemented or fruitful. An alternative might be to use some kind of qualifier, i.e to somehow sense the *type* of the object - i.e if it is a tiddler or an image etc. Mere text is disqualified and drop zone not triggered.

**Comment by tobibeer** [comment]
I think it's only right that the drop-here zone appears. After all, that is its purpose and it is literally what you can use it for within the same wiki, even if starting to drag from an editor.

I do want it to show whenever dragging is going on and I don't find it confusing when it shows up even if I would not need it to. Also, for me, it disappears if I drag and drop text within the same editor.

So, in the context of this issue, under what conditions would you not want the drop-zone to appear and why exactly? "Because I don't need it" is not a good reason for me if others actually do find it useful ...under the very same conditions.

**Comment by twMat** [comment]
Ok, I don't see when/why anyone *would* want to import from their own TW? The unnecessarily appearing greeny is not a matter of "not needing it" as much as it is a matter of it being distracting - BUT admittedly, much of it comes from the fact that the greeny *stays* there in FF. Glad to note it works in Chrome tho!

...but I guess means this is mostly a matter of #686. Not fully, but enough for me to not consider my OP important enough on its own and I'm therefore closing the issue.

**Comment by felixhayashi** [comment]
> fact that the greeny stays there in FF. 

True.
