### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by K0ertis** [Jermolene/TiddlyWiki5#2216]
Hi! I added the plugin into my TW5, but it does not work. I added manually the file $:/config/CodeMirror for close brackets automatically. But it does not work at all.

Thanks for your help!

**Comment by pmario** [comment]
Please describe your problem a bit closer. .. Without more concrete info I'd say: "You did it wrong". 
So. 

 - How did you include a plugin?
 - Which plugin. I assume it's the codemirror plugin.
 - Did you check the cm edition at: http://tiddlywiki.com/plugins/tiddlywiki/codemirror/

**Comment by K0ertis** [comment]
Oh sorry, of course: 
* I included the codemirror plugin by drag and drop **$:/plugins/tiddlywiki/codemirror**
* After save and reload I made the changes on **$:/config/CodeMirror** as described in http://tiddlywiki.com/plugins/tiddlywiki/codemirror/ and added **$:/plugins/tiddlywiki/codemirror/addon/edit/closebrackets.js**

Shouldn't that be enough?

**Comment by tobibeer** [comment]
@K0ertis, please update the issue description so that it indicates that it is about the codemirror plugin.

**Comment by pmario** [comment]
did you check the edition link?

**Comment by K0ertis** [comment]
Hi! I do not get it, sorry! I checked the edition link and when I edit " LoremIpsum" nothing happens. Am I right: I must see auto completion?

**Comment by pmario** [comment]
@K0ertis I'm sorry. I thought there is much more documentation included. ... but it's probably just in my head for the tw-classic version :/   I'm not using codemirror with tw5 atm. 

have a look at: http://tiddlywiki.com/plugins/tiddlywiki/codemirror/#%24%3A%2Fplugins%2Ftiddlywiki%2Fcodemirror%2Fusage

I'm not sure, if "auto completion" is implemented at the moment. At least I don't see any code for it. auto completion would be a different library for every language you need. 

So the basic function of this library is code highlighting, search and auto-indent. emacs and vim keyboard handling. (I personally would remove both of them, because they only add bloat if not used.)

make sure you have a working `$:/config/CodeMirror` tiddler as described at the usage tiddler. 

--------------

@ everyone who reads this. ... This plugin definitely would need some more love, to make it easier to use :)

**Comment by K0ertis** [comment]
Hi Thanks, now I got it to work! I also added the AutoCloseBrackets library but it occurs the following error:  

```Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: cm.triggerElectric is not a function```

> @ everyone who reads this. ... This plugin definitely would need some more love, to make it easier to use :)

Certainly :+1: 

Thanks

**Comment by Jermolene** [comment]
Hi @K0ertis the upcoming 5.1.12 release does include significant improvements to the CodeMirror plugin:

http://tiddlywiki.com/prerelease/plugins/tiddlywiki/codemirror

It now includes built-in syntax highlighting for HTML, JavaScript, CSS, XML, TiddlyWiki Classic and Markdown. Bracket-matching is also enabled, which turns out to be very useful when typing wikitext.

**Comment by tgrosinger** [comment]
Can this issue be marked as closed? It seem resolved, or at the very least dead.

**Comment by pmario** [comment]
@Jermolene .. K0ertis worte: 

>Hi Thanks, now I got it to work!

So should be closed.

**Comment by Jermolene** [comment]
Thanks @pmario.
