### ISSUE TITLE
have CheckboxWidget trigger actions

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2217]
It appears that one cannot embed further actions in a checkbox. This is unfortunate as there may be lists where the checkbox is used as a type of button where it is needed to actually perform two actions when clicked.

**Comment by matabele** [comment]
@tobibeer 
The widget could be modified to trigger actions, but the same actions would be triggered for a check or uncheck (or, I suppose there could be an option to select one or other.) 

How would it be possible for the widget to trigger one set of actions when checked, and another when unchecked?

**Comment by tobibeer** [comment]
> The widget could be modified to trigger actions, but the same actions would be triggered for a check or uncheck (or, I suppose there could be an option to select one or other.)

Sure, but you could use the list widget for conditionals.

**Comment by Jermolene** [comment]
I don't have the reference to hand to the earlier discussion but there is a fundamental problem with implementing action widgets for widgets like the checkbox widget that modify the tiddler store. The trouble is that when the action is triggered the tiddler store will have been changed, but the refresh cycle won't have had a chance to update the widget tree with the new values.

**Comment by tobibeer** [comment]
I think it is important we find that reference. Because one way or the other, there is a reliable refresh behavior. Either the inner widgets kicks in first or the outer checkbox does. So, both will have to act on independent data otherwise things won't work out.

**Comment by inmysocks** [comment]
The checkbox, select and radio widgets may not be able to trigger action widgets in any useful way. Their behaviour is consistent but the explanation of how it works requires more understanding than I think we should expect users to have. 

It also allows things like setting a field using the checkbox and then putting an action-setfield widget inside the checkbox widget that changes the same field as the checkbox.

**Comment by tobibeer** [comment]
> It also allows things like setting a field using the checkbox and then putting an action-setfield widget inside the checkbox widget that changes the same field as the checkbox.

That's the thing that needs communicating in quite some other way!

If a user is to trigger actions within a checkbox / radio / button …then those actions must NEVER be performed against some (state of a given) tiddler that is currently touched by the outer widget. These actions can only perform changes to independent OTHER tiddlers.

**Comment by inmysocks** [comment]
Yes, but there isn't currently any reasonable way to achieve that. And it would be very confusing to any users that don't understand the reasoning behind the behaviour if we could make it work.

This is one of the problems that we have from when the focus shifted to action widgets. Without some significant changes to the widgets we can't safely add this behaviour.

I have been thinking about this a bit and if we add an attribute to each of the widgets that sets the default behaviour we may be able to get something. For example, if we set an attribute on the select widget it would ignore the default behaviour and when you select an option it would instead invoke whatever action widgets are listed in that option as though it were a list of buttons instead of a normal select widget.
There is still a problem of ensuring that the correct option is displayed by the widget after the selection, but that may have to be left to the user to define.

Here is a quick code mock-up of what I am talking about:

<$select mode=actions tiddler=text field=text>
<option>Option 1<$action-setfield $tiddler=test text='Option 1'/><$action-setfield $tiddler=someothertiddler foo='Option 1'/></option>
<option>Option 2<$action-setfield $tiddler=test text='Option 2'/><$action-setfield $tiddler=someothertiddler foo='Option 2'/></option>
</$select>

The tiddler and field attributes of the select widget would determine the state displayed by the widget but the action of the widget would be determined by the action widgets in each option.

The radio and checkbox widgets could have similar changes, but I think that changing them to allow this sort of behaviour would make them equivalent to button widgets.

**Comment by tobibeer** [comment]
An action widget like a checkbox, select or radio must always perform its actions. It must not be, either it does its thing otherwise we trigger actions contained.

Any other contained **action-foo-bar-baz** widgets contained in a select, radio or checkbox are always run independently.

To make sure contained action widgets are not clashing with some outer widget, the code could simply never triggered any should they touch the same target tiddler as the outer checkbox, select or radio.

**Comment by inmysocks** [comment]
If we did that than you couldn't have a checkbox widget that sets two separate fields in the same tiddler, or added a tag and set a field in the same tiddler.

Something like if you have a quiz where you can decide to leave an answer blank. You would have a button for no answer which would set a field as finished and a list of radio buttons for the answers, selecting any other answer would store the answer and also set the field as finished.

There are more complex ways to achieve the same result without needing to store both parts of the result in the same tiddler, but if you are going to go with more complex solutions you don't need the radio buttons that can trigger action widgets anyway.

**Comment by tobibeer** [comment]
> If we did that than you couldn't have a checkbox widget that sets two separate fields in the same tiddler, or added a tag and set a field in the same tiddler.

Ok, I think that restricting the scope isn't a good idea, after all.

Then it appears that any inner action performed in the action widget must not be dependent on the state of the tiddler being touched by the outer radio, select or checkbox.

If you want such a dependency, then you need to use different select, radio or checkbox widgets each with their own conditional list or reveal widget.

**Comment by pmario** [comment]
@tobibeer should be added with 5.1.14 and 5.1.16 .. pls close

**Comment by Jermolene** [comment]
Thanks @pmario.
