### ISSUE TITLE
Proposal: "value" operator to test whether a title string equals something

### ISSUE THREAD

**Issue by felixhayashi** [Jermolene/TiddlyWiki5#2253]
Often I need to write `[all[current]field:title[yes]]`. That looks semantically awkward. It would make sense to add an alias for this situation: `[all[current]equals[yes]]`.

**edit** In the discussion with @tobibeer it surfaced that a generic `value` operator is appropriate here and highly required (e.g. to avoid something like `<$list filter="[<foo>regexp[^bar$]]" />` just to test whether foo equals bar).

**Comment by tobibeer** [comment]
Or perhaps just `[whatever[foo]=[that]]`.

**Comment by felixhayashi** [comment]
`=` instead of equals is shorter but I think it is preferred to use written words as filter operands.

@tobibeer when thinking about "equals": how would you test if a variable has a certain value in a filter? Say I want to test if foo equals bar. I could use a regex but that looks akward:

```
<$list filter="[<foo>regexp[^bar$]]" />
```

Any ideas?

**Comment by tobibeer** [comment]
I have not thought of using the regexp filter yet... and I think I will, the next time this problem crops up.

In any case, I don't think you even can use `field:title[value]`, because that assumes there to be such a tiddler, does it not?

Try this on TiddlyWiki.com, it returns nothing at all:

```
{{{ [[doesntexist]field:title[doesntexist]] }}}
```

Correct me if I'm wrong, but that filter simply does not exist and it very much **should**, rather pronto.  **#2186 is[empty] filter operator** was / is an attempt to test for "empty". But, in fact, what we really need is a way to test an input title for any value, so perhaps it should be:

{{{ a b c +[value[a]] }}}

which should return either:

* `true` / `yes` — when matching the value
* `false` / `no` — when not matching the value

So #2186 would be covered by doing:

```
[value[]]
```

**Comment by felixhayashi** [comment]
> In any case, I don't think you even can use field:title[value], because that assumes there to be such a tiddler, does it not?

Correct.

> Correct me if I'm wrong, but that filter simply does not exist and it very much should, rather pronto. #2186 is[empty] filter operator was / is an attempt to test for "empty"

I like that approach.

> But, in fact, what we really need is a way to test an input title for any value, so perhaps it should be:

This sounds exactly like #2186… I commented there.

**Comment by tobibeer** [comment]
The benefit of using `value[]` is that we can express both:

* `value[foo]` — returns `foo` if mathing
* `value:is[foo]` — returns `yes` (`no`) if (not) matching

**Comment by tobibeer** [comment]
What's important is, that we are not talking about any `field:title[foo]` filter here. It is very much a new filter operator in its own right. Perhaps rename the OP accordingly... and also the issue description.

**Comment by felixhayashi** [comment]
> The benefit of using value[] is that we can express both:

sweet idea

**Comment by felixhayashi** [comment]
> What's important is, that we are not talking about any field:title[foo] filter here

Yeah, the topic changed a bit… I'll rename the topic

**Comment by tobibeer** [comment]
:+1:  thx :-)

**Comment by tobibeer** [comment]
@Jermolene, would you be interested in a value[] filter as a core filter? Otherwise, I'll go ahead and implement / publish it as a plugin.

**Comment by Jermolene** [comment]
Hi @tobibeer I'd be inclined to ship it as a plugin in the first instance.

**Comment by tobibeer** [comment]
Hi @Jermolene, not entirely sure if you meant core plugin, but then I'm also not entirely sure when this plugin is needed, except perhaps to continue chaining filter logic in a single expression, instead of continuing in some emptyMessage.

Anyway, I published it as [tobibeer/value](http://tobibeer.github.io/tw5-plugins/#value) / version 0.5.0.

@felixhayashi, can you perhaps give it a test run and let me know of use cases of yours where it's doing what's otherwise more complicated and where a simple *ListWidget* `emptyMessage` or *SetWidget* `emptyValue` wouldn't suffice?

**Comment by saqimtiaz** [comment]
I believe this is resolved now with the expanded set of filters, in particular `match[]`
@Jermolene @felixhayashi I suggest this can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
