### ISSUE TITLE
Simple search should accept "$:/... "

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2318]
I propose that simple search also displays system titles if the search string is **explicitly** prefixed with `$:/` or perhaps also one or a few more character (e.g `$:/cor`) so to prevent uninformative overly long result lists.

A non-tiddlywikian is not likely to type in this prefix and be exposed to inappropriate tiddlers whereas a tiddlywikian doing this search does in deed want to find system tids and should not be forced to go to advanced for such a mundane matter as a basic search.

**Comment by pmario** [comment]
Just my thoughts.

IMO the decision was, that core tiddlers should be not show up in "ordinary" lists, because we don't want the TWclassic `excludeXXX` flag.

That's why `$:/` was created. This is a simple rule. ... As long as there are no exceptions. 

If we introduce an exception here. Where will be the next exception, that needs to be introduced, because of this one. .. What's about the the new parameter, that is needed, to remove a tiddler form this list, because it's the "exception of the exception" .. (You see my intent? ;)

IMO the argument "A non-tiddlywikian is not ..." doesn't match. As developers we should not rely on our expectations. They will be proven wrong. see: [Murphy's Law](https://en.wikipedia.org/wiki/Murphy's_law)

**Comment by pmario** [comment]
We are talking about the default behaviour here. ... IMO nothing stops a user to include a little pulugin, to do what you want.

**Comment by tobibeer** [comment]
@pmario

>  As developers we should not rely on our expectations. They will be proven wrong.

The way Murphy's Law is about expectations is not that undesirable things do happen at a given probability but rather that we tend to over-estimate that probability, systematically. In a way, your expectation of trouble is of that nature: an inclination to consider the problem case when there would realistically only be a few cases where such a change would actually be problematic.

The quality of a system is about usable design, the kind of design that best meets the user's expectations and requirements, intuitively so, without necessitating a big manual or extensive training.

As for @twMat's request though, AdvancedSearch is designed precisely for that and that's what we should use for quickly finding system or shadow tiddlers, imho... unless we prefer to scroll through the sidebar tabs, which I do surprisingly often (using my browsers search functionality though). Stupid, right?

The default search results popup could be more user friendly in that there should probably be at least two buttons for system and shadows that when clicked open the desired tab in AdvancedSearch.

**Comment by twMat** [comment]
Side note:
I find the arguments against my OP a bit comical given how TW at the same time has a UI that is not quite suitable for the public anyway. Or are you saying that TW *owners* need protection from being exposed to $ even if searching explicitly for it?

A general solution for all this would be a standard *theme* that has a *public* mode and an *system/admin* mode, where features adapt accordingly.

**Comment by pmario** [comment]
>Or are you saying that TW owners need protection from being exposed to $ even if searching explicitly for it?

System tiddlers are not there for ordinary users. They are there for makers. And if you are a maker, you should know, that AdvancedSearch is the way to go. Otherwise if an enduser is searching for some tiddlers that contain the $ sign to find eg: 10$ will be presented with a very long list of nonsense. ... That's the exact reason why system tiddlers are hidden in the default search. 

@tobibeer I'm using the browser search and highlight function quite a lot, because it is independent to TW. 

I did create a new plugin "AdvancedSearch plus", that removes the search dropdown :) and allows me to save search results as tabs in the sidebar. The UI needs a bit more love (It needs to be simpler), but it works well for me. Especially if used in company with a "tab links" like feature.

**Comment by tobibeer** [comment]
> Especially if used in company with a "tab links" like feature.

Oh, what would that be? Simply a list of quick links in the sidebar? Anyway, would be interesting to see how you especially navigate around the (for you a little more) undesirable nature of popups.

**Comment by twMat** [comment]
>System tiddlers are not there for ordinary users. They are there for makers. 

It is a good ambition to aim for a UI that distinguishes these two but I strongly suspect that in practice there is no such separation. With TW everyone is a maker or you'd go with some other solution. I can perhaps accept a distinction between *beginners* and *ordinary users*, where the former is better off protected from e.g $. But the *beginner* stage is quickly passed as one actually starts to use TW, e.g when one is no longer satisfied with `<<list-links..>>` or when one wants to modify the sidebar tabs, etc.

> Otherwise if an enduser is searching for some tiddlers that contain the $ sign to find eg: 10$ will be presented with a very long list of nonsense. ... That's the exact reason why system tiddlers are hidden in the default search.

OK but I think it is very reasonable to at least treat `$:/` as a clear enough indication that the user does in deed want system tiddlers.

A more serious and likely problem, caused by the current approach, is the fact that he can currently not type in e.g "controlpanel" and find the controlpanel.

Regardless; how search results are *presented* is a separate matter but I think it should not be too difficult to "shape" understandable results.

**Comment by tobibeer** [comment]
From my general point of view, I want **everything** configuration away from "ordinary visitors" and "basic users".

In that sense, that includes searching for and finding results on anything under the hood, e.g. system tiddlers, but especially shadows.

So, I actually agree with @pmario on this one.

> OK but I think it is very reasonable to at least treat $:/ as a clear enough indication that the user does in deed want system tiddlers.

And then what to search fo?

`$:/<search-term>`

I guess you wouldn't want to:

1. search but for titles that start exactly so, or do you?
2. to also search for shadows or even shadow contents, or do you?

**Comment by tobibeer** [comment]
> A more serious and likely problem, caused by the current approach, is the fact that he can currently not type in e.g "controlpanel" and find the controlpanel.

Yes, if you want to tweak and "fix" a thing, you pretty much need to know where to put that wrench, rather than search for "fix it" and hope TiddlyWiki is smart enough to figure out that you want it to tell you more about itself.

**Comment by twMat** [comment]
>From my general point of view, I want everything configuration away from "ordinary visitors" and "basic users".

But I agree with this - however, given the current UI, I must object to your term "basic users" or Marios "ordinary users" because I think that any TW user must very soon face e.g what ´$:/´ means. The idea to not allow `$:/` searches in standard search is a half measure in this regard and, as side noted, we'd probably need something like a *theme* that presents dedicted UI's depending on user level.

>And then what to search for?

Actually, you can search for `$:/ <search-term>` (note the space).


>Nothing stops you from...

That's a potential reply for *any* issue... but not very constructive  ;-)

**Comment by Jermolene** [comment]
The problem that system tiddlers are designed to solve is one that we had with TiddlyWiki Classic: the "everything is a tiddler" way of implementing plugins, colour palettes, stylesheets etc. means that, by default, menus and searches are cluttered with paraphernalia that is nothing to do with the content/purpose of the wiki. The solution in TWC was to tag these tiddlers "excludeLists" to prevent them from showing up in the sidebar lists. It's not a great solution because it means that the users list of tiddlers tagged "excludeLists" is now cluttered with all the extraneous tiddlers.

The idea of using the prefix `$:/` to identify system tiddlers in TW5 was (a) that a prefix is the simplest protocol for distinguishing a subset of tiddlers and (b) the use of the dollar sign was part of a conscious effort to use `$` to signpost system/internal things.

So, @twMat's OP would run counter to the raison d'être of system tiddlers. I wouldn't be adverse to supporting a master switch that "disables" system tiddlers, so that they are no longer treated specially, and just appear as ordinary tiddlers in the sidebar lists. I agree with @twMat's argument that as soon as a user switches perspective from a user of a TW to a builder, then the default system tiddler behaviour might not always be the most convenient.

**Comment by tobibeer** [comment]
> Actually, you can search for $:/ <search-term> (note the space).

Yes, but again, what to search for. Only system tiddlers, or just a defined set of system tiddlers, or also shadows? So many options and personal preferences. :-)

**Comment by twMat** [comment]
@Jermolene wrote
>So, @twMat's OP would run counter to the raison d'être of system tiddlers. 

Ok, I'm not gonna beat on this horse more *but* my point has just been that the raison d'être for *search* is to find what one is looking for, including  when one *explicitly* types ´$:/´

I like the idea of a master switch but think the idea should be more general than just "toggling" system tiddler treatment. I mean, if the idea is to cater for "builders" then there are other features that would also be very desirable.  Or, vice versa, if a display is only for the simplest out-of-the-box usage of TW, then there are things that probably should be hidden or disabled... such as several ctrl panel settings, some of the *tiddler info* stuff, the tiddler edit template *type* field and *new field*, etc etc.
Hm, this would probably mean a much simpler and likely less scary first impression of TW.

**Comment by twMat** [comment]
@tobibeer 
>Yes, but again, what to search for. 

That is a different problem. That you also have to face in AdvancedSearch.

**Comment by tobibeer** [comment]
> That is a different problem. That you also have to face in AdvancedSearch.

In AdvancedSearch, it's pretty clear where we are searching for what and how.

**Comment by twMat** [comment]
>In AdvancedSearch it's pretty clear where we are searching for what and how.

If one is not happy with the results from simple search, then one should in deed go to advanced. But SimpleSearch strongly implies that there there doesn't even *exist* a tiddler titled e.g *$:/ControlPanel*. 

Drifting from topic but; Additionally, as you know, I'm even in favor of including something like searchable keywords in parallel to tags (where you have made a good solution) because search is IMO overall not satisfying as I've mentioned in several other discussions (eögma search for "tags" on tw.com gives no meaningful result about how to use tags). Including e.g keywords could make SimpleSearch even more powerful.  With the right setup, there could even be optional plugins only to add useful keywords to e.g system tiddlers.

I'm closing this thread because I'm clearly not convincing anyone and so to permit a continued tangential discussion if desired. Thanks for everyones input.

**Comment by tobibeer** [comment]
For what it's worth, your request made me think of how in windows 8, you could hit WIN+X instead of just WIN to search for settings... and now in Windows 10, you get all results with the same search triggered with the WIN key.

So, perhaps, what you really want is for at least the most important settings, like the ControlPanel to be in the search results. After all, how many relevant system tiddlers are there for you and which?

**Comment by twMat** [comment]
>So, perhaps, what you really want ...

Hm, I don't think so. Search is search, and I just want to ensure that one finds whatever one is looking for as effortlessly as possible. 

>After all, how many relevant system tiddlers are there for you and which?

That is an interesting question. Since the thread is closed I'll allow myself to wander; An idea would be a more "intelligent" search that e.g  uses some mechanism that keeps track of how many times a tiddler has been opened or edited before, or perhaps a pre-made such "most likely to search" list... I'm guessing *system icons* is one example... but hard to predict without measuring. Contrary to e.g google saving your personal searches to improve results for you, in TW it is *only* with you in mind.

In my fiddling I'm pretty sure I occasionally stumble over rather obscure things but whath is important is of course  and it makes me think some feature to save search results would be useful; or, rather, something that count's the number of times a times a tiddler has been opened or edited and has this decide it's position in the result list (say, .
