### ISSUE TITLE
Maybe a bug in function Tiddler.hasTag()

### ISSUE THREAD

**Issue by turbojava** [Jermolene/TiddlyWiki5#2338]
In https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/tiddler.js
Original code from line 15 to 17

``` js
exports.hasTag = function(tag) {
    return this.fields.tags && this.fields.tags.indexOf(tag) !== -1;
};
```

Since "tags" field is a string of tags seperate by space, if a tag is a substring of another tag. this function will broken.
For example hasTag("butter") will also return true for "butterfly".

Following is my solution. Maybe not the best one.

``` js
exports.hasTag = function(tag) {
    return this.fields.tags && (" "+this.fields.tags+" ").indexOf(" "+tag+" ") !== -1;
};
```

**Comment by pmario** [comment]
internally tags is an array. .. There is a stringify function, which just displays it as a space separated string.

**Comment by sukima** [comment]
Crap! I didn't realize that I need to go fix my code. Thanks @pmario !

**Comment by pmario** [comment]
- go to tiddlywiki.com
 - open the dev console
 - use `$tw.wiki.getTiddler("HelloThere")`
 - analyse the object

**Comment by turbojava** [comment]
You are right. sorry for the mistake.

**Comment by pmario** [comment]
No need to be sorry. You found something, that looked wrong and you took you time to inform us. That's cool! Feedback is important. ... _No_ feedback is a _mistake_ ;)

**Comment by ldvjava** [comment]
@pmario thanks for your encourage . TiddlyWiki is great. I'm studying your code. Wishes in future, I can provide useful ideas.

----
BTW, I'm studying your code, because I want to publish TiddlyWiki over node.js onto Internet. I want it works like a real blog rather than a private notebook. That means only I can modify it after login, while others can read it without login.

The original version of TiddlyWiki can setup username/password. But after that, the read of the blog also need password.

Though there are a lot of web sites like tiddlyspot.com provides this feature. But I want a light weight solution by myself. and fortunately, my idea works!

Following are what I have done:
* modified server.js to make GET request bypass checkCredentials(); 
* make a fake 200 OK response to PUT to StoryList to suppress the alert of remeber StroyList on server side fail;
* modified syncer.js to suppress the alert for "Error retrieving skinny tiddler". I change it from alert(...) to log(...). Because when I access it through a mobile phone, Network will be blocked when the app push to background. TiddlyWiki want to sync tiddlers from server every minute, which produce a lot of alert dialogs.

Other things in my plan is:
* Change it to a plugin rather than override the core code.
* Let only tiddlers taged by "public" visible for people without login.

Do you have any suggestions?

**Comment by sukima** [comment]
@ldvjava I'm doing this the same thing. I want a public blog that only I can edit. Here is how I approached it.

I first created an simple setup that when I run it on my local computer would serve the site so I could use it normally and changes were autosaved back to the *local* server. When I was done I closed the server and ran some commands that rendered the content to a single HTML document like normal. I uploaded the single HTML to be served by my public web server. This way the TiddlyWiki was visible as a read-only document to the world but editable by my on my local computer through the node server.

As for public/private view I added a tag called private to some tiddlers. Then I copied a few of the templates and added the `[!tag[private]]` filter to them. so when I run the command to save a single page HTML it filters out any tiddler tagged private.

Here are the templates I used: https://gist.github.com/sukima/72c7782dcc8dfb221833

Also I wrote a [Yeoman](http://yeoman.io/) generator for the main setup I use. It doesn't have the private filter but with the gist above it is easy to add it.

https://www.npmjs.com/package/generator-tiddlywiki

**Comment by ldvjava** [comment]
Hi @sukima,

* I want to edit the blog anywhere simply through a browser on any computer/pad/mobilephone. Your solution need host a private tiddlywiki on a certain computer or use a private VCS, and the procedure of edit is quite complex. I have ever consider about running two instance of tiddlywiki on the same server, one for public, another for edit and a command script to export public tiddlers from the private one to the public one, but still complex.

* As for tag, I prefer to use "public" to indicate which tiddlyes should be exported. That means by default all tiddlers are private. This policy can prevent me make mistake to leak private information.@Jermolene provide a template here:  https://github.com/Jermolene/TiddlyWiki5/issues/2323

**Comment by pmario** [comment]
@turbojava ... Do we need this issue to be open?

**Comment by Jermolene** [comment]
The OP isn't quite right; `this.fields.tags` will in fact be an array of strings. That behaviour comes from the default "tiddlerfields" module for the "tags" field (it's defined in the boot kernel).
