### ISSUE TITLE
tw.com/prerelease has misleading date

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2382]
Official prerelease [TiddlyWiki Pre-release tiddler](http://tiddlywiki.com/prerelease/#TiddlyWiki%20Pre-release) has misleading subtitle

`28th April 2015 at 10:49pm`

**Mio propozicia to either update whole tiddler or tc-tag** it - perhaps simply tag it "prerelease" and put in that same tiddler

```
<style>
.tc-tagged-prerelease .tc-subtitle {display:none;}
</style>
```

possibly even

`.tc-tagged-prerelease .tc-tags-wrapper {display:none;}`

**Comment by Jermolene** [comment]
Hi @twMat the subtitle works the same as others: it's the date of last modification to the tiddler, not the date of last modification of the release.

When I release to tiddlywiki.com I do update the date of HelloThere to avoid the problem there.

Rather than making a special rule for the display of the subtitle of the prerelease tiddler, I think it would be more useful to have build information easily available: not just the last modification date of the code, but also the git repo and commit that was built. Then we would display that prominently within the prerelease tiddler

**Comment by twMat** [comment]
Sounds like a good idea - but also like a rather ambitious change which might take time to implement. My onlly concern in this issue was/is to not have a date that gives the wrong impression.

Because this issue is more about making you aware of it (since you're probably the only one who can do anything about it) you can close it if you prefer.
