### ISSUE TITLE
Prefix $:/ interferes with regexp

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2395]
(bug?)

````
{{{ [<currentTiddler>regexp:foo1[bar]] }}} (yes worky)
<hr>
{{{ [<currentTiddler>regexp:foo2[$bar]] }}} (no worky)
<hr>
{{{ [<currentTiddler>regexp:foo3[$:/bar]] }}} (no worky)

foo1 : bar
foo2 : $bar
foo3 : $:/bar
```

The leading `$` seems to mess with regexp. 

I propose prefix  (or even mid string) `$:/` is treated as special case and parsed(?) differently.

**Comment by pmario** [comment]
regexp filters are very low level. So you (thy user) needs to take the javascript regexp rules into account. 

see: http://www.regular-expressions.info/index.html .. That's the best site about regexps, I've ever found. It actually describes how it works in a step by step way, so I could actually understand it. 

If you search the site, you'll see what  `$` and many others eg: `/ [].* /` actually mean. 

Using the regexp operator _can not_ be simplified, since it is the absolutely lowest level filter we have.

**Comment by pmario** [comment]
Testing your own regexp strings can be done here eg: https://regex101.com/

**Comment by twMat** [comment]
Thanks Mario, great links. 

>Using the regexp operator can not be simplified, 

OK... this makes me think that some higher level TW regexp operator (twegexp?) would be desirable. The main point here is that a user should be able to **freely(!) use tiddler titles as "units"** (as well as "choppable strings") i.e without special consideration to our common "TW characters" (and, actually, without special knowledge of regexp). A higher level operator for this is probably quite a project though given the complexity of regexp....

...or could perhaps a `*` (asterisk/all/joker/wild..) for an arbitrary string would be an alternative? I.e `[*bar]` would capture all three examples in the OP or `[$*bar]` for the latter two.

**Comment by pmario** [comment]
we already have a higher level tw regexp eg: `prefix[$]regexp[bar]` should do what you want. I didn't test it. have a look at http://tiddlywiki.com/#Filter%20Operators  for mor combination

**Comment by twMat** [comment]
>prefix[$]regexp[bar]

Hm, that would catch also `$:/wrongbar` and would need an additional filter `!prefix...` to get `bar`. All solvable but a bit much demands on the user considering the prime status that tiddler titles should have.

**Comment by Jermolene** [comment]
Hi @twMat I think there is a fundamental problem here: regexps are tricksy, with unexpected rules that trip up beginners. You're proposing modifying the regexp syntax to avoid those gotchas but the problem is (a) by the very nature of the encoding and escaping used, you'll never remove the need for users of regexps to have a comprehensive understanding of how regexps work and (b) we end up making our regexp syntax more complicated, and more non-standard, so that we don't even have the advantage of people experienced with regexps being able to use it.

But as @pmario says, we can and have taken the common use cases and built standalone filters for them.

**Comment by twMat** [comment]
Yeah... I can see how a syntax that conflicts with the original, would be problematic. I have a case where I filter on a parameter that can have a `$:/` prefix, or not. I can likely construct a workaround (probably some if-type construction using a listwidget) but it seems convoluted give that it's just a title I'm looking for. Maybe it's a matter of just setting some best-practice solution for this type of case? I'll test around a bit. Closing this thread for now.

**Comment by tobibeer** [comment]
@twMat, the trick is to pass the actual regexp you wish to test using a variable

```
<$vars re="fancy regexp">

{{{ [<currentTiddler>regexp:foo2<re>] }}}
</$vars
```

But, of course, you would still have to know how to express your designed lookup within "fancy regexp" and that `$`, for example, is a special symbol in regexp.

**Comment by twMat** [comment]
Thanx @tobibeer - but the difficulty is the very thing with the $ symbol.... so that we can treat all tiddlers the same, regardless if they happen to be prefixed with that symbol or not. 

Annoyingly, I can't recall where I confronted this problem, so I can't see how I solved it but, as noted, I don't think it is a difficult problem to solve (wrap a filter around it to test if prefix $ then use subfilter X otherwise subfilter Y) but, given how common that prefix is in TW, I think a convoluted solution kinda discourages non-regex'perts from using regex'es.

**Comment by tobibeer** [comment]
I believe you would need some filter that escapes sensitive characters in a title, e.g.:

```
define regex() $foo[1]$(escaped)${0,2}

<$set name="escaped" filter="[escape<currentTiddler>]">

{{{ [<currentTiddler>regexp:foo1<regex>] }}}
</$set>
```

So, the above would run currentTiddler through an **escape** filter that would turn any $ and such into the escaped character variant for regexp.

**Comment by twMat** [comment]
Yes, that seems like a good solution.
Good outline for a plugin.

**Comment by tobibeer** [comment]
Hi @twMat

> Good outline for a plugin.

there you go: http://tobibeer.github.io/tw5-plugins/#escape

**Comment by twMat** [comment]
Thanks for that @tobibeer ! I can't find where I had the need for this originally, but I'm sure I will again so, again, thanks. Hope others find it too.
