### ISSUE TITLE
Mosaic display

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#2402]
Is there any way of displaying tiddler with mosaic view: like [this](http://padlet.com/PatterMaC/MathBuilt)

**Comment by sukima** [comment]
Perhaps the expeimental theme/plugin: https://github.com/Jermolene/TiddlyWiki5/tree/master/plugins/tiddlywiki/cecily

**Comment by somenxavier** [comment]
Not But anyway thank you

**Comment by Jermolene** [comment]
Hi @somenxavier the Cecily plugin is quite experimental, but is intended to serve these kinds of use cases. It provides a "story view" that lays out tiddlers according to a map of their location/size, instead of laying out the tiddlers in a contiguous vertical strip. The missing piece at the moment are pluggable options for how the tiddlers are laid out on the map; the masonry-style display you linked to being one of the examples I'd like to hit.
