### ISSUE TITLE
Sync error while processing '$:/core/ui/EditorToolbar/preview-type'

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#2453]
Getting an error (full text below) every time I refresh the page while the editor toolbar is present or `$:/core/ui/EditorToolbar/preview-type` is in the Story.

Firefox 46.0.1, Nodejs  4.4.4, TW latest from this repo.

```
syncer-browser - 10:54:06 18 5 2016

Sync error while processing '$:/core/ui/EditorToolbar/preview-type': XMLHttpRequest error code: 404
```

**Comment by Jermolene** [comment]
Hi @nameanyone apologies for the delayed response. I had a look at this problem a few weeks ago and then got distracted by something else. Now I can't seem to duplicate the issue; could you kindly verify that the problem still occurs with the latest content of the master branch? Many thanks.

**Comment by nameanyone** [comment]
Still happening to me. I just fetched. Here is tw5.com running on my desktop. Same happens in my wiki. (Also, the URL keeps turninig into a permalink. That doesn't happen in my wiki though.)

![2016-07-04_11-33-00](https://cloud.githubusercontent.com/assets/212368/16568118/493731a8-41db-11e6-9cf3-d730dd698387.png)

**Comment by Jermolene** [comment]
Hi @nameanyone 

> Also, the URL keeps turninig into a permalink. That doesn't happen in my wiki though

The easy one first: that's probably because the default tw5.com-server edition includes the setting that automatically updates the address bar. See:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com-server/tiddlers/config-Navigation-UpdateAddressBar.tid

> Still happening to me. I just fetched. Here is tw5.com running on my desktop

Weird, I'm still not seeing the error. The steps I tried on my Mac were:

1. In the TiddlyWiki repo directory, issue the command `./bin/serve.sh`
2. In Firefox, visit http://127.0.0.1:8080/
3. Use `$:/AdvancedSearch` to find the tiddler `$:/core/ui/EditorToolbar/preview-type` and open it

Do those steps correspond to what you're doing?

**Comment by nameanyone** [comment]
Normally I have another wrapper script, but yes, I just repeated your steps exactly (+ step 4) and the issue is there. Step 4 is do a refresh in your browser, by hitting F5 or whatever it is on Mac. I also implied that your story is preserved between refreshes. The tiddler must be in the story when it's being loaded.

**Comment by nameanyone** [comment]
Had to refresh my memory on how that's done - preserving history. Either via address bar updates as you explained, or by making sure `$:/DefaultTiddlers` contains `[list[$:/StoryList]]` and `$:/config/SyncFilter` does not contain `-$:/StoryList`. 

Think we covered all prerequisites now, if anyone else wants to try.

**Comment by Jermolene** [comment]
Thanks @nameanyone, I think I've figured it out now.

The first thing to note is that in my testing the problem only occurs with Firefox, and not with Chrome or Safari.

The second thing is to explain why there is a GET request for the tiddler ` $:/core/ui/EditorToolbar/preview-type` when we refresh: the problem is that that tiddler doesn't have a `text` field, which means that the client interprets it as a lazily loaded tiddler, triggering an attempt to load the body when the tiddler is displayed. That's definitely a bug: tiddlers lacking a text field will repeatedly trigger lazy loading.

The third issue is why we get an error in Firefox and not Chrome. Using the browser devtools, I can see that Chrome requests the following URL when retrieving the preview-type tiddler:

http://127.0.0.1:8080/recipes/default/tiddlers/%24%3A%2Fcore%2Fui%2FEditorToolbar%2Fpreview-type

Meanwhile, in Firefox, the URL is:

http://127.0.0.1:8080/recipes/undefined/tiddlers/%24%3A%2Fcore%2Fui%2FEditorToolbar%2Fpreview-type

It's the presence of "undefined" instead of "default" as the recipe name that causes the 404.

The reason that Firefox is using the wrong URL stems from the way that the correct recipe name is read from the server asynchronously when the TiddlyWebAdaptor starts up. In the case of Firefox, the load request for the lazily loaded tiddler is issued before the retrieval of the recipe name completes.

I'll explore some possible solutions/work-arounds.

**Comment by Jermolene** [comment]
I was wrong about one detail:

> That's definitely a bug: tiddlers lacking a text field will repeatedly trigger lazy loading.

I forgot that I fixed this problem back in 1e0d019610acd960b8c70c0b85b7bb1a25096a8f by ensuring that any tiddler is only lazily loaded once.

**Comment by Jermolene** [comment]
Hi @nameanyone please could you check if the problem is fixed for you? Many thanks.

**Comment by nameanyone** [comment]
Fixed. Thanks!
