### ISSUE TITLE
TW5 crashes, then can't edit a wiki (Uncaught Error: EBUSY)

### ISSUE THREAD

**Issue by TashaArvanitis** [Jermolene/TiddlyWiki5#2488]
I have a hefty lab notebook in TiddlyWiki (3-4 MB TW file, and img tags to just under 600 graphs etc), and I love TW5 for notetaking and as an easy place to dump plots. I use the windows desktop application (Version 0.0.8). Occasionally I'll be in the middle of editing a tiddler, often while editing the image name in an [img] tag (and frequently in a tiddler with several images), and TW5 will crash. Inconvenient, sure, but surely not irrecoverable. But when I close TW5 and reopen the wiki, trying to save anything gives the error below.

```
Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught Error: EBUSY: resource busy or locked, open '<path to my TW>.html'
```

Often I can go back to the last backup, where I can save changes without any problem, but when I move the backup to the original directory my notebook was in, the same problem appears. Any idea what might be going on here, or how I can get my notebook back without copying my ~600 images to a new directory and starting clean? (And for whatever reason, sometimes even that doesn't work!)

**Comment by Jermolene** [comment]
Hi @TashaArvanitis interesting, I've not come across this problem before. Actually there are two problems: the crashes you are experiencing when editing tiddlers, and the EBUSY error when subsequently saving.

With respect to the first problem, do you generally have the preview pane switched on? A distinct possibility is that the rendering engine within TiddlyDesktop is overwhelmed by the rapid changes and large images in the preview. It may be worth trying working without the preview pane, at least when you're editing tiddlers with a lot of images. It's also possible that an update to TiddlyDesktop to use the latest version of the underlying rendering engine would help; I'm hoping to do that in the next few weeks.

The EBUSY problem is easy to diagnose, but harder to suggest a fix. The first crash is leaving the HTML file locked, meaning that other processes (including the restarted TiddlyDesktop) are prevented from opening it. Googling the error message "EBUSY: resource busy or locked" suggests that rebooting is the best solution; horrible, but may be easier than re-copying your images. (Just a thought, you could run TiddlyDesktop under a virtual machine using eg VirtualBox, then you could just reboot the VM instead of your entire machine).

**Comment by TashaArvanitis** [comment]
Hi @Jermolene, thanks for your response! 

In terms of the first problem, you are correct that I have the preview pane open; I'll try to avoid using the preview pane when I have lots of images and see if that helps with crashes.
And on the locked file front, it's good to know that a restart should help; I'll try that next time something like this happens, if I forget to keep the preview pane closed or it doesn't help.

**Comment by Jermolene** [comment]
Hi @TashaArvanitis I'm tidying up and closing this ticket because it isn't currently actionable. Do feel free to re-open it if something changes.

**Comment by TashaArvanitis** [comment]
Just a quick update: a crash from a different cause (to do with choosing colors for tags) left me with the same EBUSY error, and a restart didn't fix the problem. Again, nothing particularly actionable, just wanted to throw this into the mix.

**Comment by TashaArvanitis** [comment]
On further investigation, if I download a new empty TW (like from http://tiddlywiki.com/) and copy it to any of the directories I've had TW5 crash in before, then try to edit it with the desktop application, I get the EBUSY error. This appears to be the case even if I delete the directory and create a new one with the same name, and is true regardless of the name/filename of the wiki I try to edit. Is it possible that a given directory only has one lock file that applies to all wikis in that directory?

**Comment by Jermolene** [comment]
Hi @TashaArvanitis interesting. Does restarting the operating system allow you to edit one of the "broken" wikis?

**Comment by TashaArvanitis** [comment]
Hi @Jermolene, the (hard) reboot didn't appear to help.

**Comment by TashaArvanitis** [comment]
Just wanted to post an update here; I've been error free for several months, possibly because I haven't been working with as many plots on a day-to-day basis. But today I crashed TW in the following situation:

* TW open, with a tiddler being edited that refers to an image myimage.png
* In windows, copy several files, including myimage.png from a different directory into the TW directory.
* When it asks me about whether to copy, overwrite, or skip the repeated image, I said "skip"

Again, not asking for any help here, just updating this in case it's useful later.
