### ISSUE TITLE
Quotes inside external links aren't accepted anymore

### ISSUE THREAD

**Issue by xcazin** [Jermolene/TiddlyWiki5#2493]
Hello,

Between 5.1.11 et 5.1.12-prerelease, something has changed that keep the following construct to work anymore as expected:

`*[[Oxord Tube stop: Marble Arch|https://www.google.co.uk/maps/place/51%C2%B030'42.8%22N+0%C2%B009'30.7%22W/@51.5118958,-0.1593048,18.25z/data=!4m5!3m4!1s0x0:0x0!8m2!3d51.51189!4d-0.15854?hl=en]]`

It is related to the part that contains minutes/quotes, but I wasn't able to spot the change in the code.

Cheers,
X.

**Comment by sukima** [comment]
As far as I remember single quotes are not valid characters for a URI and need to be escaped as `%27` That is exactly what `encodeURIComponent` does.

Even if some browsers allow single-quotes in their URL parsing rules I wouldn't trust that. Especially in a JavaScript application that attempts to create DOM element from text markup like TiddlyWiki.

I'm also willing to bet that if you pasted that into a browser then copied it from the address bar that the browser will also escape `'` with `%27`.

**Comment by Jermolene** [comment]
Hi @xcazin good spot, thank you.

The cause here is this change b326ba5b2c9e622f5fe99b00ab368bb484c1d4e5. The problem it was fixing was that external pretty link detection for `[[text|https://example.com/link.html]]` was only testing for the inclusion of a valid url, meaning a string like `Review on http://amazon.com by me` would get classed as a valid external link. The fix required that the external link was anchored to the start and end of the string.

The specific problem with your example is that the apostrophe/single quote is incorrectly not being classed as a valid character for a URL; that's why all previous versions of TiddlyWiki only hyperlink up to the apostrophe.

Fix coming up.

**Comment by Jermolene** [comment]
Hi @sukima 

> As far as I remember single quotes are not valid characters for a URI and need to be escaped as %27 That is exactly what encodeURIComponent does.

Weirdly, encodeURIComponent doesn't in fact encode single quotes. It seems that in most places (eg GitHub Flavored Markdown link detection), single quote is accepted as a URL character. Perhaps the clincher is that Google Maps generates URLs with single quotes, so they are in circulation.

**Comment by xcazin** [comment]
Oh, I see. That's why just looking at b326ba5b2c9e622f5fe99b00ab368bb484c1d4e5 was not enough. Thank you for the explanation.
