### ISSUE TITLE
Presence of a tiddler called "undefined" strips styling from empty.html

### ISSUE THREAD

**Issue by r1chard5mith** [Jermolene/TiddlyWiki5#2507]
I am able to replicate this reliably in both Chrome and Firefox on OSX.

Go to Tiddlywiki.com, download "empty.html", create a new Tiddler called "undefined", save and reload = no styling applied to the page at all, wiki seems to work normally otherwise.

NB: Tiddlywiki.com itself does NOT appear to suffer the same problem when downloaded.

**Comment by pmario** [comment]
Just tested it. I can verify the issue. ... interesting :)

**Comment by Jermolene** [comment]
Likewise; positively mind-bending. I'll accept wagers on the eventual fix...

I've temporarily added a tiddler called "undefined" and an empty text field to the "empty" edition; building it under Node.js gives an HTML file that exhibits the problem.

Even though there are no styles, it's still possible to use the resulting HTML file. Exploring further with advanced search, the filter `[all[tiddlers+shadows]tag[$:/tags/Stylesheet]]` is returning zero tiddlers. It turns out that `$:/themes/tiddlywiki/snowwhite/base` has mysteriously become a missing tiddler, despite being a shadow tiddler from `$:/themes/tiddlywiki/snowwhite`. I've no explanation for that yet.

**Comment by Jermolene** [comment]
It turned out to be pretty fundamental: `$tw.wiki.getTiddler(undefined)` was returning a tiddler called "undefined" if it exists...

**Comment by sukima** [comment]
![Mind Blown](http://i3.kym-cdn.com/photos/images/newsfeed/000/288/648/776.gif)
