### ISSUE TITLE
SyntaxError: Unexpected end of input after loading TW5 html file to TW on node.js

### ISSUE THREAD

**Issue by guillefix** [Jermolene/TiddlyWiki5#2509]
So I just installed TW on node.js using `tiddlywiki cosmos --init server` and then I did `tiddlywiki --load cosmos.html` where `cosmos.html` is a TW5 html file I had with lots of tiddlers. It created `.tid` files in the `tiddlers` folder as expected. However, then I run `tiddlywiki --server` on the root folder, and I am getting this:

```
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at $tw.modules.define.application/json (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1296:23)
    at $tw.Wiki.deserializeTiddlers (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1218:23)
    at $tw.loadTiddlersFromFile (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1449:23)
    at $tw.loadTiddlersFromPath (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1527:22)
    at /usr/lib/node_modules/tiddlywiki/boot/boot.js:1522:40
    at $tw.utils.each (/usr/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at $tw.loadTiddlersFromPath (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1520:15)
    at $tw.loadWikiTiddlers (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1686:21)
    at $tw.loadTiddlersNode (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1754:27)
```

I checked on `boot.js` but can't see anything wrong. The server worked before adding the new tiddlers (of which there are about 1000)

**Comment by guillefix** [comment]
After removing tiddlers that begun with `$__` the server is starting now. I guess those shadow tiddlers can't be imported from the html TW5?

**Comment by guillefix** [comment]
After stopping the server and starting it again, the same error comes up

**Comment by guillefix** [comment]
I found that the error was due to plugin tiddlers. I think the instructions on TW on node.js should be more clear about how to install plugins. Installing a plugin from TW itself creater a tiddler that created the error. I manually copied the `tiddlywiki/katex` folder from github to a `plugins` directory, after adding the plugin to `tiddlywiki.info` too. Even then, it was complaining about `/plugins/tiddlywiki/plugin.info'` not existing.. so I just copied the `plugin.info` from the katex folder to `/plugins/tiddlywiki/`. Doesn't seem this is working very well.. or am I missing something?

**Comment by sukima** [comment]
@guillefix 

 - If you remove all the tiddlers in the `tiddlers` directory does the problem persist?
 - Would you be willing to post your tiddlywiki.info on gist.github.com and post a link?

**Comment by guillefix** [comment]
If I remove all the tiddlers the problem goes away; but as I said above, it suffices to remove any plugin tiddlers.

This is my `tiddlywiki.info`: https://gist.github.com/guillefix/b39e6613fa6a421139d817b7813d6b1a 

I just think that adding plugins in the node.js doesn't appear straightforward.

**Comment by sukima** [comment]
So the problem is in the tiddlers. Do you have any custom plugins in the tiddlers directory? Delete each one and add them back one at a time till the problem shows up. That will be the one that is malformed. Open it in an editor and see what went wrong.

Also the Node environment for TiddlyWiki splits out all the data into organized files. Unlike the single file version which packages everything into the HTML. This means each tiddler is it's own file. It also means that types of tiddlers are organized. Regular tiddlers go in `tiddlers` folder while plugins are organized in a `plugins` directory. There is also meta data (`plugins/my-plugin/plugin.info`) for the plugin because plugins are usually more then just one file. Finally, both the node server and the single page version use the same boot code. Which means plugins need to be runnable in _both_ environments. This is why most plugins will have a `if ($tw.node)` or `if ($tw.browser)` check in them.

The reasoning is that in the single page version all the interaction is focused in the browser where organization is managed though the normal TiddlyWiki means. But on the server side most interaction is in the source code (like saving to a version control system or editing in your favorite text editor). And so it leave all the heavy lifting to the user and that is what a server side user would most likely want (i.e. control).

The `plugins` section of the `tiddlywiki.info` is only for importing official plugins from the TiddlyWiki repository. Custom ones go into your own `plugins` directory and are not referenced in the `tiddlywiki.info`.

I have an example of custom plugins on my blog: https://github.com/sukima/dev-tritarget-org

**Comment by guillefix** [comment]
Thanks. I removed the custom plugin from the `tiddlywiki.info` file, and things are working as expected. However, I think that installation of plugins from TW itself should be made to work if possible :P

**Comment by Jermolene** [comment]
Hi @guillefix I updated the docs for plugin installation under Node.js:

http://tiddlywiki.com/#Installing%20a%20plugin%20from%20the%20plugin%20library:%5B%5BInstalling%20a%20plugin%20from%20the%20plugin%20library%5D%5D%20%5B%5BUninstalling%20a%20plugin%5D%5D

**Comment by guillefix** [comment]
Thanks, I get it now!

**Comment by sukima** [comment]
Can this issue be closed now?
