### ISSUE TITLE
Dropdown for "untagged" in TagManager appear at the top of the tiddler

### ISSUE THREAD

**Issue by Evolena** [Jermolene/TiddlyWiki5#2512]
When clicking on the "untagged" pill in the $:/TagManager, the dropdown panel opens at the top of the tiddler instead of where the pill is.

It is like this since this "uintagged" pill has been added to the TagManager in 5.1.9.
The display of the "untagged" dropdown in the More > Tags tab is OK.

**Comment by tobibeer** [comment]
I'll be nagging about this for as long as it takes for this to be fixed. A *popup* always needs to be rendered with respect to the position of the anchor, period. It has nothing to do with where it is rendered in the document flow. It needs to be taken out of the flow.

**Comment by Jermolene** [comment]
Thanks @Evolena.

Hi @tobibeer if there is such a fundamental problem, why is it just the "untagged" pop up that is broken?

**Comment by tobibeer** [comment]
> Why is it just the "untagged" pop up that is broken?

It is not. Off the top of my head, all popups take on the css applied to their context: imho, that is wrong.

So far, your suggested workaround to remedy such a situation and to manually have the author take the popup out of the problematic flow has been is to separate button and popup.

Pragmatically speaking, I thought the actual reveal in **$:/core/ui/UntaggedTemplate** could be 
refactored out into some **$:/core/ui/UntaggedTemplateContents** tagged **$:/tagsPageTemplate**. After having to use a unique, defined state for all untagged popup buttons, that popup is still not placed where it should.

Having to try any such **workarounds** — that aren't even correct, because two buttons would handle the same state of one popup — and keep failing, is owed to the current design of the popup mechanism, which simply neglects what a popup generally is not: something confined to the boundaries of the immediate context of some button that is clicked to open it.

**Comment by Jermolene** [comment]
> It is not (just that), unless we ignore the other cases that do not work and which no one has quite managed to make work yet, afaics.

I'm confused by the logic here. @Evolena raised a very specific issue. It is clearly possible to fix it, because the other dropdowns in the tag manager work fine. @tobibeer is suggesting that the popup mechanism is broken and needs to be repaired. I don't see any evidence that we need to change the popup mechanism to fix the bug that @Evolena has raised.

> Off the top of my head, another case that spells "broken" is that all popups take on the css applied to their context: imho, that is wrong.

On the contrary, I find that that is a great advantage of the current design.

> So far, your suggested workaround to remedy such a situation has been is to separate popup button and popup content and to thus manually have the author try and take the popup content out of the problematic flow. Turns out the positioning algorithm isn't actually designed to literally handle that popup ...because, well, the popup positioning mechanism actually does expect the popup content to follow the button.

If the positioning algorithm is broken then we fix it, no?

> Pragmatically speaking, I thought the actual reveal in $:/core/ui/UntaggedTemplate could be 
refactored out into some $:/core/ui/UntaggedTemplateContents tagged $:/tagsPageTemplate. While this forces me to throw out the qualify macro and use a unique, defined state for all untagged popup buttons, that popup is still not placed where it should.

Are you saying that you've tried and failed to fix the bug that @Evolena reported?

> Having to try any such workarounds — that aren't even correct, because two buttons would handle the state of the same popup — and keep failing, is owed to the current design of the popup mechanism, which simply neglects what a popup generally is not: something confined to the boundaries of the immediate context of some button that is clicked to open it.

At this point in the game we can hardly change how the popup mechanism works in the kind of fundamental way you are proposing, can we? I think the best we can do is to evolve an additional mechanism.

As I've said before, if you're interested in exploring this topic, I'd recommend exploring the modal mechanism which, I think, works more like you want. Then perhaps you can create a specific proposal for evaluation.

**Comment by tobibeer** [comment]
> Are you saying that you've tried and failed to fix the bug that @Evolena reported?

I specifically wrote how I tried to, and failed.

Other than that, sure, you can take it out of the table, et voila, it works.

**Comment by Evolena** [comment]
Should be fixed by 4f78d3d

**Comment by Jermolene** [comment]
Thanks @Evolena good to see you here!
