### ISSUE TITLE
plain text tiddler gets syntax-highlighted

### ISSUE THREAD

**Issue by nameanyone** [Jermolene/TiddlyWiki5#2535]
Create a tiddler with a type text/plain, and most of the time the text will be syntax-highlighted according to an arbitrary language. For example,

`mount` is plain text, lucky
`mount ` (space at the end) is nginx
`mount | grep -P '^/dev/' | sort -k 3 | grep -P '^(?:\S+\s){2}(\S+)'` is Perl

**Comment by nameanyone** [comment]
I have the [Highlight plugin](http://tiddlywiki.com/#Highlight%20Plugin) installed, and it's a feature - automatic language detection, see https://highlightjs.org/.

Can we skip `hljs` class in plain text tiddlers?

**Comment by Jermolene** [comment]
Hi @nameanyone TiddlyWiki is passing the type "text/plain" along to highlight.js, so perhaps the problem is that highlight.js shouldn't attempt to apply syntax highlighting to "text/plain" text? Perhaps there are configuration options; worst case, we could patch the highlight plugin to disable syntax highlighting for the content type "text/plain".

**Comment by nameanyone** [comment]
> TiddlyWiki is passing the type "text/plain" along to highlight.js

I've honestly tried to figure it out, but I'm lost. What I wanted to confirm is if "text/plain" is ok. My hunch is that highlight.js nuderstands "plain" or "text" but not "text/plain", and since it does not recognize a valid language, it tries to guess it.

**Comment by Jermolene** [comment]
Hi @nameanyone yes: TiddlyWiki passes the MIME type of the tiddler to highlight.js as the "language brush", but it turns out that highlight.js doesn't actually understand MIME types. I've added a configuration mapping to convert from MIME types to highlight.js brushes which seems to fix things, let me know how it works for you.

**Comment by nameanyone** [comment]
Doesn't work with an empty mapping. https://github.com/Jermolene/TiddlyWiki5/commit/ee9d19d2993a3e4cbb44adf2fbb39c8279954a94#commitcomment-18685960.

**Comment by Jermolene** [comment]
Have you got this fix too?

ba2f831d8cd2ee349f5dcf4cd011326f5a434e4f

**Comment by Jermolene** [comment]
Aha thanks @nameanyone fix upcoming

**Comment by Jermolene** [comment]
Fixed in f079b31334ca7e66d29c33046aa75cb3bc802fa7
