### ISSUE TITLE
Disabling Escape key closing tiddler shortcut (so that codemirror vim mode works correctly)

### ISSUE THREAD

**Issue by davidmiani** [Jermolene/TiddlyWiki5#2538]
I've recently added the codemirror plugin, and enabled the vim keybinding functionality. This all works correctly and is really nice. However when I attempt to leave vim's insert mode by pressing escape, the tiddler I'm editing either closes or prompts me to close it (depending on if there are any unsaved changes). Is it possible to disable this behaviour?

**Comment by davidmiani** [comment]
As a workaround, I found that by setting the contents of the tiddler `$:/plugins/tiddlywiki/codemirror/keymap/vim.js` to the cod in [this gist](https://gist.github.com/davidmiani/715e43b6ef09e8bba73bc3f48249ca39), you can use kj to leave insert mode. This workaround makes this issue much less painful, but still requires a bit of relearning if you are use to using escape to leave insert mode.

**Comment by sukima** [comment]
Try <kbd>CTRL</kbd>+<kbd>C</kbd> and see if that helps. Often Vim plugins in browser editors have a lot of issues with <kbd>ESC</kbd> but tend to work well with <kbd>CTRL</kbd>+<kbd>C</kbd> (note I've haven't tried that on Windows only Mac).

Also I find that the Codemirror Vim plugin included in TiddlyWiki is abnoxious and almost unusable for me. So much so that I now disable it and copy/paste the content into the actual Vim program and back. I don't know why it is so difficult but it is seems that most editor authors that attempt to add Vi bindings never actually use them.

**Comment by tgrosinger** [comment]
Another possible solution is to clear the body of `$:/config/shortcuts/cancel-edit-tiddler`. This will make <kbd>ESC</kbd> return to command mode in codemirror, not cancel editing the tiddler.

**Comment by pmario** [comment]
@davidmiani ... could you solve your problem?

**Comment by davidmiani** [comment]
@pmario apart from the workarounds described so far, I don't think so. I haven't used TiddlyWiki for a while thought so I can't remember which one I used (I think I also may have stopped using vim mode as well).

**Comment by Jermolene** [comment]
Thanks @pmario @davidmiani

**Comment by zspark** [comment]
ctrl+c works well on Windows
