### ISSUE TITLE
Login modal looks odd and needs a revision to match TW styling

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2553]
Probably you don't see this modal very often because many of you use TW in offline mode, but have you noticed how odd and outdated does the login modal look?:

![awfulloginmsg](https://cloud.githubusercontent.com/assets/2270425/17951877/f85cb0ba-6a65-11e6-879d-9d9fc5d402dc.PNG)

In that screenshot it seems that it is not part of the same webpage, it even feels like some kind of fast sketch or hack. Not to mention that there is no dismiss or cancel button. You have to click login, or click login providing invalid values or live with it.

I think it is time to make this modal match the style of the rest of the UI.

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 to address the second part of your question first, it looks like you're missing the `canCancel` option for `$tw.passwordPrompt.createPrompt()`:

```
$tw.passwordPrompt.createPrompt({
			serviceName: "This is a test!",
			noUserName: false,
			canCancel: true,
			submitText: "Login",
			callback: function(data) {console.log(data)}
		});
```

In terms of the styling of the dialogue, I'm open to suggestions for improvements. Part of the goal for the current design was to make the dialogue visually distinct from the main page to give a strong cue that a password is being requested.

**Comment by danielo515** [comment]
>Hi @danielo515 to address the second part of your question first, it looks like you're missing the canCancel option for $tw.passwordPrompt.createPrompt():

Hello Jeremy, it's not my code which is triggering it, it's tiddlywiki core. I have created a PR to fix it: #2554

**Comment by danielo515** [comment]
> In terms of the styling of the dialogue, I'm open to suggestions for improvements. Part of the goal for the current design was to make the dialogue visually distinct from the main page

I agree that making visual impact on a password prompt is a good idea, but even with that idea in mind it is good to make it fit the rest of the page style.

Some improvements could be:
- Making it wider with responsive templates. There is no need to have very stretch modal dialog that can't even fit a complete url in a single line.
- Applying the above suggestion will probably avoid it from appearing on the side of the page.
- Give the input fields some padding or margin. Having it glued to each other is quite ugly. Same thing applies to the login button
- Style the login and cancel buttons to give them a more clear and visual appearance and impact. Maybe applying some colors (blue/red, or green/red) plus some icons is sufficient.
- Accepting html in the message body. I don't know why, but currently any styling block is ignored (for example `<b>`)

**Comment by Jermolene** [comment]
Hi @danielo515 sounds like a proposal for a pull request :)

**Comment by tobibeer** [comment]
If it is imperative that a user actually logs in, then it should be an actual modal. This popup is not a modal.

If it is not imperative: What do we call the thing that @danielo515 is showing in the screenshot? Clearly, it's not a modal, more of a popup. Is a popup the right thing in this case? Clearly, the popup appears to have no anchor, which for me is kinda like the `#1` rule for popups. The user needs to see what element on the page it relates to, e.g. a **login** button. A popup never just "hangs around" somewhere without a (triggering) context.

A login form surely is not of the "message" kind either, which you may except to vanish (by itself / or clicking outside of it).

In the most simple form, I would just use a tiddler showing the login status, otherwise the form.

**Comment by Jermolene** [comment]
The login dialogue is special: it's implemented in JS in the boot kernel, and not built from wikitext. The reason is that it is required early in the boot process when opening an encrypted TiddlyWiki.

Technically, in CSS terms, it is a classic overlay modal: a DIV overlaid over the screen.

It's intentional that you can interact with the page behind the login dialogue, in that I sometimes find it useful to ignore the login prompt for a few seconds. We could certainly add a modal mode.

**Comment by tobibeer** [comment]
I would argue that a popup isn't the right UX for this, at all. Instead, it should be a panel that is shown before all content, not unlike those "click to accept our cookies and see this message go" thingies.

**Comment by ght** [comment]
I suspect this has long been fixed. IIUC the credentials are entered on the "Saving" tab of the ControlPanel, which looks like this:
![TiddlyWiki-ControlPanel-Saving](https://user-images.githubusercontent.com/248399/122986547-e0389f00-d39f-11eb-818d-d91c464137ee.png)

Apologies if I missed something and this is still relevant (I'm only using offline mode), I was just digging through old inactive issues that look obsolete.

**Comment by Jermolene** [comment]
Thanks @ght. Sync adaptors can now provide their own custom login dialogue.
