### ISSUE TITLE
Usage section of corner-ribbon is confusing

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2581]
I was going to say that instructions for using the corner-ribbon plugin are confusing, but I can't consider instructions at all. They are just a chunk of text that looks alien, and awful specially because they are not even syntax highlighted. 

When I open a usage tab I expect a bit more of prose, saying something like `put any of this chunks on a tiddler and tag it`$:/tags/PageControls` or something like that.

**Comment by pmario** [comment]
Can you link to the tiddler. Otherwise this is just a rant, with no possibility to fix it.

**Comment by danielo515** [comment]
Sure!

https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/github-fork-ribbon/usage.tid

**Comment by twMat** [comment]
@danielo515 - I'd say the ribbon was a temporary experiment to see if it made sense on, if I recall, tiddlywiki.com or maybe it was in /prerelease. Jeremy decided to not include it. I believe it is more to be seen as a leftover for anyone who wants to fiddle with it rather than as something actually offered/serviced as part of TW. Assuming this is the case, I don't think this should be listed here as a TW issue.

That said, if you explain more clearly what you want to do, maybe I can help you.

**Comment by MaxenceG2M** [comment]
In the meantime, thank you danielo for the main information I was missing : "put any of this chunks on a tiddler and tag it$:/tags/PageControls`" :)

**Comment by mandarvaze** [comment]
> Has the explanation improved in any way? I didn't saw any commit on that regard

I just submitted a PR
