### ISSUE TITLE
Percentage-based layout for editor and preview is inconsistent

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#2584]
The gutter between the editor and the preview pane is inconsistently sized as a result of using %ages to control the horizontal sizes/positions.
The gutter can be made consistent using column-count property, but for that either tc-editor-toolbar must be moved out of tc-tiddler-preview, or an additional div must be introduced.

**Comment by pmario** [comment]
Is still valid. Having a look at the code and the related CSS classes, it may be doable in a backwards compatible way, without messing up existing CSS rules. .. At least TW internally. ... 

But it probably isn't annoying enough, that someone creates a PR.

**Comment by Jermolene** [comment]
Perhaps now it would make more sense to use flexbox.

**Comment by pmario** [comment]
>Perhaps now it would make more sense to use flexbox.

I think the biggest problem with flexbox is, that it has to be used consistently for everything. ... I did have a lot of problems to "contain" the right sidebar preview in a table ... as used by the palette manager ... 

Since table layout handling is mainly "black magic" performed by browsers, it's close to impossible to embed flex-box based layout settings inside tables. flexbox classes used by TW at the moment have a very high tendency to overflow table borders. ... 

The second problem may be my lack of knowledge about flex-box "containment" .. :)

**Comment by Jermolene** [comment]
Thank you @pmario
