### ISSUE TITLE
language extensions

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2611]
provide a way to cater for language extensions, i.e. language packs for purposes like

1. plugin localisations
2. language overrides

**Comment by Jermolene** [comment]
Hi @tobibeer there might be a good idea here but I think I'm not sure that this is a concrete enough proposal to warrant a ticket at this point.

Have you looked at @araname's proposal for language plugins for individual plugins in #2496?

**Comment by tobibeer** [comment]
@Jermolene, nowhere in #2496 a generic method is described.

**I need this, badly.** I don't understand how an important issue like this is closed before talking one second about solution. If something needs designing a solution, it is **actionable**. No being able to make an immediate PR does not mean not actionable.

I have amended the OP extensively, so that you and others more clearly picture the problem. Please reopen this ticket and close it only after we have sufficiently addressed the problem in terms of solution strategies.

**Comment by Jermolene** [comment]
@tobibeer if you had provided that level of detail in the first place I wouldn't have closed the ticket :smile:

> If something needs designing a solution, it is actionable

I don't think that's right. A vague, open-ended ticket asking for some speculative feature without any detail is not actionable. My role isn't to do your thinking for you.

> We want to be able to define language specific localisations

I still don't know what that statement means, because I don't know what you mean by "language specific localisations". It sounds like you want a localisation that is specific to the current language, but that is what the current language mechanism does, so I'm guessing that you must mean something else.

> This is bad. I need to know if it's en-GB or de-DE. It is of no importance what the title of the core language plugin is.

Are you familiar with the current implementation of language support? There is a variable called `languageTitle` that is set to the current language string in `$:/core/ui/PageTemplate`, and so it's available in all ordinary tiddlers.

> One method would be to amend the language switching process to rather than switch language plugins, actually switch languages. As a user, I do not switch to $/languages/de-DE. Instead I switch from en-GB to de-DE. At no time is there a need for me to switch from $:/languages/de-DE to $:/languages/tobibeer/de-DE whereas the latter would now have to be a full plugin of everything just to tweak the wee bits I want changing. Same for the core language. I do not want to have to build a custom TiddlyWiki just to tweak some language bits.

Again, I'm struggling to understand your proposal. Why does it matter that `$:/language` contains the title of the language plugin, rather than the name of the language? The latter is also available, and can be derived from the former. Users never ordinarily see language plugin tiddler titles, do they?

> $:/languages/tobibeer/de-DE

Why wouldn't you just create a custom language plugin that inherits from the standard de-DE plugin? You'd only need to provide the tiddlers that you want to override.

**Comment by tobibeer** [comment]
>> If something needs designing a solution, it is actionable

> I don't think that's right. A vague, open-ended ticket asking for some speculative feature without any detail is not actionable.

What could possibly be **speculative** about wanting to define language strings without modifying / extending a full language plugin or having to prepackage a plugin with every language users may want**?!?** In the language switcher, all I want to see is a list of languages, not `Deutsch (Deutschland)` and then also `Deutsch (Deutschland) — by tobibeer and then some`!

> My role isn't to do your thinking for you.

And then I go off, do my thinking and implementing, and it turns out a weeks worth of thinking and working was for naught, off to code limbo. So, what is your role? I think, first and foremost, that of the **architect** of TiddlyWiki. And as such, I would appreciate if you do us the honor and have some recommendation for localizing plugins other than: "pack it all up in one huge plugin to serve them all" ...and while your at it, figure out a way to do language switching for it.

>> We want to be able to define language specific localisations

> I still don't know what that statement means, because I don't know what you mean by "language specific localisations". 

It means that in a given language, the TiddlyWiki core or its plugins provide localisation, i.e. placeholders for utterings with lexical meaning, and then users but especially designers / developers come along, having a need to modify those, but without having to touch and repackage an entire plugin, including the core, so that languages can be switched to whichever target languages a user wants to adopt and provide switching for, not just for the core, but for plugins alike and a handful of rewordings that I want without inventing an entire language displayed alongside whatever dependent language there is.

> It sounds like you want a localisation that is specific to the current language, but that is what the current language mechanism does, so I'm guessing that you must mean something else.

I want localisation to my language, de-DE, but not the one provided by **$:/languages/de-DE** and I do not want to (have to) build **$:/languages/tobibeer/de-DE** just for changing a single, key localisation that is important and prominent enough for me to want to change it. I do not want my tiny wee changes to be listed as an entirely new language!

Overwriting key components is bad practice and needs to be avoided **as much as possible**!!! How is one supposed to update later!?!

> Are you familiar with the current implementation of language support? There is a variable called languageTitle that is set to the current language string in $:/core/ui/PageTemplate, and so it's available in all ordinary tiddlers.

I was not. However, I find no mention of it on tiddlywiki.com. Knowing that, I still have no way to have TiddlyWiki apply a number of language plugins with the language they are defined for corresponding to **languageTitle**.

> Again, I'm struggling to understand your proposal. Why does it matter that $:/language contains the title of the language plugin, rather than the name of the language? The latter is also available, and can be derived from the former. Users never ordinarily see language plugin tiddler titles, do they?

It does not matter what **$:/language** contains. What matters is that language switching revolves around the languageTitle being switched to, rather than what plugin has which lang field. As I switch from `en-GB` to `de-DE`. I want all plugins with field **language**=`de-DE` to be applied, preferably in an order that I can specify. I do not want any dependencies as exist for `de-AT`, because I need a whole bunch of plugin localisations, not one and I never want to select any of those in the language switcher.

> Why wouldn't you just create a custom language plugin that inherits from the standard de-DE plugin? You'd only need to provide the tiddlers that you want to override.

Because that forces me to put all localisations for my plugins into one big file ...but then I could never also load localisations from some other author, plus I would have to chose those in the language switcher... all of which makes no sense.

**Comment by Jermolene** [comment]
@tobibeer the problem here is just that (until now) I haven't had a clue what you're actually proposing.

The crucial paragraph is this one:

> It does not matter what **$:/language** contains. What matters is that language switching revolves around the languageTitle being switched to, rather than what language plugin has which **name** field. As I switch from `en-GB` to `de-DE`. I want all plugins with field **language**=`de-DE` to be applied, preferably in an order that I can specify. I do not want any dependencies as exist for `de-AT`, because I need a whole bunch of plugin localisations, not one and I never want to select any of those in the language switcher.

Finally, that's a decent, concise, functional description of the change you wanted. I wish you had put it like that right at the start.

>  I need a whole bunch of plugin localisations

Can you give some examples of plugins that need to override core language translations?

**Comment by pmario** [comment]
hmm, my reply from yesterday doesn't show up. ... Did anyone of you get an email, with the content?

**Comment by pmario** [comment]
>As I switch from en-GB to de-DE. I want all plugins with field language=de-DE to be applied, preferably in an order that I can specify. 

I think that's the key point here. It's just an improvement to the language switcher.

**Comment by pmario** [comment]
I think a "best practice" could be: 

- plugins are developed using en-GB as the default language
   - because we have the biggest reach possible.
- if a translation is missing some texts, the system automagically falls back to the default language.
- en-GB tiddlers are part of the plugin, but can be a stand alone plugin too.
- translations like de-DE are plugins themselfs and can be installed if the user needs them. 

I personally think, that the automatic fall-back is a great feature. Otherwise we may end up with a UI, that may miss some texts. 

As I see from Tobias other posts, he wants to create a "minimal" version, without any en-GB texts at all. IMO that isn't a big problem. It's just a different `--build` process. .. I'm pretty sure, with some OS "hard links" it's possible to create a German version, which doesn't contain a fallback language. (some tests needed.)

**Comment by tobibeer** [comment]
It's not that I don't want `en-GB`, it's just that the crucial part is that I don't always want it.

I would be perfectly fine if removing the last remaining language plugin was made hard when operating within the html wiki, but I feel that's pretty much a non-issue.

The missing link for me today is: how do I enable language switching for plugins? How do I make use of something like the `<<lingo>>` macro? It seems I can't. And if we can extend languages for plugins, being able to use the same mechanism to tweak a few "core" bits by overruling them, via plugin-prio or something like that, rather than repackage, is basically in the same ballpark.

**Comment by pmario** [comment]
As I wrote already. IMO Overwriting core content is an "anti-pattern". It must be a pull request for the core. Otherwise we will end up with an unmanageable mess.

**Comment by pmario** [comment]
A second thought I had lately, was: that we could / should have an eg: `plugin-generic.multids` file, which contains "core" texts, that can be used by plugin authors. Content there should be eg: 3-5 words maximum. There would be only one important rule: 

 - the file is append only. 
   - so once a "phrase" is accepted, it won't change.
   - so plugin authors can rely on them.

**Comment by tobibeer** [comment]
> As I wrote already. IMO Overwriting core language content is an "anti-pattern". It must be a pull request for the core. Otherwise we will end up with an unmanageable mess.

The point is exactly that it is not supposed to be manageable by the core,but only by the content creator of that wiki when an overwrite or by the plugin author when a plugin localisation..

> the file is append only.
> so once a "phrase" is accepted, it won't change.
> so plugin authors can rely on them.

The only thing about my OP that needs any relying on is plugin localisations. As for custom overrides by Walter to his Wiki there is nothing that needs relying on. Walter did this because he wanted to, just as he wanted to have the page-background be deeppink.

As for plugin localisations, those are *solely* the responsibility of the plugin other and none other.

**Comment by pmario** [comment]
>>As I wrote already. IMO Overwriting core language content is an "anti-pattern". It must be a pull request for the core. Otherwise we will end up with an unmanageable mess.

>The point is exactly that it is not supposed to be manageable by the core,but only by the content creator of that wiki when an overwrite or by the plugin author when a plugin localisation..

If you want to implement translation for a plugin, imo you also want that other "translators" contribute translations. right? We have [23 different languages](http://tiddlywiki.com/prerelease/editions/full/) atm. 

Why do you want to duplicate / overwrite existing "core language" strings in your plugins. It will create a additional complexity and inconsistencies!

**Comment by pmario** [comment]
OT ... OT ... OT
>A second thought I had lately, was: that we could / should have an eg: plugin-generic.multids file, which contains "core" texts, that can be used by plugin authors. Content there should be eg: 3-5 words maximum. There would be only one important rule:

> - the file is append only.
  - so once a "phrase" is accepted, it won't change.
  - so plugin authors can rely on them.

This was an additional thought, that should make plugin development easier! For some smaller plugins, the generic text sequences would be enough. So if the core would contain this stuff you'd get free translations for your plugins, because they are part of the core already. 

end of OT ... OT ... OT

**Comment by tobibeer** [comment]
> Why do you want to duplicate / overwrite existing "core language" strings in your plugins. It will create a additional complexity and inconsistencies!

Never said I wanted to do that. What I did say was that I want to be able to do the one (as a user) and the other (as a plugin author).
