### ISSUE TITLE
Plugin library in npm edition seems to be broken

### ISSUE THREAD

**Issue by ikarulus** [Jermolene/TiddlyWiki5#2709]
Opening the "Get more plugins"-page shows me some plugins to select in the chrome version.
However, in the node edition there are "Plugins (0), Themes (0), Languages (0)":
![1484243686](https://cloud.githubusercontent.com/assets/20602537/21901777/624ec984-d8f9-11e6-9442-acb1f148a4a0.png)

**Comment by tobibeer** [comment]
Apart from a missing button label, it works for me (both my library and the core) under Chrome 55.0.2883.87m & node.js & Windows 10:
![library](https://cloud.githubusercontent.com/assets/97566/21902446/3afb4292-d8fc-11e6-8855-0741780479d6.jpg)

**Comment by danielo515** [comment]
How are you serving your wiki ? HTTP or HTTPS ? If it is HTTPS then you have a protocol conflict. I think I have reported this a while ago. I do provide a library over HTTPS for noteself if that is your problem .

**Comment by ikarulus** [comment]
I do use SSL with Tiddlywiki. Can you provide a reference to this library?

**Comment by tobibeer** [comment]
FYI, I deleted my last comment, since it was related to modifications I made beforehand with the underlying core component having been refactored in the meantime.

**Comment by 0xCMP** [comment]
Yes seems like we need to fix SSL on the site somehow. I thought github would be providing that. Cloudflare could also provide SSL for free. As well as Let's Encrypt.

**Comment by danielo515** [comment]
Github provides SSL, but tiddlywiki in unable to detect when to ask for the library through https or http, it allwasy tried http. I have to open an issue about that, but I always forget

**Comment by Jermolene** [comment]
The standard plugin library url of `http://tiddlywiki.com/library/v5.1.13/index.html` is hardcoded in the shadow tiddler `$:/config/OfficialPluginLibrary`. You can overwrite that tiddler with a different URL, or just add another tiddler tagged `$:/tags/PluginLibrary` for the URL of your own library.

**Comment by danielo515** [comment]
Dear @Jermolene , would it be possible to add a hook that tries to switch the protocol used to access the plugin library? That way, you don't have to hardcode anything and you will be able to serve the same wiki over http and https

**Comment by Jermolene** [comment]
@danielo515 we could change things such that if the plugin library URL is missing a http(s) protocol, then we add the current page protocol. Thus, the library URL could be given as `tiddlywiki.com/library/v5.1.13/index.html`, which would resolve to `http://tiddlywiki.com/library/v5.1.13/index.html` for pages loaded via HTTP, and to `https://tiddlywiki.com/library/v5.1.13/index.html` for pages loaded via HTTPs.

The problem, of course, is that we don't yet support SSL for tiddlywiki.com. That is in itself a problem, and particularly so for the plugin library.

**Comment by danielo515** [comment]
> we could change things such that if the plugin library URL is missing a http(s) protocol, then we add the current page protocol. 

@Jermolene why just if the protocol is missing? Why not (also) make an attempt using the hardcoded one and in case it returns a cross-protocol error try using https?

> That is in itself a problem, and particularly so for the plugin library.

But github does support ssl. Why tiddlywiki.com does not? I am serving a plugin library over https without any problem. And, apart from that, it is not a problem because it will not work anyway because the mixed protocol error, but when you fix the SSL problem it will start working automatically.

**Comment by Jermolene** [comment]
> why just if the protocol is missing? Why not (also) make an attempt using the hardcoded one and in case it returns a cross-protocol error try using https?

But having the wrong URL for the plugin library is really a bug; the person setting things up has deliberately changed the URL of the plugin library (by moving it to an HTTPS URL), and so is responsible for updating the reference to it. Swapping out the protocol only deals with a subset of the possible errors here.

> But github does support ssl. Why tiddlywiki.com does not?

We're using GitHub pages, which only support SSL when addressed via a *.github.io URL, and doesn't work with custom domains, as we're using:

https://github.com/blog/2186-https-for-github-pages

Sadly, navigating to URLs like https://jermolene.github.io/prerelease/library/v5.1.13/index.html immediately redirects to the non-SSL version at http://tiddlywiki.com/prerelease/library/v5.1.13/index.html

> I am serving a plugin library over https without any problem. And, apart from that, it is not a problem because it will not work anyway because the mixed protocol error, but when you fix the SSL problem it will start working automatically

I'm not sure about the "it" is in some of those sentences! I think you're saying that the plugin library works over SSL if things are properly configured, but that tiddlywiki.com is not yet configured to provide an SSL plugin library.

**Comment by danielo515** [comment]
> But having the wrong URL for the plugin library is really a bug; 

Indeed

> the person setting things up has deliberately changed the URL of the plugin library (by moving it to an HTTPS URL), 

I don't think the users serving tiddlywiki over https think the same thing. Most of them probably just published their wikis to github.pages and are proud to see them there. They don't have the feeling of having change anything. They have not changed the URL of the plugin library, that is actually the problem.

> and so is responsible for updating the reference to it. 

Be prepared for a bunch of confused users.

> Swapping out the protocol only deals with a subset of the possible errors here.

It deals with the exact error we are discussing. The error is very specific and descriptive, so there is nothing wrong in making a second attempt when it occurs.

> Sadly, navigating to URLs like

that is a problem 🤔 

> I'm not sure about the "it" is in some of those sentences! 

Yes, it is a very bad sentence from my side. What I mean is: if you swap the protocol, it will not work  because tiddlywiki.com does not support SSL, that part is true. But currently it will not work either, so implementing what I'm proposing does not makes any harm. So, changing the behavior will not be an improvement neither and extra problem, but when you finally fix the SSL problem for tiddlywiki.com it will then work automatically. 

Regards

**Comment by Jermolene** [comment]
Hi @danielo515 for clarity:

My position is that TiddlyWiki core plugin library should be published over HTTPS as well as HTTP. To do that, we'll need a mechanism to select which plugin library URL should be used. The do-nothing option would be to have a second `$:/tags/PluginLibrary` tiddler pointing to the HTTPS URL. My preferred option is as given above, to allow the plugin library URL to be specified without a protocol, and then use the protocol of the current page. (I didn't pick this approach out of the air; it's how many URL references in HTML work see https://www.paulirish.com/2010/the-protocol-relative-url/).

I think you are arguing for a change to the plugin library mechanism such that if an attempt to access the plugin library over HTTP fails, then we should automatically try the same URL with HTTPS. One immediate problem with that is that detecting failure to load a plugin library is inherently slow because it involves waiting for a timeout. So I don't think that that approach is practical.

Part of the discussion on this thread is about people setting up their own plugin library when hosting over Node.js; that's an essential requirement because anyone running a fork won't want to use the core library.

**Comment by danielo515** [comment]
Hello @Jermolene ,

Thank you for taking the time to answer with such detail.

> My preferred option is as given above, to allow the plugin library URL to be specified without a protocol, and then use the protocol of the current page. 

That is definitely better than the current approach. If it is a well known and spread technique I'm fine with it.

>  One immediate problem with that is that detecting failure to load a plugin library is inherently slow because it involves waiting for a timeout

First of all, not detecting the failure at all it's slower because it tends to an infinite waiting (will never load). Second, the error in case of different protocol request is immediate, so we don't have to wait for a timeout.

> Part of the discussion on this thread is about people setting up their own plugin library when hosting over Node.js; that's an essential requirement because anyone running a fork won't want to use the core library.

Maybe on this thread, but I think it is a common practice to serve tiddlywiki from github pages.

That said, I am perfectly fine with your proposal.

Regards

**Comment by Jermolene** [comment]
Fixed in #3005
