### ISSUE TITLE
CheckboxWidget checked unchecked actions

### ISSUE THREAD

**Issue by tobibeer** [Jermolene/TiddlyWiki5#2732]
Allow to define actions to be run when the Checkbox widget is being checked or unchecked via respective widget attributes, e.g. **checkedActions**, **uncheckedActions**.

**Comment by mwiktowy** [comment]
New in 5.1.14, actions are an option on checking now but still including an "uncheckactions" option would have saved me a fair amount of effort trying to figure out how to make a fake checkboxes workaround with buttons. I ended up using mutually exclusive lists to swap visibility and do an action-createtiddler on "check" of ☐ button and  action-deletetiddler on "uncheck" of ☑ button. Quite a bit messier than check/uncheck actions would have been but I guess it is more flexible since I can make the buttons look however I want.

**Comment by twMat** [comment]
close? (@Jermolene )

**Comment by kookma** [comment]
Yes
This should be closed!

**Comment by saqimtiaz** [comment]
As of 5.1.16 the checkbox widget supports checkactions and uncheckactions. @Jermolene this can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
