### ISSUE TITLE
Can't download any themes manually

### ISSUE THREAD

**Issue by chrisportela** [Jermolene/TiddlyWiki5#2743]
Using SSL for my Wiki and I can only install manually, but I can't find a way to download any of the themes. Seems like the website is not deploying all the plugins/themes when it's being built.

Is this a known issue?

**Comment by tobibeer** [comment]
* Download themes from where?
* What's not deploying where?
* Built how?

Please provide specific details.

**Comment by 0xCMP** [comment]
> * Download themes from where?

tw5.com 

> * What's not deploying where?

My instance of TiddlyWiki which I'm serving over SSL so I can not use the normal method of the built in plugin/theme installer.

> * Built how?

Not sure, but looking through Jermolene's repos I figured it was his github pages repo which seems to be built using some utilities in another repo and was recently updated, but for some reason that update seems to be broken because the themes listed in this repo's folders are not published for downloading even though they're in that listing of officially supported themes.

i.e. http://tiddlywiki.com/#Manually%20installing%20a%20plugin

http://tiddlywiki.com/plugins/tiddlywiki/katex/

To manually install drag this link to any TW5 instance [$:/plugins/tiddlywiki/katex](http://tiddlywiki.com/plugins/tiddlywiki/katex/#%24%3A%2Fplugins%2Ftiddlywiki%2Fkatex)

Vanilla theme has no page and can't be downloaded (nor any other theme)

http://tiddlywiki.com/themes/tiddlywiki/vanilla/

Github pages repo I'm talking about https://github.com/Jermolene/jermolene.github.io

The tools I mentioned https://github.com/Jermolene/build.jermolene.github.io

**Comment by tobibeer** [comment]
If you're building a wiki, you should be able to just specify those themes for inclusion in your tiddlywiki.info ...if I'm not mistaken, see [How to build a TiddlyWiki5 from individual tiddlers](http://tiddlywiki.com/#How%20to%20build%20a%20TiddlyWiki5%20from%20individual%20tiddlers). So, no need to click on "get more plugins" in a browser based, served wiki.

**Comment by Jermolene** [comment]
Hi @0xCMP the interactive plugin manager in TW5 doesn't currently work properly for core plugins when run under Node.js (it works fine for third party plugins). As @tobibeer says, plugins from the core repository are installed in the `tiddlywiki.info` file. For example:

https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/full/tiddlywiki.info#L4-L26

**Comment by Jermolene** [comment]
Thank you @pmario
