### ISSUE TITLE
Best method for self-hosted node.js TiddlyWiki Backup

### ISSUE THREAD

**Issue by gonik** [Jermolene/TiddlyWiki5#2759]
Dear Jermolene,

First of all let me tell you, that you have done a fantastic work with TiddlyWiki. I used the standalone .html file TW for many years, since approximately 2007.

Last month I decided to give it a go and host my TW in a Raspberry Pi that I had and everything is working smoothly.
The folder i use to run the tiddlywiki server is located under `~./mywiki`.

Do I only backup that folder or I need to something else as well? Most probably I will use a cron-job to zip and store the backup. Is there any other method that you recommend?

I'm pretty new to the whole node.js thing, sorry for the many questions.

Best,
Nikos

**Comment by passuf** [comment]
Sorry for not being Jermolene, but I hope I may as well try to answer your question.

First, just to make sure, you should check that the contents of your TiddlyWiki are actually stored inside the folder on your Raspberry Pi (e.g. look at the contents of the `~/mywiki/tiddlers` folder). Each tiddler gets its own `.tid` file, you can open it with a text editor to check whether the content is up to date. See [TiddlyWikiFolders](http://tiddlywiki.com/static/TiddlyWikiFolders.html) for more info.

Since the whole TiddlyWiki is stored inside your `~/mywiki` folder (unless you included other wikis), it is sufficient to create backups of this folder. How you perform the backup is up to you, a cron-job, rsync, ssh, email, ... whatever suits you best, but I would recommend that you store your backups on a different storage than your Raspberry Pi in case it burns down. Personally, I sync the contents of the wiki folder to multiple computers using [Syncthing](https://github.com/syncthing/syncthing).

The documentation covers this part very well, take a look at [The First Rule of Using TiddlyWiki](http://tiddlywiki.com/static/The%2520First%2520Rule%2520of%2520Using%2520TiddlyWiki.html).

Hope this answers your questions.

Best,
Jonas

**Comment by gonik** [comment]
Dear Jonas,
Thank you for the comprehensive answer! Indeed I already checked the `~./mywiki` folder before opening this thread to make sure that everything is stored in there.
However I wasn't sure if this folder is the only thing I should backup (maybe TW stores something, in another folder as well).

Since you cleared this up for me, then I will setup a cronjob to backup this folder.

Again, I higly appreciate your answer.

Best,
Nikos

**Comment by Jermolene** [comment]
Thanks @passuf great answer!

**Comment by pmario** [comment]
@gonik 
can this issue be closed? .. If so .. you or Jeremy need to close it.
