### ISSUE TITLE
fixing highlightblock.js

### ISSUE THREAD

**Issue by welford** [Jermolene/TiddlyWiki5#2778]
This commit looks to have broken highlightjs on export:

https://github.com/Jermolene/TiddlyWiki5/commit/4be5f0abe8830de7e11138d56aaa3aba420ed615

Firstly, It does not seem to correctly highlight the block at all:

![image](https://cloud.githubusercontent.com/assets/4590399/23143850/9177ec78-f7bb-11e6-9790-fcb7f5c6728f.png)

Changing the line 
`hljs.highlightBlock(domNode);`
to
`domNode.children[0].innerHTML = hljs.fixMarkup(hljs.highlight(language, domNode.textContent).value);`
fixes this:

![image](https://cloud.githubusercontent.com/assets/4590399/23143918/17941b6a-f7bc-11e6-936c-0a3dd6373d32.png)

Secondly, the former method silently ignores 22 errors compared to 1 for the latter (when exporting my static blog):

`[TypeError: Cannot read property 'length' of undefined] * 22`
vs
`Cannot get textContent on a raw TW_Element * 1`

Is it possible to identify a raw TW_Element in this code and skip over those domNodes? I would like to get highlighting working again in static exports.

**Comment by Jermolene** [comment]
Thanks @welford 

So, the problem with the current code is that highlight.js is incapable of working with the fakedom on the server. (That's the `Cannot read property 'length' of undefined` error. I spent some time hacking fakedom to add more of the properties needed by highlight.js but hit a brick wall when I found that highlight.js uses the global `document` object).

As you note, the change to using highlight.js to generate a raw HTML string also fails. For me, I found it was failing when saving my static CSS tiddlers. The problem turned out to be that the full HTML rendering of the CSS tiddlers was being highlighted before trying to extract the plain text.

I've tackled this by extending the fakedom so that the textcontent of an innerhtml can be explicitly specified. Commit coming up.

**Comment by welford** [comment]
Thank you very much :)

**Comment by Jermolene** [comment]
@welford thanks for tracking things down. Let me know how the new commit works for you

**Comment by welford** [comment]
@Jermolene it works well, thanks again.,
