### ISSUE TITLE
textarea does not resize when story mode is zoom

### ISSUE THREAD

**Issue by buggyj** [Jermolene/TiddlyWiki5#2794]
Got to tiddlywiki.com, open the control panel and select zooming from the appearance->storyview tabs, then click on the info tab.
Now in the sidebar, click the open tab and select 'HelloThere', (which replace $:/ControlPanel in the story) then in the open tab click '$:/ControlPanel' - now look at the 'Default tiddlers' panel and observe the height of the textarea box.

**Comment by pmario** [comment]
Which browser do you use. I did test your steps with FF latest and it works as expected. 

can you post a screenshot *.png here, how it looks like on your screen?

**Comment by twMat** [comment]
Issue confirmed in Chrome and FF on Win10.
Note that it is necessary to go to another tiddler before looking again in Ctrlpanel default tiddlers. 
The textarea becomes contracted with a scrollbar.

**Comment by pmario** [comment]
Can confirm the issue now. Did not switch back to info tab in the second step. 

The point is, that the text area gets `style="height: 100px"` hardcoded and with the issue it gets
`style="height: auto"` which reduces the size to the content. 

That seems to be a problem with the js code, because if I change the edit-widget to edit-text-widget and set `autoHeight` parameter to yes, it still applies style=height:auto.

**Comment by pmario** [comment]
As soon as you start to type the first char, the refresh mechanism fixes the problem.

**Comment by buggyj** [comment]
closed as duplicate of #3098
