### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2807]
I would like to be able to paste images from the clipboard/memory into tiddlers. Possibly onto the drawing canvases that you get by setting tiddler *type* to image,  but ideally straight into the default editor textarea. For a digital notebook, this is a reasonable feature IMO.

Maybe these are viable routes:

* https://codepen.io/netsi1964/pen/IoJbg
* https://gist.github.com/Buildstarted/4577472
* https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by Jermolene** [comment]
Hi @twMat not sure if you know, but Chrome does already support pasting; click on the page background and then use the menu or keyboard shortcut to trigger paste, and the pasted item will be imported as a new tiddler.

Making things work in other browsers would indeed be useful, but last time I looked the prospects were not good. (Copying to the clipboard has got a lot better supported, though, and we should probably add a message or widget for it).

**Comment by twMat** [comment]
Ah - I did not know this! Great!

And on my Win10 it actually works in both **Chrome, FF and Edge!** Not IE.

Thanks @Jermolene . Closing.

**Comment by Jermolene** [comment]
Pretty neat that it works in Firefox and Edge, that's new. I've updated the docs.

**Comment by ldorigo** [comment]
Hi! 

Sorry to reopen this old issue, but I cannot get this to work, neither on Chrome nor on any browser I tried (Firefox, Safari, Opera). What I'm doing is taking a screenshot (with macOS, that copies it to the clipboard) and trying to paste it into a new tiddler I'm making. Nothing seems to happen.

At the moment, the only way there is for me to add a screenshot is: 

Save screenshot to a file -> find file on my computer -> drag to TW -> confirm import -> open the new image tiddler -> edit -> change title to something more readable than the auto-generated screenshot name -> confirm -> go to original tiddler -> click on the 'insert image'  -> find the image in the list (which is not sorted by date - so it can be quite hard to find) -> finally resume editing. 

That's more than 11 steps for something that should be trivial. When using TiddlyWiki to take notes in class as I do, it's a huge waste of time which means I often fall behind what the teacher says just because I need to annotate an image. 

So either I'm doing it wrong, or something is broken with the paste feature :)

**Comment by Plloi** [comment]
@ldorigo I just tested on windows 7 and it still works,  so I'd say open a new issue as it may be a mac specific problem.

**Comment by Jermolene** [comment]
Hi @ldorigo I'm using macOS 10.13.3 and I can paste successfully on Firefox, Safari, Opera and Chrome. The steps I took were:

1. Open tiddlywiki.com in the browser
2. Use Control-Shift-Command-4 to take a screenshot to the clipboard
3. Click within the TiddlyWiki page (eg, the space above the top tiddler)
4. Press Command-V to paste the image
5. Click import to import the image

**Comment by ldorigo** [comment]
Hi,

Indeed - that works. Sorry, it didn't occur to me that I had to click _outside_ the tiddler I was editing before pasting.

However, that only barely reduces the amount of clicks/work needed to include an image from the clipboard, as one still has to import, open the imported tiddler, rename it (this is unskippable as all pasted images have the same default name), close/go back to the tiddler he was editing, and finally add the image.

It would be really nice to be able to directly paste inside the editor and get the picture (the WikiText pointing to it) to appear where the cursor was. It could be imported and given a random name in the background. 

I'm slowly getting acquainted with the codebase, so if you don't consider this a feature that should be part of the core, I'll probably make a plugin for it in the near future :-)

**Comment by nichollskc** [comment]
Any update on this? Pasting an image directly into a tiddler (without the manual steps of importing, renaming and copying the title into the tiddler) would make a big difference to how I use tiddlywiki!

**Comment by neer201** [comment]
It will be really cool feature - it speeds up note writing!

**Comment by Jermolene** [comment]
Hi @neer201 @nichollskc we added the ability to paste an image directly into the tiddler editor in v5.2.0: https://tiddlywiki.com/#Release%205.2.0

**Comment by neer201** [comment]
@Jermolene Hi, thank you for the fast reply. Yes, I see and it works in case we drag and drop file from file manager to tiddler editor. 

But I mean another case: 
1) Suppose we use any software for screenshot capturing. When we use it, we can copy screenshots automatically (for example pasting in some document editors) to clipboard buffer. 
2) When I try to paste an image from the clipboard to the tiddler editor - nothing happens. But I can paste it in the background area and it calls import manager. 
3) But in this import manager, the default name of the image is 'image.png' and I have to rename it. Maybe if the default name will be random or hash of file it can look more convenient. And this feature can have some options in the setup menu.

**Comment by Jermolene** [comment]
> When I try to paste an image from the clipboard to the tiddler editor - nothing happens.

Pasting an image into the tiddler editor in v5.2.0 or above should bring up a popup to allow the image to be imported. If you're not seeing that then something is going wrong. What version of TW, OS and browser are you using?

**Comment by neer201** [comment]
TW 5.2.1, OSX 12.2, Chrome

Yes, you are absolutely right. It is my fault. Thank you for your help! It seems the Stroll extension changed this behavior and after completely deleting Stroll from my TW I can paste an image from the clipboard and it works.

But, I want to add that the default name of the image after pasting from the clipboard is `image.png`. Maybe it will be cool if the default name would be a random string. Because changing name every time from my point of view is inconvenient.

**Comment by linonetwo** [comment]
Pasted image from internet (without filename) should be rename to something like `Pasted image 20220523201722.png` like how Obsidian does.

**Comment by pmario** [comment]
>Pasted image from internet (without filename) should be rename to something like Pasted image 20220523201722.png like how Obsidian does.

Have a look at the bundler plugin: https://wikilabs.github.io/editions/bundler/

**Comment by playgithub** [comment]
> > Pasted image from internet (without filename) should be rename to something like Pasted image 20220523201722.png like how Obsidian does.
> 
> Have a look at the bundler plugin: https://wikilabs.github.io/editions/bundler/
> 
> ![grafik](https://user-images.githubusercontent.com/374655/222291233-5eb865c5-9243-4a55-9675-02b6795652fd.png)

Even better to make it native.
