### ISSUE TITLE
DnD to order Stylesheets

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2823]
[Demo](http://cssorder.tiddlyspot.com/).

The demo uses the coming 5.1.14 DnD features to enable the user to rearrange the **order of the stylesheets**. This is very important because the order affects which styles take precedence. There is in TW no explicit display of the default stylesheet order (which has caused much confusion for me and [others](https://groups.google.com/d/msg/tiddlywiki/BTF-MYX7DiE/FG_FM7xeAQAJ). For one thing, I assumed added stylesheets had precedence before core stylesheets, but nope).

The Demo introduces a `S:/tags/Stylesheet` tiddler with a *list field* which is what is manipulated with the DnD.

**I propose** such a re-arrangable list is presented under *Ctrlpanel > Appearance > Stylesheet Manager* or similar. It would make for a useful and also visual demonstration of the DnD functionality already in an empty TW.

**Comment by gernert** [comment]
Very nice!
FYI, some time ago I updated the [docs](http://tiddlywiki.com/prerelease/#Using%20Stylesheets)

**Comment by Jermolene** [comment]
Great stuff @twMat, and nicely demoed.

It does raise a background concern: because DnD isn't universally supported we should be careful to provide alternative means to achieve all its functionality. In this case, I think we need up/down buttons that can be used when DnD isn't available. There's an example in the XLSX importer control panel:

<img width="130" alt="screenshot 2017-04-07 11 33 17" src="https://cloud.githubusercontent.com/assets/174761/24796713/0b2f62f6-1b86-11e7-9c2a-963097f3290d.png">

**Comment by tobibeer** [comment]
> I think we need up/down buttons that can be used when DnD isn't available. 

I would tend to postpone such implementations until actually requested.

**Comment by TiddlyTweeter** [comment]
@twMat that is a very neat demo. Regardless of whether its integrated in TW directly or not, it could be very useful to ease interactive CSS design for TW.

**Comment by twMat** [comment]
Thank you everyone who engaged in this.

@pmario - the DnD feature is indeed implemented so I'm closing this thread. I do still wish there was some brief *information* about why stylesheet order matters and how to reorder. The Ctrlpanel tab you refer would be a sensible place for this. But this is a separate issue.
