### ISSUE TITLE
Feature Request: option to make new tiddler from search string

### ISSUE THREAD

**Issue by hchaase** [Jermolene/TiddlyWiki5#2831]
If the text string you search for is not found, present a button to make a new tiddler with that title. Or make a clickable text in the search drop down like: "create "your search string" ".

Why: 
you want to make a new tiddler, but search to see if you have that information already. When you don't find that info, it would be fast to just hit a button and create said tiddler.

**Comment by DelphiCoder** [comment]
I don't know how useful this would be as most people would determine if a Tiddler exists when typing in just three or four letters of the term they are looking for.  As for myself, I rarely type a complete word into the search bar before I find what I am looking for.  If a tiddler doesn't exist and because I tend to use Tiddler Titles composed of several words, I just hit the new button.

**Comment by pmario** [comment]
imo plugin territory: https://wikilabs.github.io/#new-tiddler-from-search

**Comment by hchaase** [comment]
I guess it is. and how cool you made it !

**Comment by twMat** [comment]
Agree it's plugin territory.
@pmario - cool thing!
@hchaase - close issue or further arguments to put it in standard distro?

**Comment by hchaase** [comment]
is there any guidelines on when a feature should be plugin and when core? I don't really grasp where to draw the line (and hence post properly)?

**Comment by pmario** [comment]
>is there any guidelines on when a feature should be plugin and when core? I don't really grasp where to draw the line (and hence post properly)?

I think there is no clear rule. At this time in the TW lifetime, imo most new functions should be tried to be build as plugins first. If it works -> OK ... Only if it's not possible as a plugin, it should be core. eg: because some essential low level functions don't exist .. AND the new function should be "generic" and useful for everyone. 

In my opinion, the core should provide a "playground" for stuff to be developed. So it should provide "just enough functions" that others can use, to build new and "opinionated" stuff (plugins, themes and editions) . ... 

As soon as a solutions contains someones opinion and there are different ways to achieve a "very similar" result, it should be a plugin, because diversity sparks new ideas. 

just some thoughts.

**Comment by twMat** [comment]
>is there any guidelines on when a feature should be plugin and when core? I don't really grasp where to draw the line (and hence post properly)?

Your request was not unreasonable at all. The line *is* fuzzy because of the open ended nature of TW. 

I just [posted a reply](https://groups.google.com/forum/#!topic/tiddlywiki/zLr0Y5EhKMc) on the boards about core vs plugin.

**Comment by tobibeer** [comment]
I would actually suggest the following as a core enhancement:

If you have entered any text in the search bar AND if that text is not a valid tiddler title AND you click the `+` button to add a new tiddler, then that should by default be its title instead of `New tiddler`.

At least, I see no apparent harm in a new tiddler not being called "New tiddler". To the contrary.
