### ISSUE TITLE
Req. for action widgets setclass and removeclass

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2866]
**Purpose**
Full CSS control of a tiddler...
...via a (required) active click

**Proposal**
Add action widgets to set/remove classes at "tiddler-frame level" in a **similar way that adding a tag `foo` already does**, i.e: 

`<div class="tc-tiddler-frame ...... tc-tagged-foo">`

The widget calls could be like so

`<$action-setclass $tiddler="..." class="..."/>`

`<$action-removeclass $tiddler="..." class="..."/>`

The setclass should not add a `tc-` prefix.

**Comment by tobibeer** [comment]
@twMat, I believe this is too heavily relying on the rendered state vs. the store state. Imho, the philosophy is to have the rendered state be based on / represent the stored state, so modifying a tiddler's dom representation is not a great option, I think. Possibly, there could be system a tiddler namespace to define extra tiddler classes like:

`$:/styles/tiddler/TheTiddler/class-foo`

,,,and then some mechanism to apply `class-foo` to *TheTiddler* instead?

The idea being to dynamically create or delete such class tiddlers?

Also, please suggest features in terms of what you want to achieve rather than how. In your case, the requirement is to dynamically add css classes to tiddlers when rendered. It is not to mandatorily have an action widget do it. This is a very important distinction to make: the what (and the underlying why) from the how. Feature requests should always, first and foremost, name the *what* that is being requested along any *why*. The *how* is more or less up to discussion later, once all the requirements are well defined.

If your requirement was to have an action widget trigger the behavior, I think I have demonstrated how action-set-field can easily do what you ask... and how the change you want is actually at some other place, namely the bit in the viewtemplate that determines what classes to apply upon rendering.

**Comment by pmario** [comment]
Tobias is right. action-widgets don't have an idea, about the dom and classes. ... 

But action-sendmessage could send a message, that bubbles up the widget tree. 

`<$action-sendmessage $message="tm-setclass" class="className" />` 

So ther only needs to be an event handler that catches the message and knows what to do. .... 

No idea implementation wise, but I think that could work and would be valid too.

**Comment by pmario** [comment]
IMO it would need a new widget, like linkCatcher or NavigatorWidget ... just a reminder

**Comment by twMat** [comment]
Rather short reply made even shorter: I agree.

Further, I just realized that if we implemented @pmario 's solution (which I fail to find now - link anyone?) to get away from the current "tag based" method for styling tiddlers, then this OP would probably be simple. Correct me if I'm wrong, but I believe @pmario's method instead used fields to the to-be-styled tiddler. This would mean it is simple to apply styles by means of some setwidget as @tobibeer points out.

**Comment by tobibeer** [comment]
I’ll consider making a pull request alongside a demo for my proposal, so it’s more interactive what’s going on and how. And if desired, it will make it into the core ;-)

**Comment by pmario** [comment]
>Further, I just realized that if we implemented @pmario 's solution (which I fail to find now - link anyone?) to get away from the current "tag based" method for styling tiddlers,

add data-title and data-tags to the tiddler DOM in ViewTemplate #2737

It's not exactly the usecase you created with the action-widgets. ... 

----------

I didn't implement the "class" field proposal, since I thought, the PR would have a better chance to be merged, if I stick to the basics. 

The PR is broken atm. So I'll need to fix it anyway.  We'll see

**Comment by pmario** [comment]
The actual change to the ViewTemplate is minimal. .... but there are 15 tiddlers of documentation.

**Comment by twMat** [comment]
I believe this was later fulfilled with pmarios excellent styling additions.
Closing
