### ISSUE TITLE
Modification proposal for the Explore tab

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#2874]
Hello everyone,

I would like to propose some modifications (improvements) for the new Explore tab.

**Modifications**

- Changed the name (caption) to be more accurate: Explore --> ''System Explorer'' -- similar to Windows Explorer
- Introduced 2 new concepts: ''leaf node'' (similar to a file) and ''branch node'' (similar to a folder) -- similar to Windows Explorer.
- Removed prefixes and suffixes (background noise) for the leaves and branches to make them more easier to read and cleaner.
- Improved usability by separating leaves from branches -- leaves first and branches last -- similar to Windows Explorer.

**You can test it [here](http://morosanuae.tiddlyspot.com/#System%20Explorer%20tab%20(sidebar%20-%3E%20More))**

**NEW: Now it works well also with syslink on!** - based on a Jeremy solution

This is my first intervention so... please be gentle with me!

Thanks!

**Comment by Jermolene** [comment]
Hi @morosanuae great work, thank you! Welcome to the community.

I like all the changes you have introduced (particularly number 3, it makes a great difference) and would be happy to accept them into the core.

One minor niggle is the extra gap between the leaves and branches at the top level. It looks like it is a consequence of browser default styles, in which case it could be fixed by wrapping the entire thing in another dummy/wrapper `<ol>/<li>` pair.

The problem with the 'syslink' parser also needs to be fixed. The fix may be to use the `<$text>` widget as follows:

```
\define cleanChunk()
<$list filter="[[$(chunk)$]] +[removesuffix[/]]" variable="cleanChunk">
<$text text=<<cleanChunk>>/>
</$list>
\end
```

If you're comfortable with making a GitHub pull request please go ahead when those points are resolved; otherwise I'm happy to retrieve the code from http://morosanuae.tiddlyspot.com/

Finally, apologies for the bureaucracy, but please could you sign the Contributor License Agreement, as described [here](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md).

**Comment by morosanuae** [comment]
Hi Jeremy and thanks for the feedback.

I'm very happy that you consider my work useful. I'm also very grateful for the chance to contribute to an already brilliant and useful application that I use every day.
I will try to make a pull request, but I need to learn how to do it first because I'm not an advanced GitHub user. I will also sign the CLA, no problem. I'll come back when it's done.

Thanks again.
Adrian.

**Comment by morosanuae** [comment]
@Jermolene, I made the modifications as you suggested. I also inserted the blank button for the leaves to be aligned with branches (like in the official version).
For the gap problem I had to make a few more changes than you suggested because the visual output wasn't quite like the initial version. Now there is only one `<ol>` element (main wrapper) and the leaves and branches macros populate that one list.
The only thing that bothers me now is that only the root leaves show a visual difference between default and modified tiddlers. I guess inner levels follow the styles defined for the "tc-table-of-contents" class or in other places. 
You can test the new version in the same place: [http://morosanuae.tiddlyspot.com](http://morosanuae.tiddlyspot.com).
I also signed the CLA as requested.

**Comment by morosanuae** [comment]
@Jermolene, I made a pull request. I created a new .tid file in `core/ui/MoreSideBar`. I hope I put it in the right place and the content is ok. I think it also needs the caption file...

**Comment by morosanuae** [comment]
@Jermolene, I made a new version for the System Explorer (v2) incorporating Mat ideas [(see TiddlyWikiDev discussion).](https://groups.google.com/forum/#!topic/tiddlywikidev/n2yZ_TCD0bI) and a few other esthetic changes (e.g. icons for leaves and branches). Personally I like both versions.

You can test the new version (v2) in the same place: http://morosanuae.tiddlyspot.com.

**Comment by twMat** [comment]
@morosanuae - I really like what you've done!

I'm not fully convinced with the icons because they are misleading, at least to someone who isn't familiar with TW. @Jermolene ,we should probably introduce a core *tiddler* icon...

...but the bigger problem in the folder icon, because they aren't folders of course. I think a more conventional "expand" indicator is probably better. Perhaps the angle bracket arrow or some kind of little plus sign.

An issue, probably unrelated to your creation:

Go to your site and scroll the sidebar(!) down to bottom. 
Click the _morosanuae folder multiple times so it closes and opens - and note the *jump* this causes.

**Comment by morosanuae** [comment]
@twMat - Thanks, I really appreciate it!

Maybe the folder/file icons are not accurate representations but I think they assort well with the tree perspective (vision) that is very similar with Windows Explorer, an application familiar to every computer user. Even there's no such thing as a folder in TW, this organizational units _really_ exists in the tiddler names. Maybe it would be easier for someone to think about them as "virtual folders". So IMHO the folder icons will help newcomers see things in this way.

Referring to the final issue, I tested it and you're right. It seems that the original Explore tab doesn't suffer from it. I don't know the cause yet, I need to investigate.

**Comment by morosanuae** [comment]
@twMat - about the "jump" issue. I assume you're referring to the jump of the view not of the sidebar. For me, the only "jumping" appears only if I collapse a folder that results in collapsing the entire tree which determines it to "come into view" which I guess is a normal thing. I could not replicate the issue in the order you mention it. I made a comparison with the original Explore tab and it seems to me that they behave the same.

Sorry if I wasn't very clear, English is not my native language and sometime is very hard for me to express my thoughts correctly.

**Comment by Jermolene** [comment]
Hi @morosanuae sorry for the delay. I'd like to include your V2 improvements in the core, could you prepare a PR? Will you be able to address #2907 in the same PR? Many thanks

**Comment by morosanuae** [comment]
Hello @Jermolene, no problem! I created a new PR with all the changes. See #2923.

**Comment by tobibeer** [comment]
@Jermolene / @morosanuae, any particular reason why the actual tiddlers come first and only then "folders" (even if virtual)? General convention has it (at least in windows), that folders come first.

**Comment by morosanuae** [comment]
@tobibeer I didn't follow an "official" convention. I guess it's seemed more natural to me (from less to more). And I also thought it was easier to find the tiddlers, less scrolling. In the tree root, for example, I would have to scroll down for the root system tiddlers.

**Comment by tobibeer** [comment]
I can live with the current implementation, but I would definitely prefer to have folders up top, because:

1. chances are that if I go to "explore", I care about folders most of all and only then items
2. the list of folders is somewhat well defined, individual tiddlers, not so much
3. so, they won't shift down ever further with every new tiddler in its parent folder

**Comment by Jermolene** [comment]
@morosanuae I think this can be closed?

**Comment by morosanuae** [comment]
@Jermolene I forgot that it was open, sorry. I'll close it.

@tobibeer I will close the issue but I'll think about your preference. It's a matter of personal preference anyway. Personally, I like it just the way it is now but an option to select between modes would be nice but I don't know if this is possible. I'll have to take a look first.
