### ISSUE TITLE
Add the sources tab to the dev edition

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2921]
Hello,

Usually, when I am reading something at tiddlywiki.com and I find an error I just click the info button, the sources tab and that leads me to the Github page where that tiddler lives. Very comfortable and very engaging.  I would love to have the same functionality on the dev edition, where I feel more help is needed and I have intentions to contribute. You know he easier the better.

**Comment by pmario** [comment]
That should be relatively easy. Just adjust $:/ContributionBanner from tiddlywiki.com so it fits the dev edition.

**Comment by tobibeer** [comment]
@danielo515, made a PR #3047, so I guess you can close this one.

@pmario: It turned out slightly more complicated than that. ;-)

Also, [How to add a banner for GitHub contributions](https://tiddlywiki.com/#How%20to%20add%20a%20banner%20for%20GitHub%20contributions) should probably mention the **Sources** tab in the info panel.

**Comment by danielo515** [comment]
@tobibeer I'll close it as soon as is merged.
Thanks a lot
