### ISSUE TITLE
RSOD -- Another View

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2935]
IMO, the RSOD in TiddlyWiki is a very mixed metaphor. WHY? Because a lot of the time it does NOT indicate DEATH. 

I think the current approach is wrong. 

I think it would be far better as a PINK ADVISORY, not RSOD---BECAUSE its very, very often NOT fatal. 

Doing RSOD's to play it safe I think is a flag too far. 

In a way its compensating (fearfully) that users have not backed-up. That to go on after an RSOD could mess you up. 

I think that is the wrong approach. 

As far as I understand it the RSOD expresses many states of a TW, MOST of which are recoverable from. 

By over-emphasizing RSODs as TERMINAL I think it weakens appreciation of TiddlyWiki's robustness.

Just my 2 cents.

**Comment by tobibeer** [comment]
The RSOD does not express anything terminal, except: when it comes to your session, in the sense of: You should stop working on your content changes and figure out what's wrong.

I would also not necessarily change color. Believe me when chrome shows me a square frowning face, I don't like it one bit more than a not too in-your-face red alert.

By the lack of engagement in this request I would think it's best to close it.

Otherwise, if you have any actionable proposals, please get to the drawing board and design an actual change request... reflected by the title as well. ;-)
