### ISSUE TITLE
Recent-Tab does not work anymore (Since Upgrade to 5.1.14)

### ISSUE THREAD

**Issue by gesundelehre** [Jermolene/TiddlyWiki5#2942]
Since the last upgrade, when i add new tiddlers they don't show up in the Recent-Tab anymore. 
(The old ones however still show up)

What has changed?

This is the Tiddler that is behind the Tab as of now:

```
!!Topics
<<tagging>>

!!The Actual Timeline
<$macrocall $name="timeline" format={{$:/language/RecentChanges/DateFormat}}/>
```

**Comment by twMat** [comment]
@gesundelehre - as seen on e.g tiddlywiki.com it does work so this is more a problem with your own setup. For this reason I suggest that you ask on the [forum](https://groups.google.com/forum/#!forum/tiddlywiki) instead (for your sake because you'll likely get help there). The github place is more for development issues.

Please close this issue, and see you on the forum :-)

**Comment by gesundelehre** [comment]
Somehow it now worked without having the need to change anything. Very strange....
