### ISSUE TITLE
Suggestions for future features

### ISSUE THREAD

**Issue by jkathir** [Jermolene/TiddlyWiki5#2965]
Having tags for each document (Reference: https://collatenotes.com/)
Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
Import data from Zim Wiki or Text files - (Reference: https://collatenotes.com/)
Google like search like ambar cloud (Reference: https://ambar.cloud/)
Function Keys support to navigate previous/next hit like Folio Views
Number of search results before search performed like table (Reference: http://table.branham.org/#/main)
Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)
Please go through the menus of cherry tree software and incorporate which is easly doable.
drag and drop support between nodes

**Comment by twMat** [comment]
Hi @jkathir the idea is for this github TW to only concern very well specified requests that is possible for someone to take action on. The list of ideas you post is better posted on the [discussion forum](groups.google.com/forum/#!forum/tiddlywiki), where things can be analyzed and you can reply to questions and people can express opinions. Once your suggestions are well defined and actionable, you can repost them here with one suggestion per thread.

Based on years of membership in this group, I can **assure** you that absolutely *nothing* will come from your list of suggestions otherwise, so I say this mostly for your sake.

Please close this thread.

**Comment by tobibeer** [comment]
@jkathir, pls. close. (@Jermolene)
