### ISSUE TITLE
Switch to @Arlen22's improved dropbox.tiddlywiki.com

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#2985]
The current dropbox.tiddlywiki.com only works with TiddlyWiki Classic. @Arlen22 has developed an improved version at https://twcloud.github.io/tw5-dropbox/ that works with both TWC and TW5.

http://dropbox.tiddlywiki.com currently redirects to a Dropbox public HTTPS URL hosting the original version.

We should make @Arlen22's version available as the default. Options:

* Copy @Arlen22's code over to the existing Dropbox host via a pull request to https://github.com/Jermolene/TiddlyWiki-in-the-Sky
* Change the DNS for dropbox.tiddlywiki.com to point to @Arlen22's existing deployment

It's probably a matter of what makes life easier for subsequent updates. What do you think @Arlen22?

**Comment by Arlen22** [comment]
I believe I gutted the TWC code from the one I am hosting. So we should still make the old one available or else combine the two again. 

The thing is though, it really is due for an upgrade, as I'm pretty sure it's using the Dropbox v1 API, which is going to be deprecated at some point. I'm hoping to use some of the tools here that I plan to develop for TiddlyServer. 

For security, I like Github because it uses SSL, although I don't plan to depend on it for any secrets. All of the dropbox communication is with dropbox.com directly so Github's encryption is only to make sure the page is not tampered with.

If you want to change the DNS to point to mine, I like that idea. I think you have commit access already in case you need to make changes. I want to host more connectors, but for now we only have dropbox. But we can't share commit access willy-nilly because of the shared localStorage, so it's probably fine to use Github.

**Comment by Arlen22** [comment]
That being said, the v1 API is shut down now. If someone wants to port the save mechanism for TWC, PRs are welcome. If you can't figure out the Typescript code, open an issue instead and I'll do my best to get the code in.

**Comment by Arlen22** [comment]
For some reason, TWC files do not open either. I don't understand why. If anyone understands why I would be delighted to understand. Also, is there a way I can get around TWC downloading a fresh copy on save? I can just give it the text I loaded initially if I know what to override.

**Comment by Arlen22** [comment]
I've gotten TWC files working now, although only the bare minimum. It seems to work with newer files, but not with older ones or extremely customized ones perhaps.

**Comment by Jermolene** [comment]
Hi @Arlen22 apologies for the delay. I'm trying to assemble links to add for TW 5.1.15, and wanted to ask you for the correct URL?

**Comment by Arlen22** [comment]
https://twcloud.github.io/dropbox/

**Comment by Jermolene** [comment]
Thanks @Arlen22
