### ISSUE TITLE
Unable to save over WebDAV when no file in URL

### ISSUE THREAD

**Issue by javabean** [Jermolene/TiddlyWiki5#2995]
Hello,

The WebDAV saving does not work when the html file is served as the default directory index, e.g. https://wiki.example.net/

It works when specifying a file in the URL, e.g. https://wiki.example.net/index.html

Thanks!

**Comment by pmario** [comment]
i can confirm this behaviour.

**Comment by pmario** [comment]
Hi @javabean, ... I also "fall into this trap" quite a bit. .. The problem is, that this can't be solved client side. 

eg: 
`https://example.net/`  ... by default may serve `index.html` ... BUT this depends on the server side default stting. It also could be `index.htm` ... <- see "l" is missing!

So the client doesn't have enough info to fix the problem. ... The only way I see, is that the server does a redirect to fix the URL ...
