### ISSUE TITLE
Unload tiddlers on close (nodejs flavor)

### ISSUE THREAD

**Issue by llamaqcom** [Jermolene/TiddlyWiki5#3001]
If there an option or is it feasible to unload tiddlers on closing them?

**Comment by pmario** [comment]
why?

**Comment by sancho-one** [comment]
I'd like to run two instances of TW5 on nodejs: on locally and one remote.
They are synced by Git, I even managed to restart automatically TW5 server
on git pull events, but there's still need to refresh browser to get
updates loaded. At the same time, if tiddler is unloaded, openning it will
get a fresh version. I usually tend to have minimal opened documents as I
hate cluttered space. So I close documents after finishing to work with
them. At the same time, an option to unload tiddler will cover 80% of use
cases (just not counting system tiddlers).

On Oct 27, 2017 16:27, "Mario Pietsch" <notifications@github.com> wrote:

why?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jermolene/TiddlyWiki5/issues/3001#issuecomment-340091441>,
or mute the thread

**Comment by inmysocks** [comment]
I think that there are better ways to achieve this. I am working on async adapter using websockets which can push changes to the file system and other connected wikis immediately. I am hoping to also incorporate the git plugin I am working on into it so that it will automatically commit changes to tiddlers, but I have had very little time to work on that part.

**Comment by sancho-one** [comment]
Ah ok, thank you.

⁣Sent from Blue ​

**Comment by laomaiweng** [comment]
@inmysocks, I've been needing just that (Git auto-commit + sync) for a while now, but never got around to dive in and try to implement it.
Do you have code publicly available for these features? Is your development effort still going on? Could I be of any assistance (dev, testing...)?

**Comment by inmysocks** [comment]
The syncing part is done using teh multi-user plugin I am working on. https://github.com/OokTech/TW5-MultiUser

I have some prototype git interfaces in node somewhere but I am not sure where. I haven't been very productive or organised in the past few months. Development is still ongoing but very slow.

**Comment by inmysocks** [comment]
Given the conversation here I think that this can be closed. #3060 covers the same idea with a more directly actionable approach and in the meantime the multiuser plugin can do the op is asking for.

I am not sure if @Jermolene has to do this or not.

**Comment by linonetwo** [comment]
I think this can be closed, since TidGi can handle the git-sync with remote git server, and auto reload webpage after sync.

**Comment by Jermolene** [comment]
Thanks @linonetwo @inmysocks
