### ISSUE TITLE
Placing doublequote into $:/config/NewJournal/Text breaks the New Jurnal button. 

### ISSUE THREAD

**Issue by kub1x** [Jermolene/TiddlyWiki5#3080]
Steps to reproduce: 

1. Open $:/ControlPanel
2. Ad doublequote `"` into the Text for new journal tiddlers (or directly into $:/config/NewJournal/Text)
3. Watch the "New Jurnal" button in the Tools sidebar going all Akira-ish. 

![screen-2018-01-07-17-43-42](https://user-images.githubusercontent.com/1833840/34651729-152fd278-f3d4-11e7-92f8-c952121f0da1.png)

I'm trying to figure out how to fix it myself as I love the idea of TW and would like to contribute more. 

I've found the `$:/core/ui/Buttons/new-journal` tiddler in the core, but the mentioned value is set using `<$set ...` which feels like it's part of the very core of the TW and also something a noob should not touch. Anyway it's probly not escaping doublequotes and guess it should.

**Comment by pmario** [comment]
Hi, 
There's an open PR #3079 with a fix. You could +1 the PR, if you like.

**Comment by kub1x** [comment]
Oh, didn't search the PR's. Thanks for the note. 

PS: Could you please elaborate about the difference between the `<< >>` , `$( )$` and `""" """` syntax? Or guide me to a relevant source. I tried to search the docs, but with no luck.

**Comment by pmario** [comment]
>PS: Could you please elaborate about the difference between the << >> , $( )$ and """ """ syntax? Or guide me to a relevant source. I tried to search the docs, but with no luck.

The following text may be confusing ... because it is! ... We made some "unlucky" design decisions in the past and now we need to "eat our own dogfood" ;)

---------------

We introduced tripple-double-quotes: `"""`, because we needed a way to work with strings, that contain single-double-quotes. ... That's exactly, the problem that caused the issue you and others found. 

The new-journal-button contains some code like this: 

```
<$action-sendmessage .... title=<<now "$(journalTitleTemplate)$">> ...
```

You can see, that the `"$(journalTitleTemplate)$"` variable is only covered by a single-double-qoute. .. Which causes a problem for the parsre if the content of the variable contains `"` ... So that's why we made it possible to use `"""$(journalTitleTemplate)$"""`  to avoid the problem. 

------

`$(name)$` ... is a variable reference within a macro definition.
`<<name>>` ... Syntactically this is a macro call. Technically macros are variables. ... 

So it works in the same way as `"""$(name)$"""`  .... if name contains: `asdf"` The code will break, since the parser sees `"""asdf""""` ... note, there are 4 double-qoutes at the end. `<<name>>` avoids this problem. 

hope that makes sense.

**Comment by kub1x** [comment]
Wow. Totally understandable. 
So would `<<now <<journalTitleTemplate>>>>` work as well, despite being a bit ugly? 
Are variables in macros evaluated recursively (i.e. can i use `<<>>` within a macro, or can I use `$(macro)$` if it is a variable after all)? 
Wouldn't it help if the ending of tripple-double-quotes was defined as `/"""[^"]/` in the syntax? 

I'm really just trying to get on the horse here.. well, and take advantage of your great explanation skills. Really impressed by this SW now.

**Comment by pmario** [comment]
>So would `<<now <<journalTitleTemplate>>>>` work as well, despite being a bit ugly?

Good thought, but ... no, macros can't be nested. It's not simple to parse this. ... 

That's why I had to use `<<now """$(journalTitleTemplate)$ """>>` with a space before the ` """` which was spotted immediately https://github.com/Jermolene/TiddlyWiki5/pull/3079/files#r160035658

**Comment by pmario** [comment]
>Are variables in macros evaluated recursively (i.e. can i use <<>> within a macro, or can I use $(macro)$ if it is a variable after all)?

If you need to use macros within a macrocall you'll need to use the `<$macrocall $name="macro_name" .../>` widget see: https://tiddlywiki.com/#MacroCallWidget

**Comment by pmario** [comment]
>I'm really just trying to get on the horse here.. well, and take advantage of your great explanation skills. 

:)

>Really impressed by this SW now.

TiddlyWiki is a great concept. ... It's the only software, I'm aware of, that lets the "end user" seamlessly dive "Down the Rabbit Hole" and customize the software to their liking. ... Sure, there is some friction, but all in all, it keeps me excited for quite some time already.
