### ISSUE TITLE
Bad export to json

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3081]
tiddlywiki does not export well tiddler to json.

For example, a tiddler like:
```
created: 20171224000026391
modified: 20171228124457867
tags: [[tiddlywiki especÃ­fic]] menu-tiddlywiki
title: accions

! DefiniciÃ³

Les accions que feim, els verb que involucren les activitats

! Llista

{{{ [tag[accions]] }}}

! Color

Les etiquetes que sÃ³n accions apareixen en color `#e9a9f3`
```

is exported as
```
    {
        "text": "! Definició\n\nLes accions que feim, els verb que involucren les activitats\n\n! Llista\n\n{{{ [tag[accions]] }}}\n\n! Color\n\nLes etiquetes que són accions apareixen en color `#e9a9f3`",
        "title": "accions",
        "tags": "[[tiddlywiki específic]] menu-tiddlywiki",
        "modified": "20171228124457867",
        "created": "20171224000026391"
    },
```

But the `tags` is a list. So in JSON must be a **list**, not a string with a space-separated words.

**Comment by pmario** [comment]
>But the tags is a list. So in JSON must be a list, not a string with a space-separated words.

That's not right. Tags are a "space separated list". They are just handled in a special way by the  TW UI

**Comment by somenxavier** [comment]
No. The tags is semantic a list. So in JSON must be a list, not a string.

**Comment by Jermolene** [comment]
Hi @somenxavier just to clarify, it's not really a matter of what is wrong or right, more whether the behaviour could be changed without impacting backwards compatibility.

In this case, TiddlyWiki's present behaviour when serialising list fields is to stringify them via [this function](https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L252-L268). I don't think we could change this without breaking things that depend on the current behaviour.

**Comment by somenxavier** [comment]
@Jermolene so do you don't export to JSON.

**Comment by sukima** [comment]
>No. The tags is semantically a list. So in JSON must be a list, not a string.

Says who? There is no rule this is a requirement. A Date is semantically an object but when systems export/import/store it is typically an ISO string. Semantic usage and data interchange formats do not have to match all the time.

As @Jermolene pointed out the internal system already has provisions to manage the data interchange format of tags from a String to an array. Does hindsight suggest this might be better represented as a JSON array? maybe but at the time it was felt best represented as a String. Now however, it needs to stay otherwise a change in the format will break everyone who has managed to use the old format.

> so do you don't export to JSON.

We do; you've seen it. Again to assert that JSON is not supported just because one of the values is not represented the way you want it to be is a little confusing to me.

Would you be willing to provide some explanation or documentation to help us understand the problem that you are facing?
