### ISSUE TITLE
Extend the library loading to shadow tiddlers

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#3094]
Hello again,

Currently tiddlywiki is only using one library officialy, the crypto one. But instead of directly embedding it on the default template, it is injected via filter, which is a smart decission in my oppinion. This is the filter currently:

```
is[system]type[application/javascript]library[yes]
```

This prevents plugins from injecting libraries (some required shims, for example). I think this filter should be extended to also include shadow tiddlers, and not only systems ones. At the end, is more common that a plugin includes a library that a regular user does. 
 
What do you think @Jermolene ?

**Comment by Jermolene** [comment]
Hi @danielo515 

The `library[yes]` mechanism has several parts:

* System tiddlers with the `library` field set to "yes" are saved in a special section of the HTML file with the id "libraryModules". Note that they are saved in `<script>` tags rather than the usual `<pre>` tags used in the main "storeArea".
* During the boot process, between the bootprefix and the main boot kernel those tiddlers are directly executed. That's how SJCL is loaded
* Later in the boot process, the library tiddlers are loaded from the "libraryModules" area into the store: https://github.com/Jermolene/TiddlyWiki5/blob/master/boot/boot.js#L1461-L1475

So, if we did change the filter you pointed to to include shadow tiddlers, then the result would be that the next time that wiki was loaded then those tiddlers would be reloaded as system tiddlers, overwriting the shadow values.

If that's a problem, then you can use the `$:tags/RawMarkup` mechanism to load external libraries in the browser.

**Comment by danielo515** [comment]
Hello @Jermolene 
That's a good explanation, I didn't know that those tiddlers were added again later.
The problem with the raw-markup is that it is not processed. This means that if I want to use some kind of template to transclude some other content it will not work.
For example, I have a couple of java-script files that I want to include on the header section, but for organization purposes I want to have them on separate files and merge them on TW compilation to save some boilerplate code (the script tags and the IIFE ). 
Any idea how to achieve this ?

**Comment by Jermolene** [comment]
Hi @danielo515 have you tried using `$:/tags/RawMarkupWikified`? It wikifies the content as it is transcluded into the template.

**Comment by danielo515** [comment]
Hello @jermolene
I never heard about that specific tag. Is it a new feature or something? It sounds like the perfect solution to my particular problem

**Comment by Jermolene** [comment]
Hi @danielo515 support for `$:/tags/RawMarkupWikified` was only added in v5.1.15, and it's not fantastically well documented, I'm afraid.

**Comment by danielo515** [comment]
Ok, that makes sense. My source of truth was 5.1.14, that explains my confusion.
I still have to review the chsngelog for 5.1.15 to see if it introduces any incompatibility with Noteself. Any change in the sync mechanism side?

**Comment by Jermolene** [comment]
Hi @danielo515 I think there are only minor changes to the sync mechanism since v5.1.14:

https://github.com/Jermolene/TiddlyWiki5/commits/master/plugins/tiddlywiki/filesystem

https://github.com/Jermolene/TiddlyWiki5/commits/master/core/modules/syncer.js

https://github.com/Jermolene/TiddlyWiki5/commits/master/plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js

**Comment by danielo515** [comment]
Thank you very much @Jermolene , I'll give it a try
