### ISSUE TITLE
Unintentional change in tw5.com (v5.1.15) ?

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#3101]
Hello,

I noticed that the tw5.com (v5.1.15) has the "**Sidebar layout**" option set to "Fluid story, fixed sidebar" mode. This is different from previous versions and it applies only to tw5.com wiki. The state tiddler is an overwritten shadow tiddler now. So, is this an unintentional change or not?

Thanks.

**Comment by Jermolene** [comment]
Hi @morosanuae when the sidebar layout option was introduced we kept the core default setting as "fixed-fluid" for backwards compatibility. But [since April 2016](https://github.com/Jermolene/TiddlyWiki5/commit/db86586219638eaaeb8a14b2f2bba16a43a5bc92#diff-ce71b9701095fa65faf5eb3cb3509376), the tw5.com edition has included an override to "fluid-fixed". So you'll see "fluid-fixed" on https://tiddlywiki.com/index.html but "fixed-fluid" on https://tiddlywiki.com/empty.html

**Comment by morosanuae** [comment]
Hello @Jermolene. So the "fluid-fixed" is the preferred default mode now I guess. The reason behind this change is still not clear to me, but, anyway I think it's the best choice from a visual point of view. It makes sense that the content (story river) should use a larger screen space.

Thanks.
