### ISSUE TITLE
Meta: make dragging links do more #3136

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3148]
This is a summary of #3136

goal: dragging elements into textareas and input fields should result in either the plain titles, the titles surrounded by [[ ]] , the titles surrounded by {{ }} or the titles surrounded by a user-defined prefix and suffix
how: either by dragging without modifier keys or holding shift or control to get a modified result

configuration: the tiddler $:/config/DragDefaults is used to configure what should be done for each key and what the user-prefix and user-suffix is. Therefor the fields "keys", "prefix" and "suffix" are used.

- keys field: a list containing "default" "plain" "transclude" "user"
 the **order** defines which modifier does what
 item1: no modifiers , item2: control , item3: shift , item4: control+shift

problems: 
- draggable lists like the Open Tab need to get handled. 
  Therefor the plain title string now gets pushed to the jsonData Array which gets added to the dataTransfer event-Object.
  The dropzone and droppable widgets check if there's a plain-title-string entry and use that for triggering actions and data-Import
- drag and drop between wikies
  the mentioned method to transport the plain titles with the dataTransfer Object results in an additional "Untitled" tiddler if dragging to a wiki using the "old" d&d.
  I was thinking about naming the array-entry somehow that tw ignores it but I couldn't find a way or adding a mouseout and mouseover handler that changes the Object when the mouse leaves and changes it back when it re-enters
  I wouldn't have a problem with the untitled tiddler, that's also happening sometimes with v5.1.15
- dragging tag-pills using shift doesn't work on chrome/chromium - there may be possible workarounds

Please let me know if I'm creating more problems than necessary

Simon

**Comment by pmario** [comment]
>Please let me know if I'm creating more problems than necessary

I don't think so.

I think, you have come up with a good idea, and then found out, that the "bigger picture" is a bit more complicated, as you expected. eg: inter-wiki d&d with older versions ... 

I don't know, how much of your code you need by yourself and how much is an extension to your idea, because, you think, it may be useful for more users. ...

That's the general problem a developer has. ... You can never be sure, how your functions are used by the community. ... Most of the time in a completely different way, as you intended it ;)

So my proposal would be: 

 - Create a new PR with the latest code you have in #3136
 - Or create a plugin, you publish and introduce in the google group and see, what happens.

**Comment by BurningTreeC** [comment]
> I don't know, how much of your code you need by yourself

I'd need all the code as it is now. I've seen that there were more things to address and I wouldn't be happy if they'd be left unstable

The plugin option is interesting, the option would be to override the shadow tiddlers by using the same titles, right?

I'd still like to make the PR because it feels like this is a missing core feature

I also don't want to add something for full compatibility with older versions because d&d works with them, just with a small quirk and the fix would be ugly

@pmario , thanks for your reply,

Simon

**Comment by BurningTreeC** [comment]
closing this issue now in favor of PR #3151
