### ISSUE TITLE
Permalink Activation And Default Tiddler Settings.

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3193]
As soon as you use permalink once ...

![capture](https://user-images.githubusercontent.com/28830541/37868778-6673a8d0-2fac-11e8-9d85-bb1b8e0d0efd.PNG)

... it becomes dominant. It overrides Default Tiddlers on refresh and on startup. Always its _showing only the last tiddler you permalinked_ not the set defaults.

For ages I thought I was misunderstanding the mechanism on startup. I wasn't. Just because I often invoke permalinks I was initiating the issue without realising. Its an easily reproducible bug.

**Comment by twMat** [comment]
>Always its showing only the last tiddler you permalinked not the set defaults.

But that's the whole point with permalink!? Why would you permalink otherwise?

**Comment by pmario** [comment]
ther's nothing special with "permalink". It's all browser default behavior.

Go to any other page, and it will have the same behavior, with this type of "anchored" link

**Comment by sukima** [comment]
**permalink** changes the URL of the page. It is a link to a URL that initializes TiddlyWiki to show the linked to tiddler. If you typed the URL into the address bar you would not expect TiddlyWiki to ignore your request but to show the Tiddler you typed in the URL bar. Clicking the permalink button is no different.

Basically Single Page Applications (SPA) use the Hash (or Fragment) portion of a URL to drive application state. In the case of TW it drives what tiddlers to show. The default (no fragment specified) is to show the tiddlers defined in the *Default Tiddlers* setting. Otherwise the URL fragment take precedents. This is the standard on the web for both static web pages and SPAs. A detailed example is explained in [this blog post](http://blog.mgm-tp.com/2011/10/must-know-url-hashtechniques-for-ajax-applications/).

You could press the back button of the browser to go back in history till your back to the default (no fragment) URL. Or alternatively press the **Home** button (Located by default under the **tools** tab and when checked in the main icons menu) which also clears the fragment from the URL.

**Comment by sukima** [comment]
The more I think about this. The term *permalink* is [a known term](https://en.wikipedia.org/wiki/Permalink) that specifically states that the user wishes to permanently link to the resource. Therefor it is reasonable to expect that when you permanently link to a tiddler that that tiddler becomes permanent.

This is realized in the behavior described in the original post and therefor would not be considered a bug.

**Comment by TiddlyTweeter** [comment]
@sukima @twMat @pmario 

I haven't explained the issue well enough. I agree with all your comments on the behaviour of "SPA" in most circumstances.

I'm pointing to a behaviour under specific circumstances that is counter what you would expect and is causing me hassle.

Here is a test case using tiddlywiki.com on net ... 

1 - Control Panel > Settings >  Navigation Address Bar > is: Do not update the address bar 

2 - Navigate to a Tiddler of interest and > More Actions > #permalink  (I do this ONLY to be able to then copy the link to Twitter or GG)

Perhaps the issue is the "nature of refresh" when using TW. 

I'm expecting that IF TW has Default Tiddlers at Control Panel > Default Tiddlers populated THOSE tiddlers are what I expect to see  displayed when I reload it. That is likely quite different than a normal web page.

I think navigation via "#" is one thing and reload behaviour another. This behaviour blurs them.

To take another case. 

1 - I open a Tiddler (same settings as above) click > More Actions > #permalink

2 - CLOSE that Tiddler. Click another Tiddler. Refresh. I get the Tiddler at 1. Even though its been closed and another Tiddler was foregrounded. That is not what I'd expect in normal webpages.

So whilst we have the SPA approach as the standard, some of TW behaviour isn't always in alignment.

But maybe I'm stupid?

**Comment by pmario** [comment]
>I think navigation via "#" is one thing and reload behaviour another. This behaviour blurs them.

no ... browser behavior

**Comment by TiddlyTweeter** [comment]
One clarification on @sukima's excellent point that _permalink_ is a known term. I agree. But I understand it as an address you can use to reliably invoke a web page (including a section of a web page) in a browser. Its an address.

BUT, the question I'm raising is whether on _reload_ of a TW it should be used as a directive. IMO, the Default Tiddler settings should be used on _reload_, not a happen-stance use of a permalink.

I hope I've now expressed this issue clearly enough for consideration? Even if you disagree.

**Comment by TiddlyTweeter** [comment]
@pmario wrote: "may be we want: "Copy Permalink to ClipBoard" instead of modifying the URL bar. same with PermaView. .."

As far as being able to copy permalinks without putting them into the address bar goes switching on Control Panel > Settings > Tiddler Titles > on: "Display tiddler titles as links" allows easy copy on hover. So I don't think anything more is needed on that. I would not want to see excess bloat when we have a mechanism already. If it could be lightweight from the "More" menu then it would suit me well.

My issue is browsing around frequently wanting access to permalinks in the easiest way, without having to go in and alter configuration to settings that otherwise I'd never use.

**Comment by sukima** [comment]
> the question I'm raising is whether on reload of a TW it should be used as a directive. IMO, the Default Tiddler settings should be used on reload, not a happen-stance use of a permalink

This is a browser action. TW has absolutely no control on how a browser chooses to implement a reload. A browser will refresh the page including the fragment. I am not understand how this would act any different. The scenarios you outlined is how the web was designed. I'm not understanding how that would be any different.

@pmario had a good suggestion to copy the URL without changing the URL. Is that what you want?

In regards to your second scenario of the URL not updating when you open a new tiddler there is a setting to always update the URL with what is on the screen. This way when you open a new tiddler and refresh the new tiddler is open because it is referenced in the URL.

In any case I am not understanding how this is a bug. The functionality and the excepted definitions of a permalink are (as far as I can tell) being respected in spirit. I also do not see how the behavior could be changed especially since TW has absolutely no control over how the browser reloads a page especially since the scenario of reload is *exactly* the same as if you copy pasted the permalink into a new tab. TW has no idea the difference between a new tab with a permalink URL or the current tab being refreshed. Short of creating a custom web browser I don't see this getting addressed.

For a solution I believe you need to change your own workflow. After you click the permalink in TW. press the back button of the browser to return to the default tiddlers. Alternatively press the **Home** button. The **Home** button was added to implement the exact functionality you desire which is to move from a permalink URL to the default tiddlers. The two go hand in hand. Permalink button for the permanent view and Home button for the default tiddlers view.

**Comment by TiddlyTweeter** [comment]
@sukima thankyou for you detailed, very relevant, reply.

The issue is not about my own wikis. It is rather when I browsing other TW on the net to review I find it cumbersome to have to alter their configuration to get a permalink so I can reference them. 

The issue arises because I invoke a solo single permalinked Tiddler in the simplest way but then want to look at other Tiddlers that the default opening offered. Now lost.

Discussion here has clarified for me a way I could do this more easily. If I'm reviewing a TW online I maybe get a JS shortcut via the browser working to go in and auto-change config values so access to permalinks is even easier.

I agree, now, this is NOT a bug. More an example of my naivety of not grasping how the net works. 

I changed the title of the thread to something less ominous.

And I thank you for your simple tips on using the back button. I tried it. Works well. Better than "Home" as many online TW's don't have "home".

**Comment by pmario** [comment]
>And I thank you for your simple tips on using the back button. I tried it. Works well. Better than "Home" as many online TW's don't have "home".

It's at Tools: Home button. ... most TWs have it.

**Comment by TiddlyTweeter** [comment]
> Hmmm, ... I do see a security problem here. ... If the URL fragment #do-something would change TWs configurations (the tw store), IMO it would get problematic.

Well, its just for review usage and its not gonna damage anything I can see. 

FWIW. I found a solution using AutoHotkey that simply feeds keystrokes to change a setting in TW that does what I need.

I'll close the topic.
