### ISSUE TITLE
Unable to insert images in markdown plugin with relative path in nodejs server

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#3238]
This `![cara](/home/xan/zync/proves/wikipersonal/tiddlers/face.jpg)` works but this `![cara](/tiddlers/face.jpg)` does not. Why?

Where is the relative path of `face.jpg` if it is stored in `[mywikipath]/tiddlers/face.jpg`

**Comment by inmysocks** [comment]
You may need to put a . in front of the relative path.

I am not sure it will resolve the problem but try `[cara](./tiddlers/face.jpg)`

**Comment by somenxavier** [comment]
@inmysocks No. Try it

**Comment by inmysocks** [comment]
Oh, sorry I may see what is going on. I am too used to using my things I forgot static file servers aren't part of the normal node setup.

If you have a image file in the tiddlers folder it is added to the wiki  as a tiddler and the title is set to the full path of the image. So when you use `![cara](/home/xan/zync/proves/wikipersonal/tiddlers/face.jpg)` it is displaying the image tiddler called `/home/xan/zync/proves/wikipersonal/tiddlers/face.jpg`, not the file with the file path `/home/xan/zync/proves/wikipersonal/tiddlers/face.jpg`, even though in this situation the two show the same thing.

Without a static file server node doesn't have access to the file system but files inside the tiddlers folder are made into tiddlers if they are a format that can be used in a wiki, even if there aren't .meta files to go with them.

If you are not in a situation where you can use a static file server one option that may help is adding .meta files. The structure of a .meta file is the same as a .tid file but it has no text field. The file name is the name of the image (or other media) file with `.meta` added to the end.

In your example you would create a file called face.jpg.meta and in the file put:

```
title: face.jpg
type: image/jpeg
```

Then in the wiki the tiddler would be called face.jpg instead of `/home/xan/zync/proves/wikipersonal/tiddlers/face.jpg`. You can give it another title if you don't want the tiddler to be called `face.jpg`
