### ISSUE TITLE
SelectWidget default doesn't consistently show

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3256]
On tw.com I reuse the examples given in the [docs for selectwidget](https://tiddlywiki.com/#SelectWidget) but with minor modifications - especially the inclusion of a `default` also in the second snip:

```
<$select tiddler='$:/SiteTitle' default='HelloThere'>
<$list filter='[all[shadows+tiddlers]tags[]sort[title]]'>
<option value=<<currentTiddler>>><$view field='title'/></option>
</$list>
</$select>

<$select tiddler='$:/SiteTitle' default='cities'>
<option value='cities'>A Tale of Two Cities</option>
<option value='science'>A New Kind of Science</option>
<option value='dice'>The Dice Man</option>
</$select>
```
Result

![image](https://user-images.githubusercontent.com/4534056/39621952-cf199332-4f90-11e8-8a2e-7f92599bd33a.png)

I am expecting both of them to show the default alternative, like only the topmost does. (bug?)

This is not a recent problem, I've noted it for several versions but thinking maybe I misunderstood sth.

Win10 Chrome and FF

**Comment by Jermolene** [comment]
Hi @twMat the reason is that the value in the "default" attribute is only used if the target tiddler field/index is missing. In these examples the tiddler `$:/SiteTitle` does exist and so the default value is not used.  Try changing the tiddler to `$:/SiteTitle2` and you'll see that things work as expected.

**Comment by twMat** [comment]
no way!!! Thank you! Sorry for mis-reporting.
