### ISSUE TITLE
Feature Request: Automatic "References"/Link Renaming

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3336]
When you rename a tiddler, an option is shown to also rename this tiddler in the tags and list fields of other tiddlers. I think this should also include links to this tiddler (shown in the references tab in the info pane)

**Comment by AnthonyMuscio** [comment]
Diego,

This could be a nice feature, of course this means searching all tiddlers text fields and perhaps all fields (eg List field), I am sure It is not impossible and possibly highly desirable, but the following needs to be considered

- Would you really want this in cases where the tiddler title forms part of the text in which it is quoted eg [[apply setup instructions]] if you did change the title of the tiddler [[apply setup instructions]] independently of where it is referenced, will it still be valid everywhere it was used?

-  In such a solution I think it is important to list the effected tiddlers.

A Solution? Mario's Uni-links plugin may even be a contender for insertion in the core and this creates aliases for tiddlers, which allows the tiddler names to change with the Alias staying the same. Perhaps rather than searching every tiddler and replacing the references with the new name, we could search every tiddler and replace the references with an alias (to the original title), and update the current tiddler to contain its alias. Thus the text will not necessarily change but the links to the tiddlers will be honoured.

Regards
Tony

**Comment by Jermolene** [comment]
Link renaming can be seen as just a special case of search and replace. In #3288 I've proposed a way of implementing search and replace where the user gets to review the highlighted changes, and individually accept or reject them.

Another, more ambitious, way of approaching linking renaming is to make search and replace work on the parse tree of tiddlers, rather than the raw text. Then one could explicitly restrict replacement to text that has been positively identified as a link.

**Comment by diego898** [comment]
I think Mohammad's javascript-based SNR can be a solution to this:

https://groups.google.com/d/msg/TiddlyWiki/BwgwkxaXY_o/QtibP6v7BwAJ

**Comment by diego898** [comment]
Closing in favor of #3288
