### ISSUE TITLE
Request: Enable some method of comment within or between \pragma

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#3340]
I'm sure this has come up before. But once you start using a lot of "\define" it gets quite difficult to remember what they are for. Lacking ability to comment directly in or immediately above pragma makes them hard to maintain once they get complex. I use them precisely because I want to avoid hard-coding the code below them. To maintain them well I need a note of what they are for. 

See [Query: Is there anyway to put comments with \define pragma?](https://groups.google.com/forum/#!topic/tiddlywiki/DBWzVqb2Xdo) for an example.

**Comment by twMat** [comment]
Possibly related to #2979

**Comment by TiddlyTweeter** [comment]
> Possibly related to #2979 

Definitely related. 

Eric Shulman's comments on the GG (https://groups.google.com/d/msg/tiddlywiki/DBWzVqb2Xdo/aaAYk3RyCgAJ) are particularly helpful at explaining that using `<!-- comment -->` mid \define won't always work. Its also, I think, cumbersome and makes everything too long for the sake of a comment. 

As it is right now, a "pseudo \define" line , like `\define ------() The comment`, works and is fairly economical and can sit okay with the layout. 

@pmario  suggested in #2979 that a `\comment   ` pragma could be a way. I'd prefer something briefer like `\\ The comment ...` or `\# The comment ...`

**Comment by AnthonyMuscio** [comment]
Improving the way we can comment on List and and set widgets would also be helpful, and may be achieved the same way as in this issue. I believe strongly in self documentation and it can be difficult in tiddlywiki without breaking things, so lets design it in.

Some quick examples illustrate, see the free form text at the bottom of each example, which will simply be ignored. Only vars also labels at the beginning (because there is no single value by which to name it).

```
<$list filter="[tag[task]]">
task list
</$list task list>

```
AND/OR
```
<$list filter="[tag[task]]">
task list items
</$list>/*task list*/
```

```
<$set name=variablename value="....">
code...
</$set variablename>

```

```
<$vars label="lablename"
variables defined...
>
code...
</$vars labelname>
```

Regards
Tony

**Comment by pmario** [comment]
may be `\whitespace trim` can do this, if we treat `<!-- -->` as whitespace
see: https://tiddlywiki.com/#Pragma

**Comment by AnthonyMuscio** [comment]
In relation to this and looking for a workaround Both in macro definitions and Wiki Text I realise that debugging is also a place we may want to insert something. So I thought why not combine the two into a macro?

\define debugging(comments,code)
test if in debug mode set on this tiddler eg show-debug field exists
-- Display comment
-- Transclude code eg 
\end

eg in a define
\define amacro(Fred Wilma)
<<debugging "Determine if it was fred or wilma" "<<avarialble>> <<currentTiddler>>">>
 
eg in Wiki Text

<$list filter="
<<debugging "Determin if it was fred or wilma" "<<avariable>> <<currentTiddler>>">>
blah
</$list>

You could then toggle if the debugging comments or code are active in a given current tiddler
Otherwise they will act as a static comment while editing.

Regards
Tony

**Comment by pmario** [comment]
debugging complex macros is difficult. ... you are right :)

**Comment by Jermolene** [comment]
Thank you @pmario
