### ISSUE TITLE
Allow access to multiple field values

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3347]
**Problem**: It is not possible to directly access to the *values* of the filtered out fields here:

```
[... fields[]]
```

**Note**
I had a few ideas for how this could be solved but they turned out to not be fully thought through so I'm hoping to first hear your ideas. Thank you.

**Comment by pmario** [comment]
What do you try to achieve?

**Comment by twMat** [comment]
@pmario , maybe this makes is a bit clearer why it is a problem:

```
[tag[foo]fields[]prefix[bar] ... and now get the value(-s)
```

I fully understand that this can be achieved with nested lists but that is cumbersome.

**Proposal**:

Extend the `get` operator with a `fields` suffix to extract all field values like so
```
[... fields[]get:fields[mytiddler]]">
```
Thus, the *input* is a **list of field names**
the *parameter* is the tiddler wich to apply it to
and the *output* would be their corresponding field values for the specified tiddler (presumably the tiddler from which the fields were extracted).

One may argue that the suffix should rather be named `getfields` or `sourcetiddler` or `source` some such.

**Comment by AnthonyMuscio** [comment]
Perhaps something that should influence this;

My favourite suggestion would be a subfilter on the List Widget, and/or the operator fields:values[]

I am contributing here because, I support the Allow access to multiple field values #3347 request because I see some great opportunities to use it. Including wikifying the field contents such as in http://tiddlywiki.psat.com.au/mymenus/ where the plugin lists in a transcluded form of the fields 
menu-item-1 menu-item-2 menu-item-3 etc... 

**My reasoning**

**Remember**
has:field[fieldname] differs from has[fieldname] in also returning fields with no value there in.
has:field[fieldname] implies you want the field returned, not just its values, so blanks are included

**so perhaps**
get:field[fieldname]] should differ from get[fieldname]] in also returning fields with no value there in or a blank liner if empty.
Implying get the content of the field even if it is empty.

**Why I think get:fields[] is not suitable**
This is getting awfully close to your suggestion get:fields[mytiddler]]
Where the contents is actually a tiddler name not a fieldname as in the normal get[]
So I would not recommend your suggestions

Another reason is there are cases where you may be happy to have the contents of fields without the field name such as in a set of fields sharing a prefix, however more often than not I expect people also require the fieldnames and fieldvalues such as comes from the nesting you wish to avoid;

<$list filter="[is[current]fields[]]" variable="fieldname">
<<fieldname>>:  
<$list filter="[is[current]get<fieldname>]" variable="fieldvalue">
<<fieldname>>: <<fieldvalue>><br>
</$list>
</$list>

**A new widget?**
I can't see how we could return both the title and the value in a single operator, perhaps a new widget would be good. <$listfields filter="tiddlertitles" fieldfilter="[prefix[fieldprefix]get[]]" variable=tiddlertitle value="valuevariable">
<<tiddlertitle>>: <<valuevariable>
</$listfields>

**Improve ListWidget?**
Or perhaps do the above with a subfilter in the <$list widget? 
In which case the subfilter is applied to the result of the filter, This would open up more opportunities.

**The fields[] operator**
The fields[] operator is empty perhaps that is an opportunity?
or perhaps fields:get[]
or even
fields:values[] implies you want the fields values returned, not just there names, but how do you decide if blanks field contents are included? perhaps values implies only those with values

**Comment by AnthonyMuscio** [comment]
Code example reposted as it was mangled.
```

<$list filter="[is[current]fields[]]" variable="fieldname">
<<fieldname>>:  
<$list filter="[is[current]get<fieldname>]" variable="fieldvalue">
<<fieldname>>: <<fieldvalue>><br>
</$list>
</$list>
```

**Comment by twMat** [comment]
>What do you try to achieve?

Indeed.
Closing.
