### ISSUE TITLE
Feature Request: Add option for Tags to show their caption/subtitle instead of title

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3370]
In [this google groups thread](https://groups.google.com/d/msg/tiddlywiki/pVqcVuNaTbA/BgIVHwJAAwAJ) @pmario said:

> I did think about using / showing the caption of a tag, instead of the the tag. ... This would be a field to explore. ... and should be doable with UI changes only. ... using the same mechanism that uni-link uses for standad links already. 

I'd like to open a feature request to make this UI tweat an official part of TW.

**Comment by AnthonyMuscio** [comment]
Sounds like a good idea, one place it would be helpful, but may also introduce a little more complexity is when the title is a system title, and the caption is not.

eg; $:/tags/ViewTemplate with a caption of ViewTemplate so the tag pill shows ViewTemplate

Can I now list based on the caption?

<$list filter="[tags[ViewTemplate]]">

Because otherwise how would I know the real name if I only see the caption and will I need to is[system] ?

Regards
Tony

**Comment by pmario** [comment]
Hi, .. I think this is plugin territory at the moment. The biggest problem I see at the moment is, that users need to see, that the tag is a caption or subtitle and not a real tag title. ... 

I think this behaviour has a very high potential to completely confuse new users. ... 

So it's OK to have an issue, so it will be remembered, but the first iteration should be with plugin.
