### ISSUE TITLE
[request] macrocall/variablecall with built in wikify

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3376]
A biggie. Make it possible to command "wikify" directly in macrocalls and variablecalls.

**Example problem** 

A syntactically faulty example e.g from a custom viewtemplate

```
<$list filter="[is[current]tag[foo]]">
<$reveal type="nomatch" state="$:/state/{{!!title}}" text="show">
...
</$reveal>
</$list>
```

This results in a state tiddler literally named `$:/state/{{!!title}}`. Adding a `variable=current` doesn't help. (And in the case of state (i.e system) tiddlers, the user might not even notice the error!)

**General problem**
...so, the solution (really a compromise!)  is to split out whatever parts are to be evaluated into local *macros*. In the above case this would mean the listwidget contains nothing but the macrocall.  But this

* makes for loads of contrieved nesting
* cluttered code
* it is by no means intuitive that one should have to do this!

Side note: IMO it also "diminishes" the elegance of the macro concept because you get a lot of local macros that are of absolutely no other use.

**Proposal**

It would be extremely useful with built in wikify mechanism in the macrocall/variablecall. We already have the wikify widget so the required code probably mostly exists already.

Here are some ides for syntax:

```
<< ... ||wikify>>

<wikify< ... >>

<<wikify: ...>>

<$macrocall 
    ....
    wikify=yes
>

<$macrocall 
    ....
    output=wikify
>

<$macrocall 
    ....
    type=text/plain   <---- ref. output types
>

```

BTW - rather than the cryptic term `wikified` I'd prefer a term like `evaluated` or just `text` (the latter also being an attribute in the WikifyWidget) so the syntax suggestions above would be e.g `<<...||text>>` etc.

**Comment by Jermolene** [comment]
Hi @twMat 

In terms of the particular example you chose, wikification is an expensive operation compared to text subsitution, and so it's a sledgehammer to crack a nut. Another alternative that should be much more efficient than either is:

```
<$list filter="[is[current]tag[foo]]">
<$reveal type="nomatch" state={{{ [{!!title}}addprefix[$:/state/]] }}} text="show">
...
</$reveal>
</$list>
```

Notwithstanding the merits of that example, there are still cases where wikification of widget attributes would be useful. However, again we hit the issue that wikification is an inherently heavyweight process (we have to parse the text, render it and extract the text). We'd have to significantly re-engineer the handling of widget attributes to do things efficiently.

So, although I recognise that a syntax for wikifying widget attributes might have some uses, I don't believe that it's worth the upheaval -- particularly because the wikify widget can always be used instead.

**Comment by twMat** [comment]
@Jermolene - I had no idea about the order of cost (wikification - textsubstition - tripplecurlybraces) so thanks for valuable info!

OK, so evaluation via "triple curly braces" (what's the term for that anyway?) is the most efficient. Then can't triple curlies be extended to allow this:

`<$reveal type="nomatch" state="$:/state/`{{{`!!title`}}}`" text="show">`

...i.e it evaluates its contents like a filter does but the output is in text for rather than linkified. I mean... it can't be the output format that is expensive... if anything it should be the evaluation... which you say is not expensive if using whatever mechanism is behind triple curlies.

- OR -

What is the argument against this point: Yes, wikification is expensive... but that is ok when it is called far (literally, no pun intended)... i.e the hypothetical `<<... ||wikify>>` would in deed be expensive, but it would be explicitly requested exactly like the wikifywidget.

**Comment by AnthonyMuscio** [comment]
Jeremy,

I understand that wikification is an expensive operation compared to text subsitution (I presume this is processing cost) however there are many cases where a feature is likely to be used once to reach a goal and only occurs on demand in a single tiddler, can it still be said to be expensive when it saves code complexity and eases cognitive load?

I can see how such wikification would be easy to add to a view template or be referenced in a list thus making it suddenly always in use and that does become much more expensive. 

I suppose to support simplification in code could we do something in this and other examples to either limit the scope or actually report the cost of such easier to code solutions. I often see performance (perhaps even correctly) trumping code simplicity but I am also keen to see more code simplicity. Can we find a way to stop this dichotomy occurring?.

A Similar example that comes to mind is the likely deprecation of action widgets in buttons and them forcibly being moved to \defined actions referenced in the actions parameter. I am sure there is a technical reason but ripping code out and placing it in macro definitions is often going to make understanding a solution much more complex, there is yet another place to visit to understand the code.

Regards
Tony

**Comment by Jermolene** [comment]
> I understand that wikification is an expensive operation compared to text subsitution (I presume this is processing cost) however there are many cases where a feature is likely to be used once to reach a goal and only occurs on demand in a single tiddler, can it still be said to be expensive when it saves code complexity and eases cognitive load?

Wikification of attribute values is already possible, the issue is just that it takes two steps, with an intermediate variable. This discussion is about enhancing the widget syntax so that an attribute can be directly wikified.

> I can see how such wikification would be easy to add to a view template or be referenced in a list thus making it suddenly always in use and that does become much more expensive. 

Yes, that goes for any complex wikitext, of course.

> I suppose to support simplification in code could we do something in this and other examples to either limit the scope or actually report the cost of such easier to code solutions. I often see performance (perhaps even correctly) trumping code simplicity but I am also keen to see more code simplicity. Can we find a way to stop this dichotomy occurring?.

I'm not sure that I have a general answer, but I think we all share the same goal of making TW as simple as possible, tempered only by the "laws of physics" of our chosen architecture.

> A Similar example that comes to mind is the likely deprecation of action widgets in buttons and them forcibly being moved to \defined actions referenced in the actions parameter. I am sure there is a technical reason but ripping code out and placing it in macro definitions is often going to make understanding a solution much more complex, there is yet another place to visit to understand the code.

"Deprecation" means that users are advised not to use a feature, not that it stops becoming available. The reason for avoiding text substitution macros is that they are incredibly brittle: the core used to use them extensively, and it's been the source of innumerable bugs around tricky edge cases with tiddler titles ending with double quotes, and the like. But our commitment to backwards compatibility means that old wikitext will continue to work just as it has always done.

**Comment by pmario** [comment]
>A Similar example that comes to mind is the likely deprecation of action widgets in buttons and them forcibly being moved to \defined actions referenced in the actions parameter

The truth is: Using action widgets inside buttons seems to be simple at first. ... All the parameters are calculated, when the button is rendered. ... But sometimes users need the parameters calculated, when the button is clicked. ... That's why "best practice" is to define them outside.

**Comment by Jermolene** [comment]
Can we close this?

**Comment by Jermolene** [comment]
@twMat I think that's a restatement of the original request :)

**Comment by twMat** [comment]
Doh! Sorry.
