### ISSUE TITLE
disabled attribute for button widget

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3390]
https://www.w3schools.com/tags/att_button_disabled.asp

The button widget cannot accept the html5 disabled attribute!
There are occupations you want to show button but conditionally disabled it!

Please revise button widget!

Mohammad

**Comment by AnthonyMuscio** [comment]
Kookma,

Perhaps what you ask for is valid but I would already do this as follows and adjust the class etc... to your liking. You can even interrogate or set $:/temp/disablefullscreen

```
;The Button
<$reveal type="nomatch" state="$:/temp/disablefullscreen" text="yes">
<$button message="tm-full-screen">
{{$:/core/images/full-screen-button}}
</$button>
</$reveal>
<$reveal type="match" state="$:/temp/disablefullscreen" text="yes">
<$button class="tc-btn-invisible">
{{$:/core/images/full-screen-button}}
</$button>
</$reveal>

;The toggle or set $:/temp/disablefullscreen to yes to disable
<$reveal type="nomatch" state="$:/temp/disablefullscreen" text="yes">
<$button set="$:/temp/disablefullscreen" setTo="yes">
Disable {{$:/core/images/full-screen-button}}
</$button>
</$reveal>
<$reveal type="match" state="$:/temp/disablefullscreen" text="yes">
<$button set="$:/temp/disablefullscreen" setTo="no">
Enable {{$:/core/images/full-screen-button}}
</$button>
</$reveal>
```

**Comment by kookma** [comment]
Hello Tony!
 The disabled attribute is supported by HTML5 and is quite easy to be added to button widget! It is also possible to lets user add their own calsses for disabled attribute!

I recommend for a clean and easy to understand code, Jeremy add this attribute

Thank you

**Comment by Jermolene** [comment]
Hi @kookma I agree that the disabled attribute might be useful for the button widget.

The weird thing about the "disabled" attribute is that its presence alone determines whether the element is disabled; the value of the attribute doesn't matter. In particular setting `element.setAttribute("disabled",false)` will disable the element, rather than enabling it as might be expected.

For our implementation, it'll work differently: the attribute will be applied to the button element if the widget attribute value equals "yes".

**Comment by kookma** [comment]
@Jermolene 
Thanks for clarification!
