### ISSUE TITLE
Navigation Offset to make room for top bar

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3396]
I think this has been discussed but I fail to find it as an issue. If anyone can point me to it (and it's open), I'll close this one and post the code link here below there instead.

**Background**: In order to freely be able to use the top bar, e.g for a menu, it would be necessary to control at what distance from viewport top a tiddler should halt scrolling when being navigated to. Currently we rely on the tiddlers top gutter which makes for very thin top bars. ...but "top menus" are a *huge* deal in both website and app design.

**Request**: I hope for a user setting in the controlpanel to set this distance.

**Solution, maybe**: I found [this js code](https://stackoverflow.com/questions/17534661/make-anchor-link-go-some-pixels-above-where-its-linked-to).

```
// The function actually applying the offset
function offsetAnchor() {
  if (location.hash.length !== 0) {
    window.scrollTo(window.scrollX, window.scrollY - 100);
  }
}

// Captures click events of all <a> elements with href starting with #
$(document).on('click', 'a[href^="#"]', function(event) {
  // Click events are captured before hashchanges. Timeout
  // causes offsetAnchor to be called after the page jump.
  window.setTimeout(function() {
    offsetAnchor();
  }, 0);
});

// Set the offset when entering page with hash present in the url
window.setTimeout(offsetAnchor, 0);
```

**Comment by pmario** [comment]
Just my opinion. 

 - Everything that uses vertical space on mobile devices should be avoided at all cost!

 - On PC screens there is enough horizontal space for vertical menus. (as it is)

**Comment by twMat** [comment]
You're of course entitled to your opinions but please note that...

>Everything that uses vertical space on mobile devices should be avoided at all cost!

There are ways to get around this which are common practice these days, that basically hide the topmenu on smaller screens unless you scroll them into view. Besides, if one doesn't want the topmenu on small screens, then it is just a matter to ensure that it doesn't show there **when one is actually** on the smaller screen.

>On PC screens there is enough horizontal space for vertical menus. (as it is)

I'm currently working with a TW that not only needs the sidebar, but also a left sidebar as well as the top menu. They are all "different sorts" of info. IMO it is a matter of how quickly one needs to access particular info.

**Comment by AnthonyMuscio** [comment]
twMat,

Have you looked at the material theme? it may already be on the way to what you ask, and designed for mobile as well resolving the issues Mario raises. Perhaps you can tweek it further

http://j.d.material.tiddlyspot.com/

Regards
Tony

**Comment by AnthonyMuscio** [comment]
PS Be careful, I do not know how to reverse it so put it on a copy of your wiki.

**Comment by twMat** [comment]
Thanks for pointer @AnthonyMuscio - but this really ought to be a standard control in native TW. (For personal needs, I primarily turn to the boards not gh)

**Comment by Jermolene** [comment]
Hi @twMat 

> Background: In order to freely be able to use the top bar, e.g for a menu, it would be necessary to control at what distance from viewport top a tiddler should halt scrolling when being navigated to. Currently we rely on the tiddlers top gutter which makes for very thin top bars. ...but "top menus" are a huge deal in both website and app design.

I agree that this is an issue. I use position:fixed top bars on several projects, and they all suffer from the problem of the top bar obscuring the top of tiddlers when one scrolls (for example, https://manuals.annafreud.org/ambit -- particularly noticeable on mobile).

I've explored several ways of resolving it, and I think the cleanest is to have the "scroller" component apply the offset as you suggest. Rather than storing the offset as an absolutely value, I propose instead to use a standard class `.tc-adjust-top-of-scroll`, and have the scroller measure the height of the first element with that class, and use that as the offset.

The end result is that you'd just need to apply this class to your toolbar wrapper in order to have the scroll offset adjust itself automatically as the toolbar height changes (eg because of resizing the window, or switching from landscape to portrait on a phone).

**Comment by twMat** [comment]
@Jermolene 

I note you've already merged this and I'm looking forward to testing it. Big thanks!
