### ISSUE TITLE
Make closed drafts more visible

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3409]
In TiddlyWiki instances that I've had the opportunity to examine I often find forgotten drafts: situations where a user has started to edit a tiddler, but then inadvertently closed it before completing the edit. This can happen, for example, if one clicks the "home" button, or uses the "x" in the "Open" tab of the sidebar to close a draft tiddler.

These drafts can be found in the sidebar under More/Drafts, but most users don't know that that is there, nor what to do about it.

I propose therefore to steal another feature from Gmail, and add "tabs" at the bottom of the screen to highlight any draft tiddlers that are not currently open in the story river. (The tabs would only appear if read-only mode isn't engaged with `$:/status/IsReadOnly`). For example:

![draft tabs](https://user-images.githubusercontent.com/174761/44540014-9023c480-a6fd-11e8-8147-98f933056c2e.gif)

The indicators are intentionally fairly prominent, on the basis that most users will seldom see them.

My inclination would be for this to be a default core feature because it addresses a universal usability issue. But I wouldn't be inclined to add a configuration setting for it because of the bloat entailed.

**Comment by Jermolene** [comment]
I've just committed an implementation for discussion; feedback welcome.

**Comment by twMat** [comment]
IMO,  this is a fair opportunity to introduce a notifications feature where this is alerted. Perhaps a familiar little bell at top right that, when clicked, opens a tiddler or popup to show a list with the draft titles. This area can be used for other alerts also e.g when we do federate, people will want to alert one another and we could begin to have alerts when plugins have been updated etc.

**Comment by twMat** [comment]
>Do you mean a notification that appears briefly to announce unsaved drafts, and then disappears? 

No, not transient. Anything worth alerting triggers the notification(-symbol). In this case, it would be triggered by whatever would trigger the "red bottom tabs" you originally proposed. 
(Did this answer your question or am I missing some nuance?)

**Comment by Jermolene** [comment]
Hi @twMat I am indeed confused! At the moment I've implemented persistent indicators that appear for draft tiddlers tiddlers that are closed. What are you asking should be different? The visual display of the indicators?

What problem are you trying to solve that the current design doesn't address?

**Comment by twMat** [comment]
Sorry if I was unclear. My proposal was in reply to "feedback welcome".

So, my proposal is to use a notification "system" coparable to what github and many other services feature *instead of* the "bottom tabs". The main advantage is that this is a much more *general* UI than "bottom tabs", so all kinds of notifications can be presented within the same "wrap". I also believe we will soon need this kind of system so it would not be elegant with multiple UIs for alerts.

Some specific examples of what else we will need notifications for: When we federate (and we might just be on the verge, thanx to @inmysocks ) there will be need for alerts about all kinds of things; this should be obvious if there are *push* solutions, but also if you *fetch* a batch of tiddlers you can get alerts about tids that fulfill some condition (e.g tagged with your name) or maybe there's a payload tiddler included in all fetchings that contains metadata about plugin statuses so you can get a notification that you have outdated plugins.
