### ISSUE TITLE
Loading Tiddler Message

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3424]
As per the proposed Loading Message https://github.com/Jermolene/TiddlyWiki5/issues/3417

Would it be possible to add to the View Template rendition process a similar CSS based loading tiddler message?

I think it could be toggled off until someone hosts it on line or creates a tiddler with a longer rendition process. Or we could even make it only occur on selected tiddlers by virtue of a hidden field setting.

I came to this idea when playing with the new Range operator on the 5.1.18 pre-release with the following code to display all the symbols available.

```
\define display-symbol(number)
&#$number$;
\end
<table>
<tr>
<th>Number</th>
<th>Symbol</th>
<th>Code</th>
</tr>
<$list filter="[range[33, 9999]]" variable=number>
  <tr><td><<number>>:</td><td><$macrocall $name=display-symbol number=<<number>>/></td><td> &#<<number>>;</td></tr>
</$list>
</table>
```

As you can see this use of the range operator and the others that will likely follow,  will as the tiddler renders look at you dumbly - and people may think the wiki is dead, but they are asking a lot to be done.

What I imagine is a CSS or Animated Gif that appears as soon as you save the tiddler that remains until it is replaced with the rendering of the output.

I expect with careful design it will add little or know overhead however it will help reduce a perceived performance issue  when tiddlywiki is actually working hard.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio sadly this is one of those entirely reasonable sounding requests that is in practice very challenging.

The root of the problem is that browsers only update the display during the intervals when JavaScript isn't running. Tiddlers that take a long time to render block the display because TiddlyWiki's JS code is running. The conventional solution to this is to use `setTimeout` to schedule a task in the future, giving the browser a chance to update the display first. The problem is that we can't take synchronous code like the TW parser/renderer and just make it asynchronous: they are not interchangeable. TW's parser/renderer is synchronous to get the best possible performance.

So, if our tiddler rendering JS were to put an animated GIF into the DOM before rendering the body of the tiddler then the browser wouldn't give us a chance to see it.

**Comment by AnthonyMuscio** [comment]
Closed as a result of the comment from Jeremy.
I may raise an alternate solution
