### ISSUE TITLE
[CodeMirror] they have a wishlist at their repo for new modes

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3429]
As mentioned in the title of this issue, the CodeMirror repository has a Wishlist for modes:
https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list

Should we ask to include TiddlyWiki5 syntax?

**Comment by pmario** [comment]
I think the important part is this: 

> Note that the maintainer is not committing to implementing any modes that he doesn't personally use, so there is no reason to expect any action to be taken on account of this list. If you really want a mode, you'll have to either write it yourself, or get it done on a free-lance basis (contact ...

**Comment by pmario** [comment]
I did create the TWclassic mode. ... Since TW5 is similar, it should straight forward to include it. ... The main reason I didn't make one, is, that I don't want to carry the cm-editor weight with every TW. 

If I need syntax highlighting, I use the brackets-editor. 

I also want to have auto-completion and syntax-highlighting for widgets, with is much work, and not important enough for me to invest the time needed.
