### ISSUE TITLE
Search within the extra fields

### ISSUE THREAD

**Issue by ghost** [Jermolene/TiddlyWiki5#3432]
Right now, tiddlywiki just search text in `title`, `text` and `tags` but not in the extra fields (bottom of the tiddler). I think it could be useful to have this feature.

**Comment by somenxavier** [comment]
Sometimes it does, sometimes not. Try `author: Pep Gonella`. If you search `Pep Gonella`, you don't get nothing.

**Comment by twMat** [comment]
I agree that it would make sense to search custom made fields. It is reasonable to assume that these contain data that the user is interested in.

**Comment by AnthonyMuscio** [comment]
This should be a selectable feature since fields are good way to get functional data out of the way and not appear in searches. 

The [Search operator](https://tiddlywiki.com/#search%20Operator) already permits the writing of searches that search other fields. However it seems to lack the ability to search all (or multiple) additional Fields (although this can be worked around).

Where ever the current standard search fields are set it should be possible to toggle all or add additional fields to the default search in addition to providing the ability to alter the filter when building custom searches.

**Comment by 00SS** [comment]
Relying on the ability that complex searches "can be written" means that a non-advanced user cannot easily search  custom fields. 

Since searching is so integral to finding information in a TiddlyWiki, I would like to suggest that [This Solution by tobibeer](https://tobibeer.github.io/tb5/#Searching%20In%20Tiddler%20Fields) be considered as part of a future TW5 release.

In addition, the Advanced Search "Standard" tab could have a check box to include searching custom fields. In fact, the other two tabs (System & Shadow) could also include this.

**Comment by 00SS** [comment]
It just occurred to me that the standard search does not include the **caption** field!

**Comment by kookma** [comment]
I think these are answered through plugins/codes.
Have a look at forum (https://talk.tiddlywiki.org/)

For example: https://kookma.github.io/TW-Search/

or Advance Search Plus: Adds some powerfull search tools from @pmario

**Comment by pmario** [comment]
Have a look at the field-search plugin: https://wikilabs.github.io/#field-search

Advanced Search Plus is a different thing. It's used to save different search configurations, but it has no settings to search in fields.

**Comment by pat-githubber** [comment]
> Have a look at the field-search plugin: https://wikilabs.github.io/#field-search

This works perfectly and addresses the issue 🙏

The issue could be closed.
