### ISSUE TITLE
Pretty default link symbol

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3436]
`[[|Foo]]` doesn't show up as anything. I propose to have such links to *tiddlers* or *external sites* show as subtle(!) icons. The prime use case would be where it is not desirable to have a prominent link but instead a "subtle suffixing symbol in a superscript position". (You've all seen what I'm referring to.)

Icon ideas (both take up same footprint):

![link_external](https://user-images.githubusercontent.com/4534056/45392915-d350c380-b629-11e8-8052-8bbadd0a8bb4.png) - external link
![link_internal](https://user-images.githubusercontent.com/4534056/45392831-663d2e00-b629-11e8-96fe-9cce679a1298.png) - tiddler link

*(...and the 2018 Graphic Designers Award goes to.... not Mat!)*

**Comment by Jermolene** [comment]
Hi @twMat I'm not a fan of these "special case" rules for wikitext or widget behaviour because they add a frustrating sort of complexity in that the special cases are frequently unexpected.

In this case, the idea is that if the link text is empty then we transclude an icon instead. It sets up an undesirable dependency between the JS core code and a specific icon in the core.

I guess the question is whether it would it be any easier to type `[[|whatever]]` than `<<| whatever>>`? And if it's worth the additional complexity it introduces.

**Comment by twMat** [comment]
@00SS - thanks for your thoughts.

@Jermolene 

>easier to type `[[|whatever]]` than `<<| whatever>>`?

Not easier to *type* it but for sure easier to remember, or *guess*, it. Critical, if it is to be used. 

I can't tell how much it is worth in added complexity. I can only say that as an end user I would like for there to be a subtle default link- and that is "intuitively" created.

Maybe it would be less costly with some UTF-8 *character* (e.g the `&#128279;`, i.e &#128279; ) rather than an icon? (BTW, I notice that it is not possible to type `[[&#128279;|Foo]]` nor `[[&#x1f517;|Foo]]` to get the utf character to show.)

**Comment by twMat** [comment]
Here's a solution

```
.tc-tiddlylink:empty:after {
  content:"🡕";
  font-style:normal;  /* same look for existing and missing links */
}
```
Possibly also `  margin-left:-2px;`

It doesn't differentiate between external and internal links and there is no unicode resembling the OP boxed arrow but I find the above clear enough yet subtle. Here are some other options: ⮥⭜⮭⯈🡕🡥🡭🡵🡽🢅

Does this qualify for standard distro? Current situation with *nothing* showing for `[[|link]]` is not good. I will close this thread if it is distinctly either of accept or reject.

**Comment by twMat** [comment]
...darn... of course also `[[]]` is an empty link so it is probably not a sufficient solution...

**Comment by Jermolene** [comment]
Hi @twMat

> Current situation with nothing showing for `[[|link]]` is not good.

I'd prefer to think of it the other way around: Given that `[[|link]]` doesn't do anything useful, is there an opportunity to use it as a shortcut for a common construction that is otherwise hard to type.

I've given my objections above: I don't think it's worth the complexity in learning/documentation for the benefit.

> Maybe it would be less costly with some UTF-8 character

We prefer SVG icons for several reasons, but the important one here is compatibility: those Unicode characters aren't guaranteed to work on every system. Here's your post on my machine, for instance:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/174761/60686919-5d149a80-9ea3-11e9-8da2-49cc4b95903c.png">

**Comment by twMat** [comment]
> is there an opportunity to use it as a shortcut for a common construction that is otherwise hard to type.

Is there? And where this particular syntax makes sense? 

(A syntactic construction that I *have* pondered over is `[[!!...]]` ...I guess it's a direct link to a field value? But it's a solution looking for a problem. ;-)

![image](https://user-images.githubusercontent.com/4534056/60719928-68120e00-9f29-11e9-8aa8-7b8631df0dfb.png)
Yes? Berlin wall not good icon?

**Comment by Jermolene** [comment]
> Is there? And where this particular syntax makes sense?

Not for me, but it's a good question to ask!
