### ISSUE TITLE
Noob Questions

### ISSUE THREAD

**Issue by SeabassWells** [Jermolene/TiddlyWiki5#3454]
Hi. I'm new to TiddlyWiki. I have a few question and I bet you have documentation on how to solve these. Can you direct me to the right sources to look into?

I'm seeking information on -
a) Are there solutions for encrypted, private TiddlyWikis that can be accessed through chrome?
b) Can I set reminders that bring up tiddlers on certain dates? 

--
This is such a cool tool. thanks for the work you do to make it happen!

**Comment by SeabassWells** [comment]
I found the answer to a. Is there a way to get Test1 listed above Test? 

<img width="1081" alt="screen shot 2018-09-22 at 4 28 57 pm" src="https://user-images.githubusercontent.com/6104125/45922575-aa7bca00-be84-11e8-94d0-7fd78aa8bd10.png">

**Comment by twMat** [comment]
Hi and warmly welcome, @SeabassWells !

Those are good questions but asked in the wrong place. Please post them in https://groups.google.com/forum/#!forum/tiddlywiki  where a lot of helpful people hang out. Here on github we only post things about changes in the code.

So, mostly for your sake, please close this thread and repost there :-)

**Comment by pmario** [comment]
Hi, TW contains a mechanism, that lets you encrypt the whole content. At startup the system asks for a password and decrypts the content. ... This is a built in feature. see: https://tiddlywiki.com/#Encryption

If you need to encrypt / decrypt single tiddlers, you can have a look at a plugin: https://danielorodriguez.com/TW5-EncryptTiddlerPlugin/

Reminders is a plugin too. https://tid.li/tw5/plugins.html

------

As Mat pointed out, if you have more questions you should use the google group, since more users are watching it.

**Comment by SeabassWells** [comment]
Thanks!
