### ISSUE TITLE
Question: Is there a way to load pdfs dynamically? 

### ISSUE THREAD

**Issue by polybassa** [Jermolene/TiddlyWiki5#3465]
Hi, 
thanks for this great project. 
We are currently using TiddlyWiki5 on a server as a knowledge base. We share many pdfs over this TiddlyWiki with our work group. 
Because of the file-size of this pdfs, the performance of our TiddlyWiki is decreasing. Every pdf get's loaded by requesting the index page. This leads to load times over a minute.
I'm wondering, if there is a way, to make the pdfs load dynamically, when someone opens a tiddler with a pdf. 

Greetings 
Nils

**Comment by Jermolene** [comment]
Hi @polybassa thanks!

As you may have discovered, the display of embedded PDFs within TW5 isn't consistent or reliable across different browsers. In my experience, best practice for PDFs on the web is to link to them in a new tab, rather than trying to embed them (in situations where I've needed to do that I've ended up converting the PDFs to HTML so that they can be iframed easily).

Anyhow, if you're using the server configuration of TW5 then the best approach is to store PDFs separately from the wiki. In 5.1.17 and before that means storing them on a different web server, but in the soon-to-be-released 5.1.18 there's an integrated file server that you can use. See https://tiddlywiki.com/prerelease#WebServer

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. There has been no feedback for several years.

[Dynamically loading PDFs](https://tiddlywiki.com/#How%20to%20embed%20PDF%20and%20other%20documents) can now be done using the `_canonical_uri` field. I thin the issue is resolved if needed.

**Comment by Jermolene** [comment]
Thank you @pmario
