### ISSUE TITLE
Minor Update to Journal and New Journal here

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3487]
I would like to propose that the action the new Journal button tiddlers be updated to populate a field (I propose journal-date) with a todays date/time serial number.

What this does is ensure that what ever the $:/config/NewJournal/Title set by the user there is a "machine readable date" included in all future Journal tiddlers.

This allows users to get and manipulate the date journal-date to display such information as day of week, week of year and other date information not already held within the $:/config/NewJournal/Title format.

Regardless of the title format, Journal tiddlers can be sorted and filtered by date

**The Change**
In the new Journal button tiddlers 
$:/core/ui/Buttons/new-journal and $:/core/ui/Buttons/new-journal-here

Replace the /> at the end of each line starting `<$action-sendmessage $message="tm-new-tiddler"`
with `journal-date=<<now "YYYY0MM0DD0hh0mm0ss000">>/>`

**Impact**
The addition of very few bytes to the standard wiki to enable additional functionality and further hack-ability.

**Issues**
I believe the only issue here would be the choice of the field name journal-date, if I get siome positive feedback I will submit a pull request?

**Note:**
I currently also use a Custom new journal button to create new Journal tiddlers using a supplied date rather than today so that Journal entries can be made for any date past or present whos date exists in another field. It would be easy to "improve" the new jounal buttons to also except a value or text reference to a valid date field to over ride the use of todays date.

Regards
Tony

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio the "new journal" button already sets the "created" and/or "modified" fields in the usual way, is that not sufficient for your needs? The usual conventions of TW5 would mean that the "created" field always reflects the time that the user created the journal.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio that makes sense, but it sounds like something for advanced users. The goal is to keep the core for things that are universally useful. The cost of introducing features that only cater for a small proportion of users is that it increases the complexity of the core for everyone. Meanwhile, the recommended course for you would be to use a custom new journal button.

I'm closing this issue because I'm mindful that we have too many open issues, but that doesn't mean that the discussion can't continue.
