### ISSUE TITLE
Tiddler popup behind other tiddler titlebars

### ISSUE THREAD

**Issue by Kaliaba** [Jermolene/TiddlyWiki5#3566]
Tiddler popup menu is partially coverd by other tiddlers title bar. This happens when tiddlers are folded or a tiddlers height is lesser than the popup menus height.

![image](https://user-images.githubusercontent.com/36914145/48859753-419aca80-edbf-11e8-97dd-3832dc9ac553.png)
All tiddlers folded

![image](https://user-images.githubusercontent.com/36914145/48862301-3c8d4980-edc6-11e8-9cbf-50b905e8d2ad.png)
Empty tiddler is shorter than popup menu

Tested in 
* Firefox 63.0.1 (64-bit)
* Chrome 70.0.3538.110 (Official Build) (64-bit)

With tiddlywiki version 5.1.17

Using Nodejs 8.12.0 on windows 10

**Comment by twMat** [comment]
@Kaliaba - I believe you're using the "sticky titles" setting, right? Because I don't see this problem for default settings in e.g tiddlywiki.com

Assuming you *are* using sticky titles, then this problem has already been [reported](https://github.com/Jermolene/TiddlyWiki5/issues/2747) and I suggest you close this new thread and chime in over there. It is, in deed, an annoying problem but there's at least a hacky partial solution there.
