### ISSUE TITLE
The download saver's file name has changed incompatibly in 5.1.18

### ISSUE THREAD

**Issue by tfeb** [Jermolene/TiddlyWiki5#3630]
In 5.1.17 and previous versions the file name the download saver would choose was the last component of the URL of the TiddlyWiki: if my TW came from `file:///finge/blob/fash/Spot-bat.html` the file it would save would be called `Spot-bat.html`.  In 5.1.18 the file name seems to come from the title of the TW: if the TW's title (ie `$:/SiteTitle`) is `Spot bat` then the file it saves will be `Spot bat.html` and *not* `Spot-bat.html`.

This is a disaster for anyone (like me) who has built automation around this saver.  It means, for instance, that my `make` rules which read

    $(PAGESDIR)/%.html: $(DOWNLOADSDIR)/%.html

completely fail to notice that there's a file sitting in the downloads directory which actually is the TW but with a different name.

Please either fix this, or let me know what I need to set to make the download saver not try to second-guess me like this.

**Comment by Jermolene** [comment]
Hi @tfeb apologies, I'm afraid we didn't anticipate the backwards compatibility implications of 
d96c84426484747ab19d92b1d9f49e01c9dad985.

On reflection, I'm inclined to issue 5.1.19 in the next week or so as a bug fix release with this change reverted - cc @twMat.

**Comment by twMat** [comment]
@Jermolene thanks for CC. 
Could this perhaps be solved with slugification? Or perhaps a setting to choose download file name?

**Comment by tfeb** [comment]
(Sorry for the terse/rude tone of the original report: I'd just spent an hour getting confused & cross over saves going missing & having to retype notes as a result having foolishly decided to upgrade on Sunday evening.)

I will need to fix my makefiles anyway to deal with the filename differences, which I know how to do & it's not hard.  So it might be better to resolve this more properly by having a 'use the filename / use the title' option for savers, even if that takes longer to implement, if it's not hurting other people.

(Also sorry not to offer a fix in the form of code: I don't know how to build TiddlyWiki, although I should learn.)

**Comment by Jermolene** [comment]
Hi @twMat there are two directly conflicting requirements here:

* Use the existing filename portion of the URL as the download filename
* Use the site title as the download filename

We can't satisfy both of these requirements at the same time; the best we could do is to have a switch.

Reusing the existing pathname is going to be the best option for most users most of the time because it retains the information we've already got; otherwise, we throw away the current filename and rename to the site title. So the new behaviour in v5.1.18 seems like a convoluted way to rename the file.

The only situation I can see where one might want to use the site title as the basis of the filename is when downloading a new index.html from tiddlywiki.com, is that the use case you were thinking of @twMat?

**Comment by twMat** [comment]
> The only situation I can see where one might want to use the site title as the basis of the filename is when downloading a new index.html from tiddlywiki.com, [...]

When saving from tiddlyspot, the file name becomes "tiddlywiki.html" and there is no path  (...or is the url a path?) I agree that reusing the existing pathname - and if possibly extract from url - is preferable. Otherwise the site title is preferable before reverting to default titles like "index" or "tiddlywiki".

Thank you.

**Comment by tfeb** [comment]
I think the most important thing here is that TW should avoid the Java class-file problem.

The Java class-file problem is that, if you compile a Java source file you get some output class files whose names are defined by the contents of the source file.  So any system which wants to understand the dependencies between class files and their sources needs to be willing to parse the source files.  In other words, such a system needs, really, to be Java.  That's just horrible because it means you can't write tools in other languages to deal with dependency maintenance in Java.

The current TW has this problem: you can't know the save file name unless you are TW. 

This probably doesn't matter in some rich environment using node.js &c.  But it *does* matter in hostile environments where you can't rely on that, or on fancy browser support, but have to use single-file TWs managed by `make` & shell scripts.  TW is currently an absolutely superb solution in such environments, just *because* it can be this standalone thing which sits in a file and which requires almost no support (and the support it does need you can write in a few tens of lines of shell script).  I think it's important that it remain useful in such environments, and so I think it really needs to avoid this problem.

**Comment by Jermolene** [comment]
Hi @tfeb thanks that's helpful, and confirms that we should indeed revert this behaviour.

To make things flexible we could introduce a `$:/config/DownloadSaver/FilenameTemplate` that would contain a wikitext string that would be rendered to yield the filename. We'd provide variables to the template such as the current filename extracted from the URL. The current default behaviour would be implemented by a default value of `<<current-filename>>`, and @twMat's preference of using the site title would be implemented by overriding the configuration with the value `{{$:/SiteTitle}}`.

**Comment by pmario** [comment]
But what happens if the user changes the SiteTitle several times. ... I do have browser bookmarks, that open my TWs. ... If changing the SiteTitle would change the filename, I think this link will be broken. 

I think this feature will cause more confusion, than improving the usability.

**Comment by tfeb** [comment]
I would be happy to beta test any changes in my TW in due course.  I'd need to know how to make the upgrader from the git repo so I can use it to upgrade my TWs. I presume this is easy but I could not work out how to do it in very brief looking at it (I can make the blank TW, or at least something that looks suspiciously like it, but my npm / JS skills have rotted since last time I did anything).

**Comment by Secret-HQ** [comment]
In the interest of backward-compatibility and more flexibility in naming TiddlyWiki files, I'd like to see the old behavior restored — though I can see a lot of appeal to the new behavior.

In my case, I use custom extensions for TiddlyWiki files (.TW5 and .TWC for older TiddlyWikiClassics) that allow me to handle them with my preferred browsers (which aren't the same as my day-to-day default browser).

I am, as always, all in favor of making the behavior configurable, either as part of the core or as a core plugin.  😉

**Comment by Jermolene** [comment]
As @Marxsal [points out](
https://github.com/Jermolene/TiddlyWiki5/commit/d96c84426484747ab19d92b1d9f49e01c9dad985#commitcomment-31642598), [my proposal above](
https://github.com/Jermolene/TiddlyWiki5/issues/3630#issuecomment-445745402) can be simplified by using the existing $:/info tiddlers instead of the custom variable I originally suggested.

**Comment by AnthonyMuscio** [comment]
I would support a solution that enables the old and new behaviours to be configured, and perhaps take it a little further. There is some value in both and I can see some instructions for new users being made easier using the {{$:/SiteTitle}} method, but also being able to pre-name the download file, an example is having a tiddlywiki whose download file-name is index.html because it is to be published online. But of course if someone renames the file or the {{$:/SiteTitle}} we do not want the save file changing unexpectedly, or reverting to a previous setting, so could we have a mechanism that can be set to initial save only, or set to allow such in subsequent saves. 

An example would be a wiki file tiddlywiki.html saving as index.html however it remains index html even with a subtitle change, however if index.html is changed to fred.html subsequent saves should be fred.html not index.html.

Another would be allow a user to alter the {{$:/SiteTitle}} online (or offline) and save to a file formed from the {{$:/SiteTitle}} this is a quick and controlled way of cloning the current wiki to different names eg if you have a wiki per personal user or project or subject. This will aid distribution substantially.

I am thus asking for the custom variable to be usable, if chosen but then the filename used maintained until and if the filename is renamed. We could call this the next save switch. A Wiki could have the next save switch set to {{$:/SiteTitle}} or index.html or some other construction like User-{{$:/status/UserName}} once the file is saved according to this switch if then returns to standard behaviour.

An option where this never returns to the standard behaviour could also be useful. An always save switch.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
Post script,

My desire for such behaviour will also enable some options to treat TiddlyWikis as smart Documents, Just as Microsoft Word or any other document application allows you to save as a default names, and Existing name or save as / rename as a cloning process I would like to be able to do this. 

Considering this html files, even zipped Html files, hta or asp files are often rejected as attachments by email systems making distributing TiddlyWiki files as smart documents problematic, so the ability to save or export tiddlywiki files with another extension name would also be a useful feature eg mydocumentname.tw5 which permits emailing.

The received file can be renamed to html or a local file association treat the tw5 filename as if it where html.

Regards
Trony

**Comment by Jermolene** [comment]
There'll be a new build up on https://tiddlywiki.com/prerelease that fixes this issue, do please give it a try. There is now a new hidden setting if you want the v5.1.18 behaviour: https://tiddlywiki.com/prerelease/#Hidden%20Setting%3A%20Filename%20for%20Save%20Wiki%20Button
