### ISSUE TITLE
What is different about the new tiddler content field?

### ISSUE THREAD

**Issue by dnebauer** [Jermolene/TiddlyWiki5#3676]
The web browser I'm using with TW, [qutebrowser](https://github.com/qutebrowser/qutebrowser) has a mechanism for opening an external editor when filling in forms fields. When creating a new tiddler this mechanism works with every editable field _except_ for the content field, which is obviously the field for which an external editor would be most useful:

![new-tiddler](https://user-images.githubusercontent.com/1834722/50620388-82513c00-0f46-11e9-81fb-f9f6dd47699a.png)

**In order to troubleshoot this at the browser end I need to understand what is different about the content field in comparison with the other fields.**

If it helps, the mode of failure is that the external editor (gvim) launches, I enter the content in the editor, and close the editor -- at this point for all other fields the editor content appears in the browser form field, but in the case of the content field it remains empty.

I tried to view the page source but, of course, that showed me the entire wiki. I don't have sufficient knowledge of TW to wade through that.

**Comment by gernert** [comment]
@dnebauer
As of v5.1.12 TiddlyWiki contains an editor toolbar which uses an iFrame for the editor (editor bookmarklets ceased to work as well since then).

According to @Jermolene: "The iframe was added around the textarea when we added the toolbar buttons because otherwise clicking on a button will remove any active selection from the textarea as a side effect of removing focus".

So, if you switch off the editor toolbar (Controlpanel > Settings > Editor toolbar) you can use an external editor (and bookmarklets) for the text field.

Note: I added a toggle switch for editor toolbar (and preview) below the tags field: $:/_toggle-editor-toolbar_preview, available at http://tongerner.tiddlyspot.com/ (see tab 'Code tiddlers').

**Comment by dnebauer** [comment]
This was discussed in the tiddlywiki google groups forum in this [thread](https://groups.google.com/forum/#!topic/TiddlyWiki/im3aJ9_BYLI). (I hope that is a stable link.)

The cause turned out to be the CodeMirror plugin. Disabling the plugin resulted in the external editor working successfully to provide input to the content field. This is an acceptable solution since you don't need the CodeMirror plugin if you are using an external editor for content. Of course, it means you have to commit to using one or the other unless you want to be toggling plugins constantly.

The _exact_ way in which the CodeMirror plugin interfered was not nailed down, but the consensus is that by the time the CodeMirror plugin is finished modifying the field to display line numbers, highlighting and other features, it is no longer a standard textarea and this interferes with qutebrowser's external editor mechanism.
