### ISSUE TITLE
Propose new macro and Widget message past-from-clipboard

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3731]
Hi,

I love using the copy to clipboard macro or my preferred WidgetMessage: tm-copy-to-clipboard to make taking titles and text and moving around, in between wikis and other apps. I am making a useful little tool for my wiki where I can paste titles or links found elsewhere. Such as a system tag from tiddlywiki.com

As a result I was wondering if I could propose a new macro "paste from clipboard", and WidgetMessage: tm-paste-from-clipboard if in fact this is possible with browser security. I know last pass does some thing similar.

The idea would be to provide a tiddler and/or field name (text reference) that would "receive" the current content of the clipboard when triggered, ideally with a clear or no clear clipboard contents if possible.

We could then make a suit of our own buttons for inserting the clipboard content into a field, a tiddler text, in a new tiddler, appended to a tiddler etc... This would allow for some really useful text content and manipulation tools not only between wikis but all apps with copy/paste.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
Further, such a tool may allow us to trap and better handle the accidental paste that result in import being activated with an untitled tiddler for import.

**Comment by AnthonyMuscio** [comment]
Actually the "paste from" should be extended to allow past from text reference in addition to paste from clipboard, opening the opportunity for people to build independent copy paste clipboards in TiddlyWiki, The following in V 5.1.18 helps this.

- Added new text editor operation save-selection – see WidgetMessage: tm-edit-text-operation
- Added support for editor toolbar buttons to have action widgets

Regards
Tony

**Comment by Jermolene** [comment]
Browsers do not let web pages arbitrarily read from the clipboard because it would be a security concern if you visited any web page while sensitive data is on the clipboard. All we get instead is the ability to intercept a user-initiated paste operation (ie via keyboard shortcut or menu), and perform transformations on the text prior to it being inserted. It might therefore be possible to create a widget that intercepted paste events within its content and used an action string to allow the text to be modified before the paste operation.

**Comment by AnthonyMuscio** [comment]
Closed as I stumbled across this again, I am now aware both that we cant pull from the clipboard, however we could catch the tm-copy-to-clipboard and store things sent to the clipboard in a local wiki clipboard data tiddler
