### ISSUE TITLE
A dashboard-style storyview

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3738]
Hi all,

I'd like to propose a new storyview that lets us create tiddlers anywhere in the story-river by dragging a selection

It would be a dashboard-like / desk-like look and feel

See this library I found: https://github.com/Simonwep/selection
And a modified classic storyview with a selectable grid: http://selectiondashboard.tiddlyspot.com/

I think this is very easy to do with great effect
What are your opinions about it?

all the best,
BTC

**Comment by pmario** [comment]
I personally don't see the value at the moment. IMO tiddlers would need a different ViewTemplate and they need to be resizeable and movable

**Comment by BurningTreeC** [comment]
>I personally don't see the value at the moment. IMO tiddlers would need a different ViewTemplate and they need to be resizeable and movable

yes, I thought this could spawn a bit of creativity here. it would need a different view- and edit template. tiddlers should resize in height I think. moving them could also easily be done using the hammerjs plugin. resizing would be possible, too, if needed.

>changing the storyview setting doesn't change the story "view" .. bug??

I guess there are many bugs as this is a demo created in 10 minutes...

**Comment by AnthonyMuscio** [comment]
BTC

Personally I think it has a great deal of merit.  Using your demo I highlighted an area and created new tiddlers. This would allow the easy translation of material from one source to tiddlywiki using a visual layout. Imagine I am reading about the OSI model https://en.wikipedia.org/wiki/OSI_model
I could draw the 7 layers and document each inside the tiddlers. Then Imagine if I could select all 7 layers or some of them, and tag them all with OSI.

Perhaps the best design model would be to allow the creation of multiple "dashboard Tiddlers". New or existing tiddlers can be placed on and sized on each dashboard. Perhaps a view and edit mode so accidental changes to the dashboard layout do not happen. There is no need to touch the story list and history if you get the set of tiddler back by reopening the dash board tiddler (in effect they have there own storylist and history) as there is value down the track leveraging the same mechanism all the tiddlers on the dash board can be opened as individual tiddlers etc...

The ability to use a special for of transclusion to include the Dashboard in other tiddlers, so you can have a dash board of dashboards would be good.

Ever since the Murri plugin I have seen the potential for a large screen presentation where a team use it to record a brainstorm, or a presenter uses it to organise items visually, but to think this could actualy support the creation of our Wikis using a Dashboard layout in fantastic.. 

On "**Alternate view and edit templates**", I have long believed TiddlyWiki would benefit from an easy mechanism to create and use various view and edit templates (and toolbars). Imagine on a Dashboard or an internal navigation TOC it was easy to nominate alternate view and edit templates for the tiddlers displayed there in and set different tool bars etc... even one tiddler with this view another with another view. 

If we were to go down the path of "enabling better view edit templates" I would recommend the introduction of a third called an update template, used when presenting tiddlers in a view like mode with editable elements displayed. Muuri plugin would benefit from this as well. I would also allow a template to wrap another so that all tiddlers in an internet navigation TOC could have one template for all, and one for each. Which I would explain further if required, but it would be of grate value.

Very inspiring, I hope something transpires for this.

PS I would be happy to write a design document or Requirements if you want help.

Tony

**Comment by AnthonyMuscio** [comment]
Example from Demo

![dashboard](https://user-images.githubusercontent.com/31584658/52021315-b2412e80-2548-11e9-9b67-1b7d7e1f2812.jpg)

**Comment by pmario** [comment]
I think, this is plugin territory, since there are several 3rd party libraries involved.

**Comment by AnthonyMuscio** [comment]
Mario, The dashboard does seem to be suitable as a plugin, like any alternate visualisation. There is however the posibility of some minor changes of the hackability nature could simplify the solution and open other possibilities.

**Comment by AnthonyMuscio** [comment]
Just dreaming. What if we could drag one to another to tag it, and back again for a two way tag. or drag a tag to more than one? I would allow a visual creation and relationship between tiddlers that is somewhat missing out of the box in TiddlyWiki. We could call this the visual designer, or visual creator.

What great inspiration BTC

**Comment by linonetwo** [comment]
Recommending [https://github.com/tiddly-gittly/tiddlywiki-whiteboard](https://github.com/tiddly-gittly/tiddlywiki-whiteboard) 

[https://talk.tiddlywiki.org/t/whiteboard-plugin-v0-2-3/5302](https://talk.tiddlywiki.org/t/whiteboard-plugin-v0-2-3/5302)

I'm searching for i18n solution for plugins, and come across this issue.
