### ISSUE TITLE
Feature Request: Trigger Custom Popups via Custom Strings

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3784]
As @twMat described in: https://github.com/Jermolene/TiddlyWiki5/issues/3764#issuecomment-464076426, it would be incredibly useful to trigger _custom popups_ via _custom strings:_

```
to be able to trigger _custom popups_ via _custom strings_ would be so useful that it deserves place in standard distro. Both newbies and experts should benefit from having custom triggers like `[[`, `<$`, etc show pickable options like

* tiddler titles
* widgets/macros - much needed (e.g `<$` triggers picklist of available widget with parameters)
* transclusion popups - to show arbitrary tiddler (... e.g string `wikipedia:foo` shows a tid with an iframed wikipedia for entry "foo". Or `scrap` transcluding transcludes your clippings tid)
```

An example of a plugin that gets us part way there, is Snowgoons Edit-CompText:

https://snowgoon88.github.io/TW5-extendedit/

which allows you to define custom strings to trigger its standard popup:

https://snowgoon88.github.io/TW5-extendedit/#%24%3A%2Fplugins%2Fsnowgoon88%2Fedit-comptext%2Fusage

**Comment by twMat** [comment]
In deed. This would make the editor **support** the very process of authoring and editing! The current editor merely *enables* authoring/editing. "Pick lists"  (as in Snowgoons plugin) is probably the prime examples, i.e to auto complete tiddler titles, macro- and widget calls as well as signatures or stock phrases by selecting options from a presented list. Super userful.

If both the trigger strings and the popup content is customizable, it would turn the editor into a powerful and contextual *toolbox*: Currently, the closest we get is the rich editor toolbar. While useful, it is static: It takes up real estate so it has to be much more limited and cannot take context into consideration. In contrast, very context specific "trigger strings" like `>packlist` or `>synonym:foo` or `>mathops` or `>help` can show exactly the relevant tools or info. (The `>` prefix is just an example)

*Overall it should lower the threshold to using TW because users can get help right away.*

**User friendly UI:**
By having the popup transclude individual tiddlers, it would also be really simple for users to add new ones. For example, tiddlers could be tagged `$:/tags/editortool`, have a field named `editor-trigger` and the tiddler content (i.e text field) would be what shows in the popup. Super simple and very tiddlyesque.

**Comment by diego898** [comment]
@twMat This is a **very** compeling vision and natural extension of the plugin! Plugin authors could even “plug in” into this core system, to offer additional functionality. I’m specifically thinking of @pmario’s alias plugin exposing a |? Trigger/drop down to auto complete alias for example.

**Comment by twMat** [comment]
I made http://editorpopup.tiddlyspot.com which outlines the concept in more detail.

This would really be useful.

**Comment by diego898** [comment]
@twMat Thank you for that outline! I think this could be a really powerful addition to TW. A small addition to your outline - as far as dismissing, you suggested ESC, a small X, or even a "space". I think instead of a space, at least for lists/filtering/etc. it could just also dismiss when there is nothing left to show.

**Comment by twMat** [comment]
>instead of a space, at least for lists/filtering/etc. it could just also dismiss when there is nothing left to show.

Yes, that makes sense. I'll update the outline. 

BTW, I attempted to contact @snowgoon88 August 1 but so far no reply.

**Comment by giffmex** [comment]
I don't know the technical ins and outs of all this, but if there is a way to be able to enhance the way links are created, I am all for it!

**Comment by snowgoon88** [comment]
Hello.
I would be glad to try to help, but I do not know where to begin. 
I could help in making the popup appear below the cursor.

I had a look at http://editormagic.tiddlyspot.com, but I'm still confused about the internal logic : where does the magic happend (in what tiddlers ? Have you added some javascript somewhere ?). In short, where is the code that "monitor" what the user is typing and then decides of what to show in a popup ?

Snow

**Comment by twMat** [comment]
Hello @snowgoon88 - how good to see you here! Fellow @inmysocks (Jed) is currently helping out with the popup matters, [here](https://groups.google.com/forum/#!topic/tiddlywikidev/scGK9fBKsZ8). He succeeded in using the original code that you also used but we're having a few difficulties. One is actually the CSS positioning but it is also a bit choppy in its performance. Better take the discussion over there.

>I had a look at http://editormagic.tiddlyspot.com, 

Instead, please look at [TitlePicker](http://titlepicker.tiddlyspot.com/). It is one of the modules from EditorMagic; I decided to start with this single case because people can actually understand what it is. The EditTemplate tiddler (which will become the popup eventually) identifies the "trigger" and the "fragment" i.e the `[[` and `foo`, and the TitlePicker tiddler identifies the tiddler title "suggestions" and does the replacing of `[[foo` for e.g `[[foobar]]`.

So the idea is to have the EditTemplate show as popup like in your creation but to provide a wide range of pickers, stamps etc, all using that common template. That whole package will be called "EditorMagic".

At the moment the popup-at-caret-positioning is one of the difficulties and another is the regexp to split out and replace correctly. You're more than welcome to test [TitlePicker](http://titlepicker.tiddlyspot.com/) and to try out some regexps in this macro`\define remove() $(trigger)$$(fragment)$`

**Comment by snowgoon88** [comment]
I've tried to add some meaningful remarks/questions in the google group
discussion.( here
<https://groups.google.com/forum/#!topic/tiddlywikidev/scGK9fBKsZ8> ).
Snow
