### ISSUE TITLE
Favicons don't work in IE11

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#379]

**Comment by tobibeer** [comment]
@Spangenhelm Did you mean in general or a specific file you were trying to set?

Looking at tiddlywiki.com, it appears to work for me...

![favicon](https://cloud.githubusercontent.com/assets/97566/6108733/bac71c46-b075-11e4-900f-861cd4097c38.jpg)

**Comment by tobibeer** [comment]
Ok, it appears that favicon actually came from here:

https://github.com/Jermolene/jermolene.github.io/blob/master/favicon.ico

**Comment by tobibeer** [comment]
Reading [here](http://blogs.msdn.com/b/ieinternals/archive/2013/09/08/internet-explorer-favicons-png-link-rel-icon-caching.aspx)...

> Unfortunately, IE11 does not support specifying a Favicon using a DATA URI; while embedding the favicon in this way would have a number of downsides (including impairing performance in most cases) support for embedded/scriptable favicons could be useful in a few web application scenarios.

Update doc and close?

**Comment by Spangenhelm** [comment]
@tobibeer wow it has been almost a year now and i can't really remember what was wrong but here is what i have said in the other issue:

> Can't have favicon to work in IE11 Windows 8.1 64Bits
When i drag and drop my favicon it creates a new tiddler with it: ok
it is automatically recognized as an icon: ok
then i rename the tiddler $:/siteicon or $:/favicon and save/load: not displaying the favicon
also tried both in "field" name

I think i was talking about one of my new tw that i was trying to tweak..(i should of specify the version i have used..) Have you tried to set one of your own favicon ? Sorry i cannot try it on my side because i moved to linux a while ago. If you succeed than i suppose that we will be able to close this issue.

Thanks

**Comment by tobibeer** [comment]
I think we can close the issue because it's ie11 that doesn't provide the feature of parsing data uri's for link references, or specficially the favicon reference.

In other words, if you want there to be a faviconin in ie, you will have to put it next to your file and reference it accordingly via **$:/tagsRawMarkup**.

**Comment by Jermolene** [comment]
So I think we can close this.
