### ISSUE TITLE
codemirror vim keymap: disabling tiddlywiki's escape

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3818]
Hi all,

I'm looking for a sane way to disable the escape shortcut within the editor only

CodeMirror's vim keymap has its own handling for escape, which is very important for vim users. If the keyboard widget steals that shortcut, the vim addon is nearly unusable

I want to map `:q` to cancelling (tm-cancel-tiddler), `:w` to saving (just save the tiddler, don't close) and `:wq` to save and close (tm-save-tiddler). This is vim standard functionality.

Do you have any ideas how to disable escape for the editor, leaving it untouched for the other edit-template inputs? I don't want to add a modified `$:/core/ui/EditTemplate` to the vim addon, overwriting the core edittemplate ...

**Comment by Jermolene** [comment]
Can't we just change the close tiddler keyboard shortcut to be something other than escape?

**Comment by BurningTreeC** [comment]
> Can't we just change the close tiddler keyboard shortcut to be something other than escape?

yes we could, but it's strange being used to escape in the other input fields. that's why I'm looking for ideas

**Comment by sukima** [comment]
In my experience it is **not** the websites' shortcut that interfere with the <kbd>Esc</kbd> key but the browser itself. I've never been able to find where or why but in every website which offers Vim key bindings irregardless of the JavaScript editor used (including Firefox's Development Console) all suffer from the anti-<kbd>Esc</kbd> movement.

It has been my experience that it is a universal issue affectiong every website and I have no other choice but to use <kbd>CTRL</kbd>+<kbd>C</kbd> as a replacement for <kbd>Esc</kbd>. I don't have confidence this can be fixed in the JavaScript.

**Comment by BurningTreeC** [comment]
Hi @sukima , I'm able to use escape with the vim keyMap, I'll post a gif. It can be that it's needed to set "Esc" to "handleEsc()" in the codemirror extraKeys ($:/config/codemirror/extraKeys) but it works

**Comment by BurningTreeC** [comment]
My screenrecorder is blocking keyboard input so I can't demonstrate it with a gif, but it works without problems. Nothing needs to be changed in the codemirror config, the cancel-edit-tiddler shortcut needs to be set to something other than escape.

I only tested with the newest version of the codemirror plugin
