### ISSUE TITLE
showing typed colors with their color value as background

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3821]
Is it possible to render colors, like #123456 or rgb(1,2,3), with say - a span with the color value as background-color and the color-text within?

Would be extremely helpful when working on color palettes etc. ...

I found a regex to match all hex, rgb and rgba colors:

```
/(#([\da-f]{3}){1,2}|(rgb|hsl)a\((\d{1,3}%?,\s?){3}(1|0?\.\d+)\)|(rgb|hsl)\(\d{1,3}%?(,\s?\d{1,3}%?){2}\))/ig
```

so if I type #123456 the rendered tiddler would have a span

```
<span style="background-color:#123456;">#123456</span>
```

**Comment by Jermolene** [comment]
Hi @BurningTreeC I have wondered about this too, but reckon that there are too many false positives with `#rrggbb` format. Perhaps better to use a macro? `<<rgb 459ce4>>`.

**Comment by BurningTreeC** [comment]
it would be great if a palette for example would show all its colors automatically when viewing it in view mode

I thought the text widget might test its incoming text with a good regex and then somehow add those spans surrounding the matches ... but I have no clue

**Comment by BurningTreeC** [comment]
... with a switch in the controlpanel that enables that behavior

**Comment by Jermolene** [comment]
> it would be great if a palette for example would show all its colors automatically when viewing it in view mode

I quite agree, but we'd really want it to show the indirect ones too (`<<colour background>>`), and so we'd need more than a parse rule for `#rrggbb` etc.

Sadly, it would be hard to make a custom parser for palettes because they don't have a unique content type.

To be honest, I'm think that the best approach is based on what we do already: a special palette editor tiddler that can show palettes in both view and edit mode. So perhaps we elevate it to be `called $:/PaletteManager` (but still embed it in the control panel for backwards compatibility), and enhance it a little (at the moment we don't always show the correct colour for instance, and we could really do with a little search box for finding things).

**Comment by BurningTreeC** [comment]
cool, a PaletteManager would be great!

**Comment by Jermolene** [comment]
Do you fancy giving it a go? To be clear I'm talking about taking the content of $:/core/ui/ControlPanel/Palette and putting it in $:/PaletteManager, and then putting a transclusion of $:/PaletteManager in $:/core/ui/ControlPanel/Palette (so that we don't break anybody who has transcluded the existing palette manager). And then we'd improve palette manager step by step.

**Comment by BurningTreeC** [comment]
> Do you fancy giving it a go?

just wanted to ask you the same

But I can, is it possible to easily list all possible color-names?

**Comment by Jermolene** [comment]
Have a look at the existing code -- I think we just show the colours that are defined in the current palette.

**Comment by BurningTreeC** [comment]
> Have a look at the existing code -- I think we just show the colours that are defined in the current palette.

yes that's the case. I'd like to show all possible names which makes it a lot easier when creating one.

right now I'm listing all tiddlers tagged $:/tags/Palette and get the indexes from that list. a checkbox reveals the colors that are not part of the current palette, otherwise they're hidden

**Comment by Jermolene** [comment]
Sounds good!

**Comment by BurningTreeC** [comment]
Hi @Jermolene , I found a way to do this using the regexpreplace filter (#3816 ) in the body-viewtemplate (for palettes only). It just doesn't keep the new-lines at the moment, but it shows the colors with:

```
<span style='background-color:#123456;'>#123456</span>

<span style='background-color:rgb(1,2,3);'>rgb(1,2,3)</span>
```

```
<$list filter="[all[current]tag[$:/tags/Palette]!field:hide-body[yes]]">

<$set name="replaceRegex" value="(?ig)(#([\da-f]{3}){1,2}|(rgb|hsl)a\((\d{1,3}%?,\s?){3}(1|0?\.\d+)\)|(rgb|hsl)\(\d{1,3}%?(,\s?\d{1,3}%?){2}\))">

<$set name="regex" value="<span style='background-color:$1'>$1</span>">

<$wikify name="newText" text="""<$set name="replaced" value={{{ [{!!text}regexpreplace:regex<replaceRegex>] }}}>

<$text text=<<replaced>>/>

</$set>""">

<<newText>>

</$wikify>

</$set>

</$set>

</$list>
```

**Comment by twMat** [comment]
>Is it possible to render colors, like #123456 or rgb(1,2,3), with say - a span with the color value as background-color and the color-text within?

If not already solved in TW, we'd need to consider how to contrast the text from the background. Here's a recent [article](https://css-tricks.com/css-variables-calc-rgb-enforcing-high-contrast-colors/) on the matter.

**Comment by BurningTreeC** [comment]
Hi @twMat , thanks for the article. I think the `contrastcolour` macro already does the trick, it's used on tag-pills to show text either dark or light depending on the tag-color. best to be experienced playing in the $:/TagManager

**Comment by twMat** [comment]
>I think the contrastcolour macro already does the trick,

Great, then please disregard my post :-)

**Comment by BurningTreeC** [comment]
> > I think the contrastcolour macro already does the trick,
> 
> Great, then please disregard my post :-)

still good info to read :+1:

**Comment by Jermolene** [comment]
Are you happy to close this?

**Comment by BurningTreeC** [comment]
Yes!
