### ISSUE TITLE
Should wiki and plugin folders be described by `package.json`

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#390]
At the moment, wiki folders are recognised by a `tiddlywiki.info` file in their root, and plugin folders by a `plugin.info` file. Both contains JSON metadata about the wiki.

Perhaps we should switch to using `package.json` for both purposes, and structure our fields as extensions to the format established by npm.

Then it would be possible to people to use npm to distribute wiki folders (aka editions) and plugins.

**Comment by ght** [comment]
Implementing this would mean having two different ways to describe wiki/plugin directories, and there would be two ways forward:

1. support both `package.json` and `.info` - con: more to maintain
2. switch to `package.json` - con: breaks backwards compat

The only pro I can see is that potential 3rd parties can distribute their plugins over npm. This is no less possible though AFAIU, since they can have both the `package.json` for npm, and the `.info` file for TW, so I don't think there would be any value from implementing this.

There also hasn't been any interest on this issue in >6 years, so I vote for closing it.

**Comment by Jermolene** [comment]
Thanks @ght
