### ISSUE TITLE
Add ability to load plugins via the command line

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3907]
When using TW5 under Node.js, the only way to specify plugins to be loaded into the wiki is to list them in the `tiddlywiki.info` file. That's why there is a `tw5.com-server` edition as well as the `tw5.com` edition -- the former includes the latter but adds the "tiddlywiki/filesystem" and "tiddlywiki/tiddlyweb" plugins.

It is proposed to add a mechanism to specify plugins to be loaded on the command line. This example loads the `tw5.com` edition with the "tiddlywiki/filesystem" and "tiddlywiki/tiddlyweb" plugins:

```
tiddlywiki +plugins/tiddlywiki/filesystem +plugins/tiddlywiki/tiddlyweb editions/tw5.com --listen
```

**Comment by pmario** [comment]
That's ok, but the -server edition also has several other advantages. eg: I save the $__StoryList.tid into the server, so whatever happens, it will never end up in a published version. Similar things can happen with other plugin settings, that I want to change for the development server, but I don't want them to end up "modified" in the github repo. 

We did have a discussion to combine those 2 settings. ... But for me it turned out. keeping the -server edition has advantages. 

see: https://github.com/wikilabs/editions

**Comment by Jermolene** [comment]
Hi @pmario indeed, there's no suggestion that this new mechanism obviates the need for wiki folder inclusion, just that it provides a faster option for cases where there is no need to create a `tiddlywiki.info` file.

The background to this proposal is that I've been working on an `--savewikifolder` command that saves the current wiki as a new wiki folder. It fills a hole we've had for a while, but it's a fair amount of code (nearly 2% of the total JS code in the core), so I'm not convinced that it should go in the core. But, if it is distributed as a plugin then users will have to set up a wiki folder with a `tiddlywiki.info` just so that they can access the command.

**Comment by pmario** [comment]
>... there's no suggestion that this new mechanism obviates the need for wiki folder inclusion, just that it provides a faster option for cases where there is no need to create a tiddlywiki.info file.

Yes. I saw this after I did write my response. I'm ok with that option. 

>...users will have to set up a wiki folder with a tiddlywiki.info just so that they can access the command.

I see.
