### ISSUE TITLE
Button Widget Documentation Broken

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyWiki5#3923]
The Button widget Documentation https://tiddlywiki.com/#ButtonWidget makes reference to the attribute stateTitle perhaps this supposed to be setTitle. 

The line on setTitle refers also to "Gets preferred over **state**" which is not an attribute on the button widget either. 

I think someone forgot to finish the documentation.

If someone can explain the truth of the button Widget attributes I will be happy to do the change request.

Regards
tony

**Comment by 00SS** [comment]
@AnthonyMuscio glad you spotted this mix up!

Though I am not sure and have not tested it, I believe:
`Gets preferred over state` should read `Gets preferred over set`

And I believe you are right, in both the case of `setTitle` & `setField` , at the end of the sentence:
`if the attribute stateTitle is present.` should read `if the attribute setTitle is present.`

I believe the mix up happened because the same time this was being done, the $reveal widget was also being updated by adding `stateTitle` `stateField` `stateIndex`

I think @BurningTreeC could confirm this as he was working on PR #3529 that made the changes.

**Comment by pmario** [comment]
@AnthonyMuscio IMO can be closed. setTitle should have the right text now.

**Comment by Jermolene** [comment]
Thank you @pmario
