### ISSUE TITLE
UI Suggestion: Switch discard button and checkmark

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#3932]
In reading mode, there is a big X as the rightmost button. In edit mode, the rightmost button is a checkmark - that allows you to "commit" changes **without** confirmation. This is a dangerous button in a way, and this switching of location seems inconsistent.

I frequently drop into edit mode, only to want to discard any edits I've made. Without thinking I go to the rightmost button to press a big X. However in edit mode, this is now the dangerous commit button, and the "discard" button is now in the middle (this button **does** confirm if you want to discard any changes).

Perhaps the default location for the checkmark button (in edit mode) should mirror the default location of the edit button (in normal mode), and the discard button (in edit mode) should be in the same place as the X button (in normal mode).

I am aware its possible to do this myself, on my wiki. This issue is to suggest making the change the new default. As such, responses that state "thats not the default and you can change it" aren't really helpful. If we pretend we were making it up for the first time, where would we place the buttons?

**Comment by pmario** [comment]
The problem you describe is completely new to me. I don't even think about it, where the buttons are. I'm so used to the existing behaviour. 

If you have a closer look to the toolbar button positions.

mode | . | . | . 
------------ | ----  | ----  | ----  
view mode  | more | edit |  close 
edit mode   | delete | cancel | done 

Their position is by design, because it creates a nice workflow, that exists since TWclassic in a similar way. 

1) If a user accidentally clicks "edit", they can click "cancel" without moving the mouse. If the "done" button would be there, the `modified` timestamp of the tiddler would be changed, which in turn would change the sort order in the "recent-tab"

2) If you are "done" with editing a tiddler and you want to close the tiddler you can click "done" - "close" without moving the mouse cursor. IMO that's fast and convenient.

3) There has been a similar [thread in GG 2016](https://groups.google.com/d/msg/tiddlywiki/_76g9VsbTAM/w0sNd-i8BAAJ)

4) I think the toolbar icons and their position always depend on the actual users "use-case" and "preferred workflow" ... 

>... As such, responses that state "thats not the default and you can change it" aren't really helpful

You are right, the button positions are configurable with "drag & drop" in the `ControlPanel: Appearance: Toolbars: Editor` tab, so users have a choice, if they don't like the existing configuration. IMO it is helpful, because it's a working solution. 

>... If we pretend we were making it up for the first time, where would we place the buttons?

I think changing the default behaviour after so many years, would actually do more harm than good.

**Comment by Jermolene** [comment]
Hi @diego898 I can understand the concern. @pmario has explained the logic behind the current arrangement, and I think he's right that we shouldn't change the default at this stage.
