### ISSUE TITLE
tiddlywiki.com/prerelease > See GitHub for detailed change history of this release . link 

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#3953]
tiddlywiki.com/prerelease/ > "See GitHub for detailed change history of this release" 
link : https://github.com/Jermolene/TiddlyWiki5/compare/v5.1.19...v5.1.20

says 
>There isn’t anything to compare.
We couldn’t figure out how to compare these references, do they point to valid commits?

i guess this is not what should/is intended to  happen ?

**Comment by rmunn** [comment]
If you edit the URL to say `v5.1.19...master` instead of `...v5.1.20` then it will show you the changes since the `v5.1.19` tag. The `v5.1.20` tag won't be applied until 5.1.20 is officially released, so until then the tag doesn't exist. I suppose Jermolene could make that link point to `v(current)...master` in the prerelease version, and always remember to change `master` to `v(just-released)` as part of the release process (or write a script to make that change automatically). That's prone to errors, though: forget to do it once, and now you've released a version whose change history link is broken.

**Comment by dubiouscript** [comment]
:sweat_smile: ..  this can close 
... probably only opened due to deep slepravation =S 

and finding a few broken links, 

@rmunn thanks ...
gd to know 
> v5.1.19...master
should work though !

> and always remember to change `master` to `v(just-released)` as part of the release process (or write a script to make that change automatically). That's prone to errors, though: forget to do it once, and now you've released a version whose change history link is broken.

perhaps some way to chk for broken links 
might avoid that scenario..

**Comment by Jermolene** [comment]
Cheers @dubiouscript
