### ISSUE TITLE
"allafter:include" operator fails with one element lists

### ISSUE THREAD

**Issue by mauloop** [Jermolene/TiddlyWiki5#3962]
Try:

```
aaa bbb ccc +[allafter:include[bbb]]
```

It returns 2 matches (`bbb ccc`) as expected.

Now:

```
aaa bbb ccc +[allafter:include[ccc]]
```

This returns 0 matches, but I expected 1 (`ccc`).

**Comment by AnthonyMuscio** [comment]
Forgive me, I have not used this operator before but if you are asking all after ccc and there is nothing after ccc (despite include) you are getting what you ask for, ie "all after ccc" (and that is nothing).

I fear if in the case of nothing after ccc returning ccc it is not really allafter, how will I get my use case of show all after the marker, if so include the marker, otherwise if nothing is after be empty.

To cater for ccc if it is the last what about saying +[allafter:include[ccc]] ~[[ccc]] ?

Perhaps it would be sufficient to indicate this case in the documentation?

Regards
Tony

I stand to be corrected, just my 2cents

Regards
Tony

**Comment by pmario** [comment]
I do think this is an oversight and a bug.

**Comment by mauloop** [comment]
> I fear if in the case of nothing after ccc returning ccc it is not really allafter, how will I get my use case of show all after the marker, if so include the marker, otherwise if nothing is after be empty.

This behaviour looks ambiguous. As from tiddlywiki.com documentation (https://tiddlywiki.com/#allafter%20Operator):

_specifying a suffix ('include') will include the marker in the output_

This is what happen with:

`
aaa bbb ccc +[allafter:include[bbb]]
`

The fact that the rule is not applied when the marker is the end of the list, is somewhat confusing.

> To cater for ccc if it is the last what about saying +[allafter:include[ccc]] ~[[ccc]] ?

This is exactly the workaround I'm using. Just a workaround IMO.

> Perhaps it would be sufficient to indicate this case in the documentation?

I think it could help. I spent time to understand the trick (you can imagine that "aaa bbb ccc" was just to give an easy example. The real use case was a little bit more complicated  `;^)))` ). Anyway I still think that this behaviour is not consistent with the operator specs.

Regards,

)+(au

**Comment by AnthonyMuscio** [comment]
> Anyway I still think that this behaviour is not consistent with the operator specs.

I don't disagree with you on this, only the solution must account for the case where if there is nothing after ccc do not include ccc but when their is do include ccc.

**Would it help if allafter:include[ccc]] was documented as follows? Or do you need to address another use case?**

`+[allafter:include[ccc]]`
Will include ccc only if something follows ccc

`+[allafter:include[ccc]] ~[[ccc]] `
To include ccc when nothing follows ccc 


Regards
Tony

**Comment by Jermolene** [comment]
Hi @mauloop thanks for the report, and apologies for the delay. I can confirm the problem with the `allafter` operator, and will shortly push a fix along with some tests.

**Comment by mauloop** [comment]
Thanks @Jermolene  for your answer. Don't matter for the delay. Regards,

)+(auloop
