### ISSUE TITLE
length filter op - unexpected output when empty

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3969]
`{{{ [length[]] }}}`

The above produces a weird array of some hundred numbers. I guess I was expecting either no output or `0`.

**Comment by twMat** [comment]
Actually, I found this when attempting to get a length for an empty list, like so

`{{{ +[length[]] }}}` and `{{{ "" +[length[]] }}}` 

expecting output to be `0` but there is no output at all.

**Comment by AnthonyMuscio** [comment]
I understand why and think it is not a bug, but needs to be documented to help the use of the new mathematics operators.

`{{{ [length[]] }}}`
A Filler operates on all tiddlers. You are getting a list of every tiddlers title length.

Whilst we may want to do maths with the maths operators many can also be used for tiddler and string handling so we must be careful not to undermine these possible uses. For example length is in many ways a string operator.

`{{{ +[length[]] }}}`
In this case you are saying any title listed give the length, however the + asks for any titles fed to it, yet there is no longer an implied generator of titles. This could be an interesting fact that could be used in other ways.

`{{{ "" +[length[]] }}}`
Is asking give me the length of nul titles, and no title is available to compute its length
Titles can not be zero in length

```
\define mylist() 1 2   56  0   3 4.5
{{{ [enlist<mylist>] +[length[]] }}}
```
This demonstrates how since space is used to delimit items of at least one alphanumeric character you are unlikely to ever get a 0 length returned.

If your coding requires a 0 returned when its empty then use
`{{{ "12" +[length[]] ~[[0]] }}}`

Remember the way we need tiddlywiki to work is often, "show nothing when there is nothing", if as the new numeric operators are indicating we now need to address "Show zero when there is nothing" or "Show zero when there is none". 

Regards
Tony

**Comment by twMat** [comment]
Thanks for a thorough explanation @AnthonyMuscio. However, regarding

 `{{{ +[length[]] }}} and {{{ "" +[length[]] }}}`

I'd expect them to behave analogous to how the, IMO conceptually similar, `count` behaves;

`{{{ +[count[]] }}} and {{{ "" +[count[]] }}}`

Both give `0` as output.

As you note, maybe it is a matter of documentation but these edge cases may be worthy of special attention to align with what people presumably would expect. Or maybe it's just me ;-)

OK, my point was only to bring this to @Jermolene 's attention before the operator is released, which I've now hopefully done, so I'm closing. Thanks.

**Comment by Jermolene** [comment]
Hi @twMat an alternate way of explaining it is that every filter run is preceded by an implicit `[all[tiddlers]]`. So, you were actually evaluating `[all[tiddlers]length[]]` which gives you the length of the title field of each tiddler.

**Comment by twMat** [comment]
> implicit `[all[tiddlers]]`

...but then not always, e.g `{{{ +[length[]] }}}` (no output). 

No need to delve into this further. I just wanted to make sure there was no bug. But one case, which is not unlikely to *incidentally* occur, is that where the preceding list is empty and there is no output (as opposed to `0`) might warrant an instance in the Examples tiddler.

**Comment by Jermolene** [comment]
Hi @twMat

> ...but then not always, e.g `{{{ +[length[]] }}}` (no output).

That will try to transclude tiddlers with the titles 18, 21, 15, 16, 64, 37, 27, 19, 60, 57, 36, 69... etc. You're only not seeing any output because none of those tiddlers exist. If you created one then you'd see it transcluded.

**Comment by Jermolene** [comment]
Hi @twMat

> ...but then not always, e.g `{{{ +[length[]] }}}` (no output).

That will try to transclude tiddlers with the titles 18, 21, 15, 16, 64, 37, 27, 19, 60, 57, 36, 69... etc. You're only not seeing any output because none of those tiddlers exist. If you created one then you'd see it transcluded.
