### ISSUE TITLE
Proposal: Link macro

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3972]
To get a *link* we must often type 

`<$link to={{!!title}}><$view field=title/></$link>`
...or even...
`<$link to='''$tid$'''><$view tiddler='''$tid$''' field="title"/></$link>`

This construct is *frequent*, it is *not intuitive* and it is a *mouthful*. And I type really bad with my mouth.

**Proposal**
A `<<link>>` macro that takes the current tiddlers title or a variable and converts it into a link. 

[Here is a version](http://linkmacro.tiddlyspot.com/) I'm using. (You can see the code there but currently no full contextual demo.)

To use a term I recently picked up, it would be *universal* ;-) and probably as useful for non-beginners as the `list-links` macro is for beginners. 

We/I have [previously touched](https://github.com/Jermolene/TiddlyWiki5/issues/1880) on this problem but in another context.

**Comment by Jermolene** [comment]
Hi @twMat first, just to note that the default target for the link widget is the current tiddler, so you can actually use `<$link><$view field=title/></$link>`.

Secondly, there is already a shortcut syntax for linking in the shape of `[[target|link text]]`.

The proposal here is for a `<<link>>` macro defined as follows:

```
\define link(variable, field:"title", label)
<$vars original={{!!$field$}}>
  <$list filter='$variable$ +[count[]prefix[0]]'>
    <$set name=lbl value="$label$" emptyValue=<<original>>>
      <$link to=<<original>>><<lbl>></$link>
    </$set>
  </$list>
</$vars>
<$list filter="$variable$" >
<$list filter="$variable$ +[addsuffix[)$]addprefix[$(]]" variable=var>
  <$set name=lbl value="$label$" emptyValue=<<var>>>
    <$link to=<<var>> ><<lbl>></$link>
  </$set>
</$list>
</$list>
\end
```

I have a few concerns:

* None of the other core macros are directly concerned with variables, in that none take parameters that are variable names. The core macros are all much simpler, working with tiddler titles and tags. I don't think that the fundamental use case of linking to a tiddler whose title is in a variable is at all universal, it's a specific idiom
* The definition of the macro is quite heavyweight, incorporating nested list widgets at one point. As far as I can tell, those constructions are necessary because the macro behaviour depends on which parameters are provided. In such cases I think it makes more sense to use separate macros for each type (e.g. `<<link-variable>>`, `<<link-field>>` etc.)

**Comment by twMat** [comment]
LinkWidget, current tid as default - thanks, I should have known.

However, my demo was only to illustrate the idea (I much appreciate your comments tho!) and `[[target|link text]]` is not useful in many situations. But the fact that the `[[...]]` syntax exists is an indication that the constructs I complain about are too complex.

Come to think of it, instead of a `<<link>>` macro, the ideal UI would be to repurpose the `[[...]]` construct so one could type e.g `[[!!title]]` or similar. That'd be really elegant.

Regardless, my request is simply for a more direct way to create a link in the contexts implied. (Surely, anybody would agree with this - !?)

**Comment by pmario** [comment]
The problem with macros is, that the built in "backlink" mechanism doesn't work anymore. so [[link]] variants should be used

**Comment by pmario** [comment]
The uni-link plugin, MAY provide a way (in the future) to create "standard links" that show, caption, subtitle, or a field. 

If you defined the "aliases" field, it is possible to create above links with aliases and "alias backlink" handling.

**Comment by Jermolene** [comment]
Hi @twMat @pmario one solution might be for the link widget to detect when it has no content, and to fallback to the default of the text of the `currentTiddler` variable. Thus, `<$link/>` would then become a synonym for `<$link to=<<currentTiddler>>><$view field="title"/></$link>`. There's plenty of precedents for widgets that use default content if they are empty, and in this particular case there's no backwards compatibility issues because `<$link/>` right now doesn't do anything.

**Comment by twMat** [comment]
@pmario thank you for your input. That sounds like a nice "maybe" plan for uni-link ;-)'

@Jermolene 

>`<$link/>`

Ingenious! I'm closing this issue to proposing this brilliant idea instead.
