### ISSUE TITLE
Request: is[draft]

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3999]
The `is` operator should have a category to enable filtering `is[draft]`.

I hit the same confusion ever time I want to prevent my various lists from updating as I'm drafting and the most intuitive solution is `!is[draft]`

Yes, there is the `!has[draft.of]` but not only is the `.of` suffix really un-obvious but the whole idea of "has" just doesn't make sense; I want to filter out the draft itself, not the tiddler that has a draft ...not to mention the tiddler that has a draft *of* (???)

**Comment by sycom** [comment]
How will tw know that a tiddler is a draft? By looking if it is the draft of another one. So seeking if it **has** the _draft.of_ field.

It's not so obvious but logical. What else would a is[draft] operator do? I know it's not a good reason since there is already is[image] and is[system] which may be filtered another way.

Maybe the is operator documentation could explain some workarounds for _draft_. And also _non existent_ (different from missing)?

**Comment by Jermolene** [comment]
Hi @sycom @twMat I'm in favour of adding an `is[draft]` operator, and, yes, it would be a synonym for `has[draft.of]`.

> And also non existent (different from missing)?

The `is[missing]` operator is badly named because it means "missing" in the sense of a title with no corresponding tiddler (ie non existent), rather than the `all[missing]` sense of tiddler titles that referenced via links but do not exist as tiddlers.
