### ISSUE TITLE
Proposal: separate content from display

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyWiki5#4016]
Hi,

Why don't separate tiddlers from tiddlywiki itself. I'm thinking in having `tiddlers.json` outside tiddlywiki.html. For avoiding firefox apocalypse in future versions. And for code readability

**Comment by twMat** [comment]
For your sake, and for the sake of 693 other issues, may I suggest that you instead post this in the [dev discussion group](https://groups.google.com/forum/#!forum/tiddlywikidev) and close this thread here. It is a very big question so it will of course need discussion. Once/if it leads to actual *actionable* points, you can propose those points here. As your proposal currently stands it will, almost certainly, just be left hanging...  :-)

**Comment by pmario** [comment]
@twMat is right. This issue isn't actionable. 

-----

What do you try to achieve?

--------

> For avoiding firefox apocalypse in future versions. 

Writing a `tiddlers.json` file will have the absolute same restrictions as writing a tiddlywiki.html file. So imo it wont help with the browser "apocalypse". All browser vendors restrict direct harddisk access in the same way!

> And for code readability

Which code? 

The HTML code is not supposed to be read by humans, since it is dynamically generated, during the tw build process. 

The javascript code is perfectly readable with every browsers debugger, since TW doesn't use any code obfuscation mechanisms during build

**Comment by somenxavier** [comment]
Thanks @pmario for clarification
