### ISSUE TITLE
optionally show tiddlers side by side

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4033]
it would be a great option to show tiddlers side by side within the story river, maybe optionally through a ControlPanel setting

**Comment by BurningTreeC** [comment]
I believe it would be enough to have a select widget that allows to select one, two or three columns

**Comment by BurningTreeC** [comment]
a toggle button like in https://burningtreec.github.io/tw5-muuri-view/ that cycles through the amount of columns would also be possible

**Comment by twMat** [comment]
In deed. A new story view. I recall old time tiddlywikian Saq Imitaz demoed a two column thing on one of the Oxford meetups.

I do think there are some more aspects to be dealt with, for example;

* How should scrolling work?
* How should navigation work? E.g where should a new tiddler open?
* Are the columns independent or is it perhaps so that they even out their height which means a bottom tiddler suddenly jumps to top in the other column. If not, what happens to the open tiddlers when you add/subtract a column?
* etc

**Comment by twMat** [comment]
As indicated in my post above, I'll repeat what I just posted in another thread:

This proposal is much to vague to be actionable. Please close and open in one of the google groups for refinement and come back with more specific issue. (Even if it is hopeless, because of a systemic fault, we should at least *try* to not add to our impressive pile of issues.)
