### ISSUE TITLE
search dropdown is hidden on narrow screens

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4038]
to reproduce: use a narrow view on tiddlywiki.com, so that the sidebar shows on top. then search for something so that the search dropdown shows up (Hello for example). It is hidden below the story river which is a bit annoying

**Comment by BurningTreeC** [comment]
I would prefer the sidebar not to overflow and to give it a z-index high enough so that its dropdowns show on top of the river

**Comment by pmario** [comment]
https://wikilabs.github.io/editions/advanced-search-plus/ ... gives you a new tab in the sidebar, that doesn't create a popup.

**Comment by twMat** [comment]
>give it a z-index high enough

Do you get this to work in the inspector tool? I don't.

One circumvention is to make sure you're on tab *Recent* which is longer than tab *Open*. Not a real solution of course.

**Comment by BurningTreeC** [comment]
>Do you get this to work in the inspector tool? I don't.

No I'm not getting this to work with simple css solutions neither... :(

**Comment by Jermolene** [comment]
This is indeed annoying. Here's a picture for posterity:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/174761/60525518-66a4d380-9ce6-11e9-9681-b013ac974334.png">

I think the problem is the scrollable widget in `$:/core/ui/PageTemplate/sidebar`. We don't need the scrollable at all in compact mode. I wonder if we might be able to disable it via CSS? Otherwise we'll have to attack the wikitext template...

**Comment by BurningTreeC** [comment]
My "solution" is revealing a `div` instead of the `scrollable` widget on narrow screens using the `dynaview plugin` ... but that's nothing for the core ...

**Comment by amreus** [comment]
If this is related to #6440, can it be closed also?

**Comment by Jermolene** [comment]
Thanks @pmario
