### ISSUE TITLE
filters behave differently when used in list widget and {{{ transclusion

### ISSUE THREAD

**Issue by Skeeve** [Jermolene/TiddlyWiki5#409]
Please compare these 2 examples:

   <$list filter="[text/FireFox|jEdit/]">
   <$link><$view field="title"/></$link>
   </$list>

vs.

   {{{ [text/FireFox|jEdit/] }}}

The second one termintes with "Filter error: Unterminated regular expression in filter expression" because the filterString is cut off at the pipe.

**Comment by tobibeer** [comment]
Is this still relevant or are we moving about deprecated territory?

**Comment by Jermolene** [comment]
The confusion here is that you can't use a pipe `|` within the wikitext transclusion syntax without it being interpreted as the template separator. It's essentially the same issue as not being able to link to a tiddler with a pipe in it with `[[my|pipe|tiddler]]`. So I guess it's a gotcha rather than a bug.

**Comment by pmario** [comment]
>... So I guess it's a gotcha rather than a bug.

so may be closed with a `wontfix`

**Comment by Skeeve** [comment]
I leave it to @Jermolene to close or not. If "wontfix", I'd suggest to put a new(?) "Issues and Quirks" tiddler discribing all the "Gotchas" we found.

**Comment by pmario** [comment]
@Jermolene ... close ... it's not really a bug and won't be fixed!?

**Comment by Jermolene** [comment]
Thanks @pmario
