### ISSUE TITLE
Explore using JSON Pointers to reference data within data tiddlers

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#411]
The existing RFC 6901 provides a standard way to encode pointers that de-reference items within a JSON object:

http://tools.ietf.org/html/rfc6901

The format is pretty simple (apart from the inevitable encoding gotchas). Pointers are a list of tokens each preceded by `/`. The remainder of each token gives the property name or array index of the ancestor items.

For example, given this JSON:

```
{
"one":"first",
"two":[
"second",{"third":"fourth"}
]
}
```

The following references resolve as follows:

```
/one --> first
/two/0 --> "second"
/two/1/third --> "fourth"
```

We could adopt this syntax in a more or less backwards compatible way.

**Comment by pmario** [comment]
Broken link it OP is: https://datatracker.ietf.org/doc/html/rfc6901 now

**Comment by pmario** [comment]
@Jermolene ... Since we have the new [JSON-operatos](https://tiddlywiki.com/prerelease/#jsonextract%20Operator:%5B%5Bjsonextract%20Operator%5D%5D%20%5B%5Bjsonindexes%20Operator%5D%5D%20%5B%5Bjsontype%20Operator%5D%5D%20%5B%5Bjsonget%20Operator%5D%5D) in v5.3.0 imo this issue is obsolete and should be closed

**Comment by Jermolene** [comment]
Thanks @pmario
