### ISSUE TITLE
Don't store username in wiki

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4152]
A username is, arguably, specific to a user. I therefore propose that the username is not permanently stored in the wiki when saving. Instead it might be only *locally* saved, perhaps by means of a cookie or maybe the mechanism in local storage plugin.

To use a *$:/temp* tiddler can cause problems for the (not unlikely) use case where a wiki is public and designed to hide all "admin matters", including access to where the username is set.

Another use case is a multi user wiki featuring different appearances or behaviours based on username. The default username should be empty rather than what happens to be the name when the wiki was last saved.

**Comment by Jermolene** [comment]
Hi @twMat tiddlers starting `$:/status/` are not synced (see $:/config/SyncFilter), but they are saved when using a saver (see $:/core/save/all). In fact, if you look at the latter filter you'll see that pretty much the only thing that doesn't get saved through a saver is `$:/state/popup/*` (temp and state tiddlers do get saved).

**Comment by twMat** [comment]
Thanks, but I'm afraid I don't know what to do with this information. 

Are you saying user names are not stored when uploading to a server (i.e "syncing")? Maybe my investigations of whether the user name is stored results in "yes, they're stored" only because I'm saving to Tiddlyspot... and this somehow saves instead of syncs?

Does my OP not make sense?

**Comment by Jermolene** [comment]
Hi @twMat apologies there are several points:

* Current policy is that we save pretty much everything apart from `$:/state/popup/*` tiddlers when saving with a saver. So petitions to exclude further tiddlers need a rationale for breaking that policy and treating those tiddlers differently
* Tiddlers starting `$:/status/` are not synced (even though they are saved). This prevents any problems with one users status somehow getting synced to another user
* Saving snapshots including `$:/status/` tiddlers is often useful because it preserves the wiki as it was seen

Generally, it sounds like you've got a specific use case in mind, and that that use case can be satisfied by using a custom save filter. I don't see the rationale for changing the defaults for everyone.

**Comment by twMat** [comment]
OK, to succinctly summarize this: The two specific, but not unlikely, use cases...

* a public and designed to hide all "admin matters", including access to where the username is set.
* a multi user wiki featuring different appearances or behaviours based on username

...do not justify a changed treatment of the username.

Fair enough. Thanks for replying.
