### ISSUE TITLE
@@ does not apply to shortform transclusion

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4162]
`@@` styling does not apply under certain conditions:

This most basic case - which is also the reason for the issue - does **not** work:
```
@@.myclass
{{tid}}
@@
```
This **does** work (so it is not a matter of "nested shortforms like [[{{...}}]] don't work")
```
@@.myclass
{{tid}} foo
@@
```
This also **does** work
```
@@.myclass
<$transclude tiddler=foo />
@@
```
I was expecting the same behaviour for all cases.

**Comment by Jermolene** [comment]
When used in block mode the `@@` syntax doesn't quite do what one might expect. It doesn't create any elements in the DOM, but instead uses a brittle mechanism to assign the classes to any immediately contained children of the `@@` construction.

That way of working is so that it can be used to apply classes to constructions that wouldn't otherwise allow them. For example:

```
@@.myClass
* one
* Two
@@
```

results in the following HTML:

```
<ul class="myClass">
<li>one</li>
<li>Two</li>
</ul>
```

To explain the three cases you quote.

The first one doesn't work because the transclude widget doesn't generate any DOM elements itself. Remember that `@@` only acts on its immediate children:

```
@@.myclass
{{tid}}
@@
```

This one works because `{{tid}} foo` would be parsed as a paragraph with a `<p>` tag, and the class would be given to that tag.

```
@@.myclass
{{tid}} foo
@@
```

This last one works for the same reason: a `<p>` tag is automatically wrapped around the content. You'll notice that it stops working if you add another line break before the closing `@@` because it then gets recognised as a block mode entity, and doesn't get wrapped as a paragraph.


```
@@.myclass
<$transclude tiddler=foo />
@@
```

**Comment by twMat** [comment]
Thank you for your detailed reply! 

If `{{tid}} foo` gets wrapped in a `<p>`... couldn't we make this the case for only `{{tid}}` as well?


And do I understand this consequence right then:

1. `@@{{}}...` doesn't work --> use transcludewidget instead
2. ...but this requires an additional style class!

i.e:

```
@@.myclass
*aaa
@@
```
can be styled with

`.myclass {background:red}`

But for transclusion (and now using the transcludewidget):

```
@@.myclass
<$transclude tiddler=tid mode=block/>
@@
```
**...but this invalidates the** `.myclass {background:red}` and instead one has to do 

`.myclass > ul {background:red}`

**Comment by Jermolene** [comment]
> If `{{tid}} foo` gets wrapped in a `<p>`... couldn't we make this the case for only `{{tid}}` as well?

Transclusion doesn't generate any DOM elements so it's not clear what the class would be assigned to.

>  instead one has to do 

Your conclusions look reasonable.

**Comment by Jermolene** [comment]
I should add that I now think that the block mode `@@` syntax was a mistake. The intention was to craft a modifier that could be applied to any contained components. But the resulting rules are hard to work with, and now I think it would have been better to have simply extended the list syntax to allow for a class to be assigned to the `<ol>` or `<ul>`.

In your case, it looks like you want to apply a class to transcluded content, and it is hard to imagine a general mechanism by which that could be done. I'd be inclined to move to HTML syntax if you can.

**Comment by twMat** [comment]
>Transclusion doesn't generate any DOM elements so it's not clear what the class would be assigned to.

Well, in this:
```
@@.myClass
{{}}
@@
```
Could the `@@` be made to *create* a div with `class="myClass"` surrouding the `{{}}`?

**Comment by pmario** [comment]
>Could the @@ be made to create a div with class="myClass" surrouding the {{}}, i.e first it detects that there is a transclusion inside?

IMO not in a backwards compatible way.

**Comment by Jermolene** [comment]
> Could the `@@` be made to *create* a div with `class="myClass"` surrouding the `{{}}`, i.e first it detects that there is a transclusion inside?

As @pmario notes there would be a backwards compatibility problem, and a special case for users to learn before they could take advantage of it.

**Comment by twMat** [comment]
OK, so that makes the issue a "wont' fix" then, right?

**Comment by Jermolene** [comment]
> OK, so that makes the issue a "wont' fix" then, right?

Yes :)

**Comment by twMat** [comment]
OK, thanks.
