### ISSUE TITLE
Cached version loads instead of latest

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4239]
Very problematic: When using Firefox it seems to often open an old cached file of my tiddlyspots instead of the latest version. This makes it very easy to lose several days of work. To get the latest version of my wiki to load I need to reload and keep Shift pressed during load but it is very easy to miss this and work on and then overwrite the real last version.

I believe it typically happens if FF was shut down inappropriately such as from some annoying Win10 update or if I restart the computer without manually shutting down FF. I believe the problem existed in 5.1.19 but I'm not 100% sure. As noted, it happens on my tiddlyspots - I don't know if it happens for other wikis also.

I assume it is a cache matter. Is there a way to block the browser from loading TW from cache?

**Comment by pmario** [comment]
It seems that's a FF problem. ... If you save a TW to TSpot, then close the browser without closing the tab. Reopen the browser, the "old" file is loaded. 

There is no way for TW to change this. 

This behaviour is not new. ... I think I know this problem way before FF 57.

**Comment by twMat** [comment]
>There is no way for TW to change this.

But why is it limited to tiddlyspot then - or is it not? And if it is a general FF+TW problem then shouldnt more people yell about it?

**Comment by pmario** [comment]
I think gitlab and github saver will have the same problem, but I didn't test them yet. I'm using a completely different mechanism to create TW gh-pages.

**Comment by hoelzro** [comment]
I've had the same problem as long as I can remember using the Node server.  I'm wondering if there's a header or something that can be set to discourage this behavior.

**Comment by pmario** [comment]
>I've had the same problem as long as I can remember using the Node server. I'm wondering if there's a header or something that can be set to discourage this behavior.

I think, that's a different problem. ... The node server doesn't refresh the wiki, if you changed `.tid` files with an external editor. ... You have to restart node. 

The OP is about a "browser refresh", reloading the cache, which won't help with node.

**Comment by hoelzro** [comment]
I'm familiar with that issue as well, but that's not what I'm talking about.  The behavior I'm talking about it this:

  * I'm using my wiki regularly
  * I modify tiddler A in the browser
  * I restart my browser
  * My wiki loads with the pre-modification contents of tiddler A

Is that what @twMat is describing, or am I misunderstanding?

**Comment by twMat** [comment]
>Is that what @twMat is describing

yes

**Comment by hoelzro** [comment]
I did some sleuthing on this, and one solution I found would be to set the `Cache-Control` header to `no-store` - this prevented both Firefox and Chrome from storing cache files for my test page on disk, and thus loading them upon browser restart.

@Jermolene Do you think that setting that header in the Node daemon makes sense?  Otherwise, would it make sense to prototype as a plugin for people to try out to see if anything bad happens first?  I don't exactly know the best way to implement this as a plugin, but I had an idea for a "server-middleware" module type that would allow such modules to tweak the request/response to meet their needs - that would probably merit its own issue, though.

**Comment by twMat** [comment]
@hoelzro - are you getting the problem also with Chrome? Because I only had this problem with FF which forced me back to Chrome again (them two being the only browsers I've tried).

**Comment by hoelzro** [comment]
@twMat Interestingly, I was not able to reproduce this in either browser just now with a Node-based wiki, so maybe there's something going on with my Firefox configuration, or maybe Firefox has changed its underlying behavior?  I'll have to dig in further.

**Comment by twMat** [comment]
Well how about that; I just had a Chrome freeze and had to end it via Task Manager. Upon restart, TW opens old cached page... :-/

**Comment by dubiouscript** [comment]
> I assume it is a cache matter. Is there a way to block the browser from loading TW from cache?

developer-tools > network > ( disable-cache: toggle option)

---
i haved also had some problem with cache !
while using the git lab saver (https://github.com/Jermolene/TiddlyWiki5/pull/3931)
and editing core template $:/core/templates/tiddlywiki5.html

- because editing this template requires a refresh 
of the page for the changes to 'load' with the recreated page 

but also because 
- before the changes that are save to the git lab repo
 become available the "gitlab page's" pipeline  .gitlab-ci.yml  "job" 
must first finish and publish the assets in the "public" folder 
---
https://github.com/Jermolene/TiddlyWiki5/issues/4239#issuecomment-528251489
> I think gitlab and github saver will have the same problem, but I didn't test them yet. I'm using a completely different mechanism to create TW gh-pages.

afaik only in some seemingly obscure case's when reload is required 
is appears to be a problem and caused mostly
because it is compounded by the need for the svr 'pages publish' process 
to complete before the latest version can be loaded 
even when using 'disable cache' from the dev tools! =s

**Comment by twMat** [comment]
Possible solution? - When saving, write/load both to storage and to cache! Is this possible?

**Comment by pmario** [comment]
> When saving, write/load both to storage and to cache! Is this possible?

No. The cache is handled by the browser. With the dev-tools you can disable the cache for testing purpose. ... The dev-behaviour can't be triggered by TW, because there is no API to do so.

**Comment by pmario** [comment]
@twMat ... Do we need to keep this issue open? ... IMO we **can not change** the browser behaviour from within TW. 

I did find a blog-post, that mentioned some browser config and AddOn possibilities: https://geekflare.com/disable-cache-in-browsers/ ... But I'm not sure how good they are.

**Comment by twMat** [comment]
@pmario - thanks.

I'm closing this mainly because Tiddlyspot has been mostly replaced with Tiddlyhost where I have not experienced this problem. I also don't know if the problem at all still persists on TiddlySpot (which still exists but, again, is mostly replaced by TH)

Thanks everyone who shared ideas.
