### ISSUE TITLE
[docs] Clean out "New in: 5..." alerts

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4269]
I think it is fair to expect users to update their wikis so IMO it doesn't make sense to alert that some feature was introduced more than, say, 2 updates ago. I.e the gray pills alerting "NEW IN: 5.1.14" are more a distraction than information. Anyone interested in more detailed history can study the version logs.

**Comment by Jermolene** [comment]
My intention was originally to suppress the "from-version" markers after two or three versions had elapsed. However, I've noticed several times since then that it's surprisingly common for people in the community to miss changes, perhaps because the release notes are pretty long for some releases. So my thinking now is to keep the markers for longer so that they draw attention to new features that people might have missed. When we move to v5.2.x would perhaps be the point at which we'd retire all the v5.1.x markers.

**Comment by twMat** [comment]
Fair enuff.
