### ISSUE TITLE
How many pictures in a Tiddlywiki

### ISSUE THREAD

**Issue by marypo** [Jermolene/TiddlyWiki5#4301]
Hi, after checking a lot of the sources listed at tiddlywiki.com I'd really appreciate some more information on handling images in a Tiddlywiki. With some of my wikis, I'd prefer to embed all my pictures and not move them to an extra folder. **But my wikis already crash with 5-6 photos in a tiddler.** So please tell me:
- How many pictures (and files too) am I allowed to embed (per tiddler/per wiki)?
- What syntax is best for embedding?
- Is it possible to implement a native picture gallery? The plugins are no good.
Thanks for listening.

**Comment by Jermolene** [comment]
Hi @marypo 

> How many pictures (and files too) am I allowed to embed (per tiddler/per wiki)?

The number of images that can be comfortably accommodated in a single file TiddlyWiki depends on the resources of the browser, and the size of the images. If embedding images is important to you, it may be worth exploring whether you can reduce their size using a tool like https://squoosh.app/ that compresses and resizes images.

> What syntax is best for embedding?

Generally it's more convenient to use the `[img[image-title]]` syntax because it can be easily extended with size attributes `[img width=50%[image-title]]`. Sometimes it's better to use the ordinary `{{image-title}}` transclusion syntax because it can be used with both images and other text tiddlers.

> Is it possible to implement a native picture gallery? The plugins are no good.

I've seen a few examples. It's probably worth asking on the main discussion group:

http://groups.google.com/group/TiddlyWiki

**Comment by sukima** [comment]
If you are interested I have a a couple of examples. My [main site has photography](https://tritarget.org/#Photography) in it. Because I didn't want a massive download on initial page view I store the images on another server like a CDN and use TiddlyWiki's `_canonical_uri` field to externally link to them. This works great.

Then again I also had [some TiddlyWikis that were all images](https://tritarget.org/wikis/minecraft/) and I wanted them in a single file so they could be viewed offline. Hope this helps.

**Comment by AnthonyMuscio** [comment]
Of course lets not forget if not dealing with photos, svg images are a good alternative for icons and consume less space, using the favicons font is another method, 

But with real raster images and you can also externalise images (but it is no longer a single file wiki)

**Comment by pmario** [comment]
@Jermolene -- IMO can be closed. -- No further feedback from user. So we can assume the answers where OK

**Comment by Jermolene** [comment]
Thank you @pmario
