### ISSUE TITLE
default new tiddler tags

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4303]
Hi there,
I'd like to create a small interface for default tags for the `new-tiddler`, `new-journal`, `new-image`, `new-here` and `new-journal-here` actions

There should be a tiddler like `$:/language/DefaultNewTiddlerTags` that should store the default tags in its `list field`. The `list field` is convenient because it will update when tiddlers are being renamed.

I'd like to show the default tags above the search panel in the sidebar so that it's clear that new tiddlers are tagged with those tags.

A little interface to add/remove tags should also be there.

This would be a very handy addition, what do you think?

**Comment by BurningTreeC** [comment]
![Bildschirmfoto vom 2019-10-12 11-19-53](https://user-images.githubusercontent.com/9407182/66698886-3c4db380-ece2-11e9-8d88-336cf3790910.png)

**Comment by Jermolene** [comment]
Hi @BurningTreeC 

> I'd like to create a small interface for default tags for the `new-tiddler`, `new-journal`, `new-image`, `new-here` and `new-journal-here` actions

Good idea.

> There should be a tiddler like `$:/language/DefaultNewTiddlerTags` that should store the default tags in its `list field`. The `list field` is convenient because it will update when tiddlers are being renamed.

Another possibility is to use the `tags` field, which might make it easier to reuse the existing tag editor in the configuration UI.

> I'd like to show the default tags above the search panel in the sidebar so that it's clear that new tiddlers are tagged with those tags.

> A little interface to add/remove tags should also be there.

The obvious location is the first tab of the control panel but I understand the motivation to make it more accessible. I think a top level sidebar segment is problematic as a default position because the placement will cause readers to think that the tags apply to the wiki as a whole.

I'd suggest proceeding with the simple control panel UI for the moment, and address the problem of making it more accessible later.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/174761/66700270-92245a80-ece6-11e9-9ce0-3d06b6ea0396.png">

**Comment by BurningTreeC** [comment]
>Another possibility is to use the tags field, which might make it easier to reuse the existing tag editor in the configuration UI.

I tried to avoid the tags field in order that the `$:/language/DefaultNewTiddlerTags` tiddler wouldn't show up in too many different places

**Comment by BurningTreeC** [comment]
... but it's true that it's convenient to reuse `$:/core/ui/EditTemplate/tags`

**Comment by BurningTreeC** [comment]
Would you mind to make the PR? Your mockup already looks good!

**Comment by Jermolene** [comment]
Just to note that @BurningTreeC contributed #4307 to fix this.

**Comment by AnthonyMuscio** [comment]
Is there an issue for the changes ?
> for the new-tiddler, new-journal, new-image, new-here and new-journal-here actions

I recently started using a new tiddler title of "New {{$:/SiteTitle}} tiddler" and it works quite well after renaming the site tile on a new wiki, and also helps you see what wiki you are in, if you use more than one.

**Comment by BurningTreeC** [comment]
closing this issue because #4314 is merged
