### ISSUE TITLE
Wrong reference to "Firefox Apocalypse" - should be "TiddlyFox Apocalypse"

### ISSUE THREAD

**Issue by kosi2801** [Jermolene/TiddlyWiki5#4399]
There is an invalid reference to "Firefox Apocalypse" at

https://github.com/Jermolene/TiddlyWiki5/blob/28b91613019d9470eecd2c0a6d847922ab32fac9/editions/tw5.com/tiddlers/definitions/TiddlyFox.tid#L9

As far as I can guess, this should probably reference "TiddlyFox Apocalypse" instead.

**Comment by AnthonyMuscio** [comment]
This is historical, it was changes to firefox and subsequently all browsers that stopped tiddlyfox working. TiddlyFox continued working on older versions of Firefox but the same method could not be reworked to the new version. 

Timimi now does the same as TiddlyFox did, perhaps even better, so perhaps no reference at all is required to any apocalypse. In fact it never turned into an apocalypse because it inspired a lot of work developing work arounds which have proved to help tiddlywiki in the long run.

Regards
Tony

**Comment by Jermolene** [comment]
Thanks @kosi2801 fix upcoming.
