### ISSUE TITLE
Extend sign op with arguments to work as greaterthan/lessthan/equals

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4427]
I'm not sure why numeric greaterthan, lessthan and equals were not part of the math bonanza some time back but here's perhaps an alternative:

**Proposal**
Extend `sign[]` to accept arguments `+`,`-`,`0` to give output same as input if *true* and no output if  *false*. Also enable operator negation.

**Examples**
`[[1.6]sign[+]]` --> `1.6`
`[[1.6]sign[-]]` --> `<no output>`
`[[1.6]sign[0]]` --> `<no output>`
negation
`[[1.6]!sign[+]]` --> `<no output>`
`[[1.6]!sign[-]]` --> `1.6`
`[[1.6]!sign[0]]` --> `1.6`

**Comment by Jermolene** [comment]
Hi @twMat we should probably add the numeric comparison operators. I think I deferred them so that we could consider the best way for them to work. With the success of the `match`, `then` and `else` operators, I think `[[5]greaterthan[4]]`  should return `5` and `[[5]greaterthan[6]]` should return an empty list.

**Comment by twMat** [comment]
Good to hear.
