### ISSUE TITLE
Discussion: Default behavior of line breaks

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyWiki5#443]
Hello everybody,

First of all thanks to @drsprite who pointed out the carriage return behavior,
you can find the first discussion here: https://github.com/Jermolene/TiddlyWiki5/issues/275

I'm opening this one today to see if we can discuss about how the default behavior should be:

> 1) When typing regular text and you hit "return" key once it does nothing (like now in 5.0.7 version) you have to hit it twice to actually "jump" a line. You cannot do a simple carriage return without the use of paragraphs/code blocks/hard line breaks.
> 
> 2) When you hit "return" key once it would do a simple carriage return like in any regular text editor without the need of paragraphs/code blocks/hard line breaks.

It seems like the same thing happened within <$list> it always leaves one empty line between two other (or is it a padding issue something like that?). Anyway it is taking more place than needed imo.

First we have to ask @Jermolene if it is even possible and then see if the majority of users is interested in changing default behavior or if they would rather leave it the way it is.

Thank you for your attention,
+++ Spangenhelm +++

**Comment by carugnom** [comment]
Just watching these old posts... is really so hard to get TW5 to render linebreaks or newlines as expected ?
I mean, I don't want to mess my text with triple quote blocks. I don't want to have to 'remember' to write that way because that parts are just simple text.
It looks ugly. Also I can't mix it with other markup.
Why just don't make newlines render as expected ?
In Dokuwiki is what plugins like XBR do for example.

**Comment by danielo515** [comment]
> Why just don't make newlines render as expected ?

That is your biased  point of view. People used to markdown will expect a different behavior. Rules are rules, and they are never reasonable for everyone

**Comment by carugnom** [comment]
Well I like all these simple markup languages because the basic idea is to
let the user write as few markup as posible.
Of course it makes sense to use markup for headers, tables and other places
where the text looks different.
The only point I dislike is being forced to use markup to get newlines,
because I already can make newlines in original the text.
We see a number of people asking for this feature also, right ? So I think
it would be good to have support for it.


2017-06-24 12:13 GMT-03:00 Daniel Rodríguez Rivero <notifications@github.com

**Comment by danielo515** [comment]
Well, is as simple as a custom parsing rule. Should be possible, but not for the default behavior

**Comment by carugnom** [comment]
Aha, good to know. I'll search for how to create such custom parsing rule.
Thank you !

2017-06-25 11:17 GMT-03:00 Daniel Rodríguez Rivero <notifications@github.com

**Comment by pmario** [comment]
If you really want to use GFM, you should use the [markdown-it plugin](https://wikilabs.github.io/editions/nightly/markdown-it.html), that I created. It has a GFM mode, which should pretty much do, what you want, in terms of linebreaks. 

The default setting is "commonmark" mode which uses "2 spaces at the end of the line to indicate a <br>". It's strange but would work too. see: 2nd paragraph in the "Test" tiddler. 

It is still ALPHA, since there is no html sanitation yet. So copy/pasting html code isn't safe atm. But be aware, that markdown misses many features of the TW syntax. 

----------------------

>Aha, good to know. I'll search for how to create such custom parsing rule. Thank you !

IMO it's not that simple. ... 

 - You don't want to use `<br>` which is 4 chars and does exactly what you want.
    - So it has to be less than 4 chars 
 - You don't want to use tripple-doublequotes .. aka "hard linebreak" block
    - It has to be less than 3 chars. eg: 2 or 1
    - so [all those existing formatting chars](http://tiddlywiki.com/#Transclusion%20in%20WikiText:%5B%5BTransclusion%20in%20WikiText%5D%5D%20%5B%5BTables%20in%20WikiText%5D%5D%20%5B%5BStyles%20and%20Classes%20in%20WikiText%5D%5D%20%5B%5BParagraphs%20in%20WikiText%5D%5D%20%5B%5BLinking%20in%20WikiText%5D%5D%20%5B%5BHard%20Linebreaks%20in%20WikiText%5D%5D%20%5B%5BDashes%20in%20WikiText%5D%5D%20%5B%5BFormatting%20in%20WikiText%5D%5D) are gone. Since they would create conflicts.
 - There isn't much left. ... We used the nice combinations already ;)

**Comment by carugnom** [comment]
So.... the simple parsing rule is not so simple uh?
I don't know how parsing rules work in tw5, but isn't it as easy as
replacing \n with <br> ?
Any link to learn about parsing rules ?

2017-06-25 12:17 GMT-03:00 Mario Pietsch <notifications@github.com>:

**Comment by tobibeer** [comment]
> The default setting is "commonmark" mode which uses "2 spaces at the end of the line to indicate a <br>". It's strange but would work too. see: 2nd paragraph in the "Test" tiddler.

Ha! I think it should be possible and would make sense to:

1. allow for a setting to have this apply to parsing wikitext, e.g. "transform trailing blanks more than X into linebreaks", e.g. defaulting to 1
2. to extend the parser to translate any trailing blanks at the end of a line into additional newlines `<br>`

That way, you can have it both ways:

1. you can use as many newlines in wikitext to separate concerns
2. but also control how many linebreaks are applied in the representation

**Comment by pmario** [comment]
commonmark uses exactly 2 spaces. ... and eats the rest. We shouldn't do different here. 

Because of [What if](https://groups.google.com/forum/#!topic/tiddlywiki/iC1ZNZHVU8A) ...

I'd really like to get this going. ... even if we would break the existing TW syntax, which is my biggest concern. IMO mardown "did take over the world"

**Comment by Lioric** [comment]
I'm currently using:

```
.tc-tiddler-body {
    white-space: pre-line;
}

.tc-tiddler-preview-preview {
    white-space: pre-line;
}
```

If buttons or other widgets need paragraphs to be rendered correctly I will modify them to remove the dependency, so they are displayed correctly in the tiddler contents area.

But this should not affect the UI or any other area than the tiddler contents

**Comment by carugnom** [comment]
Sorry... where do you write that code ?
Thanks !

2018-02-25 0:33 GMT-03:00 Lioric <notifications@github.com>:

**Comment by Lioric** [comment]
The simpler way is to create a tiddler with the tag `$:/tags/Stylesheet` and put those styles there

**Comment by Lioric** [comment]
Finally I did find some time to test several implementation to support newlines in a natural writing style. 

The idea is to touch as less code paths as possible (we are looking switch to a TW5 mainline instance and refactor our modifications to the outside or push our changes in mainline)

So far this is working nicely with my dataset (I'm sure there are lots of corner cases, though):

```javascript
TextNodeWidget.prototype.render = function(parent,nextSibling) {
    this.parentDomNode = parent;
    this.computeAttributes();
    this.execute();
    var text = this.getAttribute("text",this.parseTreeNode.text || "");
    text = text.replace(/\r/mg,"");

    var textNode = this.document.createTextNode(text);

+    if(text && text !== '\n' && parent.nodeName === "P") {
+        var domNode = this.document.createElement("span");
+        domNode.style.whiteSpace = "pre-line";
+        domNode.appendChild(textNode);
+        textNode = domNode;
+    }

    parent.insertBefore(textNode,nextSibling);
    this.domNodes.push(textNode);
};

```

**Comment by carugnom** [comment]
Yessssss it worked !!!

So many time asking for this and finally 5 lines of code made it work !

Thank you !!!

2018-02-25 20:25 GMT-03:00 Lioric <notifications@github.com>:

**Comment by PengjuYan** [comment]
> I'm currently using:
> 
> ```
> .tc-tiddler-body {
>     white-space: pre-line;
> }
> 
> .tc-tiddler-preview-preview {
>     white-space: pre-line;
> }
> ```
> 

Thank you @Lioric, I've been looking for this for years (!!) and it seems working well (I'll see whether there any side effects).

**Comment by PengjuYan** [comment]
> I'm currently using:
> 
> ```
> .tc-tiddler-body {
>     white-space: pre-line;
> }
> 
> .tc-tiddler-preview-preview {
>     white-space: pre-line;
> }
> ```
> 
> If buttons or other widgets need paragraphs to be rendered correctly I will modify them to remove the dependency, so they are displayed correctly in the tiddler contents area.
> 
> But this should not affect the UI or any area other than the tiddler contents

Unfortunately, it DOES has side effects. My control panel looks like this now:

<img width="903" alt="Screen Shot 2019-07-27 at 8 40 02 PM" src="https://user-images.githubusercontent.com/13349414/61994579-cfe1f180-b0ae-11e9-92a9-4804351bc71d.png">

**Comment by pmario** [comment]
also see: https://tiddlywiki.com/#Hard%20Linebreaks%20with%20CSS%20-%20Example:%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D

**Comment by PengjuYan** [comment]
> also see: https://tiddlywiki.com/#Hard%20Linebreaks%20with%20CSS%20-%20Example:%5B%5BHard%20Linebreaks%20with%20CSS%20-%20Example%5D%5D%20%5B%5BHard%20Linebreaks%20with%20CSS%5D%5D

Thank you very much @pmario, that's exactly what I want!

I guess the next mission for me is to find a way to automatically remove all the `'''` from my poem tiddlers. Any clues?

**Comment by twMat** [comment]
>I guess the next mission for me is to find a way to automatically remove all the ''' from my poem tiddlers. Any clues?

@PengjuYan  The easiest way is probably to open the wiki file in an external editor, e.g Notepad++ and do a search for that string and replace with "nothing" or some row break character.

**Comment by PengjuYan** [comment]
@twMat Thank you. That's probably the easiest way.

**Comment by pmario** [comment]
@PengjuYan ... BUT make backups first!! ;)

**Comment by defterade** [comment]
I've been pulling my hairs out trying to get this to work by default on all newly created tiddlers without having to add additional text or breaking other UI elements. My use-case is similar to that of @FrinalFrantasy, and I'm not willing to change the way I write my notes for such a seemingly trivial issue. It's the only thing stopping me from using TiddlyWiki.

> Finally I did find some time to test several implementation to support newlines in a natural writing style.

This appears to work perfectly. No UI issues so far. Thank you!

For others: you need to add those 6 lines to `$:/core/modules/widgets/text.js`. Don't forget to remove the pluses at the beginning of each line.
