### ISSUE TITLE
Bug: The StaticRiver exporter does not actually export any tiddler content

### ISSUE THREAD

**Issue by lucible** [Jermolene/TiddlyWiki5#4445]
Currently, `$:/core/templates/exporters/StaticRiver` does not export any tiddlers &/or their content when used with `--rendertiddler` to create a wiki snapshot with internal links. It results in an html page with included custom CSS, but no content.

Because `$:/core/templates/alltiddlers.template.html` is simply a reference back to the `StaticRiver` exporter, it is also broken.

To reproduce, use this command: `--rendertiddler $:/core/templates/exporters/StaticRiver alltiddlers.html text/plain` as listed in [Generating Static Sites with TiddlyWiki](https://tiddlywiki.com/static/Generating%2520Static%2520Sites%2520with%2520TiddlyWiki.html).

**Comment by lucible** [comment]
Hm, after poking around the documentation some more, it would seem this and #4448 were a misunderstanding on my part about how the render command & templates work together due to the incorrect documentation at _Generating Static Sites with TiddlyWiki_.

It would seem that `--rendertiddler "$:/core/templates/exporters/StaticRiver" test.html text/plain "" exportFilter "[tag[example]]"` -- syntax gotten from the [RenderTiddlerCommand](https://tiddlywiki.com/static/RenderTiddlerCommand.html) documentation -- does indeed produce the expected results.

However, `$:/core/templates/alltiddlers.template.html` is still broken when used with the syntax above, and appears to run infinitely without completing.

**Comment by Jermolene** [comment]
Hi @lucible it sounds like you've figured it out -- the export mechanism is separate from the saving mechanism, and it is intentional that it doesn't respect the same filters because there are alternate ways of specifying the payload for an export. As you've probably found, the docs could be improved and help in that regard is very welcome!

The command `tiddlywiki editions/prerelease/ --rendertiddler $:/core/templates/alltiddlers.template.html alltiddlers.html text/plain` works for me, but it is entirely possible that it could hang if used on a wiki that has tiddlers that recurse infinitely.

**Comment by saqimtiaz** [comment]
@Jermolene @lucible this issue can be closed.

**Comment by Jermolene** [comment]
Thanks @saqimtiaz
