### ISSUE TITLE
Advanced search, searches itself 

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4449]
- go to tiddlywiki.com
-open the $:/AdvancedSearch
-in the Filter tab enter `[all[tiddlers+shadows]search:text[hirad]]`
-TW shows 1 matches `$:/temp/advancedsearch`

But this wrong, it searches its temp tiddler and it should be avoided

**Comment by kookma** [comment]
This is a gentle reminder!

**Comment by BurningTreeC** [comment]
@kookma I believe this is the expected filter output

**Comment by kookma** [comment]
@BurningTreeC  does it make sense to show the temporary tiddler used by search box itself?

**Comment by pmario** [comment]
> does it make sense to show the temporary tiddler used by search box itself?

IMO Yes. Otherwise it's really hard to find stuff in "system" tiddlers. They are not shown in the sidebar search. ...

eg: have a look at the "filtered" tab and look in the dropdown. There is a predefined filter: "Tiddlers in Story river, excluding $:/AdvancedSearch" ... The filter is: `[list[$:/StoryList]] -$:/AdvancedSearch`  ...

So if you don't want to see something there, you'll need to remove it.

**Comment by BurningTreeC** [comment]
> @kookma I believe this is the expected filter output

In my opinion yes, too

**Comment by kookma** [comment]
@BurningTreeC, @pmario Thank you!
