### ISSUE TITLE
Making it easier to tell if the last save was successful

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#449]
If one misses the "saved wiki" notification it is hard to be certain that a save attempt succeeded.

See the discussion here:

https://groups.google.com/d/topic/tiddlywiki/ije07dVJOtk/discussion

**Comment by pmario** [comment]
@Jermolene ... This issue is from TW beta days. According to GG dicsussion about v5.0.8. ... IMO We do have an "unsaved" indicator with the "red save button" and the changed icon. 

There is also a plugin from tiddlytools, that allows to log save messages. See: https://tiddlytools.com/#TiddlyTools%2FSaveChanges%2FInfo   

So IMO this one can be closed.

**Comment by Jermolene** [comment]
Thanks @pmario
