### ISSUE TITLE
Extend removeprefix op with :suffix to make less greedy

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4520]
Ref [help request](https://groups.google.com/d/msg/tiddlywiki/3ng6jYIYeYE/FTbpRs5nBwAJ), i.e someone wanting to remove various prefixes *if* the titles have any of those prefixes.

**Proposal**: Extend `removeprefix[]` (and equivalent operators) with an operator suffix/flag to allow passing through titles that don't have the prefix at all. I.e make the operator less greedy.

Current: `"foo bar baz +[removeprefix[b]]" --> ar az`
Proposed: `"foo bar baz +[removeprefix:lazy[b]]" --> foo ar az` 

That way, the person wanting to remove prefixes can do so by "testing" them like so:

`{{{ [<currentTiddler>removeprefix:lazy[prefix1]removeprefix:lazy[prefix2].....] }}}`

**Comment by ericshulman** [comment]
In a discussion earlier today (https://groups.google.com/forum/#!topic/tiddlywiki/M8PFeakbp6U), there was a "problem" caused by the use of [removeprefix[...]].

The OP had assumed that this just removed the specified leading text from the items being filtered when, in fact, it also does the matching action of [prefix[...]]

However, it would be helpful if there was a filter actually did *just* remove leading (or trailing) text,
without regard to any matching.  One example of a filter that does this kind of non-matching action
is "[trim[]]" (introduced in 5.1.20), which removes leading/trailing whitespace from the input items,
but doesn't have any effect on items that don't have leading/trailing whitespace.  Thus, a filter containing this:

[[  foobar ]] [[mumble]] [[gronk snork  ]] [[  frotz]] +[trim[]]
becomes just
[[foobar]] [[mumble]] [[gronk snork]] [[frotz]]

My thought is this... we could extend the current [trim[]] syntax to only remove leading
OR trailing whitespace by adding a suffix to the operator:

[trim:prefix[]] would remove only leading whitespace
[trim:suffix[]] would remove only trailing whitespace

and enable removing of other leading/trailing text values, not just whitespace, by adding a parameter to the operator:

[trim[foo]] would remove leading/trailing text "foo"
[trim:prefix[foo]] would remove only leading text "foo"
[trim:suffix[foo]] would remove only trailing text "foo"

The parameter would also be able to handle repeating text.  Thus, you could trim a list of "zero-padded" numbers, like this:
[[123]] [[0.004]] [[0007.0]] [[000089]] [[27.00]] [[05.00]] +[trim[0]trim:suffix[.]]
would produce this result:
[[123]] [[.004]] [[7]] [[89]] [[27]] [[5]]

and something like:
[[  this is some text...  ]] +[trim[ ]trim[.]]
would produce this result
[[this is some text]]

I can think of several instances where such a filter could have saved me untold amount of
effort in handling variations on field values entered by users via an $edit-text widget

**Comment by twMat** [comment]
@ericshulman , I like your idea a lot and it is better than my OP.

Will you post an issue or PR? - in which case I will close this thread.

**Comment by rmunn** [comment]
I like @ericshulman's idea too, so I posted it in #4809 so it wouldn't get lost.

**Comment by rmunn** [comment]
PR in #4811.

**Comment by rmunn** [comment]
@twMat - #4811 has been merged, so if you're happy with the way the trim operator gained a parameter (and :prefix and :suffix suffixes to be able to trim only one end instead of both), then you can close this issue.

**Comment by twMat** [comment]
thanx!
