### ISSUE TITLE
The sortan operator use with modified field

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4524]
Ref: https://groups.google.com/d/msg/tiddlywiki/gjl1Mxj7F9I/j3I34kT0AgAJ

1. Open https://tiddlywiki.com/
2. create a new tiddler
3. put the below script and save
4. you see the red window

**Scripts**

```
<$list filter="[tag[HelloThere]sortan[modified]]">

</$list>
```

P.s: I know modified is number and sort can be used, but sortan also should work.

**Comment by rmunn** [comment]
The modified field is a [date field](https://tiddlywiki.com/#Date%20Fields), and is not actually a number even if it looks like a number. Internally, the various sort operators all go through the same process when compare two tiddler titles to see which one should come before the other one:

1. Get the two field values from the two tiddlers (which might be their title or some other field).
1. Is this a numeric sort (e.g., nsort or nsortcs) *and* the two values are numbers? Then compare numerically.
1. Is this an alphanumeric sort (e.g., sortan)? Then use the Javascript `localeCompare` function (only valid on strings, and not valid on dates) to compare the two values, passing it the `numeric=true` option.
1. Are the two values dates? Then use date comparison to compare them.
1. Convert the two values to strings in case they weren't strings already, then use `localeCompare` to compare them without passing the `numeric=true` option.

Result: calling `sortan` on a date field hits step 3 before step 4, so TiddlyWiki tries to use the `localeCompare` on dates, which is not valid, and it never gets to step 4. This bug could be fixed by swapping steps 4 and 3, so that the "are these two values date?" check comes before the "was the `sortan` operator used?" check.
