### ISSUE TITLE
should / why is ??!!  _canonical_uri making an options request

### ISSUE THREAD

**Issue by dubiouscript** [Jermolene/TiddlyWiki5#4537]
after adding  _canonical_uri  field and setting url
leaving the content type field empty

after  confirming changes
a request is made to the resource location
with 
> Request method:OPTIONS

setting the type to text plain and confirming changes 
no request is made ?? =S

same as the above with content type  markdown

setting content type to html makes a get request
which returns 
content-type: text/plain; charset=utf-8
and displays a empty frame
if i view source on the frame i see the uri content 

i guess im ether doing something wrong !??
 or something is a bit squewiff!

=]

any one have any hints on
what im missing in this case 
or 
 exactly how/where the _canonical_uri  creates the request is made

**Comment by Jermolene** [comment]
Hi @dubiouscript you've run into the "external text" feature. When a text tiddler having a _canonical_uri field is first viewed the system tries to load the content for that tiddler from the specified URI. That's done with GET request via XMLHttpRequest, which forces a CORS pre-flight check which you're seeing as the OPTIONS request.

**Comment by dubiouscript** [comment]
> That's done with GET request via XMLHttpRequest, which forces a CORS pre-flight check which you're seeing as the OPTIONS request.

i guess this means the browser is what creating the extra request's ?

**Comment by saqimtiaz** [comment]
I ran into this yesterday and was quite surprised that `GET` requests to a `CORS` enabled server were failing the pre-flight request, when the `OPTIONS` request should not even have been necessary. The server in questions was returning the correct `CORS` headers but did not support the `OPTIONS` method.

There is a bit of a nuance to this that I think the `$tw.utils.httpRequest` method is missing.  Requests classified as "simple" by the browser do not necessitate a pre-flight `OPTIONS` request. A simple request is one that is either `GET, HEAD or POST` and does not include any additional request headers, as well [as a few other requirements.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests)

However, the `$tw.utils.httpRequest` method **always** triggers an `OPTIONS` pre-flight request since [it adds the X-Requested-With header](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/dom/http.js#L79) which is needed for the node.js server. This means that a simple `GET` request to a `CORS` enabled server - which however does not supports the `OPTIONS` method - fails whereas it should succeed. An example of such a server is GitHub pages which supports `CORS` but not the `OPTIONS` method. 

It would be desirable to refactor this method so that only requests to the node server receive the `X-Requested-With` header.

Example of a .tid file on Github pages that cannot be loaded via _canonical_uri: https://saqimtiaz.github.io/sq-tw/temp/test.tid
Note that this does work without the `X-Requested-With` header.

**Comment by Jermolene** [comment]
> There is a bit of a nuance to this that I think the `$tw.utils.httpRequest` method is missing. Requests classified as "simple" by the browser do not necessitate a pre-flight `OPTIONS` request. A simple request is one that is either `GET, HEAD or POST` and does not include any additional request headers, as well [as a few other requirements.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests)
> 
> However, the `$tw.utils.httpRequest` method **always** triggers an `OPTIONS` pre-flight request since [it adds the X-Requested-With header](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/dom/http.js#L79) which is needed for the node.js server. This means that a simple `GET` request to a `CORS` enabled server - which however does not supports the `OPTIONS` method - fails whereas it should succeed. An example of such a server is GitHub pages which supports `CORS` but not the `OPTIONS` method.
> 
> It would be desirable to refactor this method so that only requests to the node server receive the `X-Requested-With` header.

Ouch! I had no idea that `X-Requested-With` had those extra semantics.

> Example of a .tid file on Github pages that cannot be loaded via _canonical_uri: https://saqimtiaz.github.io/sq-tw/temp/test.tid
> Note that this does work without the `X-Requested-With` header.

But why does viewing https://tiddlywiki.com/#Alice%20in%20Wonderland work as expected?

**Comment by saqimtiaz** [comment]
> But why does viewing https://tiddlywiki.com/#Alice%20in%20Wonderland work as expected?

@Jermolene the `_canonical_uri` for the tiddler in question is for the same server/origin as the wiki, therefore CORS never comes into consideration and an OPTIONS request is never triggered. The nuances described above only apply for cross-origin requests.

Try adding a tiddler on tiddlywiki.com with a `_canonical_uri` field with value `https://saqimtiaz.github.io/sq-tw/temp/test.tid` to trigger the `OPTIONS` request. This fails to work even though the `.tid` file is served with the correct `CORS` headers. Commenting out the line for the `X-Requested-With` header will allow this to work.

Note that just loading https://tiddlywiki.com with no permalink does show a failed OPTIONS request in the console that originates from the PUT saver.

**Comment by Jermolene** [comment]
> @Jermolene the `_canonical_uri` for the tiddler in question is for the same server/origin as the wiki, therefore CORS never comes into consideration and an OPTIONS request is never triggered. The nuances described above only apply for cross-origin requests.

Doh, of course, sorry not thinking.

**Comment by joshuafontany** [comment]
Is THAT was that failed OPTIONS request is is the console... Good Catch!

Best,
Joshua F
