### ISSUE TITLE
[IDEA] The filter attribute needs a single unified enclosure

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4576]
It is a problem to have to be very careful to encompass filters with either of; single quotes, double quotes or triple double quotes. It is a error prone and it causes cognitive dissonance when wikitext coding.

**Syntax ideas**
`{{{...}}}` clearly does work for encompassing a filter (...or is this only because `}}}` is such an unlikely string elsewhere?). Could `{{{` be universally used for enclosing a filter - if prefixing it with `filter=` disables its "translcusionary aspects"?

Or `filter=[[[ ... ]]]` i.e *including space character separators* (but no quotes) on both sides of the actual filter. 

Or `"[ ... ]"` i.e single double quote+bracket+space.

**Comment by pmario** [comment]
The TW parser needs a "start" and an "end" marker to detect something. eg: //italic//  To make it easier for users start and end are the same. ... It could be a single / ... BUT ... this is a character that already has a meaning in prose text. ... Where // is not used in prose text. 

For our wikitext we already used all the "double-markers" that are easy to remember. 

{{xx}} .. is used for transclusion. So {{{filter}}} is the "logical" extension for "filtered transclusions"

`filter=[[[ ... ]]]` can not be easily written if you use a real filter eg: `filter=[[[[tag[test]]]]]` I think this is a 10 times more error prone as the existing syntax. 

>Or '"[ ... ]"' i.e single double quote+bracket+space.

I think the possibility is too high, that someone uses it in prose text. And "space" shouldn't have a meaning. It needs to be possible to ignore it.

**Comment by twMat** [comment]
I think you missed some critical points I made:

>Could `{{{` be universally used for enclosing a filter - **if prefixing it with `filter=` disables its "translcusionary aspects"?**

And 

>Or filter=[[[ ... ]]] i.e **including space character separators**

**Comment by pmario** [comment]
>Could {{{ be universally used for enclosing a filter - if prefixing it with filter= disables its "translcusionary aspects"?

hmm, but then it's the same as `filter="[tag[x]]"` ... so why typing 6 more chars than needed? 

Why having a different parameter syntax for the filter attribute than for any other attribute. ... 

Widget attributs are `name=value` . So it's OK to write `title=mario` It would be OK to write `title=mario p` ... BUT there is a space in between. That's why we need "parser start/end" markers for strings with spaces. That's the double quote `"`. 

Since some strings can have a double quote as part of the text eg_ `string with \" in it` there is the possibility to cover those strings within single quotes. 

IMO that's a simple rule, which is much simpler as using `"string with \" in it"`, which would have been a possibility too. 

-----

Spaces should have no meaning for syntax detection, because it's difficult for humans to to count them. see: "&nbsp;&nbsp;" or `" "` ... Count the number of spaces between the quotes.

**Comment by twMat** [comment]
(Mario, my friend, did you actually read the OP? Is it poorly phrased or something?)

>hmm, but then it's the same as filter="[tag[x]]" ... so why typing 6 more chars than needed?

Because `filter="[[This is a "problem"]]"` which is what my OP is about.

When we call a variable as an argument for a filter, we can do `filter=<<foo>>`. I.e the angle brackets serve as unambiguous enclosures (or do I misunderstand?). My request here is to find some unambiguous enclosures for the filter attribute because we currently have three variants (`'`,`"` and `"""`) where the simpler ones are particularly risky.

Do you have any suggestion for a good universal "enclosure delimiter" for filter attributes?

**Comment by pmario** [comment]
>Do you have any suggestion for a good universal "enclosure delimiter" for filter attributes?

If this would have been the question in the OP I would have understood it. ... I think there are no "viable" start/stop combinations left, except the one we use atm the Triple Double Quote `"""`

In reality every widget parameter which contains a string should be covered by TDQs ... BUT ... for convenience we don't enforce it. There are a lot of "user-cases" where a single DQ is OK and won't cause problems. 

For those where it causes problems we may need to improve the docs, or they will get help in the GG.

**Comment by Jermolene** [comment]
Hi @twMat the problem is that the quotes matter because they mean something; if we used the same quotes for everything then we could no longer distinguish those cases.

When we use triple braces around an attribute then the content are interpreted as a filter, but the result that is assigned to the attribute is the first result of executing that filter. Meanwhile, using double quotes around the filter in the list widget will assign the filter string itself to the attribute.

**Comment by twMat** [comment]
@pmario and @Jermolene - thanks for input.

OK, OK, triple double quotes it is. Makes """sense""" ;-)

For reference, or perhaps just generally interesting; there are actually quite a few [bracket characters](https://stackoverflow.com/questions/13535172/list-of-all-unicodes-open-close-brackets) but not many that are easily typed on the keyboard.

**Comment by pmario** [comment]
>For reference, or perhaps just generally interesting; there are actually quite a few bracket characters but not many that are easily typed on the keyboard.

That's right, if users can't type them, we can't use them. There are many differences in keyboard layouts, which makes it even more restricted.

**Comment by Jermolene** [comment]
Hi @twMat if I'm understanding correctly, the problem here is confusion from the profusion of different quote styles. The tentative solution of using letters instead of symbols turns out to require more typing, and is more challenging for some users. But there might still be some merit in the idea. Elsewhere in TiddlyWiki we have the bits of syntax that can be abbreviated. For example, within filters, `[[HelloThere]]` is equivalent to `[field:title[HelloThere]]`. So one could imagine, for example `{{HelloThere}}` being an abbreviation for `{transclude{HelloThere}}`. But that's all probably for TWX.

I wonder if syntax highlighting and popup help on hover might go a long way to address the confusion.

**Comment by twMat** [comment]
>one could imagine, for example {{HelloThere}} being an abbreviation for {transclude{HelloThere}}

I like this because all of transclusions, variables and macro calls "feel" like peeking, or 'digging out', what's inside the argument. So maybe they could all use this braces syntax: 

* `{transclude{...}}` and also super compact `{{...}}`
* `{var{...}}`
* `{macro{...}}`

I assume this is friendly also for dyslectics and the verbal mention of what it is should certainly be more obvious for newcomers. Maybe it would also be conceptually simpler to understand that "anything with `[...]` are filters or filter ops" and "anything with `{...}` are some kind of 'functionality' " (I'm afraid to use the term *function* here).

It would also free up `<>` which could be reserved for using as symbolic placeholders.

>I wonder if syntax highlighting and popup help on hover might go a long way to address the confusion.

Yes, for sure. I'm slowly working on it....

**Comment by pmario** [comment]
That's interesting. With uni-link I'm thinking about the "other way around". eg:

Alias links use this syntax: `[[alias|?]]`, which is backwards compatible and "neutral" if used with older wikis. `[[alias|?c]]`, `[[alias|?t]]`, `[[alias|?...]]` allow the user to specify a field, that should be shown instead of the alias text. 

In the background an alias-link is converted to a macro-call like: 

```
<$macrocall $name="aka" field=".."/>
```

The source looks like this: https://github.com/wikilabs/plugins/blob/5b7d18f96323048ea3f32cef2d55bc68bfaa078c/wikilabs/uni-link/tiddlers/aka-macros.tid#L6-L21

Since it's a macro now, I can do what ever I want. It **would** be possible to call any macro like: 
`[[alias|<test]] or [[alias|>test]] or [[alias|?<test]] ` , 
which will kind of replace `<<test param:"alias">>`
some `\define xx()` in the header of the tiddler can set variables, that are needed for the macro. 

OR

It could be used like: `[[alias|?}test]]` ... which would be `{{resolved-alias||test}}`. Where `resolved-alias` is the tiddler name and `test` is the template. So it can replace transclusions. Or `[[alias|?}]]` will be `{{resolved-alias}}` ... 

I did hesitate to implement something like this, since it's like "all/many roads lead to Rome", which I think shouldn't be the case. ... BUT some requests in the GG make me think about the possibilities again.

**Comment by twMat** [comment]
That's very interesting @pmario  
Just to be sure I understand, your  post is apropos my later post about more general syntax matters, right, and not about the initial OP concerning how to enclose filters specifically.

**Comment by pmario** [comment]
@twMat  it's the answer to https://github.com/Jermolene/TiddlyWiki5/issues/4576#issuecomment-617759111
