### ISSUE TITLE
Add support for LaTeX tiddlers

### ISSUE THREAD

**Issue by zedoul** [Jermolene/TiddlyWiki5#458]
Great work! 

I wondering if there is a way to use LaTeX here. 

If there is no way, or no plugin, could you let me know how can where is the document to develop plug-in?

**Comment by wasevah** [comment]
Hey guys,
I was using the plugin from
 https://github.com/kpe/tw5-mathjax-plugin/tree/v0.1.0
for about a year, everything was working fine, but recently I opened up my TiddlyWiki and found that latex was not being rendered.  I'm not sure what the issue is. I don't remember updating TiddlyWiki anytime recently, and I didn't make any major changes to my TiddlyWiki, so it seems likely that there may be a problem with the online CDN thing.  I tried downloading an empty TiddlyWiki (latest version from tiddlywiki.com), adding the kpe plugin, and testing some math.  That also failed to render.  

I would switch to the KaTeX plugin, but that doesn't seem to support single '$' characters for delimiting math (which is an essential feature to me, since it allows me to move excerpts back and forth easily between the TiddlyWiki and proper .tex files).  
Thanks for any help!

**Comment by pmario** [comment]
If you open the dev tools: console with `f12`. Are there any error messages?

**Comment by wasevah** [comment]
Hi @pmario, thanks, but there didn't appear to be any error messages (though I'm not sure I opened the same console that you are thinking of). 
Anyways, I changed the CDN server in the kpe/tw5-mathjax-plugin to 
https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
and math now renders.  So I think the problem is with the other server.

**Comment by hirak99** [comment]
After importing it, the status says -

"Blocked plugin (due to incoming 5.0.12-beta being older than existing 5.0.12-beta)"

Is that the reason why this is not working? I tried to search for ways to disable this... 'helpful' blocking, of plugins I like to use. Unfortunately I couldn't find any way to override the block yet. May be it's burried somewhere in the options, but that's unlikely.

I suppose if the author changes the version in the server, that might help?
