### ISSUE TITLE
Lists in Markdown and TW5 tiddlers do not have the same formatting.

### ISSUE THREAD

**Issue by tanrak** [Jermolene/TiddlyWiki5#4592]
**Describe the bug**
Lists in Markdown and TW5 tiddlers do not have the same formatting.

**To Reproduce**
Create a list in a Markdown Tiddler. Create a list in a TW5 Tiddler. Compare.

**Expected behavior**
List format in Markdown Tiddler as in TW5 Tiddler.

**Screenshots**
Markdown:
![Hpgf3sXoUo](https://user-images.githubusercontent.com/35105392/79998941-9ca48580-84bb-11ea-8b49-d85f0c28fe1d.png)

Tiddlywiki:
![lRtihf56Wo](https://user-images.githubusercontent.com/35105392/79999073-c5c51600-84bb-11ea-829f-3d2e0fa62129.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
- TiddlyWiki: 5.1.22

**Comment by pmario** [comment]
That's right. It seems the remarkable plugin covers the list content inside a paragraph, which has a margion-top and -bottom assigned in TW. ..

There is no good indicator atm, that the text was created by markdown. So at the moment we can't really set a CSS class or something to improve it. ... :/

Needs a bit more investigation.

**Comment by Jermolene** [comment]
Thanks @tanrak I'm seeing the same behaviour.

@MidnightLightning the `<li>` tags have nested `<p>` tags within them, which is indeed different from TiddlyWiki's native wikitext. Trying out the remarkable.js demo at https://jonschlinkert.github.io/remarkable/demo/ it seems that this might be an artefact of the added wikitext processing. What do you think?

**Comment by pmario** [comment]
The markdown demo page does a similar thing: https://jonschlinkert.github.io/remarkable/demo/

**Comment by Jermolene** [comment]
> The markdown demo page does a similar thing: https://jonschlinkert.github.io/remarkable/demo/

Not in my tests. See below:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/174761/80001187-ff931e00-84b5-11ea-913c-8a5d2332816c.png">

**Comment by pmario** [comment]
Try inspect the DOM and it will look different

**Comment by pmario** [comment]
from the DOM

```
<ul>
<li><p>a sdlfkjh</p></li>
<li><p>lkjölj</p></li>
</ul>
```

**Comment by Jermolene** [comment]
Indeed, how weird, why would they show different HTML on the page? Anyhow, it does indeed look like that's how Remarkable does things.

**Comment by pmario** [comment]
>Indeed, how weird, why would they show different HTML on the page? Anyhow, it does indeed look like that's how Remarkable does things.

Indeed weird. I think we need to create an issue there.

**Comment by Jermolene** [comment]
I fed the generated HTML into the W3C validator and it is perfectly valid HTML, as is the markup generated by TW5.

**Comment by pmario** [comment]
Yea, If you have a look at the remarkable demo page and acitvate the "debug" info you'll see that the AST creates a paragraph. ... So imo we should create a `.tc-markdown-rendered` or something similar at the element level. .... OR if it is mixed `tc-markdown` or `tc-tw-syntax` ... so we know who did the rendering.

**Comment by MidnightLightning** [comment]
@tanrak @Jermolene This is likely due to the config setting to hand off parsing of text to the WikiText parser after the Remarkable parser is done. That allows for users to combine Wiki-style things like macros in with a Markdown document, but then may also create artifacts like this.

When I did the conversion to the Remarkable library (https://github.com/Jermolene/TiddlyWiki5/pull/3876), I also added in the config option to not do that handoff (`renderWikiText`). Can you try setting that config option to `false` and see if that clears this up?

There is also logic to strip off the paragraph tags that the WikiText parser adds if the text is in a block level element (https://github.com/Jermolene/TiddlyWiki5/pull/3876/files#diff-1020acb76f1c766c12adcf59af1c0e48R168), but the list of "block level elements" might not be detecting `<li/>` elements properly? If we wanted to remove the paragraph wrappers around list item contents in all cases, that may be the place to investigate?

**Comment by MidnightLightning** [comment]
Oh, I see what you're saying with it also appearing in the Remarkable demo too, so it may be the Remarkable layer doing that. If after you turn the config off the paragraphs are still there, I agree with @pmario 's latest comment that adding CSS classes for the different parsers would help be able to make different styles to match the different parser behaviors.

**Comment by pmario** [comment]
>@pmario 's latest comment that adding CSS classes for the different parsers would help be able to make different styles to match the different parser behaviors.

yea, ... Which is a workaround, which would be good by itself, because it makes us somewhat independent.

Fixing the parsing mechanism would be good too. 

I did have a look at remarkable repo. ... There is one more problem with nested lists as an open issue. 
see: https://github.com/jonschlinkert/remarkable/issues/222

**Comment by Jermolene** [comment]
Hi @pmario we'd have to wrap the output of the parser in a `<div>` or `<span>` to carry the class, but that does sound doable. I suppose the question is whether there are any more problems like this lurking.

**Comment by MidnightLightning** [comment]
> I did have a look at remarkable repo. ... There is one more problem with nested lists as an open issue.
> see: [jonschlinkert/remarkable#222](https://github.com/jonschlinkert/remarkable/issues/222)

Yikes; reported in 2016, and not responded to or dealt with? Though, in playing with the demo website, it looks like indenting the sub-lists one more space properly parses them (at least indenting them to the right locations, though still wrapped in paragraphs):

![Capture](https://user-images.githubusercontent.com/250250/80006920-2a1bb180-848b-11ea-9e37-f8d9e5c50e9e.PNG)

**Comment by robinmetral** [comment]
I don't think that the paragraph tag inside `li` should necessarily be stripped off, especially since it can come in handy with list items containing multiple paragraphs:

```markdown
- first bullet, first paragraph

  second paragraph
- second bullet
```

This should render something like:

```html
<li>
  <p>first bullet, first paragraph</p>
  <p>second paragraph</p>
</li>
<li>
  <p>second bullet</p>
</li>
```

However I do agree that we need to be able to tell these "`p`-inside-`li`"s apart from normal paragraphs, the spacing looks off otherwise.

I'm not familiar enough with user stylesheet for TiddlyWiki yet, but we might be able to simply style `li > p`?

**Comment by robinmetral** [comment]
Update on ☝️:

Turns out the spacing issues are very easy to fix with a user stylesheet.

Just add a Tiddler with tag `$:/tags/Stylesheet` and this CSS as the content:

```css
li > p {
  /*
   * you can remove the margin altogether, I'm setting it as 8px
   * in order to differentiate between multiple paragraphs in a
   * single bullet (see the comment above)
   */
  margin: 0 0 8px;
}
```

Note that it doesn't seem to have any side-effects on my end, but there could be some depending on your config.

**Comment by tanrak** [comment]
Thanks.  This workaround is enough for me. After all, it is more a cosmetic nature.

**Comment by pmario** [comment]
@tanrak ... It's only you or Jeremy, which can close it. .. So you should do it ;)

**Comment by tanrak** [comment]
@pmario thanks for the hint. I will close now the issue.
