### ISSUE TITLE
[IDEA] Is now the time to add server sent events to core?

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#4608]
@Jermolene 

With the recent improvements to the syncer, is it time to add server-sent-events? I don't know what all the use cases would be, but I think it would be useful, as I'm sure you well know. 

We can add it as a route to the Server. I would propose setting aside the `events` route for it. Do we have all events go through one channel or do we allow multiple channels as URLs under `events`?

Server Sent Events allows named events to be sent in addition to the unnamed "message" event. However, I would proposed that each plugin have its own route under events named according to the plugin scope. This way every plugin can own its own channel. 

- `events/core`
- `events/plugins/tiddlywiki/tiddlyweb`
- `events/plugins/arlen22/plugin-name`
- `events/themes/someone/dashboard`

If that's too many connections, we could also have the plugins use the same prefixes for the event names themselves, but it seems like it would be more useful to have separate channels. Also, I don't think a large number of connections is really a problem. Node is capable of handling "1 million concurrent connections". 

We can make a `ServerSentEvents` class which would handle all of this so that plugins could easily setup their own route and would include instructions on the exact parameters to use. Regex can be compiled from a string, so we can set it up based on constructor parameters. 

Please see https://github.com/Jermolene/TiddlyWiki5/pull/4609 for the code that was included here.

**Comment by joshuafontany** [comment]
@Arlen22 , I am looking at implementing an oEmbed library to  TW on Node.js, and this seems exactly what I want. The Server has to send/handle the requests for the Embed json, in order to avoid CORS errors. The Node library I want to use has smart white-listing and a few other methods to handle common oEmbed issues.

I am looking through your code now. What would be the best way to implement this, as its own plugin with its own named route, like `events/plugins/joshuafotnany/oembed`? I will start with reading your tiddlyweb implementation. It would be very useful to have a test or demo setup to see this in action. Thanks!

Best,
Joshua F

**Comment by NicolasPetton** [comment]
@Arlen22 @Jermolene now that #5279 is merged, should we close this one?

**Comment by Jermolene** [comment]
Thanks @NicolasPetton
