### ISSUE TITLE
[BUG] Loading JS tiddlers in a theme

### ISSUE THREAD

**Issue by NicolasPetton** [Jermolene/TiddlyWiki5#4622]
**Describe the bug**

If I include a JS tiddler in a theme as a global module, the tiddler never gets executed. It works fine in a regular plugin though.

**To Reproduce**
1. Add a global module JS tiddler in a theme
2. Reload
3. The module is never executed

**Expected behavior**
This behavior might be on purpose, but I find it surprising that themes cannot contain JS modules.

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser Firefox
 - Version 75.0

**Comment by Jermolene** [comment]
Hi @NicolasPetton themes aren't intended to contain JS modules, the idea is that they are purely CSS (and wikitext for the control panel theme tweaks page). Part of the reasoning is that JS modules cannot be loaded/unloaded dynamically, and so plugins containing JS can't be switched in and out dynamically, as we do for theme plugins.

The current design is quite aggressive in trying to separate out elements of the visual appearance so that they are independently switchable: themes, palettes, storyviews, and soon layouts.

**Comment by NicolasPetton** [comment]
> The current design is quite aggressive in trying to separate out elements of the visual appearance so that they are independently switchable: themes, palettes, storyviews, and soon layouts.

What if my theme includes layouts, and needs to register hooks? (My use-case)

**Comment by Jermolene** [comment]
Hi @NicolasPetton 

> What if my theme includes layouts, and needs to register hooks? (My use-case)

As things stand, it wouldn't be classified as a theme because it contains JS modules.

Making it possible for themes to contain JS modules would require us to make JS modules switchable, which presents some fundamental difficulties: how does one "undo" the effect of loading a module? In TW5 modules can have side effects, and so we'd need a way to undo those side effects, presumably a handler that every non-trivial module would implement. That would be a burden on every single module, and we would struggle to make sure that all modules properly tested that code path.

**Comment by pmario** [comment]
I think it should be possible to package the js-elements into a real plugin, which requires a "save and restart".

The user can install the js-plugin. If there is no theme, that plugin widgets will be not activated. So no problems. 

If the theme will be installed on it's own, it is able to check if the plugin is there. If not just display some info, what's needed.

I think this scenario is relatively easy to handle.

**Comment by Jermolene** [comment]
Hi @NicolasPetton indeed @pmario's suggestion makes sense.

**Comment by NicolasPetton** [comment]
Jeremy Ruston <notifications@github.com> writes:

> Hi @NicolasPetton indeed @pmario's suggestion makes sense.

Yes, that's what I did already when I realized I couldn't include
JavaScript into my theme.
