### ISSUE TITLE
[BUG] GitHub Saver Corrupts Emoji

### ISSUE THREAD

**Issue by philips** [Jermolene/TiddlyWiki5#4685]
**Describe the bug**

New user here.

I wanted a Tiddler with Emoji's in it. For example 🎥.

Adding these Emoji directly with git works fine.

However, the TW GitHub saver seems to corrupt them. See this Gist of a patch the GitHub saver generated: https://gist.github.com/philips/78767c849be6f7ba625a6f3b68c0194f

**To Reproduce**
1. Go to any Tiddler after enabling GitHub saver
2. Click on Edit
3. Input an emoji like 🎥
4. See broken commits

**Expected behavior**
Emoji's saved without issue.

**Desktop (please complete the following information):**
 - OS: ChromeOS 83
 - Browser Chrome

**Comment by rmunn** [comment]
Looks like an encoding issue combined with failing to handle surrogate pairs properly. For example, in the line "📚 ⏳ Doughnut Economics - Kate Raworth", 📚 gets corrupted but ⏳ comes through fine. That fact lets us narrow down the bug: ⏳ is U+23F3 HOURGLASS WITH FLOWING SAND, which is in the Basic Multilingual Plane (U+0000 to U+FFFF) and can therefore be represented by Javascript as a single character. But 📚 is U+1F4DA BOOKS, which is in one of the Supplementary planes (specifically, the U+10000 to U+1FFFF place) and thus is represented by Javascript (which uses UTF-16 internally) as two surrogate pairs, 0xD83D 0xDCDA. Note that I did not write those as U+D83D U+DCDA, because U+ represents a Unicode *codepoint*, and the surrogate pairs aren't code points, they're code units. But when the conversion to UTF-8 happened, instead of treating the 0xD83D 0xDCDA pair as two code units representing the code point U+1F4DA (whose UTF-8 equivalent should have been 0xF0 0x9F 0x93 0x9A), it treated them as the (invalid) code points U+D83D U+DCDA, and the conversion to UTF-8 then pretends U+D83D is a real character and converts it to three bytes that are not, in fact, valid UTF-8. Same with the not-really-a-character U+DCDA, which gets converted to three bytes that are not valid UTF-8. Then when Gist reads your file, it sees those three-byte UTF-8 sequences that would decode to surrogate pairs, says "Oh, that's totally invalid", and converts each of them to three occurrences of U+FFFD REPLACEMENT CHARACTER, for six total U+FFFDs for each emoji in the U+10000-1FFFF range.

What needs to happen is that TiddlyWiki's GitHub saver needs to be aware of surrogate pairs and handle them properly: the two code units representing 📚 should have been turned into the *correct* four-byte UTF-8 sequence 0xF0 0x9F 0x93 0x9A.

**Comment by rmunn** [comment]
I believe the bug is in the [core/modules/utils/base64-utf8/base64-utf8.module.js](https://github.com/Jermolene/TiddlyWiki5/blob/8cf458d3b3f1e38c14a2819529e08dca4a7e297c/core/modules/utils/base64-utf8/base64-utf8.module.js) file, which goes through the string one character at a time calling [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) to get each character. But the MDN documentation warns that this function does not handle surrogate pairs properly, and suggests using the [codePointAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt) function instead if you want surrogate pairs handled properly. Thing is, codePointAt is not supported by Internet Explorer, so TiddlyWiki can't use it. However, the MDN docs for codePointAt include a polyfill that can be used to provide it. We wouldn't want to use that polyfill directly, since it wouldn't correctly advance the loop variable by 2 instead of 1 when a surrogate pair is encountered, but we can use the parts of it that detect surrogate pairs and have those parts do the right thing inside the loop.

Note that this is not just an issue with emojis; this would make TiddlyWiki's GitHub saver unusable for anyone whose language is represented in the higher Unicode planes, such as anyone who wants to translate TiddlyWiki into [Osage](https://en.wikipedia.org/wiki/Osage_script).

**Comment by philips** [comment]
Wow, thank you for the detailed technical analysis and patch!
