### ISSUE TITLE
[BUG] Can't save by gitea saver when login gitea

### ISSUE THREAD

**Issue by sunsteam** [Jermolene/TiddlyWiki5#4837]
**Describe the bug**
I deploy gitea and tiddlywiki on 192.168.1.20/git and 192.168.1.20:80 , afterI login gitea, the tiddlywiki put action fail on 401, perhaps cookie conflict. the account id are same , but api token and passowrd both save in password? i guess.

I found two way to fix manually
1. clean the cookie
2. or revise the js, change header Authorization: Basic c3VueXV4aW5nOmY2ZDdlMDRmY2ViYThiOGM4YWU0MTg1MmM5NmI1NTg3OWIwNmI1Mjk= to Authorization: token "the real token"

**To Reproduce**
1. login gitea on 192.168.1.20/git
2. save tiddlywiki on 192.168.1.20 by gitea saver
3. get file info ok but put file fail , 401 code.

**Screenshots**
![image](https://user-images.githubusercontent.com/7489390/91940084-7b855880-ed29-11ea-9ae0-fd7015ecbcb3.png)
![image](https://user-images.githubusercontent.com/7489390/91937272-26931380-ed24-11ea-95a6-6737582d8d0f.png)

**Desktop (please complete the following information):**
- "tiddlywiki-version 5.1.22"
- "Gitea version: 1.13.0+dev-410-g2ef318e6f"
- "Chrome/84.0.4147.135 "

**Additional context**
requset info

PUT /git/api/v1/repos/sunyuxing/Juno-Wiki/contents/index.html HTTP/1.1
Host: 192.168.1.20
Connection: keep-alive
Content-Length: 3691319
Accept: application/json
X-Requested-With: TiddlyWiki
Authorization: Basic c3VueXV4aW5nOmY2ZDdlMDRmY2ViYThiOGM4YWU0MTg1MmM5NmI1NTg3OWIwNmI1Mjk=
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: http://192.168.1.20
Referer: http://192.168.1.20/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: lang=zh-CN; i_like_gitea=10eb754532062a61; _csrf=ajL8eTIWm3N5013RhGz6DwtHIxw6MTU5OTAwOTMwMTE5NjEyMzc2NA

**Comment by rmunn** [comment]
The Gitea saver currently takes the token you specify and uses it as if it was a password, putting an HTTP header "Authorization: Basic (username:password in base64)" into the request. (See [line 34 of gitea.js](https://github.com/Jermolene/TiddlyWiki5/blob/422eb43e50bf659099c9e018d5fa3b2803379725/core/modules/savers/gitea.js#L34). But according to the [Gitea API docs](https://try.gitea.io/api/swagger#/repository/repoUpdateFile), token authentication in Gitea is done by sending a header "Authorization: token (the token)". So line 34 needs to be changed to:

```javascript
"Authorization": "token " + password
```

and then it should work.

**Comment by rmunn** [comment]
#4854 should fix this. I have **not** been able to test that code since I don't have Gitea installed on my computer, but that change does exactly what you did manually in option 2 to fix this (change the Authorization header to be Authorization: "token (the real token)"). @sunsteam, if you can edit the gitea.js file in your local installation of Tiddlywiki to make the same change that I made in #4854, please mention the results as a comment in #4854 so that we can have confidence that my fix is working.

**Comment by rmunn** [comment]
@sunsteam - This fix has been included in the TiddlyWiki 5.1.23 prerelease. If you go to https://tiddlywiki.com/prerelease/ and download an empty copy with the Download Empty button (in the Getting Started tiddler), you should be able to test that the Gitea saver is working correctly now. If it isn't, please reopen this bug report or make a new one so that we know the problem wasn't fixed.
