### ISSUE TITLE
[BUG] IMO html attribute parser creates strange effects, due to missing test

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4838]
IMO html attribute parser creates strange effects, due to missing test

To reproduce: Type the following text into a new tiddler at: https://tiddlywiki.com/prerelease/ 

```
<div tick= test="asdf"/>
```

 - Select "parse tree" in the preview pane.
 - MODE: inline
 - You'll see: 

```
    {
        "type": "text",
        "text": "<div tick= test=\"asdf\"/>"
    }
```

because the attribute parser fails

## Expected

```
    {
        "type": "element",
        "start": 0,
        "attributes": {
            "tick": {
                "start": 4,
                "name": "tick",
                "type": "string",
                "value": "FALSE",               <------ or something similar
                "end": 12
            },
            "test": {
                "start": 12,
                "name": "test",
                "type": "string",
                "value": "asdf",
                "end": 24
            }
        },
        "tag": "div",
        "isSelfClosing": true,
        "end": 26,
        "isBlock": false
    }
```

## Conclusion

 - The problem is `tick= test="..`   The attribute parser treats `test` as the value for `tick`
 - There are some tests in `test-html-parser.js` ... but this specific case isn't tested, so it can't fail. 
 - If an attribute is eg: `tick` the value will be `true`
 - If an attribute is `tick=` IMO the vaule should be `false`   @Jermolene what do you think??

**Comment by rmunn** [comment]
Writing an attribute as `something=` with nothing after the equals sign is [invalid HTML syntax](https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#syntax-attributes). The HTML spec allows attributes to be written in one of four ways:

1. Empty attributes: `<foo attr>`. This is equivalent to writing `<foo attr="">`: the value of `attr` is the empty string.
1. Unquoted values: `<foo attr=bar>`. Note that any number of spaces are allowed before and/or after the =, so `<foo attr = bar>` is also valid and sets the value of `attr` to "bar".
1. Single-quoted values: `<foo attr='bar'>`. Again, spaces allowed around the equals sign.
1. Double-quoted values: `<foo attr="bar">`. Again, spaces allowed around the equals sign.

Writing `<div tick= test="asdf"/>` is invalid HTML syntax, and it should be no surprise that TiddlyWiki doesn't parse it. If you want `tick` to have no value, you should either write `<div tick test="asdf"/>` or `<div tick="" test="asdf"/>`. If TiddlyWiki fails to parse either one of those two syntaxes, then that would be a bug.

**Comment by rmunn** [comment]
The tests in test-html-parser.js cover all four of those cases quite adequately, BTW. So this is, IMHO, not a bug and you can close this issue. Writing an empty attribute with correct syntax is covered by the unit tests and parses correctly, and TiddlyWiki should *not* try to handle invalid HTML syntax as there are a million and one ways to write invalid syntax and it would be impossible to cover them all.

**Comment by rmunn** [comment]
While it's true that setting the value to "true" is different than the way HTML treats [boolean attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes), where the value must be empty and the presence of the attribute means "true" and its absence means "false", TiddlyWiki has chosen to allow the `disabled="false"` syntax for turning off a Boolean attribute. Which means that having an empty attribute get the value "true" is the thing that comes the closest to HTML's treatment of Boolean attributes, and is a deviation from the spec that makes sense for TW.

As for your proposal, especially the `<input disable= other="xxx">` part, it's actually *very* hard to write a *high-performance* regular expression that would distinguish that from the `<input disable= other>` case, where the value of the `disable` attribute *should* be "other" (as it would be an unquoted value). And the parsing part of TiddlyWiki *needs* to be high-performance, as that's the part that happens the most. That's why I downvoted it: because it's not actually possible to do in an efficient way, and it's not worth creating inefficiency to parse invalid HTML, especially if that invalid HTML is a temporary situation where the user is still typing.

As for the preview pane, it might be possible to do something like [debouncing](https://davidwalsh.name/javascript-debounce-function) the preview pane so that it only generates a preview when the user has not typed anything for X milliseconds, where X might default to 500 (half a second) but be configurable. That way if you're typing `disable=""`, you probably won't pause for half a second after typing the equal key, and (at least if you're a fast typist) you won't get the RSOD halfway through writing what would turn out to be valid HTML.

**Comment by pmario** [comment]
TW already has a debouncing timeout of 400ms. see: https://tiddlywiki.com/#Hidden%20Setting%3A%20Typing%20Refresh%20Delay ... more info will follow

**Comment by pmario** [comment]
I did a test with FF and this code. It seems the browser is "self healing" ... It messes up the `value` param with a "wrong" value: `data-foo="test"` so "readonly" will be correct again. 

It "eats" `data-foo="test"` ... but that seems to be according to the spec. 

TW parser messes up all the params that follow an invalid param. ... So I'm not really satisfied, with the browser behaviour. 

```
var s = '<option value= data-foo="test" readonly>Value 1</option>';

var test_element = document.createElement('div');
test_element.innerHTML = s;

var element = test_element.childNodes[0];
var attributes = element.attributes;

for (var i = 0; i < attributes.length; i++) {
    var attribute = attributes[i];

    console.log(attribute.name, '=>', attribute.value);
}
```

I did have a closer look at the code and it seems there should be a compatible and relatively easy fix. ... at lest in my brain. So we'll see what a real comiler "thinks" ;)

**Comment by pmario** [comment]
The responsible code is at: https://github.com/Jermolene/TiddlyWiki5/blob/422eb43e50bf659099c9e018d5fa3b2803379725/core/modules/parsers/parseutils.js#L212-L214

I'll create a PR if there is a compatible fix. 

If not, may be `exports.parseAttributeStrict = function(source,pos) {` may be an option for plugin authors. It will apply a stricter ruleset, that will set `attribut=` to true.

**Comment by pmario** [comment]
OK. I did some more testing and as long as the syntax is invalid TW shows the "broken" hmtl string. So users will see, what's going on. ... I'll need to find the part of the code, that does this detection and use it. I thought parseAttribute() will do this :/
