### ISSUE TITLE
[BUG] Join operator returns non-empty output from empty input

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#4852]
**Describe the bug**
An empty filter output if directed as input to a join operator will return something!!!

**To Reproduce**
1. Go to https://tiddlywiki.com/
2. Create a tiddler and put the below wikitext inside its text field

`
<$list filter="[tag[not-exist]]" emptyMessage="I am empty">
I am here
</$list>
`
Save and see the result. It will shows `I am empty`

3. Next change the wikitext with below one
`
<$list filter="[tag[not-exist]join[_]]" emptyMessage="I am empty">
I am here
</$list>
`
Save and see the result: `I am here`

That means an empty filter output if fed to a join operator will return non-empty output.

**Expected behavior**
Nothing shall be displayed!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 81
 - TW 5.1.22

While I know this behavior may be useful in some situation, but this is confusing!

**Comment by rmunn** [comment]
This appears to be on purpose to match the behavior of the [Javascript `join` function on arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join), where the documentation says "If arr.length is 0, the empty string is returned." There's also a test added by https://github.com/Jermolene/TiddlyWiki5/pull/4396 to ensure that the join operator won't return null when passed in an empty list, and will instead return a list of one item (and that item will be the empty string).

OTOH, I agree with you that the behavior of the join operator is surprising and non-obvious: when there is no input, instead of returning a list of one item, join should return an empty list. So I'll submit a fix to fix this bug and change the behavior introduced by #4396. It's going to be a one-line fix in the code, plus a few more lines for the changes I'll be making to unit tests.

**Comment by kookma** [comment]
Many thanks @rmunn 
Yes, one expect to see consistency among all filter operator.
