### ISSUE TITLE
Advanced Search -> Export Tiddlers drop-down breaks when double quotations are used in Filter tab

### ISSUE THREAD

**Issue by mwiktowy** [Jermolene/TiddlyWiki5#4860]
I was looking for a way to list a few individual tiddlers for export together into a single JSON file. I entered "Tiddler One" "Tiddler Two" into the Filter tab search box (which properly matched the tiddlers that I wanted) and clicked the export tiddlers button. Instead of the normal options, each option showed a bunch of underlying code and didn't function correctly.

I finally figured out the proper way ( [[Tiddler One]] [[Tiddler Two]] ... also using single tick-mark/apostrophe quotes works ) but it seemed that the intuitive way of using double quotes that properly matched shouldn't break the export feature.

**Comment by rmunn** [comment]
Here's a couple of screenshots for reproduction purposes. If I enter `"HelloThere" "GettingStarted"` in the Advanced Search tiddler, I see this, which would lead me (if I was a new user who didn't know filter syntax yet) to believe that the syntax was correct:

![image](https://user-images.githubusercontent.com/90762/93737159-a23dfd00-fc0c-11ea-8ee9-fd2d801f7d76.png)

If I then click on the Export button of the Advanced Search tiddler, this is the popup that results, with the "bunch of underlying code" that was mentioned:

![image](https://user-images.githubusercontent.com/90762/93737173-b255dc80-fc0c-11ea-8062-eaf146a7daa6.png)

Digging into this, the code that's causing this seems to be in the `export.tid` file, where the action-sendmessage widget is called like this:

```plaintext
<$action-sendmessage $message="tm-download-file" $param=<<currentTiddler>> exportFilter="""$exportFilter$""" filename=<<exportButtonFilename """$baseFilename$""">>/>
```

The triple-quotes around the `$exportFilter$` parameter substitution are intended to be able to handle just about any text, but if the contents of `$exportFilter$` begin and end with quotation marks, then what happens is `exportFilter=""""some text""""` and the first three quotation marks are matched by the parser as the end of the value, so the fourth quotation mark confuses the parser and it fails.

If the `exportFilter` parameter here was written using the parameter-as-variable syntax `<<__...__>>`, then this appears to solve the issue. However, when I tried it, I got mixed results. Exporting as JSON, only the first of the two tiddlers was exported (I got the HelloThere tiddler, but not GettingStarted). Exporting as HTML, I got both tiddlers. I believe this has something to do with the syntax with which the `exportFilter` parameter is accessed in $:/core/templates/exporters/JsonFile and how it's accessed in $:/core/templates/exporters/StaticRiver/Content, but I don't have time today to pursue this investigation any further. This *should* be solvable, though.

**Comment by pmario** [comment]
@rmunn ... You are right and there is a fix. .. BUT non the less if `"a" "b"` is used a filter, ONLY "a" will be exported, because the filter is not considered valid by the function.

**Comment by rmunn** [comment]
@pmario - Not necessarily: see my last paragraph, where the HTML exporter did export both tiddlers. It depends on how the exporter is written. What needs to happen is either: a) all exporters are written to allow filters like `"a" "b"` to work, or b) the export mechanism detects invalid filters like `"a" "b"` and warns the user about them.

**Comment by pmario** [comment]
I found it PR is under way!

**Comment by pmario** [comment]
I did write the tests and there are a lot of problems. ... :/

**Comment by pmario** [comment]
See: Fix 4860 parser problem with tripple double qoutes. #4863

**Comment by Jermolene** [comment]
Thanks @mwiktowy @rmunn @pmario. I had a further dig into this. Part of the solution is the change to `$:/core/macros/export` pointed out by @rmunn and included in @pmario's PR — see https://github.com/Jermolene/TiddlyWiki5/pull/4863/files#diff-a35c98393856bad6bdeb543a99565eb0

The remaining problems are with the template in `$:/core/templates/exporters/JsonFile` which currently looks like this:

```
\define renderContent()
<$text text=<<jsontiddlers filter:"""$(exportFilter)$""">>/>
\end
<<renderContent>>
```

It is a clumsy way to render the plain text of the output of a macro. We can't change the triple double quotes to use `<<variable>>` notation because it is not supported the wikitext syntax for a macro call. In this case we can't use the `<$macrocall>` widget because it always wikifies it's output, and can't be used to render plain text.

It may be possible to fix things using the `<$wikify>` widget but I prefer the idea of extending the `<$macrocall>` widget so that it can render the macro output as plain text by specifying the `$output` attribute as `text/raw`. I'll commit the fix shortly once I've got the associated documentation updated.

**Comment by Jermolene** [comment]
For clarity, the proposed `$:/core/templates/exporters/JsonFile` looks like this:

```
<$macrocall $name="jsontiddlers" filter=<<exportFilter>> $output="text/raw"/>
```
