### ISSUE TITLE
Update GitHub Actions to avoid deprecated "set-env" command

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#4885]
GitHub have announced that the "set-env" command should no longer be used in actions:

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Action and workflow authors who are setting environment variables via stdout should update any usage of the set-env and add-path workflow commands to use the new environment files.

It links to this guide:

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

`.github/workflows/ci.yml` currently uses the following `set-env` commands:

```
echo ::set-env name=TW5_BUILD_BRANCH::${TW5_BUILD_BRANCH}
echo ::set-env name=TW5_BUILD_VERSION::$(./bin/get-plugin-library-version-number)
echo ::set-env name=TW5_BUILD_DETAILS::Prerelease built from branch \'$TW5_BUILD_BRANCH\' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')
```

If I understand correctly, they should be changed as follows:

```
echo "${TW5_BUILD_BRANCH}" >> $TW5_BUILD_BRANCH
echo "$(./bin/get-plugin-library-version-number)" >> $TW5_BUILD_VERSION
echo "Prerelease built from branch \'$TW5_BUILD_BRANCH\' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')" >> $TW5_BUILD_DETAILS
```

Does that look right to you @ento? I'm always a bit uncertain about Bash quoting, and the third line nests single quotes inside double quotes.

**Comment by ento** [comment]
I think the backslashes will be unnecessary - they become part of the string instead of being interpreted as escape characters:

```sh
$ FOO=bar
$ echo "a \'$FOO\' b"
a \'bar\' b
$ echo "a '$FOO' b"
a 'bar' b
```

Also, I think we need to use the `$GITHUB_ENV` environment variable as written. "During the execution of a workflow, the runner generates temporary files that can be used to perform certain actions" from the documentation, as I interpret, means that `$GITHUB_ENV` holds a path to a file that the runner reads back later to make user-defined environment variables available in subsequent actions.

So for the `build-prerelease` job, it'll be

```sh
echo "TW5_BUILD_BRANCH=${TW5_BUILD_BRANCH}" >> $GITHUB_ENV
echo "TW5_BUILD_VERSION=$(./bin/get-plugin-library-version-number)" >> $GITHUB_ENV
echo "TW5_BUILD_DETAILS=Prerelease built from branch '$TW5_BUILD_BRANCH' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')" >> $GITHUB_ENV
```

And for ` build-tiddlywiki-com`,

```sh
echo "TW5_BUILD_BRANCH=${TW5_BUILD_BRANCH}" >> $GITHUB_ENV
echo "TW5_BUILD_VERSION=$(./bin/get-plugin-library-version-number)" >> $GITHUB_ENV
echo "TW5_BUILD_DETAILS=Built from branch '$TW5_BUILD_BRANCH' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date +'%F %T %Z')" >> $GITHUB_ENV
```

**Comment by rmunn** [comment]
@ento is right: you need to write to `$GITHUB_ENV`. What's going on is that Github Actions creates a temporary file and stores its name in the `$GITHUB_ENV` variable. So by putting `>> $GITHUB_ENV` at the end of each `echo` statement, you're appending lines to that temporary file. Before each action in the workflow, that file is read and parsed, and its contents made available as environment variables to that action. Which is why, as the docs say, the current action doesn't have access to the environment variable you've just set, but subsequent actions do.

**Comment by Jermolene** [comment]
Thank you @ento @rmunn much appreciated, and apologies for the delay.
