### ISSUE TITLE
[IDEA] Typed Semantic Link (link with metadata)

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#4982]
**Is your feature request related to a problem? Please describe.**
In https://www.remnote.io/documentation/kBtxCZsYPAaKrP2Yy , RemNote introduce its "Universal Descriptors", which is a list of predicates that descript the type of the link.

<img width="702" alt="截屏2020-11-06 上午11 22 20" src="https://user-images.githubusercontent.com/3746270/98322476-73e07980-2022-11eb-80cf-797dd02d4e09.png">

<img width="745" alt="截屏2020-11-06 上午10 51 33" src="https://user-images.githubusercontent.com/3746270/98320486-0af70280-201e-11eb-96cb-e8f9516f62d2.png">

For example, you can have this kind of typed link `after Operator (Examples) -[Example Of]-> after Operator`

And later you can filter it `<<list-links filter:"[all[![is[system]]]links[Example Of]]">>` to get these links.

And actually this kind of link will form a triple, Just like JSON-LD and RDF, which may support logic-based AI reasoning:

> Bob -[Parent Of]-> Alice  ; Catalina -[Parent Of]-> Bob
> 
> Show GrandParent `all[![is[system]]]links[Parent Of]getLinkTargetFilter[]links[Parent Of]`

**Describe the solution you'd like**

Extend a new syntax `[Link Type[Link Text|Link target]]`, currently, we have `ext` link type, this syntax exists, I just need to update the link indexer, and add more filter to use this new graph information.

**Describe alternatives you've considered**
Just let link text be their type `[[Parent Of|Alice]]`, in this way we can easily create a typed link, we just need to create a new filter that is aware of the link text.

**Additional context**
I hope the whole wiki can be a small symantic web, that can support spaced repeation usage like RemNote.

**Comment by Jermolene** [comment]
Hi @linonetwo that's an interesting idea. The same thing has occurred to me: that a regular "pretty link" like `[[target|text]]` is already somewhat like an RDF triple:

* The target of the link
* The description of the link
* The (implied) source of the link

As you say, the missing piece would be a filter that can operate on the link text. I think we can do that for the case of links generated by the `[[target|text]]` syntax because they only contain plain text, but in general the content of a `<$link>` widget can be rich content, meaning that one would need to parse and render it to be able to extract the plain text content.

**Comment by linonetwo** [comment]
(Maybe move this to a discussion?, or continue the discussion at [https://talk.tiddlywiki.org/t/are-link-tags-typed-links-implemented-for-tiddlywiki/1920/6](https://talk.tiddlywiki.org/t/are-link-tags-typed-links-implemented-for-tiddlywiki/1920/6) )

I come across a typed-link plugin for obsidian today [https://juggl.io/Link+Types](https://juggl.io/Link+Types) , I think its syntax is better `hasPainted:: [[The Night Watch]]`

**Comment by linonetwo** [comment]
[SuperTag](https://talk.tiddlywiki.org/t/supertag-plugin-auto-generate-a-field-editor-on-view-template/6245) is the future, easier for normal user to use.

Most of human don't like add metadata, if without a beautiful UI.
