### ISSUE TITLE
New Import dialog "edit name" issue

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5011]
If an import dialog looks like this. 

![grafik](https://user-images.githubusercontent.com/374655/98482398-6208fd00-2201-11eb-943d-a159cbdbac85.png)

There are several elements, that are _not_ selected. ... BUT there is still an edit name button.

## Expected behaviour

 - The edit button should be not revealed, if the element isn't selected.

@saqimtiaz ... The selection info is a field. Do you see an easy way to implement it?

**Comment by pmario** [comment]
The size of the edit button is different. ... strange!

**Comment by pmario** [comment]
The problem seems to be: 

```
.tc-tiddler-frame img, .tc-tiddler-frame svg, .tc-tiddler-frame canvas, .tc-tiddler-frame embed, .tc-tiddler-frame iframe {
    max-width: 100%;
}
´´´

**Comment by saqimtiaz** [comment]
Both should be an easy fix. I'll take a look tomorrow.

**Comment by Jermolene** [comment]
I don't think that it is inconsistent to show the rename button for tiddlers that are not selected. Hiding/showing them as the checkbox changes state seems visually distracting.

**Comment by pmario** [comment]
We have a "disabled" button attribute now in 5.1.23. IMO it doesn't make sense to allow editing the name and _not_ importing it

**Comment by saqimtiaz** [comment]
@pmario I am testing the disabled attribute right now. I tried hiding/showing the button and I agree it was a bit jarring.

**Comment by saqimtiaz** [comment]
Using the disabled attribute works in principle but I would not recommend it, as the button appears visually identical when disabled or not, since we are using an icon and no borders/padding or other default button styling.

Personally I don't think it is a problem that you can edit the name of an unselected tiddler. Otherwise we would be unnecessarily complicating things. What would happen in the suggested scenario, if the user had edited the name and then unselects the tiddler, should we reset the name?

The issue with button size should be resolved.

I would close this as "wont fix" and revisit if there is further user feedback that suggests there is an issue here.
