### ISSUE TITLE
[IDEA] Add actions parameter to "range widget"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5029]
The idea is to add action parameterS to the "range widget". 

@saqimtiaz pointed out, that all "interactive" widgets that can have an **actions** parameter, should have 1 or more.

Some thoughts about the specs follow.

## Spec / Ideas

 1. Add info about "click" and "click-release" state ... 
   1.1 This means, there at least 2 actions
 2. While the "handle" is clicked, _no_ actions should be fired
   2.1 This avoids overloading the wiki internal "change" tasks 
   2.2 This avoids update problems if changes are auto-saved to a server
 3. Modifier keys ???

Did I miss something?

**Comment by pmario** [comment]
The html range-input fires 

 - a "change" event, ONLY if the start-value is different to the end-value
 - an "input" event, WHENEVER the slider is moved ... this causes a lot of events and IMO should be avoided. 

## Additional Spec

 - There needs to be a difference between "change" and "input" .. Which means we have 4 actions now.

**Comment by Jermolene** [comment]
Hi @pmario good idea.

> While the "handle" is clicked, no actions should be fired
> 2.1 This avoids overloading the wiki internal "change" tasks

I think that might be a bit restrictive. The refresh cycle is often quick enough for interactive use.

> 2.2 This avoids update problems if changes are auto-saved to a server

I think that sort of throttling would be the responsibility of the sync subsystem.

**Comment by saqimtiaz** [comment]
One consideration here is that IE10/11 do not fire an `input` event on range elements, but instead fire the `change` event on `mousemove`.

Other browsers only fire `change` on `mouseup`, and `input` on `mousemove`.

This naturally restricts us to only being able to invoke actions on `mousemove` rather than `mouseup` if we want to maintain IE support.

Note that `handleInputEvent` already does debouncing and can do the same for invoking actions.

See #4534 for some related issues with event handling for range elements.

**Comment by Jermolene** [comment]
I'm much less worried about IE 10/11 support these days, especially for something like this where generally all IE 10/11 users would lose is some interactivity.

**Comment by saqimtiaz** [comment]
@Jermolene to clarify my point was that if we fire actions on mouse-move, as you suggest for interactive use, then we also get IE10/11 compatibility at no cost.

**Comment by Jermolene** [comment]
Apologies @saqimtiaz, but why wouldn't we just use the "input" event and stay away from "mousemove"?

**Comment by saqimtiaz** [comment]
@Jermolene we are saying the same thing but talking around each other.

The `input` event is fired on the mouse moving, as opposed to mouse up/release.

**Comment by twMat** [comment]
Related to #3252

@pmario asks in the current OP:
>Did I miss something?

In the referred link, I give a use case that I hope would be resolved with the current proposal, i.e:

>A specific use case is when I'm currently dealing with core tiddlers for metric values, e.g font-size, story width etc. These tiddlers include units, e.g 14px. The RangeWidget directly edits a field but it only outputs a number... so it will need several complex steps just to append the "px" to that number and, worst of all, I believe it would require some manual action to do so ..."set the range slider AND then click the button" :-(

**Comment by pmario** [comment]
@twMat ... I think your usecase will be relatively simple to solve with the new action functions.

**Comment by pmario** [comment]
@saqimtiaz, @Jermolene mouse-move isn't possible, since it also fires, if the button isn't dragged, which makes the logic complicated. 

Using mouse-down and mouse-up makes it pretty simple to implement the same behaviour for all browsers. The new commit will contain some more lines of code, to deal with the quirks.

 - detect IE (1 liner).
 - if change event fires and isIE .. call IntupEvent handler instead
 - if change is detected and NOT IE .. default
 - on mouse-up and isIE ... we call changeEvent

This makes the stuff compatible. ... Once IE is deprecated, we can remove the additional code, which will be simple.

**Comment by saqimtiaz** [comment]
I suspect we are overcomplicating this, both conceptually and with mixing and matching terminology.

`handleInputEvent` doesn't need to be much more complicated than this:
```
RangeWidget.prototype.handleInputEvent = function(event) {
	if(this.getValue() !== this.inputDomNode.value) {
		if(this.tiddlerIndex) {
			this.wiki.setText(this.tiddlerTitle,"",this.tiddlerIndex,this.inputDomNode.value);
		} else {
			this.wiki.setText(this.tiddlerTitle,this.tiddlerField,null,this.inputDomNode.value);
		}
		if(this.actions) {
			this.invokeActionString(this.actions,this,event,{actionValue: this.inputDomNode.value});
		}
	}
};
```

`handleInputEvent` already does debouncing and the current implementation works well across browsers, allowing the slider to be used interactively so that you can see the changes as you drag the slider.

**Comment by pmario** [comment]
@saqimtiaz The  actions I'm interested in are the "change" and "mouse-up", that are fired, when the button is released.

**Comment by saqimtiaz** [comment]
> The actions I'm interested in are the "change" and "mouse-up", that are fired, when the button is released.

@pmario why? That is inconsistent with how the `range` widget currently works, and [as Jeremy mentions](https://github.com/Jermolene/TiddlyWiki5/issues/5029#issuecomment-726926797) it seems far too restrictive. Using actions should extend the possibilities currently available with the `range` widget, not restrict them. The current implementation allows interactive use, is debounced and has no performance problems, and allows more possibilities.

What you suggest also doesn't provide a satisfactory solution to use cases like the one in #3252 as you have to release the slider to see changes take effect.

**Comment by pmario** [comment]
That's why we need all of them. The user can decide, which one to use

**Comment by saqimtiaz** [comment]
I don't see any benefit, only unnecessary complexity. But I'm willing to be convinced otherwise, and will wait to see your code and hopefully some examples of use cases that warrant this.

**Comment by rmunn** [comment]
Speaking for the moment as a potential user of this feature rather than as a developer, I (as a potential user) would want the `change` and `input` events to be available as they're handled by all modern browsers (i.e., not IE). That is, I want to be able to react to two things:

* Did the user move the slider? (The `input` event).
* Did the user decide "Yes, that's the value I want" by releasing the mouse button after moving the slider? (The `change` event).

One example of how someone could use this would be an image-scaling widget that would show a preview of the scaled image as the user drags the slider around, and would only save the actual scaled image to a tiddler when the user commits to the slider value by releasing the mouse button. I.e., on an `input` event the widget would calculate a new image scaled appropriately and insert that into the preview tiddler, and on a `change` event it would save the actual image tiddler.

I also would want to be able to *not* react to the `input` events, because in some use cases I wouldn't care about them. E.g., in another use case I can think of, I would want to use the slider to assign a value to a "how many people in this group?" state tiddler, with possible numbers (in my use case) between 1 and about 5 or 6. In this case, I wouldn't care about any preview, and would want to be able to tell the widget to NOT hook up the `input` event for efficiency's sake. The simplest way of doing that, of course, would be to not specify an `inputAction=...` parameter to the range widget, and then the widget only hooks up events that the user actually wants to handle.

**Comment by saqimtiaz** [comment]
@pmario can this be closed?
