### ISSUE TITLE
[BUG] New $:/Import in TW 5.1.23 too much information

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5048]
**Describe the bug**
I tried to re import a plugin two times and I got the below status message

```
(requires reload) Blocked plugin (due to incoming 2.1.1 being older than existing 2.1.1)
A tiddler with this title already exists. 
```

1. It says required reload, but then says it is blocked. This is confusing!
2. It says incoming 2.1.1 is older than existing 2.1.1, but it is not correct! They are the same
3. It says A tiddler with this title already exists.

I may recommend to use a clear status message here

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Drag and drop a sample plugin (I did this with my own plugin)
3. Save and reload (if required)
4. Repeat step 2
5. See the message

**Expected behavior**
A clear status message is required.

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/99190352-55455580-277b-11eb-826c-3c1aebfea961.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 10
 - Version TW 5.1.23

**Comment by saqimtiaz** [comment]
@kookma this is useful feedback, thank you. I struggled a bit with the same issue of too much information in the Status column when working on the import UI recently. However, I am unsure as to how much we can resolve at the moment and therefore decided this was better tackled as part of a redesign, see #5013.

> * It says required reload, but then says it is blocked. This is confusing!
Right. One of the issues here is that status messages don't take into account other messages. For instance, if a tiddler is blocked due to being older, we probably don't need to display any other information.

> * It says incoming 2.1.1 is older than existing 2.1.1, but it is not correct! They are the same
From what I recall the import process only allows importing plugins that are newer than the current version. So a more accurate message might be: "Incoming 2.1.1 is not newer than existing 2.1.1". 
This should be fixable but we would need consensus on what the exact text should be.

> * It says A tiddler with this title already exists.
Which is redundant for a tiddler that is blocked and cannot be imported. However, this message is created by wikitext and has no reliable/easy way of knowing if the tiddler is blocked as those messages are handled by JavaScript. We might be able to address this by checking the tiddler field corresponding to the status message for that tiddler. I'll have a look if I can find the time.

**Comment by kookma** [comment]
Thank you @saqimtiaz I am in favor of https://github.com/Jermolene/TiddlyWiki5/issues/5013.

**Comment by saqimtiaz** [comment]
I've had a bit of a look. Here are some things we can do relatively easily for 5.1.23:
- If a plugin is blocked, do not display the `(requires reload)` message. ([Code](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/upgraders/plugins.js#L60))
- Modify the [message](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/language/en-GB/Import.multids#L22) `Upgrader/Plugins/Suppressed/Version` from `Blocked plugin (due to incoming <<incoming>> being older than existing <<existing>>)` to `Blocked plugin (due to incoming <<incoming>> not being newer than existing <<existing>>)`

I haven't looked at [system and state tiddler handling](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/upgraders/system.js) yet.

**Comment by kookma** [comment]
> * If a plugin is blocked, do not display the `(requires reload)` message. ([Code](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/upgraders/plugins.js#L60))
Yes!

> * Modify the [message](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/language/en-GB/Import.multids#L22) `Upgrader/Plugins/Suppressed/Version` from `Blocked plugin (due to incoming <<incoming>> being older than existing <<existing>>)` to `Blocked plugin (due to incoming <<incoming>> not being newer than existing <<existing>>)`

Yes!

These changes make things much more clear!
