### ISSUE TITLE
[Question] How to do debugging?

### ISSUE THREAD

**Issue by zhangaz1** [Jermolene/TiddlyWiki5#5093]
is there a way to debug the tiddler/macro/widget?

**Comment by saqimtiaz** [comment]
@zhangaz1 in the soon to be released TiddlyWiki 5.1.23 there are two widgets that can be used for debugging:
`action-log` and `log`.

They are available via the 5.1.23 pre-release at the moment:
https://tiddlywiki.com/prerelease/#ActionLogWidget:ActionLogWidget%20LogWidget

**Comment by AnthonyMuscio** [comment]
There are a lot of ways to introduce debugging methods in macros and wiki text, and with widgets just by making use of existing feature's. I do this a lot, I also build up my code testing as I go. You can make your own debug macro that tests for a debug mode setting and only displays additional content when in debug mode.

- There is also the preview mode on the editor see also the core plugin $:/plugins/tiddlywiki/internals
- The `<<transclusion>>` variable and dump variables widget can help.
- The new widgets Saq mentions are good for action-widgets which are otherwise somewhat invisible.
- Using <$text text=<<var or macro>> /> is a common method, and may indicate you need to wikify a value before use.

Regards
Tony

**Comment by zhangaz1** [comment]
@saqimtiaz & @AnthonyMuscio : thanks, I will to try. 

is there a way to debug wikitext rendering like javascript "debugger;" symbol, to step in in browser devtool bar?

**Comment by zhangaz1** [comment]
> There are a lot of ways to introduce debugging methods in macros and wiki text, and with widgets just by making use of existing feature's. I do this a lot, I also build up my code testing as I go. You can make your own debug macro that tests for a debug mode setting and only displays additional content when in debug mode.
> 
> * There is also the preview mode on the editor see also the core plugin $:/plugins/tiddlywiki/internals 
> * The `<<transclusion>>` variable and dump variables widget can help.
> * The new widgets Saq mentions are good for action-widgets which are otherwise somewhat invisible.
> * Using <$text text=<> /> is a common method, and may indicate you need to wikify a value before use.
> 
> Regards
> Tony

**Comment by zhangaz1** [comment]
@AnthonyMuscio : I have try the plugin internals, it's very useful. 

but I don't know how to do debug by these way:

* The <<transclusion>> variable and dump variables widget can help.
* The new widgets Saq mentions are good for action-widgets which are otherwise somewhat invisible.
* Using <$text text=<> /> is a common method, and may indicate you need to wikify a value before use.

**Comment by saqimtiaz** [comment]
@zhangaz1 if you are thinking of debugging in JavaScript with breakpoints, we do not have anything like that for wiki text.

However you can use the widgets <$action-log> and <$log> to see how the values of your variables change in a block of wikitext or actions.

```
<$vars name={{!!myname}}>
<$action-log $tiddler="mytiddler" myfield=<<name>> />
<$action-setfield $tiddler="mytiddler" myfield=<<name>> />
</$vars>
```

**Comment by zhangaz1** [comment]
@saqimtiaz got it, thanks!
