### ISSUE TITLE
[BUG] TW server creates $:/StoryList.tid in wrong directory.

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5208]
To reproduce: 

 - Use 5.1.23pre

Download the latest repos to eg: /temp/

 - https://github.com/wikilabs/editions/tree/master/edit-tabs-server  and
 - https://github.com/wikilabs/editions/tree/master/edit-tabs
 - `cd ./edit-tabs-server`
 - `npm run start` ... It will start a server 
 - If you open the page  http://localhost:8080 it will create the $:/StoryList in the wrong directory.
    - I don't want it to be saved at `edit-tabs/tiddlers/`, because this makes problems for published versions. 

 `tiddlywiki.info` in the server directory is

```
	"includeWikis": [
		"../edit-tabs"
	],
	"config": {
		"default-tiddler-location": "../edit-tabs/tiddlers"
	}
```

`default-tiddler-location` is `edit-tabs` **but** I don't want `$:/StoryList` to be saved, to the position, where it came from

## Expected

The $:/StoryList, which is loaded from `edit-tabs-server/tiddlers/$__StoryLIst.tid` should be used to save the file`. It should 
**not** be part of the "production wiki"! 

@rimi, @saqimtiaz, @Jermolene ... There is still a problem with the new syncer!

**Comment by pmario** [comment]
If it gets complicated in the code, to do this, just tell me, what I need to do with the new config tiddlers. ... BUT that needs be "simple"!

**Comment by saqimtiaz** [comment]
@pmario this would be an issue with the `fileInfo` fix rather than the `syncer`.
See #5176 and #5113

@joshuafontany could you please take a look?

**Comment by saqimtiaz** [comment]
@pmario I suspect something like this in `$:/config/FileSystemPaths` would fix the problem for you:
`[prefix[$:/StoryList]removeprefix[$:/]]`

However we should check and make sure that the underlying behaviour in the case of `includeWikis` is correct. I have never used this option so I am not familiar with what the behaviour is supposed to be like.

**Comment by joshuafontany** [comment]
I don't think that would work. You would need to include the relative path back to the "/tiddlers" folder in the folder that the primary tiddlywiki.info file was loaded from.To catch all system tiddlers you would want `[prefix[$:/]removeprefix[$:/]addprefix[../../edit-tabs-server/tiddlers/system]]`.

I also noted that the `$:/StoryList` was saved to the folder defined in a tiddlywiki.info's "default-tiddler-location" property during the `tw.com-server tests`. I assumed this was correct because of the recent changes to how system tiddlers are synced (currently being saved to the server, but not synced back). If there is an existing `$:/StoryList` in the tiddlywiki.fino /tiddlers folder, it should be loaded & saved back correctly (with path listed in `$:/config/OriginalTiddlerPaths`, but if there is no `$:/StoryList` on disk and you have told the config to save all files to the "default-tiddler-location", that is where all newly written files will go.

Its an interesting problem. Because the paths in `$:/config/OriginalTiddlerPaths` were never used before, this is newly defined behavior. But this bug seems like it would pop up in previous versions, if the $:/StoryList is not defined on startup, but the default-tiddler-location points out of the folder the info file was loaded from.....

**Comment by joshuafontany** [comment]
Yes, 5.1.22 writes new system tiddlers to the directory defined in  "default-tiddler-location".

**Comment by joshuafontany** [comment]
And the bug manifests with ./bin.serve.sh but not when starting node.js debugger via VSCode. Fun..... Time for some deep debugging...

But when the bug occurs, it writes the file with an encoded filename, interesting... I wondering if we are triggering different code paths somehow...

**Comment by joshuafontany** [comment]
Aaah, it was user input sensitivity. I was passing a full path for the wiki to be loaded, most of the scripts pass a relative path.

And we are storing that as-is in `$tw.boot.wikiPath`, which fails the compare test later to see if the new file-location starts with the wikiPath. Ok, going to fix this up, and take the opportunity to improve the performance of some of the functions called.

**Comment by joshuafontany** [comment]
https://github.com/Jermolene/TiddlyWiki5/pull/5213 should patch this bug, specifically calling path.resolve() on line 385 of filesystem.js. Mahalo @pmario for catching this before release!

**Comment by Jermolene** [comment]
Thanks everyone
