### ISSUE TITLE
[BUG] Is anybody else noticing that jasmine doesn't work anymore on browser?

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#5243]
Jasmine still works with the core testing framework in `editions`, but ever since the fix for #5210 (Dec 4th) came in, jasmine no longer runs in the browser for any of my projects, including Relink.

I'm still looking into this, but I'm coming into this cold. Does anyone know why the single line: `exports.after = ["commands"];` would cause the tests to stop initializing?

**Comment by flibbles** [comment]
Actually, scratch that. I doesn't work with the core testing framework either. I hadn't refreshed it properly.

**Comment by flibbles** [comment]
Okay. Stepping through the code. It looks like it never runs because it's waiting on the "commands" startup task to finish, but it never runs because it's configured to only run on NodeJS.

@Jermolene, might it be appropriate to remove startupModules from the `remainingStartupModules` list if it's never going to run at all?

@ento, pinging you on this, since this is code you were working on.

**Comment by ento** [comment]
Whoops, thanks for diagnosing, @flibbles 

> might it be appropriate to remove startupModules from the remainingStartupModules list if it's never going to run at all?

The check for the `after` constraint requires that the specified modules are marked as executed in `$tw.boot.executedStartupModules`:

https://github.com/Jermolene/TiddlyWiki5/blob/50d8325d4c9f17892ec36e9fc818cfcb3655f150/boot/boot.js#L2498-L2506

So I think removing the commands module from `remainingStartupModules` will still leave `jasmine` hanging.

We could...

1. Move the `$tw.boot.doesTaskMatchPlatform()` check to right before calling `task.startup()` and skip the call if platform does not match. Otherwise, do all other housekeeping stuff like marking it as executed. There could be unforeseen (further) regression from this change.
2. Add a way to say "this startup module should be executed last"..? I feel like this'll add too much complexity if any of the other alternatives suffice
3. Set jasmine's `.after` constraint conditionally based on the current platform.
4. Revert the offending PR. Make it so that Node.js tests are only run when a `--runtests` command is specified, and change `bin/test.sh` to do two passes: one to run Node.js tests, one to generate HTML.
5. (...are there other ways to fix this?)

I'll work on 1) to see if it works in practice (this feels like the most fundamental fix) and look into running browser tests in CI as well.

**Comment by flibbles** [comment]
I would say set jasmine's `.after` constraint to be conditional based on current platform. The change only needs to be in jasmine then, not in the boot code. Especially this close to V5.1.23, making changes to the actual module loader could be risky, or non-backward compatible.

Also, I would probably give the jasmine module a name, like `exports.name = 'jasmine'` or something. Not related to what you're doing, but I noticed while debugging the code that every other startup module has a name, but jasmine is undefined, which means no one can disable it or set start up modules around it.

**Comment by flibbles** [comment]
Also, should a more major change come down the line, this conditional setting of `exports` in jasmine won't break anything, or have any back-compat problems.

**Comment by Jermolene** [comment]
Thanks @flibbles @ento. Fix (3) does indeed sound like the lowest impact.

**Comment by ento** [comment]
> Especially this close to V5.1.23, making changes to the actual module loader could be risky, or non-backward compatible.

Yup, that makes sense. I can do a PR with (3) (+ setting a name on the module).

**Comment by ento** [comment]
-> #5254
