### ISSUE TITLE
[BUG] Add documentation for unique[] filter operator

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#5310]
Presumably as an oversight, the [unique[]](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/filters/x-listops.js#L180) listops filter is undocumented.

**Comment by flibbles** [comment]
I literally rewrote the unique operator for myself once because I didn't think it existed. I was actually planning to do this as part of my LinkedList conversion. I was also thinking of introducing the obvious complement.

Input: cats dogs cats lizards cats birds dogs bugs
`[unique[]]` -> **cats** **dogs** cats **lizards** cats **birds** dogs **bugs**
`[!unique[]]` -> cats dogs **cats** lizards **cats** birds **dogs** bugs

But that's neither here nor there. Unique is useful to users, and I agree it needs documentation.

**Comment by clutterstack** [comment]
I had a look at this today, as I couldn't find a pull request on the subject. The problem is that I've never used the `unique[]` filter. I don't know what consequences that has for my reading of it. For one thing, my example may not be the most interesting.

I'm also not sure that `unique` is usefully described as an Order Operator, but if it is not tagged as such, it will not show up in the Extended List Operators table in the ActionListopsWidget tiddler.

If the below screenshot looks like a useful start, I can make it into a PR.

![Screenshot_2021-02-16 TiddlyWiki — a non-linear personal web notebook(4)](https://user-images.githubusercontent.com/5599856/108139482-26968e00-708e-11eb-8930-7778364c5483.png)

**Comment by saqimtiaz** [comment]
@clutterstack those docs look good to me.

**Comment by clutterstack** [comment]
PR #5651 submitted.

**Comment by saqimtiaz** [comment]
Closed in #5651
