### ISSUE TITLE
[BUG] Svg color in tag pill does not match the text color

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5318]
**Describe the bug**
The color of svg in the tag pill does not match the text color

**Expected behavior**
Color of svg and text shall be the same. 

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/103126255-f5f43280-46a2-11eb-8f75-b8d69f8d739d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Chrome 87
 - Version 5.1.23

**Comment by rmunn** [comment]
When you talk about the "svg" here, you mean the X that can be clicked to remove the tag, right?

**Comment by kookma** [comment]
> When you talk about the "svg" here, you mean the X that can be clicked to remove the tag, right?

Yes, Am I wrong? Isn't it a svg image? I assume if it is a text like `x` then it will be while! I did not check the underlaying code!

**Comment by rmunn** [comment]
Yes, I just checked and it's an SVG. My question was just to clarify what it was, because I didn't know immediately what you meant when you talked about the "svg". And there can be more than one SVG in a tag pill, by the way. In the "done" tag pill, there's a checkmark before the word "done" that's an SVG and is the same as the text color, while the X after the text is an SVG whose color is not necessarily the same as the text color.

**Comment by kookma** [comment]
@rmunn - I think in the case I sent above it is better to have the `x` in white color. Let's see what @BurningTreeC  says in this regard.

**Comment by BurningTreeC** [comment]
Hi @kookma @rmunn ,

this cross doesn't have the color of the tag-pill-text because of a recent css change for the `tc-btn-invisible` fill color.
there's a pretty quick solution for that though, I'll create a PR
