### ISSUE TITLE
[IDEA] Display "caption" or "plugin-title"|"caption", etc. for plugins

### ISSUE THREAD

**Issue by diego898** [Jermolene/TiddlyWiki5#5509]
**Is your feature request related to a problem? Please describe.**
Nico's excellent [Projectify](https://projectify.wiki/demo.html) comes with [excellent documentation](https://projectify.wiki/demo.html#%24%3A%2Fplugins%2Fnico%2Fprojectify%2Fdoc%2FHelp). Its strange/off-putting for these tiddlers to have such unsightly titles when they are so "public facing". Of course, they must to be "part of the plugin".

**Describe the solution you'd like**
I think it would be slightly less intimidating+more helpful (at the very least, more aesthetically pleasing) if plugin "subtiddlers" could display a "pseudo title", something like: 

"Projectify ❯ Help", where Projectify would come from a "plugin-title" field, and "Help" would come from "caption", etc. 

**Additional context**
* This would of course only affect the ViewTemplate, and editing the tiddler would reveal its "real" title anyway. 
* Additional idea: if a plugin author specifies a "plugin-color" or something, all plugin tiddlers can have that same background color or something, just to serve as an additional indication that these tiddlers "belong together".

**Comment by Jermolene** [comment]
Hi @diego898 I appreciate the problem. We could indeed extend the view template to display an alternative, friendlier title when available. My concern is that things are more confusing if there's exceptional behaviour. Instead of saying "here is where the title of the tiddler is displayed" we'd have to say "here is where the title of the tiddler is displayed, unless there's a caption field in which case that is displayed instead". The cumulative effect of lots of complexity along those lines risks overwhelming users.

Generally, I'm relaxed about TiddlyWiki showing its workings: using TiddlyWiki effectively requires a level of understanding of how it works, and each time we expose the workings we provide a learning opportunity for people.

In this case, there are a few other things we can do to address the problem:

* The problem only occurs if the plugin tiddlers are displayed in the story river. That can be avoided by displaying the content elsewhere, for instance like the floating help panel in the official plugin library, or a sidebar tab, or a modal
* We can just go ahead and use non-system tiddler titles for shadow tiddlers. The chances of a random TiddlyWiki containing a tiddler titled "Projectify -> Help -> Start" might be considered quite low

**Comment by diego898** [comment]
Hey @Jermolene - to your second bullet point, yes this is how other plugin authors have solved it, and that documentation stays local to the "demo page" unless you yourself drag it over.

I was just thinking that the idea of "shadow" tiddlers and tiddlers whose titles start with "$:/" can feel "dangerous" to new users. I appreciate that in TW the internals are bare. Indeed, thats what attracted me to it. 

I was just thinking that if: 

1. the core is to remain as small as possible
2. empty will be the standard version to distribute to everyone

then we can stand to make plugins a "bit easier": to find, to install (ie: not having to search google groups for them), to read through, interact with, etc.
