### ISSUE TITLE
[IDEA] Editor needs indentation

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#5515]
**Describe the bug**
In the editor, indenting for readability currently has to be done by using multiple *spacebar characters*. This is a problem because it increases file size, and it is difficult to align things when the indentations are bigger. Worst, the created distance appears different in different editors so text that is aligned in one editor may be totally misaligned in another which is particularly distracting when collaborating on a project.

This issue is somewhat related to #4398

**Proposal**
A way to directly via the keyboard type a character (not *copy-pasting* one), presumably **the `tab` character.**

**Screenshots** (..well....)

```
<$list
  filter="[[long filter taking up whole editor width]]
          [[additional filter neatly aligned for ease on eye]]
>
```
becomes

```
<$list
     filter="[[long filter taking up whole editor width]]
                [[additional filter neatly aligned for ease on eye]]
>
```

**Comment by rmunn** [comment]
First thought: the Tab character has wide use in accessibility. People who have trouble using a mouse (limited mobility) often use keyboard navigation features of their browser extensively, hitting Tab to move from one control to another, and Space to activate controls (press buttons, check checkboxes, and so on). If the editor grabs the Tab character for itself, that could badly affect people who need the Tab character for navigating their browser controls. A visual enhancement feature (like alignment) that's merely "nice to have" for some users should never take away from accessibility features (like Tab navigation) that's essential for other users. That's not to say that we can't add a feature where the editor captures the Tab key to insert indentation, but we **must** make it an optional feature **that defaults to being OFF**, so that people who rely on the Tab character for browser navigation don't get "stuck" on the editor with no ability to get back to the settings to turn the feature off.

Second thought: if you're lining up text from different lines while using a proportional font, you're never going to get alignment right, because as you point out the width will vary from editor to editor. Fixed-width fonts are required if you're going to align different lines.

Third thought: if you're using tab characters for alignment, you're never going to get alignment right, because the width of tab characters can vary from editor to editor. GitHub defaults to showing them as 8, VS Code shows them as 4, and some people (especially when working in Javascript) like to set their editor's tab settings to 2. And if the number of spaces you need for alignment is not an exact multiple of your tab size (for instance, in the example you gave you'd need 10 spaces in the "additional filter" line to line it up neatly with the "long filter" line), then you're going to need to insert space characters *anyway* to get the alignment you want.

So the best way to get the result you're asking for is for the Tab **key** to insert a number of space **characters** (exact number configurable in an option), to reduce the amount of pressing the space key that you have to do. Furthermore, you'll want to change the Editor Font Family setting (in Appearance) to use a fixed-width font (perhaps the same list as the Code Font settings) so that your alignment will work.

**Comment by twMat** [comment]
@rmunn - much appreciated input. 

In spite of your points, some way to get indentation is needed. **How do all other code editors solve indentation?**

Your last paragraphs suggests a key to insert multiple space characters in one click. That's better than currently but it is still not good because arrow stepping through this is tedious and each extra character = 1 byte.

**Comment by Jermolene** [comment]
Hi @twMat my usual workaround for this is the CodeMirror editor, which respects the tab key to insert tab characters.

**Comment by saqimtiaz** [comment]
As @Jermolene mentions, it sounds like you want an editor optimized for coding, i.e. CodeMirror.

Otherwise you should be able to setup a editor toolbar button that inserts a tab character and uses the tab key as a shortcut.

**Comment by twMat** [comment]
> the CodeMirror editor

OK, thanks everyone.

**Comment by morosanuae** [comment]
My humble opinion is that the TAB indentation should be available by default, without the need for an extra plugin or extra modifications. I often have the need to quickly indent the code with TABS in newly created demo wikis and the missing TAB indentation always becomes a source of frustration. But I never choose to install the CodeMirror plugin, I prefer to copy and format the code in Notepad++ as it is much quicker. Anyway, I don't really understand why such basic functionality is not included by default? Is there a technical obstacle preventing this?

**Comment by Jermolene** [comment]
> My humble opinion is that the TAB indentation should be available by default, without the need for an extra plugin or extra modifications. I often have the need to quickly indent the code with TABS in newly created demo wikis and the missing TAB indentation always becomes a source of frustration. But I never choose to install the CodeMirror plugin, I prefer to copy and format the code in Notepad++ as it is a much quicker method. Anyway, I don't really understand why such basic functionality is not included by default? Is there a technical obstacle preventing this?

We maintain the browser default behaviour of the tab key because that is the norm for accessibility purposes. We understand the need for some users to enter tab characters directly, and believe that the CodeMirror editor is a good solution for those users.

There is no technical reason why the core editor couldn't support an option for inserting tabs directly. My personal opinion remains that the CodeMirror plugin is a reasonable solution to the problem, and we shouldn't make the core editor any more complicated.
