### ISSUE TITLE
[BUG] Hiding Missing Links is broken for static copies of TiddlyWikis on versions above 5.1.17

### ISSUE THREAD

**Issue by tenkabuto** [Jermolene/TiddlyWiki5#5539]
When I generate my static TiddlyWiki site via versions of TiddlyWiki NodeJS above 5.1.17, my static site includes links to tiddlers that do not exist (are "missing"), making a broken link. It seems like 5.1.18 introduced this issue.

The "Enable links to missing tiddlers" setting is disabled in my TW, and missing tiddlers are not linked to inside the TW web interface. But they are linked to when I generate a static site version of the TW.

# Steps to reproduce
1. Use a version of TW above 5.1.17
2. Produce a static version of a TiddlyWiki that has a link to a missing tiddler and the "Enable links to missing tiddlers" setting is disabled
3. Check if the link to the missing tiddler appears in the static copy

# Expected behaviour
Generated static versions of TiddlyWikis would have links to missing tiddlers hidden or not hidden according to the "Enable links to missing tiddlers" setting and if they're linked to via the full TiddlyWiki interface.

# Context (OS, browser etc.)
I'm using Linux in Ubuntu, but I'm not sure which platform this most pertains to.

**Comment by saqimtiaz** [comment]
@tenkabuto I'm unsure as to why this worked in TW <5.1.18 as you mention. However this issue is most likely because your template for static HTML generation doesn't transclude the default PageTemplate (which defines the tv-showing-missing-links variable) and also doesn't define `tv-showing-missing-links` on its own. One of the two would be needed.

You can either wrap your template with a `vars` widget to set the value of `tv-showing-missing-links` to the value of the `$:/config/MissingLinks` tiddler

`<$vars tv-show-missing-links={{$:/config/MissingLinks}}>`

OR you can define a hardcoded value for it by adding a macro definition at the very beginning of your static template:

`\define tv-show-missing-links () no`

**Comment by tenkabuto** [comment]
@saqimtiaz This did indeed fix the issue. Thank you! I'm amazed that you were able to infer that this was the issue with my setup.
