### ISSUE TITLE
[IDEA] Make the keybaord widget more "hackable"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#5618]
@Jermolene We do have widget subclassing now. I would like to restructure the keyboard widget a little bit, so it's possible to make it easier to change the `.handleChangeEvent()`

At the moment the keyboard widget can't pass variables on to the actions it calls. ... 

At the moment the `.render()` function is a big junk of code that also contains the "keydown" event

```
KeyboardWidget.prototype.render = function(parent,nextSibling) {
	var self = this;
	// Remember parent

// ------------- snip

	domNode.addEventListener("keydown",function (event) {
		if($tw.keyboardManager.checkKeyDescriptors(event,self.keyInfoArray)) {
			var handled = self.invokeActions(self,event);
			if(self.actions) {
				self.invokeActionString(self.actions,self,event);
			}
			self.dispatchMessage(event);
			if(handled || self.actions || self.message) {
				event.preventDefault();
				event.stopPropagation();
			}
			return true;
		}
		return false;
	},false);

// ------------- snip
};
```

I would like to have it similar to:

```
KeyboardWidget.prototype.render = function(parent,nextSibling) {
	var self = this;
	// Remember parent

// ------------- snip

	// Add a event handler
	$tw.utils.addEventListeners(this.inputDomNode,[
		{name: "keydown", handlerObject: this, handlerMethod: "handleChangeEvent"}
	]);

// ------------- snip
};
```

Is there a chance you'd merge it?

**Comment by pmario** [comment]
I did have a closer look about the possibilities the [keyboard-widget](https://tiddlywiki.com/#KeyboardWidget) has. The `key` parameter is capable of handling a keys-array. eg:

tiddler `test-note` needs to be eg: "I was here!"

```
\define notify()
<$action-sendmessage $message="tm-notify" $param="test-note" />
\end

<$keyboard key="1 2 3 a b c enter escape" actions=<<notify>> >
  <$list filter="1 2 3 a b c" variable=index>
    <<index>>, 
  </$list>
  <$edit-text tiddler="demo-key-xxx" tag=input disabled=yesX focusX />
</$keyboard>
```

The problem is, that `notify()` doesn't get any info ... 

!! The proposal

.. is, that the following info should be given to the action. 

```
key = "1", 
keyCode =  "49"
shiftKey = "yes/no"
altKey = "yes/no"
ctrlKey = "yes/no"
metaKey = "yes/no"
```
as  defined at: https://github.com/Jermolene/TiddlyWiki5/blob/85ba7ac041ef4e17c1ebed3132ca6c08c3dc4602/core/modules/keyboard.js#L270-L275

This will allow the `notify()` action to be extremely simple and powerful. May be `extraKey = metaKey or altKey` to make it easier to define Mac and Windows/Linux at the same time.

**Comment by Jermolene** [comment]
Hi @pmario both refactoring the event handler into a separate method and passing the additional variables seems reasonable, please do go ahead.

**Comment by saqimtiaz** [comment]
@Jermolene @pmario I am wondering if extending `<$keyboard>` with these variables is the best way to go, or if perhaps we should cater for this use case in `<$eventcatcher>`? While the keyboard widget does support multiple `key strings` in the `key` parameter, this seems designed for multiple `key strings` that trigger the _same action_. 

On the surface the proposal to extend  `<$keyboard>` in this manner to allow differentiating between different keys in the action string seems viable. However, when used with the `key descriptor syntax`, such as `((my-shortcut))`, ([which allows making shortcut keys configurable via the Control Panel](https://tiddlywiki.com/#Keyboard%20Shortcut%20Descriptor)), this is going to become very problematic if at all possible. Can we have an example of how this would be done in the action string? If it is possible and we can document how to do so, that would make this a more viable option.

Otherwise `<$keyboard>` is a relatively easy to use widget that can handle shortcuts at a higher level than keycodes and is thus approachable for users. Introducing the complexity of variables associated with `keyCodes` etc is likely to lead to confusion even if this is an additional optional feature.

Instead could we extend `<$eventcatcher>` to provide the `key` and `keyCode` information for `keydown` events? The `modifier` variable is already provided. This is already a widget targeted at advanced users and it makes sense to further flesh it out. When we introduced `<$eventcatcher>` we had intentionally foregone specific handling of `keydown` events and associated event attributes as we assumed the higher level handling in `<$keyboard>` would be sufficient.

**Comment by pmario** [comment]
I will publish a POC soon. It will use dynamically created keys. It will be used to extend the edit toolbar buttons. 

Initially I only used the `key` info. But debugging the code, I saw that the proposed extra info is very easy to reach, because the existing js variables already contain the info. So only a little bit of "yes/no" boolian adjustments had to be made.

**Comment by saqimtiaz** [comment]
@pmario a POC would be helpful but please make it a minimal one that is easy to follow without needing to understand code that isn't directly relevant to the proposal.

Do note that we already have established precedence from several widgets for how we pass information regarding modifier keys to action strings and the implementation here would need to be consistent: https://github.com/Jermolene/TiddlyWiki5/search?q=getEventModifierKeyDescriptor
