### ISSUE TITLE
[IDEA] allow access wiki on PC via scanning QR code

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#5669]
**Is your feature request related to a problem? Please describe.**

I'd like to scan QR code from the nodejs wiki running on localhost PC, and edit wiki on the phone.
But scanned url started with https://localhost, which is unable to access in the phone.

**Describe the solution you'd like**

The `$:/info/url/hostname` is currently `localhost`, despite of my starting option being [`'host=0.0.0.0',`](https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/f9c12a8225ff139f3c5488a99381e11383bdccb1/src/services/wiki/wikiWorker.ts#L41)

I think it should be the actual ip, when hostname parameter set to '0.0.0.0' when using nodejs wiki.

**Describe alternatives you've considered**

Maybe add another option, that generates a QR code with the actual ip. instead of using:

https://github.com/Jermolene/TiddlyWiki5/blob/d8ac00a10856b1b64311b8e0496344d5b0c1b987/plugins/tiddlywiki/qrcode/ViewToolbarButton/URL.tid#L10

**Additional context**

I hope I can use nodejs wiki in the phone.

**Comment by rmunn** [comment]
In your `startNodeJSWiki` function, would you be able to detect the IP address of the local Ethernet / WiFi connections, and pass that in to the `host` option instead of `host=0.0.0.0`? I haven't looked at TiddlyWiki's QR code generation so I don't know if there's a bug in it that ignores the `host` option, but it seems to me that your `startNodeJSWiki` function will be the best place to figure out the IP address that you need to listen on, and then pass that to TW. (And you could make it user-configurable so that people who need to listen on a specific adapter, say on Ethernet but *not* WiFi, can do so).

**Comment by linonetwo** [comment]
@rmunn I don't quite understand

> people can listen on a specific adapter, say on Ethernet but not WiFi

How to achieve this?

And, for the `host=0.0.0.0`, yes, maybe I should pass IP using 

```js
import ip from 'ip';
const localHostIP = ip.address()
```

**Comment by rmunn** [comment]
What I mean is that let's say someone has a computer with an Ethernet adapter and WiFi that are on two different networks. Say the Ethernet adapter is connected to the 192.168.1.x network and the WiFi adapter is on the 192.168.2.x network. The user may want to run TiddlyWiki on the WiFi network but not the Ethernet network, or the other way around.

So if you let your Node.js script take a `--host` argument on the command line, then the user could run it with `--host 192.168.2.x` to have TiddlyWiki listed only on the WiFi adapter's address, so it will respond to HTTP requests coming in the WiFi network but won't respond to HTTP requests coming in on the Ethernet network.

Now, since you're trying to make TiddlyGit-Desktop as easy to use as possible for people who aren't computer experts, maybe you don't want to use a command-line argument for that, and instead you'd want to use a menu option, or a checkbox in a dialog box somewhere. But the point is, your script could probably detect the IP addresses of the computer's network adapters, and if more than one network adapter has a valid IP address, you'd probably want some way of letting the user say "Only run TiddlyGit-Desktop on *this* adapter and not *that* one." I work almost exclusively on Linux so I don't know how Windows and OS X will declare their network adapters and how to detect them, but hopefully that shouldn't be too hard for you to find out.

**Comment by linonetwo** [comment]
I think this should be done in user-side, provide correct IP when starting a wiki, closing this.
