### ISSUE TITLE
Provide easy access to system tags

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#569]
All system tags $:/tags/... have disappeared from the tags list in the Sidebar.
In this way it becomes difficult to see which tiddlers are tagged with e.g. $:/tags/stylesheet.
You have to find a tiddler tagged with $:/tags/stylesheet and click the tag.

I suggest to add a tab System tags (below the tab Tags) with something like:

<$list filter="[all[tiddlers+shadows]tags[]is[system]sort[title]]">

<$transclude tiddler="$:/core/ui/TagTemplate"/> <small class="tw-menu-list-count"><$count filter="[all[current]tagging[]]"/></small>

</$list>

**Comment by tobibeer** [comment]
> As long as there will be system tag pills (so you can click them), I don't mind where. But the "systems tags" filter is not enough; it is only a listing.

There are a few options:

1. use that filter, click on a result, then open the **IntoPanel > Tagging**
    * *good enough for me*
2. we use a template for the advanced search result list in the filter tab that also renders a tag-pill, if a tiddler is a tag, rather than just a link
    * *possibly the best solution, and helpful with any query in the filter tab*
3. we create a new tab, perhaps under **ControlPanel > Info > Advanced** and specifically list system tags
    * *too specific to my taste and hence not all too useful, unless a one-liner would indicate what that system-tag is for*

**Comment by gernert** [comment]
I made a plugin to add a 'System tags' tab, available at http://tongerner.tiddlyspot.com/
