### ISSUE TITLE
[BUG] Internal JavaScript Error : when trying to open "$:/core/templates/html-tiddler"

### ISSUE THREAD

**Issue by msameen99** [Jermolene/TiddlyWiki5#5696]
**Describe the bug**
In TW5 Stable, Pre-release and Empty versions, when I tried to open the "$:/core/templates/html-tiddler" , I got the red
`Internal JavaScript Error:Uncaught RangeError: Maximum call stack size exceeded`
error message. 

**To Reproduce**
1. Go to 'https://tiddlywiki.com/' or 'https://tiddlywiki.com/prerelease/'
2. Try to open the '$:/core/templates/html-tiddler' tiddler
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16881960/118565542-a6f28b00-b772-11eb-8985-69ecdf27772d.png)

**Comment by pmario** [comment]
I do get a "too much recursion" error.

**Comment by saqimtiaz** [comment]
On Chrome I get the same error as @msameen99 

Currently we have similar issues when viewing most core template tiddlers. #5136 is related.

**Comment by pmario** [comment]
I think, this needs to be classified as a bug, because the tiddler can't be shown, because of the RSOD. I do get the RSOD with the message "too much recursion" ...

Other elements that have this problem, have a "recursion protection", so the tiddler can be opened and edited. This protection doesn't seem to work for this tiddler.

**Comment by pmario** [comment]
@Jermolene -- Can be closed, since this shadow tiddler is detected as template now and is shown in text/plain mode.

**Comment by Jermolene** [comment]
Thank you @pmario
