### ISSUE TITLE
[BUG] Tiddler loses focus when $tiddler is used

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#5746]
**Describe the bug**

**To Reproduce**
1. Go to https://tiddlywiki.com/prerelease/
2. Create a TEST tiddler with below content

```
\define tempTid() xx$:/temp
\define tempTid2() xx$:/temp2

!! Test 1: Loses focus

<$tiddler tiddler=<<tempTid>> >

St Name <$edit-text field="st-name" />

St Numb  <$edit-text field="st-number" />
</$tiddler>


!! Test 2: keeps focus

St Name <$edit-text tiddler=<<tempTid2>>  field="st-name" />

St Numb <$edit-text tiddler=<<tempTid2>>  field="st-number" />
```

3. Enter something in textbox Test 1: tiddler loses focus
4. Enter something in input textbox Test 2: tiddler keeps focus
5. Error: there is something wrong with $tiddler here

**Expected behavior**
Tiddler should remain in focus

**TiddlyWiki Configuration (please complete the following information):**
 - Version 5.124

**Comment by saqimtiaz** [comment]
@kookma this is the same underlying issues as when using an <$edit-text> widget to edit a field in the same tiddler.

The good news is that when the improvements described in #5736 are implemented, this will no longer happen.

**Comment by kookma** [comment]
Hi Saq,
but `<$tiddler tiddler=<<tempTid>> >` means using another tiddler

**Comment by pmario** [comment]
It seems it only looses the focus if the xx$:/temp tiddlers don't exist. If the tiddlers exist, I don't have a problem at tiddlywiki.com

**Comment by kookma** [comment]
Hi @pmario 

> It seems it only looses the focus if the xx$:/temp tiddlers don't exist. If the tiddlers exist, I don't have a problem at tiddlywiki.com

Yes I confirm this! focus is lost when temp tiddler is not exist!

**Comment by kookma** [comment]
@saqimtiaz  while #5736 has been merged but it seems this issue persists!

**Comment by pmario** [comment]
>@saqimtiaz while #5736 has been merged but it seems this issue persists!

I think that was the wrong PR number. It has to do with the "focus handling" PRs from BTC ... They may help

**Comment by saqimtiaz** [comment]
@kookma apologies I misinterpreted the issue here.

The issue here is that wrapping the edit-text widgets in a tiddler widget has the same problem as wrapping then in a vars widget, i.e. when a dependent tiddler changes they re-render their content.

I'll have a look later to see if there are improvements we can make here, but it may turn out that this is a limitation we need to work around.

**Comment by pmario** [comment]
I think the problem here is, that the focus is _only_ gone, if the the "target tiddler" doesn't exist. If it exists, there is no problem.

**Comment by saqimtiaz** [comment]
@pmario yes from what I recall of the code, the tiddler being missing or not is used to calculate the internal state of the tiddler widget.

**Comment by saqimtiaz** [comment]
@kookma the <$tiddler> widget [sets various variables](https://tiddlywiki.com/#TiddlerWidget) including `missingTiddlerClass` which is `tc-tiddler-exists` or `tc-tiddler-missing` depending on whether the tiddler exists.

When this variable changes, like when a tiddler that didn't exist is created, the widget has to refresh itself so that its children get the new value of the variable. This is similar to `vars/set/wikify` widgets and what happens when the value of the widget changes. 

So this isn't a bug, and it is something we cannot change because of backwards compatibility. If we were writing this widget today, we would do it differently because we have more options now with filters.

I would recommend using this pattern for this use case:

```
<$vars currentTiddler="xx$:/temp" >

St Name <$edit-text field="st-name" />

St Numb  <$edit-text field="st-number" />
</$vars>
```

**Comment by kookma** [comment]
Hi Saq,
Thank you for the detailed explanation and the solution provided!

Much appreciated!
