### ISSUE TITLE
tiddler/macro not refreshed after recent commits

### ISSUE THREAD

**Issue by cdruan** [Jermolene/TiddlyWiki5#5903]
The following setup no longer works after I synced up with the master branch. The last working version I had has commits up to May 23.

Added a default mapping for a color entry not present in the active palette, like this:

Tiddler `$:/config/DefaultColourMappings/fab-background` with the following content:

```
<$macrocall $name="color-contrast" color=<<colour page-background>> />
```

`color-contrast` is a JavaScript macro. When the palette's `page-background` color is changed, the value of `<<colour fab-background>>` should be updated accordingly (in a stylesheet). But in fact, the underlying JS function is never invoked.

Incidentally, if I replace the body of the DefaultMapping tiddler with either plain `<<colour page-background>>` or a filtered transclusion that ultimately calls the same JS function--e.g. `{{{ [<colour page-background>contrast[]] }}}`--then all colors are updated as expected.

**Comment by Jermolene** [comment]
Hi @cdruan apologies for the late reply, and thank you for the additional information. Just to confirm, does that example work in v5.1.23 but not in v5.2.0-prerelease? Do you know the exact commit that broke things?

**Comment by saqimtiaz** [comment]
I will admit I have never looked at the colour mappings and how they work, so creating a test case would be tricky for me.

However, the obvious culprit for refresh issues would be #5736. If indeed that is the culprit - despite rather extensive tests and multiple code reviews by multiple people - then I suggest we revert it for 5.2.0 and revisit the idea at a later time.

**Comment by cdruan** [comment]
@Jermolene @saqimtiaz 

Yes, the example given works in v5.1.23 as well as the earlier versions of the pre-release. 

Frankly, I was surprised that a macro call containing macro attribute, e.g.

 `<$macrocall $name="color-contrast" color=<<colour page-background>> />`

inside a `$:/config/DefaultColorMappings/xxx` tiddler worked in the first place, because the same macrocall strategy in a stylesheet never worked for me, not even in v5.1.23. For example:

```css
.tc-tiddler-title .tc-titlebar {
    color: <$macrocall $name="color-contrast" color={{$:/palettes/MyPalette##primary}} />;   /* will refresh */
    color: <$macrocall $name="color-contrast" color=<<colour primary>> />;             /*  will NOT refresh  */
}
```

(Not refreshed means the macrocall, e.g. color-contrast macro, is not invoked when its attribute's color value has changed.)

**Comment by saqimtiaz** [comment]
There is a report of another refresh problem [here](https://groups.google.com/g/tiddlywiki/c/5q6J2tt7Yiw) which I have tracked down to a [JavaScript macro](file:///C:/Users/saq/Downloads/empty.html#%24%3A%2Fmacros%2Fsk%2Ftogglers.js) being used where a widget would have been more appropriate, so that it refreshed when tiddlers it depends on update. 

I suspect these refresh issues are due JavaScript macros that are not deterministic and are therefore problematic from the point of view of refresh handling. The optimizations I made in #5736 were based on the assumption that if a transcluded field itself had not changed, it did not need to be re-rendered and any other transcluded content or macros within it would update because of their own refresh handling.

This isn't true for JavaScript macros and I think is the underlying reason for these issues. I am not sure that we can reconcile the optimizations with such usage of macros. The benefits of the changes in #5736 are compelling and these issues seem to be due to inappropriate usage of macros... but we do have a commitment to backwards compatibility.

**Comment by saqimtiaz** [comment]
However, at least in the case of the issue reported in the GG it seems untenable for us to support such offspec usage of macros.

**Comment by pmario** [comment]
>`color-contrast` is a JavaScript macro.

@cdruan ... I can't find `color-contrast` in the TW-core. I only can find a `$:/core/modules/macros/contrastcolour.js` which is used in the tag-dropdown. ... 

Where does your macro come from?

**Comment by pmario** [comment]
I think, this is a case where we should "execute" a deprecation. So we need to tell authors, that macros are "text substitutions" only. .. If they implement "side effects" into js macros they may be bitten. ... 

We also should test, if it is possible to create the same "error state" with wikitext macros. ... If it is possible we will need to think about the new code again. 

I would suggest, that we revert the change for 5.2.0 and tell plugin authors, that macros with side-effects won't work in the next version 5.2.1 ... So we re-introduce the change immediately into the 5.2.1-prerelease again. 

So the macro authors have more time to fix the problem. .. It would probably be nice to tell them how they should implement the function with a widget instead of a macro. 

Just some thoughts.

**Comment by saqimtiaz** [comment]
> I can't find `color-contrast` in the TW-core.

I had assumed this was a core macro that I am unfamiliar with. @cdruan could you please post the code for this macro so we can confirm if my hypothesis is correct?

> I would suggest, that we revert the change for 5.2.0 and tell plugin authors, that macros with side-effects probably won't work in the next version 5.2.1

Considering the lack of maintenance of a lot of the older plugins and macros, I suspect this wont get us very far. We probably need to go ahead and break macros that rely on such behaviour to make users realize and report that there is a problem.

**Comment by pmario** [comment]
As I wrote in GG the workaround seems to work. So it should be fixable by users .... 

```
<$vars x={{!!toggled}} y={{!!barray}}>
<<macro>>
</$vars>
```

**Comment by cdruan** [comment]
Hi @saqimtiaz ,

Thanks for your explanation. I think I tracked down why a macro call like the following:

```
<$macrocall $name="color-macro" color=<<colour page-background>> />
```

will refresh in the `$:/config/DefaultColourMappings/fab-background` tiddler&mdash;PRIOR to your optimization&mdash;but will not refresh in other regular tiddlers.

It comes down to the `colour` macro usage, for example:

```css
button.fab-button {
	background-color: <<colour fab-background>>;
}
```

The definition of the `colour` macro is this:

```
\define colour(name)
<$transclude tiddler={{$:/palette}} index="$name$">
    <$transclude tiddler="$:/palettes/Vanilla" index="$name$">
        <$transclude tiddler="$:/config/DefaultColourMappings/$name$"/>
    </$transclude>
</$transclude>
\end
```

So, when `page-background` that `fab-background` depends on gets changed in a palette dictionary, the palette tiddler is marked as changed. In the old code, as long as the transclude tiddler is one of the changed tiddlers, the entire `<$transclude tiddler={{$:/palette}} index="fab-background">` node will be removed and recreated and ultimately re-execute the inner most block `<$transclude tiddler="$:/config/DefaultColourMappings/fab-background"/>`. That is why the macro was able to refresh inside the `$:/config/DefaultColourMappings/fab-background` tiddler in the older version of TW.

Whereas if I do this:

```css
button.fab-button {
	background-color: <$macrocall $name="color-macro" color=<<colour page-background>> />;
}
```

The regular `MacroCallWidget.prototype.refresh()` kicks in. Since the `color` parameter evaluates to the original subsituted text of `<<colour page-background>>`, the refresh is optimized away. Therefore, this macrocall will not get refreshed. This behavior is consistent in both new and old TW versions.

For confirmation, when I remove the final condition <code><b>&& this.parserNeedsRefresh()</b></code> in line 113:

https://github.com/Jermolene/TiddlyWiki5/blob/199ca57f1c9e286c7ff0bf28f9f6a152ca923da5/core/modules/widgets/transclude.js#L111-L119

then my original setup, as well as the following, will refresh as desired:

```css
button.fab-button {
	background-color: <$transclude tiddler={{$:/palette}} index="fab-background"><$macrocall $name="color-macro" color=<<colour page-background>> /></$transclude>;
}
```

Alternatively, if I "hack" the first condition of line 105 to use `==` instead of `===`:

https://github.com/Jermolene/TiddlyWiki5/blob/199ca57f1c9e286c7ff0bf28f9f6a152ca923da5/core/modules/widgets/transclude.js#L103-L106

then I can trigger the entire block of `colour` macro to refresh due to the index `fab-background` non-existent in the palette tiddler, therefore, `this.sourceText` is assigned `null`.  I'm not sure if this has unintended consequences or even desirable at all, but effectively it will refresh the fallback block unconditionally when the tiddler of the outer `$transclude` widget is marked as changed.

Mystery is solved for me. I now have a few ways to ensure a macro inside `$:/config/DefaultColourMappings/xxx` tiddler is refreshed when its input is tied to the palette dictionary, so I'll be fine with TW's recent change.

Thanks for your support.

**Comment by pmario** [comment]
@cdruan  I have the "gut feeling", that you are still on a problem. ... 

Especially this makes me think, that there is a problem in the code. 

> Alternatively, if I "hack" the first condition of line 105 to use `==` instead of `===`:
> 
> https://github.com/Jermolene/TiddlyWiki5/blob/199ca57f1c9e286c7ff0bf28f9f6a152ca923da5/core/modules/widgets/transclude.js#L103-L106
> 
> then I can trigger the entire block of `colour` macro to refresh due to the index `fab-background` non-existent in the palette tiddler, therefore, `this.sourceText` is assigned `null`. I'm not sure if this has unintended consequences or even desirable at all, but effectively it will refresh the fallback block unconditionally when the tiddler of the outer `$transclude` widget is marked as changed.

**Comment by saqimtiaz** [comment]
> Alternatively, if I "hack" the first condition of line 105 to use `==` instead of `===`:
> then I can trigger the entire block of `colour` macro to refresh due to the index `fab-background` non-existent in the palette tiddler, therefore, `this.sourceText` is assigned `null`. I'm not sure if this has unintended consequences or even desirable at all, but effectively it will refresh the fallback block unconditionally when the tiddler of the outer `$transclude` widget is marked as changed.

The condition `this.sourceText === undefined` is there for the parsers that do not set the `sourceText` attribute and therefore always need a refresh as we do not have the data necessary to determine what has changed within the target tiddler. Changing it  to `this.sourceText == undefined` will trigger extra refreshes even when the parser returns `null`, which means unnecessary refreshing of fallback content where possibly otherwise not needed. The fallback content should handle its own refreshing.
