### ISSUE TITLE
[IDEA] a better way to highlight duplicates in a list

### ISSUE THREAD

**Issue by Paulgilbert2000** [Jermolene/TiddlyWiki5#5921]
Request to have a java script macro, that returns a list of duplicates, or a data-tiddler with the duplicates as index and the color as a value. 

https://groups.google.com/g/tiddlywiki/c/ahbcnXqVgl8

**Comment by Jermolene** [comment]
Thanks @Paulgilbert2000 but I think @AnthonyMuscio's [solution](https://groups.google.com/g/tiddlywiki/c/ahbcnXqVgl8/m/7p2d-udiAwAJ) answers the request adequately, I don't see the need for a new core primitive.

**Comment by pmario** [comment]
@Jermolene .. You may move this issue to the "discussions" section. .. I didn't think about it, as I did suggest to raise an issue here. 

... In the thread I did suggest to raise an issue, because I thought, that this is a sensible desire, since we have the possibility to show duplicates in lists. ... But I was thinking a bit further. 

eg: What if there are 6 tiddlers. A & B have `field: x` .. so they are "red". C & D have `field: y` .. so they are "red" and E &F have `field: z` .. so they are "red" ... --> IMO that's a problem. All elements are red now. Since all of them are red, there is no useful information anymore. ... 

I would like to discuss a possibility to solve this problem with a decent amount of code. Tony's solution will break down with my testcase. ... 

The other testcase I was thinking about was: I want to know the number of elements that are duplicated. Eg: `field : x` is there 3 times. ... and so on. 

I think there is a reason for the `count[]` operator. I think there may be a reason for a `duplicates` macro too. ... BUT it may be different to `count[]`
