### ISSUE TITLE
[IDEA] In JSON tiddler, tags should be an array

### ISSUE THREAD

**Issue by ibnishak** [Jermolene/TiddlyWiki5#6002]
Rather than merely separated by white-space, tags should be an array. This conforms with JSON format better.

**Comment by pmario** [comment]
In plain text spaces _are_ the separator for an array. The only difference we use in TW, is that we cover "tags with spaces" in double braces.

**Comment by ibnishak** [comment]
When saved as json tiddler, the formatting ought to respect the rules of json IMO

**Comment by Jermolene** [comment]
Hi @ibnishak you're asking why a tiddler "HelloThere" with the tags A, B and C is represented in JSON like this:

```
[
	{
		"text":"text",
		"tags":"A B C",
		"title":"HelloThere"
	}
]
```

Instead of like this:

```
[
	{
		"text":"text",
		"tags":["A","B","C"],
		"title":"HelloThere"
	}
]
```

There are a couple of reasons that we represent list fields as strings in the JSON representation:

* It's very convenient to be able to process all tiddler fields as strings, without having special processing to handle arrays
* At present, it could only be done by hardcoding the convention that the `tags` and `list` fields are treated as lists. The trouble is that other fields can also contain lists but there is no mechanism for those fields to be represented as lists, so we'd end up with an inconsistency

So, in the end, while using an array would make some operations a little bit simpler, it would make things overall more irregular and inconsistent.

**Comment by pmario** [comment]
I do see your desire, but I think that train has left a long time ago.

----

> When saved as json tiddler, the formatting ought to respect the rules of json IMO

It does, otherwise we wouldn't be able to run it through `JSON.parse()`. ... IMO what you want, is a change, in a global convention, that lists / arrays in TiddlyWiki are "space separated elements in a string". 

That's a fundamental difference. For consistency reasons we would also need to change the `list` field. 

Since users are not able to create "array like" fields, other than space-separated atm, we would have 2 different types of fields in a JSON tiddler. tags and lists as arrays and user-fields as "space separated". .. IMO that would only lead to more complexity and confusion for users and developers.

We also would introduce a new inconsistency between .JSON and .TID files .. At the moment you can copy / Paste a tag-string from one file to the other and it will work. This wouldn't be possible anymore.
