### ISSUE TITLE
Bug with permalink/permaview + bracket in the title

### ISSUE THREAD

**Issue by Evolena** [Jermolene/TiddlyWiki5#622]
When you set the navigation address bar setting to permaview or permalink, if you edit a tiddler with a bracket in its title, then you get this error (seen in the story and the open tab of the sidebar):

"Filter error: Missing [ in filter expression"

There is no error if the setting = no, or if the tiddler is displayed but not edited.

**Comment by tobibeer** [comment]
Would it be safe to actually implement a check that disalows or warns users from using certain characters in tiddler titles? That seems the much more practical and reasonable approach to me... atm, I'd see anything like `| < > [ ]` in there

**Comment by Jermolene** [comment]
I think a warning would be a reasonable idea. It could be done as yet another conditional edit template segment displaying a yellow warning panel.

**Comment by tobibeer** [comment]
Mhh, there are more situations for creating tiddlers than simply editing one.

**Comment by Jermolene** [comment]
> Mhhh, there are more situations for creating tiddlers than simply editing one.

Such as?

I think that those situations don't allow us to interject a warning. We could do something like the new plugin modification warning that tells the user whenever a tiddler title containing the dodgy characters were created. But the feedback isn't as direct.

**Comment by tobibeer** [comment]
Ok, so we're not addressing any programatic issues as those are expected to digress gracefully ...in this case: Do nothing at all ... or create problematic titles nonetheless?

**Comment by Jermolene** [comment]
I'm suggesting we analyse the situations where programmatic creation of a tiddler might result in a troublesome character in the title.

Basically, we can either tackle this at the "top" by trapping UI actions that result in troublesome title characters or at the "bottom" by trapping programmatic attempts. Doing the latter is hard because one has lost the context of the UI for presenting feedback to the user.

So, my proposal is to find and fix the places in the core UI where the user may end up creating a title with a troublesome character. Custom UI components that create tiddlers will have to tackle the problem themselves.

**Comment by pmario** [comment]
IMO this bug is related to #293 "Tiddler titles or tags containing `$(x)$` do not work"

**Comment by tobibeer** [comment]
I think it's time for **NamingConventions**: with a list of characters that should be avoided, even must not be used... also explaining a little bit about namespacing.

**Comment by pmario** [comment]
>I think it's time for NamingConventions: with a list of characters that should be avoided, even must not be used... also explaining a little bit about namespacing.

Good idea! IMO there are some users, that have a look to a "Best Practices" tiddler.

**Comment by pmario** [comment]
we do have a warning in place now. So imo this one may be closed.
