### ISSUE TITLE
[IDEA] Class attribute in TranscludeWidget

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6373]
From time to time I need to style a transclusion, but that means wrapping it in a div. Could there be a direct `class` attribute in the TranscludeWidget?

**Comment by pmario** [comment]
The transclusion widget doesn't create a wrapper element. ... So there will be no element that can get the class. 

The existing possibility to use templates will allow you to use `{{tiddler||template}}` to add the requested functionality, without the need to modify the core. 

If you need more flexibility with parameters you can use macros.

---

Transclusions can be used in different contexts. So it's different elements that need to be used as a wrapper. Depending on the mode inline or block. So we will need a new "html tag" parameter too.

We would need to add a lot more code than just the "add class" logic, to the transclusion widget for a convenience function, that is rarely used.

**Comment by twMat** [comment]
Thank you @pmario , that was a good answer, bringing up arguments from all angles.

I think the key point you make is that "it is rarely used" - but do consider that transcludewidget itself is used *extensively*, so even a share of those uses could add up to pretty much.

Good point about it needing both "html tag" and "class" attributes. **Considering that a transclusion is a confined segment of content, I think it does make sense to easily target it with CSS**. In some sense it is like justifying the existence of divs in html.

**Comment by Jermolene** [comment]
Hi @twMat @pmario 

The short answer is as @pmario says: transclusions do not generate any DOM elements themselves, and so there isn't anywhere to put the class.

If transclusions did always generate a wrapper element then the DOM tree would get larger and more complicated. But a deeper problem would stem from HTML's nesting requirements (eg `<li>` within `<ol>`) which mean that it wouldn't be possible to transclude an `<li>` within a `<ol>` because the browser would not like the additional HTML element in between.

If transclusions were to sometimes generate a wrapper element then the widget implementation would become much complicated with conditional logic for the two modes. And there would be no functional difference between manually adding the wrapper element around the transclusion and creating it automatically.

So, I think the direction we need to look is again towards custom wikitext markup, perhaps along the lines @pmario has been investigating. At its simplest, we need macros that are invoked via matching a regexp, with the parameters to the invocation being taken from the capture groups in the regexp.

**Comment by twMat** [comment]
Thanks for your reply @Jermolene .  

>[...] At its simplest, we need macros that are invoked via matching a regexp, with the parameters to the invocation being taken from the capture groups in the regexp.

...so the (then embedded) transclusion would be invoked via a filter evaluation? It sounds absolutely intriguing but I don't quite understand how it relates to my OP. Have you elaborated on this general idea somewhere?

Meanwhile, closing this. Thanks for your input guys.
