### ISSUE TITLE
[BUG]  exports.terminalColour = function(colour) { in FireFox creates noisy logs for no good reason

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6396]
This issue is slightly related to:  **[BUG] Blocking javascript console output does not block bdebugging ouput from syncer-browser-tiddlyweb** #6339 

The log output in the FireFox debug console is noisy for no good reason. 

See the `<empty string>` text `<empty-string>` elements.

```
<empty string> TiddlyWebAdaptor: Status: {"username":"","anonymous":true,"read_only":false,"space":{"recipe":"default"},"tiddlywiki_version":"5.2.2-prerelease"} <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> syncer-browser-tiddlyweb: Retrieving skinny tiddler list <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> syncer-browser-tiddlyweb: Dispatching 'save' task: $:/StoryList <empty string> $:/core/modules/utils/logger.js:52:26
<empty string> syncer-browser-tiddlyweb: Checking dirty status <empty string> 3 $:/core/modules/utils/logger.js:52:26
```

IMO FireFox does the right thing. It shows that console.log got a parameter to log that actually was an empty string, so the dev knows what's going on ... BUT in this case it's annoying, since it will always be empty in the browser. It only makes sense for node and tty sessioins.

The empty strings come from `exports.terminalColour = function(colour) {` line 35: https://github.com/Jermolene/TiddlyWiki5/blob/54bfb28063ace6e03d5c9b218fc6e02fdc714cba/core/modules/utils/utils.js#L24-L36

The proposal is, to implement the `if(!$tw.browser` check in the calling function already. ... So the function isn't called at all if used in the browser.

**Comment by pmario** [comment]
@Jermolene .. Should I try to create a PR for this issue and #6339, because these 2 issues bug me every time I need to debug something. ... Or do you prefer 2 separate PRs?

**Comment by flibbles** [comment]
I see this ball got dropped, so I went ahead and created a PR (#6947), because this was bugging the hell out of me, and I'm pretty certain it has no overlap with #6339.

@pmario's proposal would work, but it turns out that including color directives in the log messages is not a problem, so we don't have to worry about not calling "terminalColor". What we have to worry about is how we pass arguments to "console.log"

```javascript
console.log(terminalColor(), compenentName + ":", message, terminalColor())
```
In addition to the problem that firefox would print "<empty string>" whenever terminalColor() returned "", this introduces a whitespace between every argument, so even when not in firefox, there was a space character at the start and end of every log message (and that was bugging me too).

Instead, my PR is something like this:

```javascript
console.log(terminalColor() + compenentName + ":", message + terminalColor())
```
This does not introduce whitespace, nor does firefox have any emptyString arguments. Problem solved.

This PR took me five minutes to make, so it won't hurt my feelings if you prefer @pmario's solution. But I do prefer mine.

**Comment by Jermolene** [comment]
Thanks @flibbles I'm happy to merge #6947 – do you have any thoughts @pmario?

**Comment by pmario** [comment]
@Jermolene ... Sorry for the late reply, but I needed to test it. It works for me, sou you can merge it.
