### ISSUE TITLE
[IDEA] Make the tiddlers title draggable by default

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6436]
Ref [this discussion](https://talk.tiddlywiki.org/t/importing-tiddlers-drag-a-link/2227/10).

It is desirable that tiddler titles, as they appear at top of the tiddler, are by default draggable handles like they are when the "titles as links" setting is active. This is so tiddlers themselves by default are *directly* draggable e.g into other wikis, so to not force the user to locate a draggable *link* to that tiddler.

An alternative is to make the "titles as links" setting active by default, but this might cause confusion for casual users.

**Comment by pmario** [comment]
I personally don't like the blue underlined title colour of the tiddler title, if the "titles as link" setting is active. My tiddlers titles are __no__ headings. I use headings in the tiddler body. So the blue colour highlights the element more than I would want to have it. ... 

I know, I could change the title CSS, but that's way too much work. 

The second difference is, that "title as link" titles, if exported as a static page also have this link, which will create a new http-request if clicked. 

I did some testing with a modified view-template

 - If the setting is active and I hover over the title, the cursor changes to the "click hand" symbol
 - If the title link is covered by a `<$draggable title=<<currenTiddler>>` widget the "move" cursor will be shown. 

So there is a difference. ... The biggest problem with a draggable-widget is, that it creates an additional DOM element, which is bad for styling CSS. 

-------

@Jermolene 

The [linkwidget]() already has a "draggable" parameter. But this parameter is only active, if a link is created. 

IMO it may be possible to activate this parameter to create a simple draggable, without using the draggable widget, because the functionality seems to be there already.

**Comment by kookma** [comment]
> I personally don't like the blue underlined title colour of the tiddler title, if the "titles as link" setting is active

I am in the same boat!  What I expect is the tiddler title as is but draggable! This can be also done if a handle appear when hover mouse over title!

**Comment by Jermolene** [comment]
Thanks @pmario @kookma 

I don't think making the tiddler title draggable by default is a good idea:

* It breaks the ability to select text within the tiddler title
* It changes the mouse cursor. While it is needed to show that the thing is draggable I find it ugly and distracting
* Making the titles draggable implies that the tiddlers within the story river can be reordered via drag and drop, whereas in fact it has to be done in the "open" tab

> IMO it may be possible to activate this parameter to create a simple draggable, without using the draggable widget, because the functionality seems to be there already.

Behind the scenes the link widget uses the same code as the draggable widget. What would be the goal?

**Comment by CodaCodr** [comment]
Agree with @Jermolene - that would be an awkward UX if not ugly.

How about something akin to the copy-to-clipboard icon for code on TW .com? Perhaps an icon/button/thing that appears left of the title?

**Comment by twMat** [comment]
> I don't think making the tiddler title draggable by default is a good idea:

Closing.
