### ISSUE TITLE
Bug saving default sidebar tab on v5.2.1

### ISSUE THREAD

**Issue by PotOfCoffee2Go** [Jermolene/TiddlyWiki5#6492]
Steps to reproduce bug:

 1) https://tiddlywiki.com/ and download empty.html (v5.2.1)

 2) Open 'empty.html'
 3) ControlPanel -> Appearence -> Settings -> Default Sidebar Tab
 4) Change to 'Tools'
 5) Save as 'empty (1).html'

 6) Open 'empty (1).html'
 7) Just select the 'Open' tab in sidebar
 8) Save as 'empty (1) (1).html'

 9) Open 'empty (1) (1).html'
 10) "bug" - Notice that sidebar displaying the 'Open' tab (should be 'Tools')
 11) ControlPanel -> Appearence -> Settings -> Default Sidebar Tab
 12) Indicates 'Tools' is to be default sidebar tab on load

**Comment by pmario** [comment]
That's desired behaviour. In step 7) you change the tiddler `$:/state/tab/sidebar--595412856` .. So it exists. As soon as this tiddler exists it will be persistent, in single-file wikis, since `$:/state/*` tiddlers are saved. 

See the [tabs macro docs](https://tiddlywiki.com/#tabs%20Macro) It says: 

>**default**
>    The title of the tiddler whose tab is to be selected by default, **if the state tiddler doesn't exist.** The state tiddler takes precedence over this setting

You may remove all of some state tiddlers with a TW [startup action](https://tiddlywiki.com/#StartupActions) ... or even simpler ... 

 - You can create a tiddler **named eg:** `my-save-exclude-filter` 
 - and **tag it:** `$:/tags/Macro` 
 - with this content:

```
\define publishFilter() -[[$:/state/tab/sidebar--595412856]]
```

Now your sidebar-tab state filter will be excluded from the save file. .. [$:/core/save/all](https://tiddlywiki.com/#%24%3A%2Fcore%2Fsave%2Fall) is responsible, for what is saved in singel-file wikis. ... Using the `publishFilter` will allow you to define additional rules, which are added there (see the **last** parameter in save/all) 

You could also use `-[prefix[$:/state/]]`, if you wish to do so.

**Comment by PotOfCoffee2Go** [comment]
Thanks for the detailed response. I had misinterpreted that setting to 'tools' in the ControlPanel was all that was required to keep it locked onto that sidebar tab on reload.
