### ISSUE TITLE
[tw.com/prerelease] Change release notes example 

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6549]
I'm *almost* certain @saqimtiaz posted somewhere that it was a bad idea to use the following form

`<span class={{{...}}}>`

...because the filter outputs a link which triggers unnecessary css refreshes. Something along those lines. But this is used in the prerelease [release notes](https://tiddlywiki.com/prerelease/), as an example of "support for line breaks within filtered transcluded attributes" (currently the very first item in the release notes).

Sorry if I've misunderstood something.

**Comment by CodaCodr** [comment]
It doesn't create a link in that context (my stuff would be severely broken if it did). Check the following at tiddlywiki.com

```
<span class={{{ [[HelloThere]] }}}>Mat</span>
```

But I also recall Saq warning against something in that area...

**Comment by saqimtiaz** [comment]
The [warning in question](https://talk.tiddlywiki.org/t/some-thoughts-on-performance/1268/20?u=saqimtiaz) was to do with using inline filtered transclusions in stylesheets which under specific circumstances could cause updates of the style block even without the CSS changing.

1) that isn't the case here, this is a filtered widget attribute. Inline filtered transclusions are filtered widget attributes are distinct and separate mechanism though both have to do with evaluating filters.
2) the underlying issue that resulted in the excessive CSS refreshes under the circumstances outlined has since been patched. Now the style block is only updated when the CSS has actually changed compare to the active value.

**Comment by twMat** [comment]
Thanks for clarifications!
Thus no issue.
Closing.
