### ISSUE TITLE
[Proposal] Move the documentation macros into a "core plugin"

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6577]
**It is proposed to move all the "documentation macros"** that are part of tidlywiki.com edition at the moment **into its own plugin**. So other users especially translators can use them for their own wikis. 

I think there would be several advantages: 

- We get a unified look for TW related documentation
- Translators and plugin authors wouldn't have to create the "wheel" again
- There may be more contributions to improve the plugin
- .. and so on. 

What do you think?

**Comment by Jermolene** [comment]
Hi @pmario at first I thought that was a great idea, for the reasons you gave. However, on reflection I'm not so sure:

* Firstly, there is an alternative: for the translated editions to use a tiddlywiki.files arrangement to include all the tiddlers from (say) `editions/tw5.com/shared`
* The only advantage of making it be a plugin is so that other people can use it. But the problem there is that a lot of the macros are highly specific to TW documentation (eg the filter operator macros), so it would take a fair bit of work to refactor things for reuasability, and to do the documentation
* I'd still like to explore packaging the documentation as a core en-GB plugin with optional translated versions in sub-plugins (a la TW's packaging of CodeMirror). It doesn't seem like it would make sense to have the macros in a separate plugin, so if we got to that point we'd be committed to maintaining an orphan plugin


* It's already relatively easy for users to snip out macros that they are interested in and reuse them because they are so simple

**Comment by pmario** [comment]
OK. That saves me time.
