### ISSUE TITLE
[IDEA] tag attribute for the list widget

### ISSUE THREAD

**Issue by Telumire** [Jermolene/TiddlyWiki5#6694]
As of now, the list widget does not generate a parent container and only iterate its content. If we want to display a list of link, we need to manually enclose the list widget in an ul element.

A tag attribute would remove the need for manually adding an enclosing ul element and would make the list widget works in a manner congruous to the button widget (which allows to set the parent container to any html element with the tag attribute).

It may also provide a slight performance improvement if the filter output is empty : the ul wouldn't be rendered, and fewer elements to render lead to increased performances.

Even without performances gain, it would increase the code readability.

The syntax would look like this : `<$list tag="ul" filter=".."></$list>` instead of `<ul><$list filter=".."></$list></ul>`

**Comment by joshuafontany** [comment]
Oooh, seconded. This will help writing more complex UI elements.

**Comment by twMat** [comment]
IMO, related to [#2202 Add preMessage parameter to listwidget](https://github.com/Jermolene/TiddlyWiki5/issues/2202#)

**Comment by Jermolene** [comment]
The OP identifies a common pattern that I certainly recognise. The usual way to solve it is by nesting an extra list widget: `<$list><ol><$list><li>...`, and I agree that that is clumsy and repetitive.

At the moment, widgets are divided into two categories: those that generate DOM elements, and those that don't. It is important that widgets like the transclude widget and the list widget don't generate DOM elements because then it would be impossible to use them (for example) in between an `<ol>` and its child `<li>` elements.

This proposal would require the list widget to generate DOM elements under some circumstances and not others. We've deliberately avoided creating hybrid widgets that sometimes generate DOM elements and sometimes don't because their existence makes it a lot harder to reason about what's going on.

But I do think it is worth trying to figure out a better solution. In terms of efficiency, the best way to approach this would be to compute the iterated list once, and then use the result both as the conditional for whether to render the list, and the source of the data for the list. The changes in #6666 should give us a means to package up that pattern for reuse.

**Comment by Telumire** [comment]
>This proposal would require the list widget to generate DOM elements under some circumstances and not others. We've deliberately avoided creating hybrid widgets that sometimes generate DOM elements and sometimes don't because their existence makes it a lot harder to reason about what's going on.

I see, that make sense. Since you think that we can achieve that with https://github.com/Jermolene/TiddlyWiki5/pull/6666 then I'll close this issue, thanks !
