### ISSUE TITLE
Add support for generation of RSS feeds

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#677]
To be exposed in several ways:
- under Node.js to generate an RSS XML file
- under Node.js to server an RSS file over HTTP
- in the browser to save a separate RSS XML file

**Comment by makefu** [comment]
Hi, just wanted to check back what the status of this issue is. I would really love to have RSS generation (back again) for my TW5 static file (no nodejs)!

**Comment by Jermolene** [comment]
Hi @makefu yes there's been a bunch of work on this by @dullroar - see https://groups.google.com/d/topic/tiddlywiki/ol5pOKhU99k/discussion

**Comment by makefu** [comment]
Hi @Jermolene , actually i already looked into this and changed the plugin source to create permalinks instead of direct links tou static files for my single-file Tiddlywiki. Unfortunately this only works for me when importing tiddler with nodejs and adding the plugins in the /plugins folder and not with the single-file version of mine.

It is a bit off-topic but is there a way import a plugin folder directly into tiddlywiki or compile it into the single-tiddler file format which can be directly imported?

**Comment by Jermolene** [comment]
Ah @makefu I didn't realise you were working in the browser. @dullroar will be able to advise if he's done any work on getting it working in the browser.

> It is a bit off-topic but is there a way import a plugin folder directly into tiddlywiki or compile it into the single-tiddler file format which can be directly imported?

No. At the moment, those "exploded" plugin folders need the Node.js configuration of TiddlyWiki. It would be possible to write a standalone utiltity to "compile" them to JSON, though.

**Comment by makefu** [comment]
I have it now in a 'works-for-me' state. For those interested, this is what i have done for the atomfeed plugin:

1. prepare tiddlywiki env

``` bash
     tiddlywiki --init kb
     mkdir plugins
     cd kb/plugins
     git clone https://github.com/dullroar/TW5-atomfeed.git dullroar
     # add to tiddlywiki.info under "plugins": [ ... , "dullroar/atomfeed" ]
```

2. patch the `atomentries.js.tid`

```bash
    makefu@x ~/s/k/p/atomfeed> diff atomentries.js.tid atomentries.js.tid.old
    50,52c50,54
    < 		var server = $tw.wiki.getTiddlerText("atomserver", "").trim();
    < 		server += "#";
    <         x += "\t\t\t<link href='" + server + element.title.replace(/ /g,"%20") + "' />\n";
    ---
    > 		var server = $tw.wiki.getTiddlerText("atomserver", "");
    > 		if (server.slice(-1) !== "/") {
    > 			server += "/";
    > 		}
    >         x += "\t\t\t<link href='" + server + element.title.replace(/ /g,"%2520") + ".html' />\n";
```

3. change `atomserver.tid` last line to the full path to your file. In my case `http://euer.krebsco.de/wiki/index.html`

4. render atomfeed by defining the --load library

`tiddlywiki --load path-to-my-tiddlywiki.html --rendertiddler atomfeed atom.xml text/plain`

**Comment by dullroar** [comment]
Thanks, Felix. Given where my needs were for that plugin and my priorities right now, I probably wasn't going to get to it any time soon. But I did [update the readme](https://github.com/dullroar/TW5-atomfeed/commit/0c9e04cdc58da46bbd3e7af2e183175ff155db22) with a pointer to your technique above (with attribution, of course! :smiley: ).

**Comment by Jermolene** [comment]
Thanks @dullroar

**Comment by gesundelehre** [comment]
How is this above technique from @makefu compatible with the current version of the Atom-Feed Plugin? @dullroar do you may be able to answer this question? Or maybe @sukima?

Because it seems that the plugin was updated since this conversation here.

Thanks in advance

**Comment by sukima** [comment]
@gesundelehre I made a massive refactor of the plugin a while ago and am using it on my website https://tritarget.org/ (source: https://github.com/sukima/dev-tritarget-org) So far it seems to work and when I post a new article my slack bot picks up the RSS update. So I guess it work!

As for documentation I forgot to do that and the README is out of date. It's on my really long TODO list. (https://github.com/dullroar/TW5-atomfeed/issues/9)

**Comment by gesundelehre** [comment]
@sukima

however, there's no file called atomserver.tid in the atomferd plugin master now - what should i do instead of changing this file?

also what is the "tiddlywiki env"?
And how do i patch something? is this a git-feature or a commandline command to patch something?

i'm sorry, but i'm really not tht much acquainted with node.js & commandline & git.

Could you please help me out, as i currently do not really understand how i could possibly do the above tasks that you described to fix the atom-feed.

Thank you very much in advance

PS: if you happen to answer my question here, it may be easiest for you to just update the readme-file instead and add a good manual on how to go about it and then just redirect me to the updated readme.

Thus you could kill two flies with one strike, answering my question and updating the readme.

Looking forward to your answer. Thanks a lot.
Greetings

**Comment by sukima** [comment]
@Jermolene Do we want to close this issue since the plugin does fit the needs?

**Comment by sukima** [comment]
>PS: if you happen to answer my question here, it may be easiest for you to just update the readme-file instead and add a good manual on how to go about it and then just redirect me to the updated readme.

@gesundelehre You must have missed it so I will repeat:

>As for documentation I forgot to do that and the README is out of date. It's on my really long TODO list.

I can try helping further but my retained knowledge of what I did was so long ago I don't remember much. Can this conversation move to dullroar/TW5-atomfeed#9 so we don't continue to spam TiddlyWiki contributors?
