### ISSUE TITLE
[BUG] Empty CSS Class in WIkitext Construct Destroys the  Following Constructs

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#6864]
### Describe the bug

As described in https://tiddlywiki.com/prerelease/#Styles%20and%20Classes%20in%20WikiText
Tiddlywiki allows CSS class in Wikitext construct.

An empty CSS class in Wikitext like below 

```
@@.anyclass
@@
```

destroys the following constructs.

### Expected behavior

Tiddlywiki shall handle empty CSS in WIkitext construct!

### To Reproduce

1. Go to [#Styles%20and%20Classes%20in%20WikiText](https://tiddlywiki.com/prerelease/)
2. Create a new tiddler
3. Put the below Wikitext in tiddler body

```
@@.test

@@

@@.tc-card
One
@@

Hi Tiddlywiki

```
4. See the output, it works fine
5. Now remove the empty line from first CSS class in worktext .e.g

```
@@.test
@@

@@.tc-card
One
@@

Hi Tiddlywiki
```

5. See error

## Normal case works
![image](https://user-images.githubusercontent.com/830394/182062652-8f6244e3-5117-4679-b94e-372a96ac3c66.png)

## Special case does not work
![image](https://user-images.githubusercontent.com/830394/182062731-1910d859-85ed-44bb-b24f-c14040018211.png)

### TiddlyWiki Configuration

- Version 5.2.3p

### Desktop (please complete the following information):

-Chrome 102
-Windows 10

**Comment by Jermolene** [comment]
Hi @kookma the behaviour is a little surprising, but is intentional. Look at the [third example in the docs](https://tiddlywiki.com/prerelease/#Styles%20and%20Classes%20in%20WikiText):

```
@@.tc-tiddler-frame
@@width:400px;
Some text
@@
```

As you can see, consecutive lines starting `@@` are interpreted as one, with all the classes/styles merged together.

Your example looks like this:

```
@@.test
@@

@@.tc-card
One
@@

Hi Tiddlywiki
```

The first two lines are interpreted as the start of a styled block. The `@@.tc-card` line is not recognised as the end of the styled block, and so is actually interpreted as the inline styling syntax.

**Comment by Jermolene** [comment]
Hi @kookma the behaviour is a little surprising, but is intentional. Look at the [third example in the docs](https://tiddlywiki.com/prerelease/#Styles%20and%20Classes%20in%20WikiText):

```
@@.tc-tiddler-frame
@@width:400px;
Some text
@@
```

As you can see, consecutive lines starting `@@` are interpreted as one, with all the classes/styles merged together.

Your example looks like this:

```
@@.test
@@

@@.tc-card
One
@@

Hi Tiddlywiki
```

The first two lines are interpreted as the start of a styled block. The `@@.tc-card` line is not recognised as the end of the styled block, and so is actually interpreted as the inline styling syntax.

**Comment by pmario** [comment]
hmmm, but the rendered text is wrong if the classes should be "combinged". It shouldn't show them.

![image](https://user-images.githubusercontent.com/374655/182114558-03d8cca7-a28b-486f-8cbb-c455c02059cc.png)

**Comment by Jermolene** [comment]
> hmmm, but the rendered text is wrong if the classes should be "combinged". It shouldn't show them.

The third line is blank, so that marks the end of the header of the styled block. Hence the `@@.tc-card` line is not interpreted as part of the styled block header, but instead is parsed as an inline styled run.

**Comment by kookma** [comment]
Thank you for clarification!
