### ISSUE TITLE
[BUG] Nameless field can't be deleted

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#6886]
### Describe the bug

I happened to create a nameless custom field. This can't be deleted via the field delete button.

### To Reproduce

1. Create a new tiddler so you're in edit view
2. ~~Type `<$edit-text field={{!!currentTiddler}} />` and loudly say *"Yes, this could happen to anyone at 1 am"*~~<br>(update) Type `<$edit-text field='' />` (i.e just a missing argument)
3. Save the tiddler
4. Back in view mode, enter some value in the little editor field
5. Open the editor and see the nameless field with the entered value
6. Attempt to delete the field by clicking the delete button

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by kookma** [comment]
Confirmed (TW 5.2.3 + Chrome 102).
This is a bug!
It makes no sense to set value to nameless field!

**Comment by Jermolene** [comment]
This is an interesting one! The requirement for a field name is that it be a string of characters; a valid string is a zero length string. So, there's nothing in the design of TiddlyWiki at the moment to prevent creating fields with a zero length name; indeed, there's nothing inconsistent or irregular about them. Arguably, the issue is just that the UI doesn't permit these fields to be deleted.

This gets tricky because in the TW core JS it is not possible for a write to a tiddler to fail. That's super important because it avoids having to have error checking everywhere that we change the values of tiddlers. So, it's not clear what we should do when faced with HS code that creates such a field:

```js
wiki.addTiddler({title: "HelloThere, "": "Zero length field"})
```

Given that there's no mechanism for that call to return with an error, the question would be what we do with the zero length field name. We could change the field name to something else, or we could entirely ignore that field. But then the problem is that code would observe a different tiddler value than that which it had set.

So, overall, I think it would actually be a good deal easier to just fix the UI so that these fields can be handled as expected.

**Comment by pmario** [comment]
>So, overall, I think it would actually be a good deal easier to just fix the UI so that these fields can be handled as expected.

The problem is that action-deletefield doesn't allow us to enter an empty `$field=""` parameter at the moment. So we'll need to change that widget.

**Comment by pmario** [comment]
@Jermolene 

>So, overall, I think it would actually be a good deal easier to just fix the UI so that these fields can be handled as expected.

IMO that's not possible. If you use a client-server configuration, the tiddler will be saved to the .tid file with an empty field name. 

BUT 

If you reload the wiki, that field is gone. .. So we need to "block" the possibility to write a field like this.

**Comment by pmario** [comment]
>The problem is that action-deletefield doesn't allow us to enter an empty $field="" parameter at the moment. So we'll need to change that widget.

I'll create a PR, that should fix that problem in a moment.

**Comment by Jermolene** [comment]
> IMO that's not possible. If you use a client-server configuration, the tiddler will be saved to the .tid file with an empty field name.

We already inspect tiddlers to see if they can safely be saved in .tid file format. So we need to update the logic to force tiddlers with blank fieldnames to be saved in JSON.

**Comment by kookma** [comment]
> 2\. Type `<$edit-text field={{!!currentTiddler}} />` and loudly say _"Yes, this could happen to anyone at 1 am"_

Can't this use a default field e.g: `text`

**Comment by twMat** [comment]
@kookma - do you mean as a fallback? IMO, the `text` field, specifically, is risky because of overwrites so the user loses info. (Besides, in this case without a `tiddler` argument it would overwite itself.) But maybe there could be a fallback field called `missing` or some such? On the other hand, if there is to be a "handling mechanism" for this then why not an error message.

BTW, I updated the OP to clarify the issue, i.e `<$edit-text field='' />`

**Comment by kookma** [comment]
> @kookma - do you mean as a fallback?

Yes!

**Comment by pmario** [comment]
@twMat PR #6888 is merged and should allow us to remove those type of fields from a tiddler

**Comment by twMat** [comment]
Thanx @pmario !
