### ISSUE TITLE
[IDEA] multiline syntax for list wikitext elements

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#6905]
Proposal: add a new optional syntax element `:` as a "start-marker" and `;` as an end-marker to the wikitext list-syntax

```
* element 1

**: element 1.1 multiline
element 1.1 line 2
;
*.classx: element 2 
line 2
;
```

- The start-marker is optional and can be placed after the existing `.class` marker
- The end-marker has to be the only character in a line. 
- Hard line-breaks should be implemented as defined in the commonmark spec [1]
  - 2 spaces at the end of the line
  - or: \ at the end of the line. 

I did see the syntax at: https://plantuml.com/en/mindmap-diagram#c52a6bf8d847484d

[1] https://spec.commonmark.org/0.30/#hard-line-breaks

**Comment by rmunn** [comment]
Two spaces at the end of a line can be difficult in a Web app like TiddlyWiki, because of how HTML collapses multiple whitespace into a single space. In some circumstances, that could lead to hard linebreaks getting lost because the tiddler's data went through an HTML transformation. Most of the time it would probably be okay, but it could definitely happen that some HTML parser processes a TW file and collapses multiple whitespace into a single space "to save bandwidth" or something, and then suddenly your hard linebreaks wouldn't be hard anymore.

So I recommend that if hard linebreaks are done the way you suggest, the TW documentation strongly recommends using the "`\` at the end of the line" approach, rather than the "two or more space characters at the end of the line" approach from https://spec.commonmark.org/0.30/#hard-line-breaks.

**Comment by pmario** [comment]
>Two spaces at the end of a line can be difficult in a Web app like TiddlyWiki, because of how HTML collapses multiple whitespace into a single space.

That's not a problem, since a tiddler will be stored as JSON data or as a text .tid file, where spaces are preserved. The conversion from text to HTML code is done by the TW core and if the core does it right, the browser doesn't see the 2 spaces. 

But you are right. 2 spaces to indicate a hard line-break is a bit problematic, because they are invisible in most editors. ... BUT it is part of the Markdown - commonmark spec. So we can say "They also did it that way". ..

**Comment by kookma** [comment]
I got used to:

```
* One
* Two Multiline <div>
  for example a codeblock comes here
</div>
```
```

**Comment by Jermolene** [comment]
Hi @pmario I don't think this proposal is backwards compatible. The "list" parse rule treats definitions lists as a type of list alongside bullets and numbers. See the code here:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/list.js

That means that your first example is already a valid list item:

```
**: element 1.1 multiline
```

**Comment by pmario** [comment]
>**: element 1.1 multiline

ouch ... you are right. ... It would have been to nice :/ ... So we need other delimiters. ... 

May be a wikitext-version of @kookma's example is the "solution" then. The STYLE element is only there for easy testing. In production it would be a stylesheet-tiddler. 

```
<style>
.hl {
  white-space: pre-wrap
}
</style>

* element 1

** @@.hl element 1.1 multiline
element 1.1 line 2 
@@
* @@.calssX.hl element 2 
line 2
@@
```

**Comment by Jermolene** [comment]
Hi @pmario I think that's right: the way to think about this is that we need a syntactic structure that can appear in inline contexts, but contain block content. It doesn't need to be a special capability of the list parser.

**Comment by pmario** [comment]
I did open a new issue for this one:  [IDEA] Thinking about a possibility to extend styled blocks with parameters eg: mode=block parameter #6908
