### ISSUE TITLE
[BUG] Markdown: Paragraph in every list item when list contains empty line

### ISSUE THREAD

**Issue by MaxGyver83** [Jermolene/TiddlyWiki5#6930]
### Describe the bug

Sometimes I split long lists into sections/small lists for better readability.

```
* list 1, item 1
* list 1, item 2

* list 2, item 1
* list 2, item 2
```

They get joined into one long list when parsed:

![image](https://user-images.githubusercontent.com/13970628/187064770-ca6db70a-0295-4c26-88d9-8383d20afb8e.png)

This is intended behavior as explained in #3158:

> That behaviour is by design; and matches Markdown's behaviour.

But when I do the same in Markdown tiddlers, there is a gap between all list items:

![image](https://user-images.githubusercontent.com/13970628/187064813-ecee2c1e-487c-4b87-bc56-290be9ab225d.png)

The reason is, that every list item gets wrapped into a paragraph:

```html
<li>
  ::marker
  <p>list 1, item 1</p>
</li>
```

I have tried the same in @cdruan's  [Markdown PR Demo](https://cdruan.github.io/TiddlyWiki5/) (belonging to #6528):

![image](https://user-images.githubusercontent.com/13970628/187064953-a8d82906-ad74-4d7f-8023-683f72be4e1e.png)

Here, the gaps are smaller. But the underlying HTML looks even worse:

```html
<li>
  ::marker
  <p>
    <p>list 1, item 2</p>
  </p>
</li>
```

Every list item gets wrapped into two paragraphs!

(Another obversation, maybe related: When the list section are divided by **two** empty lines, WikiText tiddlers still look the same. In cdruan's Markdown tiddlers, they get rendered unchanged, too. But in the current _Remarkable_ Markdown tiddlers, I get two separate lists (with no gaps within each list).)

### Expected behavior

No paragraph tags.

### To Reproduce

1. Create a markdown tiddler containing:
```
* list 1, item 1
* list 1, item 2

* list 2, item 1
* list 2, item 2
```
2. See the preview.

### TiddlyWiki Configuration

- Version: v5.2.3
- Saving mechanism: Node.js
- Plugins installed: Markdown

### Desktop (please complete the following information):

- OS: Arch Linux
- Browser: Firefox
- Version: 103.0.2 (64-bit)

**Comment by cdruan** [comment]
Hi @MaxGyver83 

Regarding to PR #6528's behavior (i.e. markdown-it's behavior):

* The list items may be separated by any number of blank lines.
* You can use two different kinds of markers to create two separate lists. For example:

  ```md
  * list 1, item 1
  * list 1, item 2
  - list 2, item 1
  - list 2, item 2
  ```

  or

  ```md
  1. list 1, item 1
  1. list 1, item 2
  1) list 2, item 1
  1) list 2, item 2
  ```

* You can create a *tight* list if none of the list items are separated by blank lines. Otherwise, the list is considered a *loose* list and list items will be wrapped in `<p>` tags.

&mdash; [GFM](https://github.github.com/gfm/#lists) and [CommonMark ](https://spec.commonmark.org/0.30/#lists) specs.

In your example, all of the list items have the same marker and there is a blank line within the list, so the list will be rendered as one *loose* list. As for the double `<p>` tag wraps you're seeing, there's a technical reason behind it: markdown creates the first `<p>` tag and TiddlyWiki wraps block content with another `<p>`. I'm aware of this behavior. It's a little annoying but visually the output seems fine.

Current markdown plugin (remarkable parser) behaves almost the same as described above except that it splits a list when it sees two or more consecutive blank lines. So in your exmaple, the list is still considered one "loose" list.

Hope this explains what you're seeing.

**Comment by pmario** [comment]
I think, that's the solution already

```
* list 1, item 1
* list 1, item 2

- list 2, item 1
- list 2, item 2
```

**Comment by MaxGyver83** [comment]
@cdruan , @pmario : Thank you!

A typical case of "it's not a bug, it's a feature" :laughing:
