### ISSUE TITLE
[IDEA] Simplify the default edit view, and introduce local tiddler settings

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7022]
**Problem**
The *default* edit view is too cluttered in general, and possibly even intimidating for those taking a first look at TW.

**Solution**
Hide the templates for *type* and *custom fields* - this is OK **as long as it is trivial to *(i)* discover and *(ii)* bring forth the hidden stuff on a need basis.**

[Proof of concept](https://tiddlersettings.tiddlyhost.com/) - this does not have templates hidden by default but shows an edit view *toolbar button* to hide/show the templates.

This illustration gives an idea what we should aim for (even if it goes beyond this immediate proposal with the cleaned up editor tool buttons):

<img width="302" alt="image" src="https://user-images.githubusercontent.com/4534056/200058727-3413f1fc-1ad4-4f94-b630-878d9f3ffdec.png">

Thus:

1. Change the default settings to hide at least the *type field* template and the *custom fields* template
2. Introduce a tiddler-local "control" to easily discover and un-hide templates on a tiddler-need basis

**Comment by kookma** [comment]
Neat idea!
I support having options to simply show/hide elements.
We have this for toolbar buttons why not to have it for other UI elements?

**Comment by pmario** [comment]
The POC seems to be a "per tiddler" setting. I want it to be global. IMO it doesn't make sense to change the setting for every tiddler again and again ..

**Comment by pmario** [comment]
The problem with more than 3 elements for the tiddler toolbar is, that Jeremy will most likely reject that. There are several other PRs and issues where this was discussed. So there needs to be a way to avoid the "cog" in the toolbar

**Comment by pmario** [comment]
I personally would prefer a new setting element similar to the the "field visibility" settings in the tiddler info area also shown in the edit-view. My edit-fields plugin has a similar setting. .. But also a problem with 4 elements in the toolbar

![image](https://user-images.githubusercontent.com/374655/200099225-1fe43948-0fdf-446f-94a3-25fd8f78fb5c.png)

**Comment by saqimtiaz** [comment]
From my perspective there a few problems with this proposal:
- we have not established the value and benefits of hiding certain fields by default.
- the core needs to strive for consistency, especially considering newcomers for whom it would be far more user friendly to find that all text based tiddlers have the same editing interface.
-  It isn't particularly desirable either for the presentation of the data (the edit template) to be mixed with the data (the fields of the tiddler). I strongly feel that any per tiddler affordance to hide or show fields is plugin territory.

Since the introduction of the [Field Editor Cascade](https://tiddlywiki.com/#Field%20Editor%20Cascade), we now have the following for each custom field:
- a customizable cascade that determines what editing interface to show.
- a config tiddler that can be used to hide the field in the editing interface.

What would be interesting to explore is to bringing the display of default tiddler fields, which is currently hardcoded into the edit template, into line with the new display handling for custom fields. That is, each default field should also have a config tiddler that can be used to hide it and should use a cascade to determine the editing interface, with the caveat that safe mode should override any customizations. That is, treat all fields the same in terms of displaying them or not, and choosing and the editing interface, rather than the current situation where custom fields are a separate thing altogether.

This would mean that there are core affordances for customizing the display of every field, both in terms of whether it is displayed at all and also in choosing the editing interface.

It would also be interesting to extend the mechanism for hiding fields to have a bit more nuance, in other tools I have found the option to set a field to display "only when not empty" quite useful as well.

These low level modifications to the edit template would open the door to use cascades and config tiddlers to customize the display of any field as well as control whether it is displayed. It should also be relatively easy then to make the order of the display of the fields configurable as well, perhaps via drag and drop. The user interface for all of this could then first be explored entirely via plugins to establish good UX patterns and gather user data before trying to determine what if any changes are applicable to the core.

Lastly, all of this can be explored as a plugin without the need for any core support. When it comes to such pervasive user interface changes, it is always prudent to test ideas and gather user feedback to refine those ideas before trying to make any changes to the actual product. Plugins provide a wonderful opportunity for this.

**Comment by pmario** [comment]
>What would be interesting to explore is to bringing the display of default tiddler fields, which is currently hardcoded into the edit template, into line with the new display handling for custom fields. 

That's true. We should be consistent. Hardcoded exceptions are always limiting. ... 

>This would mean that there are core affordances for customizing the display of every field, both in terms of whether it is displayed at all and also in choosing the editing interface.

Absolutely. IMO https://tiddlywiki.com/#Customizing%20EditTemplate%20field%20rendering has been the first step into that direction. .. But the remaining PR (draft? can't find it atm) has been stalled

**Comment by twMat** [comment]
>The POC seems to be a "per tiddler" setting. I want it to be global. IMO it doesn't make sense to change the setting for every tiddler again and again ..

Well, there should *also* be a global setting, I didn't want to get into that to muddle the OP. But a key aspect to the OP is to set things locally because otherwise usage of, say, the *type* template in a single tiddler would "force show" this in every tiddler. Why would anyone want that? (Compare it to creating a custom field - what if *each* custom field were globally seen? Both the "foo" field and the *type* field concern only a few tiddlers.)

>I personally would prefer a new setting element similar to the the "field visibility" settings in the tiddler info 

I would think it is not immediately discoverable there for those that need to discover it.

**Comment by twMat** [comment]
OK, OK, ain't gonna happen. 
Closing.
