### ISSUE TITLE
[IDEA] add focus="yes" parameter to $select widget

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#7070]
In several places, I have a `$button` widget that triggers a popup via `<$reveal type="popup"... >` .  The popup contains a `$select` widget.  It would be a significant improvement for keyboard interaction if that `$select` widget could automatically get the focus as soon as it is rendered within the `$reveal` widget.  This same type of interaction is currently available for the $edit-text widget by using a parameter `focus="yes"`.  By adding handling for `focus="yes"` to the `$select` widget it would be possible to click (or press the `space` key) to trigger a `$button` that displays a listbox, and then immediately use the down-arrow key to scroll through the available listbox options to make a selection.

To add this optional behavior to the `$select` widget, just two small changes are needed in `$:/core/modules/widgets/select.js`:

In `SelectWidget.prototype.execute` add 1 line:
   `this.selectFocus = this.getAttribute("focus");`

In `SelectWidget.prototype.render` add 1 line:
   `if(this.selectFocus=="yes") { this.getSelectDomNode().focus(); }`

**Comment by Jermolene** [comment]
Thanks @ericshulman that sounds like a good idea.

Would another contributor like to volunteer to take the baton from Eric and make a PR with documentation updates?

**Comment by kookma** [comment]
@ericshulman 
The above proposed solution only works with focus="yes", what about focus="true"? I am not sure, but I see the `$edit-text` accepts both!

**Comment by Jermolene** [comment]
Hi @kookma the convention in TW5 is to use "yes"/"no" rather than "true"/"false". Inconsistencies have crept in a few places like the `<$edit-text>` widget. Those are the result of well-meaning PRs that I didn't catch. It seems harmless and perhaps helpful to support both conventions, but in practice that kind of inconsistency breeds complexity at an alarming rate. For example, imagine in the future that we have the ability to reach into a widget and access its attributes. Any code that needs to check the status of the focus attribute will have to test it against twice as many strings.

So, I'd prefer that we identify all the situations where "true"/"false" are accepted and (a) where possible make sure that "yes"/"no" were accepted too and (b) mark the usages of "true"/"false" as deprecated in the docs.

**Comment by kookma** [comment]
> So, I'd prefer that we identify all the situations where "true"/"false" are accepted and (a) where possible make sure that "yes"/"no" were accepted too and (b) mark the usages of "true"/"false" as deprecated in the docs.

After 5.2.4 release I will check the tiddlywiki.com and will prepare some PRs to revise the documentations.

**Comment by pmario** [comment]
@ericshulman .. I think this one can be closed. There has been a merge.
