### ISSUE TITLE
[IDEA] add `format:timestamp[dateformat]` filter operator

### ISSUE THREAD

**Issue by ericshulman** [Jermolene/TiddlyWiki5#7120]
**Is your feature request related to a problem? Please describe.**
As of TW5.2.4, a "TIMESTAMP" filter operand has been added: `format:date[TIMESTAMP]` to convert a date input value into a "Unix Epoch" timestamp (number of milliseconds since "January 1, 1970 00:00:00.000")

The following code implements `format:timestamp[dateformat]` to provide the inverse conversion (i.e., from a Unix Epoch timestamp to TWCore date-formatted string.

* First, it checks the input to make sure it is an integer value.  Note that negative integer values are permitted and specify milliseconds BEFORE the beginning of the "Unix Epoch" start date.
* Then, it applies the filter operand to format the output. If no operand is specified, it defaults to a 17-digit UTC TWCore serial date format ("`[UTC]YYYY0MM0DD0hh0mm0ss0XXX`").
* If the input is not a valid signed integer, it returns "Invalid timestamp value"

```text
/*\
title: $:/core/modules/filters/format/timestamp.js
type: application/javascript
module-type: formatfilteroperator
\*/
(function(){

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*
Export our filter function
*/
exports.timestamp = function(source,operand,options) {
	var results = [];
	source(function(tiddler,title) {
		if (title.match(/^-?\d+$/)) {
			var value = new Date(Number(title));
			results.push($tw.utils.formatDateString(value,operand || "[UTC]YYYY0MM0DD0hh0mm0ss0XXX"));
		} else{ 
			results.push("Invalid timestamp value");
		}
	});
	return results;
};
})();
```

**Comment by AnthonyMuscio** [comment]
Very good idea to implement this, can we just package this as a plugin for use until the core gets it?

A little more;
* Please Left me define "key date formats" as the TiddlyWIki Serial Date and the Unix date serial (or timestamp)
* The former is the default tiddlywiki full date time stamp and the latter is one on which we can do maths.

This does make me look at `DateFormat` and `format:date` and ask if we still have unnecessary gaps in the core features on dates.
* A data picker from HTML to  "key date formats"
* Another gap is a simple way to go from any DateFormat to "key date formats"

It is possible to take any date eg YYYY-0MM-0DD and spit this into seperate value's then use these to generate a new string that complies with the TiddlyWiki serial date [UTC]YYYY0MM0DD0hh0mm0ss0XXX however this requires some fairly skilled wiki text.

My question here, due to its relevance, but likely to give rise to a seperate GitHub request, is could we allow an input date format that is used to translate the the given date to one of the  "key date formats" a tiddlywiki date serial number or unix time stamp?
* Then from any date to either of the "key date formats" is trivial.
* Then from any of the "key date formats" to any date format is already trivial.

eg;
input 2022-12-16, input date format "YYYY-0MM-0DD" that converts this to [UTC]YYYY0MM0DD0hh0mm0ss0XXX or TIMESTAMP
* This can just assume the date is valid
* Its really only a string manipulation into the tiddlywiki serial date, then if TIMESTAMP is the desired output use the existing conversion.

All this will take is parsing the input date format, against the input date and rearranging the position of the values. Whilst this is possible by other means this would simplify the process substantially for everyday users. Much of the code to do this is possibly already in the core.

**Comment by yaisog** [comment]
@Jermolene: What do you think? I would love to have this, to complement the TIMESTAMP format output. This would also enable simple date calculations like, e.g. a day from today, two weeks from now.

**Comment by ericshulman** [comment]
> > If the input is not a valid signed integer, it returns "Invalid timestamp value"
> Other operators that expect a numeric value interpret invalid values as "0".

Other operators that expect numeric input generally return numeric output (e.g., math filters).  However, in this case, the proposed operator takes numeric input and returns text output.

Substituting "0" for an invalid input value (non-numeric or non-integer) would result in returning valid formatted date text for the start of the Unix epoch (Jan 1, 1970 00:00:00).

Instead, I suggest that an invalid input value should just pass through, unchanged.

Thus, the code would be:
```
exports.timestamp = function(source,operand,options) {
	var results = [];
	source(function(tiddler,title) {
		if (title.match(/^-?\d+$/)) {
			var value = new Date(Number(title));
			results.push($tw.utils.formatDateString(value,operand || "[UTC]YYYY0MM0DD0hh0mm0ss0XXX"));
		} else{ 
			results.push(title);
		}
	});
	return results;
};
})();
```

**Comment by yaisog** [comment]
I could make a PR, but I would just copy/paste Eric's code verbatim. That seems to me like taking credit for others' work, though. I'd only do it if @ericshulman wants me to...

**Comment by pmario** [comment]
@yaisog .. I think you can create a PR. IMO Eric did choose this format for some other contributions lately.

**Comment by Jermolene** [comment]
Hi @yaisog @pmario indeed, I or another core developer generally make PRs on @ericshulman's behalf.

**Comment by AnthonyMuscio** [comment]
I have done a brief test on this 

```
{{{ [<now YYYY0MM0DD0hh0mm0ss0XXX>format:date[TIMESTAMP]format:timestamp[]] }}}

{{{ [<now YYYY0MM0DD0hh0mm0ss0XXX>] }}}
```

Can this please make it into the next release ?
* The unix time is not at all useful until this is available.
* I am yet to workout how we handle UTC with this and if we need a feature to support it.

**Comment by yaisog** [comment]
Since Unix timestamps are defined in UTC, you might need to add or subtract a number of microseconds to get local time. Especially since `format:date[]` also interprets the input as UTC.

I currently use something like this:
```
<$let timezoneOffset={{{ [<now TZD>multiply[3600000]] }}}
      timestamp={{{ [<now YYYY0MM0DD0hh0mm0ss0XXX>format:date[TIMESTAMP]subtract<timezoneOffset>] }}} >
```

**Comment by AnthonyMuscio** [comment]
> you might need to add or subtract a number of microseconds to get local time

I wonder if we need to add a local / UTC time option for unix time?

**Comment by linonetwo** [comment]
@yaisog Can your example turn TIMESTAMP back to tw date format? I need `<<now [UTC]YYYY0MM0DD0hh0mm0ss0XXX>>` but in +8 time zone, seems there is no simple way for this.

**Comment by yaisog** [comment]
> I need `<<now [UTC]YYYY0MM0DD0hh0mm0ss0XXX>>` in +8 time zone

Hi @linonetwo, couldn't you just leave out the `[UTC]` token from the format string to get the date in local time?

To be honest, these UTC conversions confuse the heck out of me. Reading over my example from three posts above, I feel quite stupid. One could just as well get the same value for `timestamp` by using the `[UTC]` token, without the need for manual subtraction:
```
<$let timestamp={{{ [<now [UTC]YYYY0MM0DD0hh0mm0ss0XXX>format:date[TIMESTAMP]] }}} >
```
I'm not sure what I wanted to demonstrate back then, but it doesn't seem to make sense a month later...
