### ISSUE TITLE
[BUG] Render Static Page when a Tiddler has Star in its Title

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7123]
### Describe the bug

Generate static tiddlers using `tiddlywiki mywiki --build static` raises an error if a tiddler has title including start `*` character

### Expected behavior

The tiddler with `*` in the title shall be handled. 

### To Reproduce

Using node.js

1. create a new Tiddlywiki: `tiddlywiki mywiki --init server`
2. open the new Tiddlywiki: `tiddlywiki mywiki --listen`
3. create a tiddler with odd name e.g. `Hey Everyone*` and save
4. generate static tiddlers `tiddlywiki mywiki --build static`

See the error.

```
at $:/core/modules/commands/rendertiddlers.js:62:6
    at $tw.utils.each ($:/boot/boot.js:146:12)
    at Command.execute ($:/core/modules/commands/rendertiddlers.js:47:12)
    at Commander.executeNextCommand ($:/core/modules/commander.js:107:14)
    at Command.callback ($:/core/modules/commander.js:119:13)
    at $:/core/modules/commands/rendertiddler.js:50:8
    at FSReqCallback.oncomplete (node:fs:201:23) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: ....\\mywiki\\output\\static\\Hey EveryOne*.html'
}

Node.js v18.4.0
```

### TiddlyWiki Configuration

- Version [e.g. v5.2.4]
- Saving mechanism Node.js 
- Plugins installed: no extra plugin

### Desktop (please complete the following information):

- OS: [Win 10]
- Browser edge/chrome 108

### Additional context

A discussion has been started here:

https://talk.tiddlywiki.org/t/possible-bug-render-static-pages/5478

**Comment by Jermolene** [comment]
Thanks @kookma as you note, it seems this problem only occurs under Windows. I can't reproduce it under macOS.

According to [Microsoft's docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file), the following characters are illegal in filenames:

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

Putting `[[<>:"/\|?*]encodeuricomponent[]]` in the TW advanced search "Filter" tab yields:

```
%3C%3E%3A%22%2F%5C%7C%3F*
```

So, asterisk is the only one of the illegal characters that is not currently encoded. I think the most effective fix for interoperability would be to extend the core `encodeuricomponent` filter operator to additionally encode `*` as `%2a`. The matching `decodeuricomponent` filter operator would correctly decode it to an asterisk, as does JavaScript's built in `encodeURIComponent` function.

There is also a case to be made to encode single quotes, because they are illegal on some filing systems (notably Amazon's S3).

It's worth Windows has some trickier file naming requirements too:

> Do not use the following reserved names for the name of a file:
> * CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).
> * Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

**Comment by Jermolene** [comment]
> It is interesting to know the export tiddler button generates a file name like `Hey EveryOne_.html` for a tiddler with `Hey EveryOne*` title on Windows (Chrome/Edge 108 - Tiddlywiki 5.2.4)!

When exporting files in the browser, any illegal characters are automatically replaced by the browser rather than generating an error as under Node.js.
