### ISSUE TITLE
[BUG] EditTextWidget loses focus

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#7188]
### Describe the bug

(Feel free to improve the headline for this issue)

The EditTextWidget loses focus after a first character (only) is typed into the following construct... *sometimes!* (Sorry, I know this is the worst type of error)

If focus *is* lost and thereafter manually appointed, you can continue to type the intended string without repeated loss of focus.

(In the code below, never mind the "irrational" aspects, e.g that the defined $let variable remains unused, etc. It is from a bigger context.)

```
<$let notused={{{ [<qualify mystate>get[text]] }}} >

<$edit-text tiddler="temp" field=myfield
	inputActions="""<$action-setfield $tiddler=<<qualify mystate>> text=xxx />"""
/>
<$button>
	<$action-setfield $tiddler="temp" myfield=""/>
	<$action-setfield $tiddler=<<qualify mystate>> text=xxx />
	X
</$button>

</$let>
```

My theory: The *qualify* macro is re-evaluated on input which is what draws away focus to, um, something else. (Then, after the user manually resets the focus, the qualify macro understands that it had better not do it again *or else* !)

### Expected behavior

Focus should remain in the editor.

### To Reproduce

1. Copy-paste the code into e.g https://tiddlywiki.com/empty
2. If you don't experience the problem, please try a few more times. I get it the absolute majority of times.

### TiddlyWiki Configuration

TW version latest
Win11
Brave, Edge, Chrome, Firefox

**Comment by saqimtiaz** [comment]
This is expected behaviour and not a bug. 

If the tiddler title returned by `<<qualify mystate>>` does not exist, typing the first character creates it, which in turn changes the value of the variable `notused`. The mechanism by which the UI becomes aware of the change of variable values is by refreshing the contents of the widget assigning the variable, which results in loss of focus. In the provided construct, any action that changes the value of the variable `notused` will cause a refresh and an associated loss of focus.

**Comment by twMat** [comment]
OK, understandable. I appreciate the clarification @saqimtiaz !
