### ISSUE TITLE
[Idea] The keyboard-driven-inpu-macros should be more user-friendly for plugin authors

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7250]
The [keyboard-driven-input macros tiddler](https://tiddlywiki.com/#%24%3A%2Fcore%2Fmacros%2Fkeyboard-driven-input) contains the `change-input-tab` macro, which uses a `tag` parameter to define the list of tabs in the $:/AdvancedSearch tiddler.

**I would like to have a variable `explicitTabList` or similar, that contains a predefined list.**

This will allow plugin authors to provide the `explicitTabList` without the need to overwrite the core code. It will allow us to reuse the existing keyboard handling, which is super complex.  

At the moment the `tabsList` is created like this:

```
<$set name="tabsList" filter="[all[shadows+tiddlers]tag<__tag__>!has[draft.of]]">
```

The proposed code should look like this: 

```
<$set name="tabsList" filter="[enlist<explicitTabList>] ~[all[shadows+tiddlers]tag<__tag__>!has[draft.of]]">
```

As you can see, the `explicitTabList` is only used if it is defined. 

------

@BurningTreeC I think, there is a second problem. IMO the `nextTab` variable should reuse the `tabList` as shown in the code below.

```
\define change-input-tab(stateTitle,tag,beforeafter,defaultState,actions)
\whitespace trim
<$set name="tabsList" filter="[enlist<explicitTabList>] ~[all[shadows+tiddlers]tag<__tag__>!has[draft.of]]">
<$let
	currentState={{{ [<__stateTitle__>!is[missing]get[text]] ~[<__defaultState__>] }}}
	firstTab={{{ [enlist<tabsList>nth[1]] }}}
	lastTab={{{ [enlist<tabsList>last[]] }}}
	nextTab={{{ [[enlist<tabsList>$beforeafter$<currentState>] ~[[$beforeafter$]removeprefix[after]suffix[]addprefix<firstTab>] ~[[$beforeafter$]removeprefix[before]suffix[]addprefix<lastTab>] }}}>
<$action-setfield $tiddler=<<__stateTitle__>> text=<<nextTab>>/>
$actions$
</$let>
</$set>
\end
```

With those changes in place I could completely reuse the existing keyboard handling of the $:/AdvancedSearch tab with my [AdvancedSearchPlus plugin](https://wikilabs.github.io/editions/advanced-search-plus/#%24%3A%2FAdvancedSearch), without the need to overwrite all of the core plugins. 

The plugin basically removes the "caption" from the core and replaces it with "icons" ... The rest of the function should stay the same. 

![image](https://user-images.githubusercontent.com/374655/216620255-a3937cb1-0a56-4d67-a0e0-38185e902c9f.png)

@Jermolene ... What do you think?

**Comment by Jermolene** [comment]
Hi @pmario I understand the problem, but I'm not sure that it is practical or advisable to extend the existing keyboard-driven-input macro in this way.

As you note, one of the issues with these macros is that they are already quite complex. Making them more complex will make it harder for other people to understand and adapt the code.

But fundamentally, it's deeply unfortunate that the tab switching behaviour of $:/AdvancedSearch is implemented at this level at all (personally I also hate the inconsistency that we have keyboard shortcuts for switching some tabs and not for others). Ideally, things would be layered so that the two mechanisms were independent. While we have to accept the present state of affairs I don't think we should exacerbate the problem further.

**Comment by pmario** [comment]
Yea, the whole mechanism needs some love. There is a lot of almost identical "duplicated" code. ... 

I think I found a workaround for my plugin, that overwrites only 2 macros in a compatible way.
