### ISSUE TITLE
[BUG] RSOE with Dynannotate on tiddlywiki.com (prerelease)

### ISSUE THREAD

**Issue by yaisog** [Jermolene/TiddlyWiki5#7258]
### Describe the bug

Using `$dynannotate` anywhere in _HelloThere_ on tiddlywiki.com/prerelease causes this:
![image](https://user-images.githubusercontent.com/1133745/217884636-9e4588ba-552d-4cd9-a854-2ff8061d5145.png)
In new tiddlers, it works OK.

### Expected behavior

No RSOE.

### To Reproduce

1. Go to tiddlywiki.com/prerelease.
2. Wrap any content in _HelloThere_ in $dynannotate (I used the `search` parameter).

### Screenshots

See above.

### TiddlyWiki Configuration

5.2.6-prerelease as of 2023-02-09

**Comment by Jermolene** [comment]
Thanks @yaisog I think you'll like this one... You're correct that it affects HelloThere but not most other tiddlers.

The big clue is that the RSOE only occurs if Saving -> General -> Autosave  is switched "on" in control panel. The RSOE actually occurs during the save operation where `$:/core/templates/static.content` causes a static rendering of HelloThere to be embedded in the saved HTML file. The underlying problem is that the static rendering is performed with the fakedom, which doesn't work with dynannotate.

Fix coming up.
