### ISSUE TITLE
[IDEA] Delay the backlink indexer

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7277]
**Is your feature request related to a problem? Please describe.**

It consumes too much time to re-parse tiddlers.

![截屏2023-02-22 13 44 54](https://user-images.githubusercontent.com/3746270/220533776-b1c4b471-1be5-406c-b473-362437727c5d.png)

The direct cause is a list widget's filter uses backlink filter. And this list widget is on a ViewTemplate that show under every tiddler.

**Describe the solution you'd like**

Delay execution of this indexer, or ask this widget lazy render it self after FCP: do these heavy job only after First Contentful Paint.

https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/core/modules/startup/render.js#L64-L66

For example, just return in the `render()`, and when `$tw.hooks.invokeHook("th-page-refreshed");` fired, render those lazy widgets again?

I'm not sure if this is possible, need to ask @Jermolene 

![截屏2023-02-22 13 46 38](https://user-images.githubusercontent.com/3746270/220534103-fc69e2b3-4c1d-463c-9209-0b231079beec.png)

**Describe alternatives you've considered**

Cache the inder parse result in 

```
BacklinksIndexer.prototype._getLinks = function(tiddler) {
// need cache here, so it won't need to prepare it on each page refresh.
	var parser =  this.wiki.parseText(tiddler.fields.type, tiddler.fields.text, {});
	if(parser) {
		return this.wiki.extractLinks(parser.tree);
	}
	return [];
}
```

**Additional context**

Still trying to fix #7151

**Comment by pmario** [comment]
>Delay execution of this indexer, or ask this widget lazy render it self after FCP

What is FCP?

**Comment by pmario** [comment]
>The direct cause is a list widget's filter uses backlink filter. And this list widget is on a ViewTemplate that show under every tiddler.

Why don't you hide it and show after user interaction?

**Comment by linonetwo** [comment]
> > Delay execution of this indexer, or ask this widget lazy render it self after FCP
> 
> What is FCP?

It is a web vital https://web.dev/fcp/

**Comment by linonetwo** [comment]
> > The direct cause is a list widget's filter uses backlink filter. And this list widget is on a ViewTemplate that show under every tiddler.
> 
> Why don't you hide it and show after user interaction?

Good idea, I can create a lazy widget to hide it , and show it when `th-page-refreshed` message received.

But this makes extra burden when creating powerful things in tw.

> Hide it and show after user interaction?

This is not acceptable to me, I want things to be automated.

**Comment by pmario** [comment]
I think there is is only 1 place where the indexers are rebuilt. 

indexer.init() is called when $tw.wiki() store is initialized: https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/boot/boot.js#L1135-L1143

All indexers are rebuilt when all plugins are unpacked. see: https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/boot/boot.js#L1453-L1458

-----------

**Just brainstorming**

The problem is, that `.unpackPluginTiddlers()` is executed several times. .. Which completely destroys all caches ... Which is especially problematic at startup, since users don't know what's going on. 

I'm not sure if it's really needed to destroy all caches if eg: a new plugin is loaded. IMO updating the existing cache should be more performant. ... We should have a closer look there. 

IMO it should be possible to create the backlinks cache,  server side and treat it as a cache-plugin. It would be a new type of plugins, that can be used to preheat the cache at startup. The plugin is thrown away after heating the cache, to save memory. 

https://github.com/Jermolene/TiddlyWiki5/blob/95dc56d8508109a76c232cfbcd858889d32916a9/core/modules/indexers/backlinks-index.js#L24-L26

**Comment by linonetwo** [comment]
[tw-loading-profiling.json.zip](https://github.com/Jermolene/TiddlyWiki5/files/10803186/tw-loading-profiling.json.zip)

Attach my chrome devtool profile

**Comment by linonetwo** [comment]
> IMO it should be possible to create the backlinks cache, server side and treat it as a cache-plugin. It would be a new type of plugins, that can be used to preheat the cache at startup. The plugin is thrown away after heating the cache, to save memory.

cache-plugin is a good idea, I think the same parsing for backlink has been done on server side already.

But this won't solve HTML wiki's problem, because this backlink indeder is making my HTML wiki slow to open on Tiddloid.

Or maybe we can store the indexer in the indexdb. And do stale-while-revalidate strategy on the cache, use them to render the first scene, and recalculate them. This is similar to defer the index creation. Just add a step to load previous cache.

**Comment by pmario** [comment]
Which device was used to create the profile?
It seems there are 175 `_getLinks` calls and only 5 of them seem to cause a problem. .. Can you show the template that creates the backlinks section of the viewtemplate?

**Comment by pmario** [comment]
It seems to spend most of the time to search for linkeBreaks to detect block mode. .. Is it possible, that your code is big and without any linebreaks?

**Comment by linonetwo** [comment]
> search for linkeBreaks to detect block mode

Maybe CJK language don't have line break?

The plugin is https://github.com/tiddly-gittly/tiddlywiki-plugins/blob/master/plugins/linonetwo/inverse-link-and-folder/list-link.tid 



> Which device was used to create the profile?

MacBook Pro 19 , in TidGi app, which is powerful enough, but still consume lots of time, because I have 15k+ tiddlers.

**Comment by pmario** [comment]
Try the following: 

at $:/core/ui/TagTemplate  set the reveal-line with `animate="yes"` to `animate="no"`

like so:

```
<$reveal state=<<qualify "$:/state/popup/tag">> type="popup" position="below" animate="no" class="tc-drop-down">
```

Does it make a difference?

**Comment by linonetwo** [comment]
> set the reveal-line with `animate="yes"` to `animate="no"`

No difference.

I will come back to something later. Now I have to fix some bug in Tiddloid first.

**Comment by pmario** [comment]
Can you post a screenshot, how such a backlinks area looks like, for a tiddler. ... I'm not interested in the text of the pills I'm only interested how many of them are shown in

- how many of them are shown in 链入
- how many of them are shown in 此文件夹中的文件

I think with 8k tiddlers and a lot of tags and backlinks your map should be quite complex. Backlink indexing is **the most expensive** index we can create with TW, because it has to parse every tiddler text to get the link-info. 

For me it looks like this with FF

![image](https://user-images.githubusercontent.com/374655/220882257-b7e1aadd-8f6b-448c-93b2-40a33e5be424.png)

and like this with Edge ...  I do not have those RegExp searches for 2 linkebreaks that is part of your profile. ... All the RegExps in your flamechart cause the delays. 

------->>>> [Profile-20230223T114029.pmario.zip](https://github.com/Jermolene/TiddlyWiki5/files/10812636/Profile-20230223T114029.pmario.zip)

![image](https://user-images.githubusercontent.com/374655/220883368-2f624714-babf-4c41-a05e-aa822faff976.png)

**Comment by pmario** [comment]
I forgot to mention, that from inspecting your profile, I found out that the regexp iteration comes from an html table, which seems to contain an H3 element and many TDs, which seem to be completely empty. .. 

Is it possible that you have some table fragments, that are visible but should not be active there?

**Comment by Jermolene** [comment]
Hi @linonetwo 

> Delay execution of this indexer, or ask this widget lazy render it self after FCP: do these heavy job only after First Contentful Paint.

Avoiding displaying the backlinks in the initial refresh would definitely improve startup times.

One possibility might be to introduce a new variant of `$:/tags/StartupActions` for actions that are performed after the initial render of a wiki. Perhaps `$:/tags/PostStartupActions`.

Then you could hide your backlinks in the viewtemplate behind a config tiddler that you'd initialise inside the post startup actions.

**Comment by saqimtiaz** [comment]
Note that we do have the $:/tags/StartupAction/PostRender actions available.

**Comment by Jermolene** [comment]
> Note that we do have the `$:/tags/StartupAction/PostRender` actions available.

Ooh yes, I'd forgotten about that, I think that should work here.

**Comment by linonetwo** [comment]
> which seems to contain an H3 element and many TDs, which seem to be completely empty. ..

No, I don't use any manual table, only KooKma's dynamic table.



> Do you use the wikify-widget in your templates?

No.

---

All slow down comes from the day I import 10k tiddler from GoogleClendar, then the kin-filter and backlink[] and field-indexer gets very slow. Most of these tiddlers are something like:

```yaml
@ -0,0 +1,12 @@
calendarEntry: yes
caption: 综合写代码
created: 20230224151720152
creator: 林一二
draft.title: 
endDate: 20230224151500000
modified: 20230224151720152
modifier: 林一二
startDate: 20230224120000000
tags: 解决问题
title: 2023-02-24T20:00:00+08:00
type: text/vnd.tiddlywiki
```

Only metadata, no code, just increase the count of titles in the wiki.

**Comment by linonetwo** [comment]
I will try `$:/tags/StartupAction/PostRender` first, and If it works, I will write a tutorial about this.

But now I'm working on Tiddloid's bug, my wiki is too big that it causes the Android app OutOfMemory when saving the wiki.

**Comment by linonetwo** [comment]
Problem was solved by optimizing the code. But the technique here is still worth a try. I will use `$:/tags/StartupAction/PostRender` to build a task runner for https://talk.tiddlywiki.org/t/i-want-a-import-browser-history-plugin-and-a-robot-plugin-to-auto-import-daily/6285

that can auto import data to tw after it starts.
