### ISSUE TITLE
[BUG] New here with default tag "aa aa" does not work as intended

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7354]
### Describe the bug

As described at: https://talk.tiddlywiki.org/t/now-is-the-time-to-help-with-testing-the-tiddlywiki-v5-2-6-prerelease/6405/15?u=pmario

There is a problem if the $:/config/NewTiddler/Tags to `aa aa` which is changed to `[[aa aa]]` .. Wich is OK. 

BUT .. "New here" command does it wrong. See screenshot. 

To reproducde: 

- Open ControlPanel
- Set [Tags for new tiddlers](https://tiddlywiki.com/prerelease/#%24%3A%2Fconfig%2FNewTiddler%2FTags) to eg: "aa aa"
- Create a New Tiddler with the right sidebar + button -> OK
- Use the "New Here" from the tiddler "more dropdown" as shown in the screenshot
- -> problem the tag is now `[[aa aa]]` wich is wrong

### Screenshots

![grafik](https://user-images.githubusercontent.com/374655/224477669-8ef8e03e-c5f8-44f3-9b8f-6cb51b3c47fc.png)

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by pmario** [comment]
@Jermolene .. This one should be fixed till 20th

**Comment by Jermolene** [comment]
Hi @pmario

I've investigated and have a fix ready to go.

> This one should be fixed till 20th

I think you're saying that this bug should be fixed before the 20th March release of v5.2.6?

As far as I can tell, this bug has existed for several years. Generally, in these freeze periods we are focussed on fixing bugs introduced in the new version, and defer fixes for older bugs.

However, in this case the fix is simple enough that I propose to push it now.
