### ISSUE TITLE
Add a WebDAV Saver

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#738]
As discussed in this thread, it turns out to be pretty simple to get WebDAV up and running:

https://groups.google.com/d/topic/tiddlywikidev/eb5JHNm_eak/discussion

@FND has hacked together a working implementation:

https://gist.github.com/FND/b3e969f5ed471b55c831

**Comment by edrex** [comment]
@FND, does your store load and save individual .tids in the same format as used by the NodeJS server? I'm very much interested in continuing this work.

Here's a sketch of what I'm planning:

Phase 1:

- Minimal HTML TiddlyWiki loads first, then loads all tiddlers in store by walking directory indexes. This will be slow with HTTP/1.1, but wicked fast with HTTP/2 pipelining.
- Reference WebDAV server with HTTP/2 support, with a similar interface to `tiddlywiki server`. Either in Golang or Node.js. I'm already pretty familiar with the http2 implementation in Go. This is just for convenience - the goal is that any WebDAV server will work.

Phase 2:

Introduce a [Service Worker](https://github.com/slightlyoff/ServiceWorker/blob/master/explainer.md) for cache management and offline data access, which will provide a reliable offline experience on [supporting browsers](http://caniuse.com/#feat=serviceworkers). I think this will be independent of WebDAV, still need to work out the details.

**Comment by FND** [comment]
My implementation there uses TiddlyWeb's tiddler RFC822-style serialization (i.e. `key: value` pairs, blank line, body) - which, as I recall, is also what TW5's Node implementation was based on. So I imagine it should be fully compatible.

It would be very exciting to see this actually working out, so you're more than welcome to pick up the code and use it however you see fit. Unfortunately, since I stalled out on this effort quite a while ago, I'm not sure that I'll be much help at this point - though I can try, so let me know if anything's unclear.

By the way, that Taskard repo has moved to https://github.com/FND/taskard.original - so I'm afraid the URLs above aren't quite right anymore (it's all still there though, just add the ".original" suffix).

**Comment by edrex** [comment]
## Timeline

### Developer preview

* [ ] Test suite for client
* [ ] If on HTTP, check server headers for DAV
* [ ] Queries root for list of tiddlers with `[PROPFIND](http://www.webdav.org/specs/rfc4918.html#METHOD_PROPFIND) Depth: infinity` on root resource
* [ ] Root defaults to the current URL with file extension and index.html stripped and '/' appended:
  * `"/My Documents/wiki.html" -> "/My Documents/wiki/"`
  * `"/foo/index.html" => ""foo/"`
* [ ] Map between resource paths and tiddler titles as in `tiddlywiki --server`
* [ ] Get/load tiddlers in the RFC format

### MVP

* [ ] Get/load binary tiddlers
* [ ] Test on Owncloud
* [ ] Test with Camlistore webdavfs

### MVP+1

* [ ] Poll server for updates if ETAGS are supported, fetch and reload changes. See [owncloud's notes on this](https://github.com/owncloud/core/wiki/spec:-WebDAV-Optimizations).


### And a pony

* Non-default option to back up metadata-only tiddlers to HTML periodically, to optimize initial load time.
* HTTP/2 pipelining when client and server support it.
* Offline loading via [Service Workers](https://github.com/slightlyoff/ServiceWorker/blob/master/explainer.md) on [supported browsers](http://caniuse.com/#feat=serviceworkers).

**Comment by edrex** [comment]
The webdav litmus test is a good resource: http://www.webdav.org/neon/litmus/

**Comment by edrex** [comment]
Just from a cursory look, https://github.com/FND/dav-dump looks like a solid foundation.

### Initial experiments

* [ ] Try to adapt FND's store implementation as a TW5 plugin. Can we do it entirely as a TW5 plugin? If not, what modifications to boot.js are needed?
* [ ] Also eval available WebDAV client libs on NPM. Let's not be all insular eh?

**Comment by edrex** [comment]
> This is partly because the current canSave method always returns true; it should probably check that the wiki has been loaded from an http(s) URL. Even then, there is no way for JS to be able to tell that the wiki was loaded via webdav.

@Jermolene we can check for [DAV header](http://www.webdav.org/specs/rfc2518.html#rfc.section.9.1) in the initial response.

A flow for a (core) plugin might look something like this:

On boot

 - if DAV header in initial response (+ more followup checks perhaps)
 - switch `dav.enabled` preference *IDK yet how the TW5 pref system works, just making this up*
 - case `undefined`:
   - Prompt user: "I appear to be on a server with DAV extensions. Would you like me to use DAV when saving?"
     - **Save as single HTML file**
     - **Save as individual .tid files**
     - **No**
     - **Ask me later** (on save)
 - etc

or something like that. It might also ask whenever it is accessed from a new URL.

**Comment by edrex** [comment]
Actually it would be great if there was a preference, initially unset, which says *"I know how to save myself, I use this method"*. It could be set to `dav.html` for single file or `dav.tiddlers` for isomorphic mode.

**Comment by Jermolene** [comment]
Hi @edrex 

> we can check for DAV header in the initial response.

As far as I am aware, it is not possible for JS code to access the headers obtained when the HTML file itself was loaded by the browser; all we can do is to make a further XMLHttpRequest to the same server, and check for the header in the response.

> Prompt user: "I appear to be on a server with DAV extensions. Would you like me to use DAV when saving?"

What we're really talking about here is the interactions between the "saver mechanism" (which is concerned with saving the entire HTML file) and the "sync mechanism" (which is concerned with syncing individual tiddlers to an asynchronous store API (either the TiddlyWeb HTTP API or the Node.js asynchronous file APIs).

Right now there's rather minimal logic for switching between the syncer and the saver; we just need to tighten things up a little, and then you'd write a webdav syncer that would (by default) take over from the saver mechanism.

While thinking about this area I'd be looking for opportunities to share code with the TiddlyWeb syncer module. The logic should be much the same, and the implementation extremely similar.

**Comment by Jermolene** [comment]
By the way @edrex my personal tepidity for WebDAV historically has been driven by the feeling that there is declining choice in both client and server implementations -- there was a time when both Microsoft and Apple were showing an interest in WebDAV. Now the new wave Silicon Valley companies like Google and Dropbox don't seem to be at all enthusiastic. What WebDAV server are you planning to work with?

**Comment by edrex** [comment]
> As far as I am aware, it is not possible for JS code to access the headers obtained when the HTML file itself was loaded by the browser; all we can do is to make a further XMLHttpRequest to the same server, and check for the header in the response.

> oh boo. as I was writing that, I felt the tickle of a dissonant memory, now I realize what it was.

> my personal tepidity for WebDAV historically has been driven by the feeling that there is declining choice in both client and server implementations -- there was a time when both Microsoft and Apple were showing an interest in WebDAV. Now the new wave Silicon Valley companies like Google and Dropbox don't seem to be at all enthusiastic. What WebDAV server are you planning to work with?

Owncloud is one of the most interesting implementations, as it's quite popular and has gone whole-hog with CardDAV, CalDAV, for exposing its data. I'd tend to follow their lead. jsDAV makes it super easy to add DAV support to a Node.js server, so a baked-in tiddlywiki subcommand might also be an attractive option. Honestly I think the new wave Valley companies turning up their nose at DAV is mostly coming from a strategy getting ecosystem devs locked in to their proprietary API juice. Lock-in strategies are only effective for first and second movers, and as the market for cloud data storage matures and switches to commodity (where we are now) common protocols become an important consideration in consumer choice, which in this case I think predicts DAV (or something like it, but I don't know what that would be, and DAV is pretty technically sweet) making a comeback.

**Comment by Jermolene** [comment]
Thank you @edrex I wasn't aware that Owncloud used *DAV like that, jolly good. I've seen some other private cloud projects - this one uses TW both for the home page and as a sample app: https://librenote.aerobatic.io/

**Comment by edrex** [comment]
In [SyncAdaptorModules](http://tiddlywiki.com/dev/#SyncAdaptorModules) doc, getSkinnyTiddlers is listed as necessary for remote -> store sync. 

For non-tiddlyweb sync adapters, it won't be possible to get some fields without getting the text, so it seems like a more general method would be something like `listTiddlers(callback)`, just returning an array of titles, and then `getTiddler` to actually fetch.

I also wonder if inverting the control so that the adapter can just inject tiddlers into the store whenever wouldn't be better, since then the adapter can make choices about what to load and when. I plan to support polling the server for changes; other adapters may even support push updates via eg the new [push api](https://www.w3.org/TR/push-api/) that came in with service workers. It seems like adapters can already do this by calling methods on `options.wiki`, yes?

**Comment by edrex** [comment]
**Updates:**

 - Last Tues I knocked together a convenient webdav server command, installable by npm: [dav-server](https://github.com/edrex/dav-server).
 - I think a good goal is full interoperability with `tiddlywiki --server`. Reading a directory should result in the same store content; client-side writes should result in the same filesystem changes. I'm currently mapping out any differences between @FND's store and the TW5 server here.

**Comment by Jermolene** [comment]
Hi @edrex for servers that don't support skinny tiddlers, "getSkinnyTiddlers" should just return the full tiddler. There's no point in the adaptor exposing tiddlers for which it only knows the title; the core needs the other fields before it can anything useful with the tiddler (like include it in listings).

> I also wonder if inverting the control so that the adapter can just inject tiddlers into the store whenever wouldn't be better, since then the adapter can make choices about what to load and when. I plan to support polling the server for changes; other adapters may even support push updates via eg the new push api that came in with service workers. It seems like adapters can already do this by calling methods on options.wiki, yes?

As things stand, adaptors should not modify the store directly. They do have access to the wiki object but that's for things like reading configuration data.

I'd expect to run into issues with the syncadaptor interface; it's only been evolved sufficiently to cover the current filesystem and tiddlyweb adaptors, and I'd be happy to see it evolve further. In particular, we need better logic for selecting the current syncadaptor; there's a lot of special casing at the moment.

But, if the assumptions of the sync mechanism are too restrictive it may be better to do something entirely separate, and consider later whether/how to merge things.

By the way, in terms of the problem of an HTML wiki figuring out whether it was loaded from a DAV server, the technique that the TiddlyWeb adaptor uses is that the presence of the plugin indicates that the server should be used. That would suggest that we'd keep DAV support as a plugin.

**Comment by FND** [comment]
Thanks for keeping us updated, @edrex! I'm very happy to see you making progress and will try to respond to your DAV-Dump issues over the next few days. (Things are a little busy right now on my end.)

(dav-server seems a useful tool to avoid [familiar headaches](https://github.com/mikedeboer/jsDAV/issues/111#issuecomment-178248431))

**Comment by edrex** [comment]
>  for servers that don't support skinny tiddlers, "getSkinnyTiddlers" should just return the full tiddler. There's no point in the adaptor exposing tiddlers for which it only knows the title; the core needs the other fields before it can anything useful with the tiddler (like include it in listings).

That will work fine for the initial load when all tiddlers need to be fetched anyway, although it's memory inefficient to queue up all the loaded tiddlers in the adapter before returning them to the store. 

`Syncer#syncFromServer` also uses `getSkinnyTiddlers` to poll for changes, using the revision field. For non-TiddlyWeb sources this will need to be generalized to use an opaque revision supplied by the sync adapter (`ETag || modtime` for webdav).

I think the minimal interface change to support this would be to add a method:

```
/* Returns a map from available tiddler titles to an opaque revision string */
listTiddlers () => { "$title": "$revision", ... } // implicit callback
```

and modify `loadTiddler` to return a tuple:

```
loadTiddler(title) => (tiddler, revision) // with callback
```

We could merge the `getSkinnyTiddlers` method into `listTiddlers`, allowing the property values to be either a string `"$revision"` or a skinny tiddler, in which case the revision is extracted from the object as currently.

WebDAV's `listTiddlers` would make a PROPFIND{ Depth:1 } request to the root to list all contained resources along with their `getetag` and `d:getlastmodified` properties. It would use etag as the revision if available, otherwise lastmod. 

Likewise, `loadTiddler` would GET, and use the ETag or LastModified header as revision.

**Comment by edrex** [comment]
I decided to implement a simple saver module as a first step, since that will be immediately useful. It will work with any server which accepts a PUT request to the current URL, which includes webdav, couchdb, riak, etc.

**Comment by FND** [comment]
Hey, just wanted to check in and say that I've finally started to use TiddlyWiki's WebDAV saving. Getting started was a bit daunting, but possibly just because I was overthinking it: [The documentation](http://tiddlywiki.com/#GettingStarted%20-%20WebDAV) doesn't mention that TW auto-detects WebDAV support, so I went down a bit of a rabbit hole before realizing it Just Works™.

Anyway, it works great, so thanks!

**Comment by Jermolene** [comment]
Hi @FND that's great to hear, thanks for the feedback.

**Comment by tlhonmey** [comment]
The auto-detect is nice, but for some things like {own,next}cloud you can't open the page directly via the webdav interface, so it doesn't detect and therefore doesn't save.

Is there an easy place to poke it to tell it "always save via webdav to X location"?  I've tried fiddling with it myself, but I'm not sure I understand it well enough...

**Comment by ght** [comment]
@tlhonmey You should probably open a new issue for this, it sounds like a useful feature! This issue was closed almost 5 years ago, your request will just get overlooked and forgotten here.
