### ISSUE TITLE
[BUG] The First Attribute of a Parameters Pragma is Overwritten when Is used Inside a Procedure

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#7458]
### Describe the bug

If you use `\parameters` inside a `procedure` the value of first attribute of parameters will be overwritten by procedure first attribute

### To Reproduce

1. Go to ['...'](https://tiddlywiki.com/prerelease)
2. Create a new tiddler with below contents

```
\procedure eqn(x)
\parameters (a:2, b:5)
* x = <<x>>
* a = <<a>>
* b = <<b>>
\end

<<eqn 4>>
```

you will get

- x = 4
- a = 4
- b = 5

Note how `a` is overwritten by `x`

### TiddlyWiki Configuration

- Version 5.3.0

- OS: Win10
- Browser Chrome/Edge 112

**Comment by kookma** [comment]
Second example

```
\procedure eqn()
\parameters (a:2, b:5)
* a = <<a>>
* b = <<b>>
\end

<<eqn 344>>
```

produces

- a = 344
- b = 5

**Comment by kookma** [comment]
Third example

```
\procedure mymacro()
<$parameters name={{$:/SiteTitle}} age="21">
My name is <<name>> and my age is <<age>>.
</$parameters>
\end

<<mymacro GitHub 15>>
```

produces:  My name is [GitHub](https://tiddlywiki.com/prerelease/#GitHub) and my age is 15.

**Comment by kookma** [comment]
Fourth example: here a **macro** is used

```
\define mymacro()
<$parameters name={{$:/SiteTitle}} age="21">
My name is <<name>> and my age is <<age>>.
</$parameters>
\end
```

produces: My name is GitHub and my age is 15.
<<mymacro GitHub 15>>
```

**Comment by pmario** [comment]
That's a tricky one. TW has "positional" and "named" parameters. So it's an implementation detail.

 .. @Jermolene may be it would be an option to use a "rest-like" syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters 

```
\procedure eqn(x, y)
\parameters (... a:2, b:5)

```

**Comment by pmario** [comment]
>It seems there is a bug with both \parameters pragma and <$parameters widget! whne are used inside procedures

It's more like a "misuse". It's not intended to be used that way. ... **But** for sure it's an issue. ... As I wrote IMO it's how "positional" parameters are resolved at the moment. 

Javascript has a similar problem, if you have a closer look at the link from my first post. They solved it with the ...rest parameter. May be we can resolve the problem in a similar way. 

BUT I think it will increase mental complexity quite a bit. :/

**Comment by pmario** [comment]
@kookma take your examples and preview them as "parse-tree" and "widget-tree" ... May be youi'll see, how it is implemented at the moment. I'm not sure if the JSON output makes sense, but it would be worth a try.

**Comment by Jermolene** [comment]
Hi @kookma @pmario the parameters widget reaches up the widget tree to the parent transclude widget and then processes each of its attributes in turn, assigning a value to the associated variable from either the provided parameter value or the default value if no parameter value was provided.

Perhaps the surprising thing is that there's nothing to stop using multiple parameters widgets within the same procedure; they'll all just be processed in turn in the usual way. As far as I can tell, that's all that is happening in your examples.

It might be helpful if you could indicate the output that you expected from your examples.

**Comment by kookma** [comment]
This can be error-prone! it will overwrite the parameters anyway! Example

```
\procedure myproc(x:10)
\parameters (a:100, b:200)

* x=<<x>>
* a=<<a>>
* b=<<b>>
\end

<<myproc 50>>
```

Produces 

- x=50
- a=50
- b=200

That means we cannot use the `\parameters` inside a procedure has an attribute!

**Comment by kookma** [comment]
> It might be helpful if you could indicate the output that you expected from your examples.

For the below example

```
\procedure myproc(x:10)
\parameters (a:100, b:200)

* x=<<x>>
* a=<<a>>
* b=<<b>>
\end

<<myproc >>
```

I expect

- x=50
- a=100
- b=200

**Comment by Jermolene** [comment]
Thank you @kookma. If we take your latest example, it is equivalent to the following:

```
<$let myproc="""
\parameters (x:10)
\parameters (a:100, b:200)

* x=<<x>>
* a=<<a>>
* b=<<b>>
""">

<<myproc 50>>
```

The crux of the confusion is that those two parameters widgets are entirely independent. They are both processed as if the other parameter widget is not there.

**Comment by Jermolene** [comment]
Hi @kookma thanks for the clarification. It seems that the confusion is the way that each parameters widget reruns the processing for positional parameters. Again, I don't quite see why this is an issue. There doesn't seem to be a good reason to have multiple parameters widgets within a definition, but if users attempt it (as here), the results are consistent and logical, as long as one understands that each parameters widget is processed independently.

**Comment by pmario** [comment]
I personally think, that the `\parameters` pragma  and the widget should **not** be used in procedures at all. So IMO it also is a documentation problem. ... 

I'm not sure, if we should or can do something on the parser level. May be a message similar to the "recursion warning" would be an option if possible.

**Comment by pmario** [comment]
>I'm really not seeing why any of this is considered a problem. Additional engineering just to give more meaningful error messages for contrived scenarios that don't have a practical application doesn't seem a good use of effort.

I do not have a problem with the existing functionality. I did see the code how it is implemented. ... But it's not obvious for standard users to see, why the following code creates unexpected results.

The problem here is that `<<eqn..` is activated with an unnamed parameter. So we need to document, that this can cause problems as the following example shows. 

```
\procedure eqn(x)
\parameters (a:2, b:5)
* x = <<x>>
* a = <<a>>
* b = <<b>>
\end

<<eqn 4>>
```

Calling the procedure with a **named parameter works** as expected. For ordinary users that's also not obvious. I know the code so it's clear why that works and the other one does not. 

```
<<eqn a:4>>
```

**Conclusion**

Grom my point of view we should declare "named parameters" as a best practice (which is always has been) and should never use unnamed params in our code UI code.

**Comment by kookma** [comment]
> Again, I don't quite see why this is an issue.

Because in below example, overwriting p is unexpected even for an experienced user.

```
\procedure myproc2(a)
This is a=<<a>>, <<.lorem>>
hundred lines of code...
..
another hundred lines of code...
<$parameters p=100>
and this is internal p=<<p>>
</$parameters>
\end

<<myproc2 20>>
```

I do not expect `p` in a parameters widget in such depth shall be overwritten while I only pass value for `a` attribute? How casual user shall know in advance, if he/she call `<<myproc2 20>>` to pass 20 to `a`, also a parameter in deepest line of code will be changed! 
This can be error prone!

**Comment by Jermolene** [comment]
Thanks @kookma – the bit I don't follow is why you would want to put a second parameters widget within the same definition? Sticking with a single parameter definition avoids all the confusion.

The suggestion that this confusion could be a rationale for removing positional parameter support leaves me a bit baffled.

**Comment by kookma** [comment]
> the bit I don't follow is why you would want to put a second parameters widget within the same definition?

Ah, may be I misunderstand procedure, please kindly clarify by answering the below question:

Is the below example contains one parameters widget or two?

```
\procedure myproc2(a)
This is a=<<a>>, <<.lorem>>
hundred lines of code...
..
another hundred lines of code...
<$parameters p=100>
and this is internal p=<<p>>
</$parameters>
\end

<<myproc2 20>>
```

If it has two (means `procedure` itself is equal to parameters), then from your explanation, I should avoid using `$parameters` inside procedure! If the above example has one `$parameters` then my raised issue in previous post is valid!

**Comment by Jermolene** [comment]
Hi @kookma procedure definitions include an implicit parameters widget – see my [comment above](https://github.com/Jermolene/TiddlyWiki5/issues/7458#issuecomment-1549358751) for details. So your example includes two parameters widgets in total.

There is one situation where it is useful to include a parameters widget within a procedure, which is when you want to assign a dynamic value as the default value. For example:

```
\procedure myproc2()
<$parameters p={{MyDefaultValue}}>
...
</$parameters>
\end

<<myproc2>>
```

**Comment by kookma** [comment]
Thank you for clarification! Like @pmario I would recommend adding this clarification into official doc.
I will submit a PR with few examples.

**Comment by Jermolene** [comment]
Thank you @kookma that would be great.

**Comment by flibbles** [comment]
> The bit I don't follow is why you would want to put a second parameters widget within the same definition? Sticking with a single parameter definition avoids all the confusion.

@Jermolene, I think it's a bold assumption to assume the end-users won't do stupid things.

I've just come upon this issue now that I'm coding Relink to handle parameters. If multiple parameters are used, relinking becomes ambiguous as parameters work now. I *could* join in with the whole "You shouldn't be doing this", response to this issue, but it does seem lazy.

I haven't looked at the implementation, so maybe I'm wrong when I suggest this, but why don't sequential parameter declarations simply acknowledge what parameters already exist, and then append their own arguments to the end so they all have unique argument indices?

**Comment by Jermolene** [comment]
> > The bit I don't follow is why you would want to put a second parameters widget within the same definition? Sticking with a single parameter definition avoids all the confusion.
> 
> @Jermolene, I think it's a bold assumption to assume the end-users won't do stupid things.

It might have been clearer if I'd said "I don't understand what you would expect to happen if you put a second parameters widget within the same definition".

> I haven't looked at the implementation, so maybe I'm wrong when I suggest this, but why don't sequential parameter declarations simply acknowledge what parameters already exist, and then append their own arguments to the end so they all have unique argument indices?

That's a good idea that has not come up before. I think it could be done quite neatly, I'll investigate.

**Comment by Jermolene** [comment]
I've created a branch with a failing test at https://github.com/Jermolene/TiddlyWiki5/tree/coalesce-parameter-widgets, and started to think about the implementation.

**Comment by Jermolene** [comment]
Hi @flibbles the problem I'm running into is the `$depth` attribute. It allows one to reach up and access parameters of transclusions higher up in the widget tree. It makes coalescing parameters widgets harder because the parameters widgets targeting a particular transclusion might be anywhere in the widget tree, including with intermediate transclusions. I'll continue thinking about it, but it looks like a very complex undertaking.

**Comment by flibbles** [comment]
@Jermolene. Ah. The `$depth` attribute. I've been meaning to bring that up.

First of all, I'd like to say I'm grateful that you've taken my suggestion seriously and considered whether it's possible. If we move forward, I'd be happy to dig in myself and create a PR which implements sequential index assignment.

I'd also like to say that in general, the more I have to implement v5.3.x, the more I start to understand the purpose of some of the new features.

* `\procedure` is great. Far less bug prone. and I've seen the necessity of it when it comes to using substitution attributes, since you can't mix the two.
* About that, substitution attributes may be the best new feature of v5.3.0. They solve a very common problem that I (and probably a lot of people have) about string construction, and it's a far more appropriate use of substitution than the way \macro was using them.
* \function? I've since found several places where I've personally used it. Not sure why it's not called `\filter`, but I like the feature as it is.
* `\widget`? Lots of potential there. I think it could use some work making all the slot and fill stuff more practical, but definitely a start that could provide a lot of problem solving.

The `$depth` attribute.

**What is it FOR?**

It's a bizarre thing, isn't it? Besides making relinking impossible if it's ever used, I can't think of a practical use case, and I'm not able to make sense of [the documentation's example](https://tiddlywiki.com/#SlotWidget).

I'll stop there. There's a **lot** I want to say about it, but I won't turn this thread into a discussion about it's merits. (I'm still planning to make a discussion thread about it.)

But it would be a real pity if that `$depth` feature prevented this practical solution from existing. Seems like the only reason to bother using the depth attribute is if someone were recursively calling the same procedure, because otherwise they already have access to parent arguments in the parse tree node. Right?? And then only a lunatic would use `$depth` when they could just *call* the arguments they want. Right? Right???  So... any depth-arguments must already have to have their own indices, and in that case they could recycle the same position.

I'd give you an example to clarify my point, but honestly, I can't think of one that makes any sense. Every time I've ever tried to comprehend the `$depth` attribute, it's like I'm trying to make sense of some quantum physics phenomenon. It's just so unlike any real life experience that we have no reference to make sense of it.

**Comment by btheado** [comment]
> The $depth attribute.
> What is it FOR?

Prior to #7451, the [visible transcludes](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FVisibleTransclude:%24%3A%2Fcore%2Fui%2FVisibleTransclude%20%5B%5BVisible%20Transclusions%5D%5D%20HelloThere) functionality used the depth parameter.

Here is another case which uses the depth parameter:

https://github.com/Jermolene/TiddlyWiki5/pull/7340#issuecomment-1530011419 

I'm finding it difficult to provide a summary on what the above is doing (red flag, I know :-)), but maybe playing with the demo and reading the preceding comments will make it more clear?

**Comment by flibbles** [comment]
For that [#7430 comment](https://github.com/Jermolene/TiddlyWiki5/pull/7340#issuecomment-1530011419), doesn't the following make a much easier to understand solution?
```
\parameters(filter)
<$list filter="[subfilter<filter>is[tiddler]first[]]">

<$list-template>

<$transclude $tiddler=<<currentTiddler>> />

</$list-template>
<$list-empty>

<$slot $name=ts-raw />

</$list-empty>
</$list>
```

**Comment by flibbles** [comment]
And even if someone can come up with a situation complicated enough where $depth is needed to access ts-raw from higher up, which is what's happening in your examples, that's still for ts-raw, not for parameters. I'm still suspicious that using $depth for anything results in difficult-to-understand solutions.

**Comment by flibbles** [comment]
Better yet, we can use the fancy new conditional shortcut syntax I used to hate. Though I admit this might not have been around when you wrote that solution.
```
\parameters(filter)
<% if [subfilter<filter>is[tiddler]first[]] %>

<$transclude $tiddler=<<condition>> />

<% else %>

<$slot $name=ts-raw />

<% endif %>
```

**Comment by Jermolene** [comment]
Hi @flibbles @btheado I am also struggling to find use cases for the `$depth` attribute of the parameters widget. As @btheado notes, at one point it was necessary in order to be able to use a custom widget to override the transclude widget, but subsequently we developed a better approach win #7451 and now the core no longer uses the `$depth` attribute.

I don't think it would be ridiculous to remove the `$depth` attribute in the prerelease and see if it causes any issues for users.

**Comment by pmario** [comment]
>I don't think it would be ridiculous to remove the $depth attribute in the prerelease and see if it causes any issues for users.

+1 -- I would be in favour of this suggestion.

**Comment by flibbles** [comment]
> I don't think it would be ridiculous to remove the $depth attribute in the prerelease and see if it causes any issues for users.

I also agree with removing it, and not just because it makes my job with Relink easier. I honestly believe no one is using $depth with $attributes right now.

AFterward, if you'd like, @Jermolene, I can look into making added parameters sequential have sequential indices if you haven't already. It was my idea. Seems like it should be my work.
