### ISSUE TITLE
BelowStory does not work in Zoomin view

### ISSUE THREAD

**Issue by gernert** [Jermolene/TiddlyWiki5#746]
quote frm https://groups.google.com/d/msg/tiddlywiki/qv7Hvl1KbVg/HbED3PMExgAJ

> How can I modify the code in order for a  footnote tiddler (below the story river) to be visible when in zooming view?
> The problem appears only with a note "below the river" but not "above the river".

To reproduce:
1) Start in Classic view
2) Create a tiddler with some 'above' text tagged with $:/tags/AboveStory
3) Create a tiddler with some 'below' text tagged with $:/tags/BelowStory

The tiddlers created in 2) and 3) will be displayed above and below the story.

4) Switch to Zoomin view

The tiddlers created in 2) and 3) will be displayed BOTH above the story.

5) Save and reload

Although you now see only the tiddler created in 2), closing all tiddlers shows BOTH the tiddlers created in step 2) and 3).

**Comment by sobjornstad** [comment]
This issue still occurs in 5.3.6.

Making the footer part of the tiddler is not a very satisfactory solution, because it results in the footer appearing *within* the tiddler, rather than in the background of the page as expected. Also, if you want to be able to switch between `classic` and `zoomin` mode, you'd then have to add logic to detect which one is in use and render the footer in the appropriate location.

I dug up an obscure hack I had used in a wiki awhile ago and updated it to work with the current version:

```
.tc-page-container.tc-page-view-zoomin .tc-tiddler-frame {
    position: unset;
}
```

...which overrides this vanilla theme rule:

```
.tc-page-container.tc-page-view-zoomin .tc-tiddler-frame {
	position: absolute;
	display: block;
	width: 100%;
}
```

I don't fully understand why this is set to `position: absolute` by default, so I'd imagine this breaks something obscure, but I haven't been able to figure out what it is, if so.
