### ISSUE TITLE
[BUG] Behavior of the last filter when zero items requested

### ISSUE THREAD

**Issue by DBH321** [Jermolene/TiddlyWiki5#7507]
### Describe the bug

When using a variable to decide how many list items the last filter operator should return, it can happen that the number calculated is zero. In this case the last operator returns the entire list not no items as would seem to be the correct action. 

(As expected !limit<n> for n=0 returns the whole list, since it is stated to be a synonym for last. Note though that it is not strictly a synonym since last[N] defaults to N=1 and !limit[N] defaults to N=0 according to tiddlywiki.com. !limit[] returns the entire list not no items as one would assume from the statement about the default value being 0 or the last item if it was fully synonymous with last.)

### Expected behavior

When n=0 last<n> should return nothing. It would make the most sense when one is requesting some number of list items that if the number is zero, then nothing is returned. Note that this would match the behavior of first<n> when n=0 which returns nothing. It would also match the behavior of limit[N] which should default to N=0 and limit[] returns nothing.

### To Reproduce

Create and display a tiddler with this wiki text-

NB hardcoded 0 was just done for completeness

\define zero() 0

\define theList()  A B C D E F G H I J

!Last:

nothing: {{{ [enlist<theList>last[]] }}}

<<zero>>: {{{ [enlist<theList>last<zero>] }}}

hardcoded 0: {{{ [enlist<theList>last[0]] }}}

!First:

2: {{{ [enlist<theList>first[2]] }}}

nothing: {{{ [enlist<theList>first[]] }}}

<<zero>>: {{{ [enlist<theList>first<zero>] }}}

hardcoded 0: {{{ [enlist<theList>first[0]] }}}

!"""!"""limit:

nothing: {{{ [enlist<theList>!limit[]] }}}

<<zero>>: {{{ [enlist<theList>!limit<zero>] }}}

hardcoded 0: {{{ [enlist<theList>!limit[0]] }}}

!limit:

nothing: {{{ [enlist<theList>limit[]] }}}

<<zero>>: {{{ [enlist<theList>limit<zero>] }}}

hardcoded 0: {{{ [enlist<theList>limit[0]] }}}

### TiddlyWiki Configuration

- Version  v5.1.27
- Saving mechanism TiddlyDesktop
- Plugins installed none

### Desktop (please complete the following information):

- OS: MacOS 13.4
- Browser TiddlyDesktop
- Version 0.0.14

**Comment by rmunn** [comment]
Yes, that's a bug. BTW, your "To Reproduce" example came out garbled, because GitHub interprets `<<foo>>` as an invalid HTML element `<foo>` inside angle brackets and renders it as <<foo>>. (I typed `<<foo>>` at the end of that sentence without putting backticks around it; see how it came out wrong?) It doesn't matter here as it's quite easy to figure out how to reproduce it, but in the future you'll want to use triple-backticks at the start and end of any TW text you put in a GitHub issue. (When writing comments on an issue you can click on the "Preview" tab to check that it's coming out right, but unfortunately the issue form doesn't have a "Preview" tab in the reproduction section — something I wish GitHub would fix.)
