### ISSUE TITLE
[IDEA] Standardize Settings Tabs

### ISSUE THREAD

**Issue by GameDungeon** [Jermolene/TiddlyWiki5#7522]
Currently, the code mirror plugin overrides the control panel's settings menu to add tabs. It then creates a tab for itself to allow you to select between changing tiddlywiki and code mirror settings. Other plugins use this same method of overwriting the settings menu and creating the tabs as well. 

I propose that those overrides become the default functionality, making the settings menu tabs there by default (of course only with a single tab), with the ability to add more tabs through tags.

This has two main benefits:

- It prevents two plugins from overriding the settings menu in two slightly different ways creating a conflict and breaking a plugin.
- It creates a standard place where users can expect to settings pages for installed plugins.

**Comment by kookma** [comment]
I have raised this before. There will be no Setting tab, if you do not install CodeMirror. As you said it overwrites the core tiddler.

See
* https://github.com/Jermolene/TiddlyWiki5/issues/5520
* Not directly related but worth to be seen if Settings can be overhauled: https://github.com/Jermolene/TiddlyWiki5/issues/4507

**Comment by twMat** [comment]
How would the default Settings tab then appear when no Codemirror is installed? I.e would it be a tab with a *single* subtab under it? Not so elegant.

A more general idea would be to make the //tabs// macro **recursive** to show a tree of subtabs. If there is only a single child, then no tab is shown, only the content. This would enable anyone to add *anything anywhere* to the ControlPanel but also e.g to the Sidebar tabs.

If children are added via //tags// then, for backwards compat, I guess the //tabs macro// would need some added parameter to toggle this behaveiour. 

Individual tiddlers (i.e tabs) could enforce *vertical* display of its subtabs with a field `tabs:vertical`, and *block* subtabs, i.e block further recursion downwards, with `tabs:no` or some such.

**Comment by Jermolene** [comment]
Thanks @twMat it sounds like the core of your suggestion is to tweak things so that tab lists with a single entry are not rendered as a tab, with just the content being rendered.

The problem I have with that idea is that the dynamism makes it harder to give unambiguous documentation instructions. One can no longer say "Look under Settings -> TiddlyWiki in control panel", because that path wouldn't necessarily be the same for the user depending on what plugins they have loaded.

**Comment by twMat** [comment]
>One can no longer say "Look under Settings -> TiddlyWiki in control panel", because that path wouldn't necessarily be the same for the user depending on what plugins they have loaded.

@Jermolene - hm, but unless the user totally stays with the default TW setup, we can *never* state any path with full certainty anyway since anything could have been overwritten (as exemplified in the very OP).

But, OK, if even if the particular OP is solved with the special solution from @GameDungeon , what do you think about my more general idea? It would be a user friendly way to modify TW without overwriting things, very much aligned with how we use tags in other contexts. Should I post a separate request for it or do you want neither the bath water nor the baby? (C'mon, look at those adorable eyes!)

**Comment by Jermolene** [comment]
> @Jermolene - hm, but unless the user totally stays with the default TW setup, we can _never_ state any path with full certainty anyway since anything could have been overwritten (as exemplified in the very OP).

Only if one is dealing with plugins that have overwritten control panel tabs, rather than just inserting some new ones.

To be clear, I think that the current behaviour of the CodeMirror plugin is wrong. It only got merged because it was part of a much bigger PR that didn't include adequate documentation – see https://github.com/Jermolene/TiddlyWiki5/pull/3184/files#diff-b16f5279dd8caf7d7558fae0645e731a5b2aa278cf674ca054e91cb7bd1ea2a4


> But, OK, if even if the particular OP is solved with the special solution from @GameDungeon , what do you think about my more general idea? It would be a user friendly way to modify TW without overwriting things, very much aligned with how we use tags in other contexts. Should I post a separate request for it or do you want neither the bath water nor the baby? (C'mon, look at those adorable eyes!)

Most of your suggestion [above](https://github.com/Jermolene/TiddlyWiki5/issues/7522#issuecomment-1585559175) applies to the current situation: it is not necessary to overwrite anything in order to insert new sidebar tabs, or control panel tabs.

**Comment by pmario** [comment]
>It only got merged because it was part of a much bigger PR that didn't include adequate documentation – see https://github.com/Jermolene/TiddlyWiki5/pull/3184/files#diff-b16f5279dd8caf7d7558fae0645e731a5b2aa278cf674ca054e91cb7bd1ea2a4

I'm pretty sure, that the "offending" configuration tiddler would have not been part of the PR if we would have seen it. ... We tested the cm plugins and the settings tabs "just felt right". I'm sure it was an oversight. 

The PR mentioned was a huge thing. It made working with the different CM plugins a "no-brainer". That was not the case prior to the PR. The whole system was complicated, brittle and without reading the code **it was impossible to use it.** 

All elements are now configured in a way, that they work out of the box with sensible configurations, when the plugins are imported. The internal structure is now defined in a way that will allow other devs to easily create new cm-plugins without the need to ever change the main cm-plugin. IMO that's a great achievement.

Just my thoughts.
--- rant deleted ---

**Comment by twMat** [comment]
>Most of your suggestion https://github.com/Jermolene/TiddlyWiki5/issues/7522#issuecomment-1585559175 applies to the current situation: it is not necessary to overwrite anything in order to insert new sidebar tabs, or control panel tabs.

True. OK, thanks for replying.
