### ISSUE TITLE
[IDEA] Conditional Blocks (If Statements)

### ISSUE THREAD

**Issue by GameDungeon** [Jermolene/TiddlyWiki5#7570]
**Is your feature request related to a problem? Please describe.**
Having conditional blocks (blocks of wikitext that are shown or hidden based on a filter) (if elseif and else) is an important part of making view templates and other advanced wikitext functions.

**Describe the solution you'd like**
This is currently done with the list widget, but I find that very unintuitive. Additionally, it makes else and elseif functionality very verbose to write out, with each requiring us to list every previous check (unless there is some way to do it that I'm unaware of). Additionally, I struggle to believe that using a list like that is especially performant.  

I'm not quite sure of the ideal syntax of these blocks, and that is something for discussion. 

To throw out something, but I'm sure people can suggest something better:

```
@if "[filter]"
    content
@elseif "[filter]"
    content
@else
    content
@endif
```

**Comment by rmunn** [comment]
This was discussed last year in https://github.com/Jermolene/TiddlyWiki5/issues/6862 but the discussion petered out with no action coming of it. One difficulty is that the way the TW code is currently written, there's a fundamental assumption that any part of the widget tree can be refreshed without affecting its neighbors, only its children. But an `<$if>` widget would break that assumption, because it would have to go looking for a sibling `<$else>` widget if it got refreshed. See https://github.com/Jermolene/TiddlyWiki5/issues/6862#issuecomment-1200449657 for more details on that.

In the meantime, there's a [condition plugin](http://chronicles.wiki/TiddlyWikiFormula/#%24%3A%2Fplugins%2Febalster%2Fcondition) that might help. I haven't used it myself (just found out about it from browsing the discussion in #6862) so I don't know if it's been kept up-to-date, or if the changes that TW 5.3.0 is about to make to the widget system will break some undocumented assumption that the condition plugin is depending on. But it might be a possible workaround until something official is added to TW. I agree that some official way of doing `<$if> ... <$else>` is a good idea, as using `<$list>` just feels awkward.

**Comment by GameDungeon** [comment]
What if the whole thing was treated as a single widget (by using parser shenanigans or whatever) You could use a non-widget syntax for it like suggested above. By using the whole construction it can decide what displays inside it, whether it be an if block or the else or nothing. That bypasses the issue entirely.

**Comment by GameDungeon** [comment]
I think this is a case where the widget syntax needs to be abandoned. I can't think of a way that it would work well while keeping it. If you think outside that, many more options open up.

**Comment by rmunn** [comment]
In https://github.com/Jermolene/TiddlyWiki5/issues/6862#issuecomment-1200449657, Jermolene proposed the following syntax for an `$if` widget:

```plaintext
<$if filter="condition">
  <$then>Value if true</$then>
  <$else>Value if false</$else>
</$if>
```

The advantage of this is that the `$if` widget would know how to handle its child widgets `$then` and `$else`, but the general widget code wouldn't have to be rewritten to expect dependencies between sibling widgets. However, the drawback of this syntax is that it doesn't allow any practical way to write an `elseif`; if you have a chain of `elseif` conditoins, you'd end up nesting deeper and deeper. So some sort of pragma-like syntax would be needed. To that end, I've opened #7680 which would be required before any kind of `\if` pragma syntax would be useful.

**Comment by pmario** [comment]
>The advantage of this is that the $if widget would know how to handle its child widgets $then and $else,

That's not true. Parents do **not** know anything about their children and they should not.

**Comment by rmunn** [comment]
> > The advantage of this is that the $if widget would know how to handle its child widgets $then and $else,
> 
> That's not true. Parents do **not** know anything about their children and they should not.

I meant that the `$if` widget would need to break that rule and actually scan its children. See https://github.com/Jermolene/TiddlyWiki5/issues/7680#issuecomment-1687036612 — "[This syntax] relies on an implementation of the "if" widget that scans and processes its child widgets consecutively until it finds one that can be displayed."

**Comment by Jermolene** [comment]
Final implementation in #7710
