### ISSUE TITLE
Unexpected and undocumented behaviour for $tw.utils.base64Encode()

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#7626]
[As reported](https://github.com/Jermolene/TiddlyWiki5/commit/9b2af1359614f4ad5afd05be7cf9853909334592) by @Jermolene, the utility method `base64encode()` can yield unexpected results in some situations that lead to garbled and unusable data.

Investigation shows that the method `base64encode()` is not a replacement for the the `window.btoa()` method.

- `window.btoa()` cannot handle arbitrary Unicode text that might contain characters that occupy more than one byte , only binary strings (i.e., a string in which each character in the string is treated as a byte of binary data).
- to work around this and to be usable for arbitrary text, `$tw.utils.base64Encode()` first [encodes the input as UTF8](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/utils/base64-utf8/base64-utf8.module.js#L97). This fits the use case for things like the [GitHub Saver](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/savers/github.js#L73).
- However, it means that when you pass a binary string to `$tw.utils.base64Encode()`, the UTF8 encoding leads to a garbled output. Disabling the UTF8 encoding by commenting out the relevant line leads to the expected behaviour. 

We could potentially add a flag to the method for disabling the UTF8 encoding. We should document this for tiddlywiki.com/dev as well as in the code itself.

**Comment by Jermolene** [comment]
Thank you @saqimtiaz that's very helpful, and makes sense. I agree that a flag to suppress the UTF8 encoding step would be useful.

**Comment by rmunn** [comment]
The way `$tw.utils.base64Encode` works is to call the `base64` function from `base64-utf8.module.js`. That function was written in such a way that it asks you to pass in a utf8 module for it to use, and it will call `.encode` on the module you pass in. So if you wanted to suppress the UTF-8 encoding step, you could just pass it a "dummy" utf8 module like this:

```js
var dummyUtf8 = { encode: function(input) { return input; } }
return base64utf8.base64.encode.call(dummyUtf8,inputString);
```

**Comment by rmunn** [comment]
In [this commit message](https://github.com/Jermolene/TiddlyWiki5/commit/9b2af1359614f4ad5afd05be7cf9853909334592), @Jermolene expressed concern about the recently-added `encodebase64` and `decodebase64` filters. I'm also concerned, because their documentation doesn't match their current behavior. I have a suggestion to fix the problem, and I'll make a PR implementing my suggestion. But first let me explain the problem, then I'll lay out my suggestion.

The documentation for the `encodebase64` filter says "the input strings are interpreted as binary data". But the current behavior is to interpret the input strings as *text*, and run a UTF-8 encoding step first before running the base64 step. (Which is the *correct* behavior for text input, by the way, for the reasons that @saqimtiaz already laid out. Anyone wanting to know more should read about [base64 and the "Unicode problem" at MDN](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)).

The way I suggest to resolve this is to add a suffix to `encodebase64` (and `decodebase64` too, of course) to select either the "input is text" or "input is binary" behavior. The question is, what should the default be?

1. No suffix = treat as binary data (what the documentation currently says, but NOT how it currently behaves). Add `text` suffix to treat as text instead, doing a UTF-8 encode step before base64 encoding.
2. No suffix = treat as text data (what the current behavior is, but NOT what the documentation says it does). Add `binary` suffix to treat as binary instead, skipping the UTF-8 encode step.

My inclination is to go with option 1, where we say "Hey, the behavior doesn't match the documentation. That's a bug, and the behavior should be *changed* to match the documentation instead." Since the `encodebase64` filter was just added in release 5.2.6 in March 2023, five months ago, I doubt that many people have started using it yet, especially because it's buggy at the moment. So I don't think there are a lot of wikis out there relying on the current behavior, and I think it's safe to change the behavior.

However, ultimately it's @Jermolene's call whether we need to keep the current, albeit buggy, behavior, for the sake of backwards compatibility and not breaking people's existing wikis. ("Buggy" in the sense that it doesn't do what the documentation says it does: it's perfectly *correct* behavior for text input). If we need to keep the current behavior, then we must go with option 2.

**Comment by rmunn** [comment]
BTW, while we're adding suffixes to the `encodebase64` filter operator, I'd like to propose another suffix: `urlsafe`. The normal base64 behavior is to use `+` and `/` for the last two characters of its 64-character "alphabet", encoding values 62 and 63. There's a [widely-used base64 variant](https://datatracker.ietf.org/doc/html/rfc4648#section-5), usually called URL-safe base64, where the last two characters are `-` (hyphen) and `_` (underscore) instead of `+` and `/`, so that the resulting text can be used in a URL (e.g., in a query parameter) without any further quoting needed. So I propose adding a second optional suffix to `encodebase64`, which will output `-` instead of `+` and `/` instead of `_`, for compatibility with other implementations.

The `urlsafe` suffix will be orthogonal to the `binary` (or `text`) suffix: either one, or both, or none, can be specified.

Finally. the decoder should (IMHO) handle either the "standard" or "URL-safe" variants without needing a suffix, because it is always obvious and unambiguous which one is being used. (There are no base64 variants in common use that use both `+` and `-`, or both `/` and `_`, so the meaning of any of those four characters will be obvious to the decoder). But we should allow the `urlsafe` suffix to be passed to the decoder anyway, to keep its interface parallel to the `encodebase64` operator. (It will, effectvely, do nothing).

**Comment by saqimtiaz** [comment]
> 2\. No suffix = treat as text data (what the current behavior is, but NOT what the documentation says it does). Add `binary` suffix to treat as binary instead, skipping the UTF-8 encode step.

I would suggest that we go with this approach and update the documentation to ensure that the behaviour of any wikitext using the operator does not change, thus minimizing the impact for end users.

**Comment by rmunn** [comment]
@Jermolene We need a decision from you. Right now the `encodebase64` filter is broken. The documentation says it treats its input as binary, but in fact it treats its input as text. I think that's a bug, and the behavior should be changed to match what the documentation says, fixing the bug. @saqimtiaz thinks that people may be depending on the current buggy behavior, and we must not change the current behavior, and instead adjust the documentation to match the current behavior. (Which I think would break user's expectations, because I think people are expecting the behavior to match the documention, and would consider the current behavior a bug that needs to be fixed). I'm willing to implement it either way, but it's your project so it should be your decision. Please let us know.

Also, do you want this change to go into 5.3.1 so that the `encodebase64` filter gets fixed as soon as possible? Or will this one go into 5.3.2?
