### ISSUE TITLE
[BUG] Transcluded functions do not dynamically refresh

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7696]
While arguing with user: rmunn about the join feature in list widgets I did find and update problem with `functions`. But I'm not sure if that's intended or a bug. 

To reproduce

- Copy the following code into a tiddler at tiddlywiki.com
- Open the Preveiw Panel
- Create 10 items with <kbd>Create</kbd> button
- -> **Problem: The `<<list-join "[enlist{!!items}]">>` is not update**
- Close preview
- Open prevew
- now it is updated. 
- add new elements into the top Items: input box
- -> Problem: **The links will be updated, but the text is not**

@Jermolene   **Is this behaviour intended?**

```
\function list-join(filter, sep:", ") [subfilter<filter>join<sep>]

Items: <$edit field="items" /> <br/>

<<list-join "[enlist{!!items}]">>

---

<$let joined-list=<<list-join "[enlist{!!items}]">> >
	<$list filter="[<joined-list>enlist-input[]]" variable="item" >
		<$link to={{{ [<item>removesuffix[,]else<item>] }}}><<item>></$link>
	</$list>
</$let>

Create <$edit field="itemcount" />
items <$button action>Create<$action-setfield items={{{ [range{!!itemcount}join[ ]] }}}></$action-setfield></$button>
```

**Comment by Jermolene** [comment]
Hi @pmario good catch, I think this is indeed a bug.

**Comment by Jermolene** [comment]
I made a failing test over at #7698

**Comment by rmunn** [comment]
I left a comment at https://github.com/Jermolene/TiddlyWiki5/pull/7698#issuecomment-1702144333 with what I think is the first step towards a solution.

**Comment by AnthonyMuscio** [comment]
And as mario saw, I reported something very similar

If you have a tiddler you are editing, that contains a function definition, that makes use of a field value, and you are viewing the result in the Preview > Output most other forms of definition and wiki text are immediately reflected in the preview.

However if you change the value in a field used by a function, it will not update until you either save and reopen the tiddler, or close and reopen the preview.

Is this a bug or a feature?_

A related piece of evidence is us you have the additional edit buttons, save but not close, will not result in the functions result updating. I thought that did do a refresh, because we lose the cursor position.

**Comment by rmunn** [comment]
@AnthonyMuscio - Yes, that's a bug. Anytime a filter would refresh, a function containing that filter should also refresh.

I did a brief search through the GitHub issues list and couldn't find the report you mentioned. I'm guessing that's because you mentioned it as a comment on an issue opened by someone else, and the GitHub issues search for "author:AnthonyMuscio" only lists issues that you opened. Could you give us a link to your report? It might be useful to have the details linked in this issue.

**Comment by AnthonyMuscio** [comment]
@rmunn sorry its was in talk.tiddlywiki

**Comment by pmario** [comment]
Tony's post at [Talk](https://talk.tiddlywiki.org/t/observation-functions-using-fields-do-not-update-in-draft/7953)

**Comment by rmunn** [comment]
I have a fix in #7755 that should fix this bug. You can try it out at https://tiddlywiki5-git-fork-rmunn-proposed-function-r-8584f8-jermolene.vercel.app/ to verify that the bug is fixed; @pmario, I reproduced your test case from https://github.com/Jermolene/TiddlyWiki5/issues/7696#issue-1864854677 and it does seem to be fixed (update the items list and it fails on tiddlywiki.com but succeeds on that Vercel preview that includes my PR). Please let me know if you find other test cases that don't work.

**Comment by rmunn** [comment]
This should be fixed by https://github.com/Jermolene/TiddlyWiki5/pull/7698 which was merged three days ago. @pmario, can you confirm that this is fixed now?

**Comment by pmario** [comment]
@rmunn Thanks -- Yes it seems to be fixed now
