### ISSUE TITLE
[IDEA] Automatically Switch Between Dark / Light Palette Depending on Browser Setting

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#7754]
Started at: https://talk.tiddlywiki.org/t/config-tiddler-title-for-default-light-dark-palette-e-g-config-palette-default-dark/8071

**It is proposed** to automatically change to light / dark palettes depending on the browser setting. 

- 2 config tiddlers should define the default palettes: 
   - `$:/config/palette/default-dark -> $:/palettes/GruvboxDark`
   - `$:/config/palette/default-light -> $:/palettes/Vanilla`
- It should be possible to Enable / Disable the automatic mode

**Prove of Concept** 

![grafik](https://github.com/Jermolene/TiddlyWiki5/assets/374655/855a24ce-cbd1-46ee-8048-a20d8c34d365)

**Known Problems**

- With the current version of TW a browser reload is needed 
- The detection at: https://github.com/Jermolene/TiddlyWiki5/blob/773c1f83f24f5da81224a0b8f8abbb759041a9dd/core/modules/info/platform.js#L40 misses some functions
- **Separated PR**: It should be possible to dynamically activate an action-tiddler when the browser setting is changed

**Comment by pmario** [comment]
I'm preparing a PR atm

**Comment by linonetwo** [comment]
How to set $:/config/palette/default-light to $:/palettes/Notion using UI? 

Some people in QQ group say its annoying to customize wiki when there is no build-in config form for them. (When talk about sidebar position)

**Comment by Jermolene** [comment]
Thanks @pmario – how would backwards compatibility be handled? I think it's problematic to migrate from a single configuration tiddler to two interrelated ones.

One could imagine an arrangement such as "Use the palette titles from $:/config/palette/default-dark and $:/config/palette/default-light if they exist, otherwise use the title from $:/palette" but this would break any existing code using the $:/palette tiddler.

**Comment by pmario** [comment]
>Thanks @pmario – how would backwards compatibility be handled?

`$:/palette` will be untouched. 

The `$:/config/palette/default-dark - light` tiddlers are only used if the 
`$:/config/palette/enable-light-dark-detection` is set to `yes`. 

The `enable` tiddler does **not exist by default**. (Except we decide to enable that setting by default)

**Comment by pmario** [comment]
> How to set :/palettes/Notion using UI?

![grafik](https://github.com/Jermolene/TiddlyWiki5/assets/374655/592b6a4f-a772-4e1d-bd0f-61b275952c2a)

**Comment by Jermolene** [comment]
Wouldn't it be a lot simpler if the `$:/palette` tiddler was extended with "dark" and "light" fields. If they are present, then their values would be used in place of the "text" field.

On a separate note, I think the UI is too complex. Being able to select different palettes for light and dark mode is I think a minority requirement, and I'm uncomfortable if we make using palettes more complicated for the majority of people who don't care about light and dark mode.

**Comment by pmario** [comment]
>Being able to select different palettes for light and dark mode is I think a minority requirement, and I'm uncomfortable if we make using palettes more complicated for the majority of people who don't care about light and dark mode.

Dark palettes are a "must have" in the web at the moment.

IMO this PR is a big "quality of live" improvement.

If the setting is **on by default**, the user switches **the browser UI** to "Dark Mode" and the TW Palette also changes. -> 
**No user intervention needed. That's what users expect today.**

--------

>On a separate note, I think the UI is too complex. 

I did try it with a "select-wdiget" and "text only dropdown". It looks absolutely alien in that context.

There is nothing new. It's the same experience in the **Right Sidebar -> Tools -> palette** button. All the symbols and the visual UI is the same. 

![grafik](https://github.com/Jermolene/TiddlyWiki5/assets/374655/01994c60-2f9e-40ec-ba8d-414775857059)

**Comment by Jermolene** [comment]
> Dark palettes are a "must have" in the web at the moment.

I am not disputing the demand for automatic dark/light mode switching. The complexity I am talking about is having to manage two separate palette settings. Dark mode should be automatic, and users shouldn't have to configure it unless they've got unusual needs.

> There is nothing new. It's the same experience in the **Right Sidebar -> Tools -> palette** button. All the symbols and the visual UI is the same.

The part that is new is having to separately select two palettes, one for dark mode and one for light mode. Even if the user doesn't change the default, presenting it as two separate choices is unnecessary additional cognitive load on the user.

**Comment by pmario** [comment]
>Wouldn't it be a lot simpler if the $:/palette tiddler was extended with "dark" and "light" fields. If they are present, then their values would be used in place of the "text" field.

IMO that's a backwards compatibility problem. Every existing plugin and hand-crafted UI will overwrite those fields because they do not have them. This will cause a lot of bug reports that will be hard to find, because fields are invisible by default

**Comment by Jermolene** [comment]
> IMO that's a backwards compatibility problem. Every existing plugin and hand-crafted UI will overwrite those fields because they do not have them. This will cause a lot of bug reports that will be hard to find, because fields are invisible by default

I think the backwards compatibility situation is much simpler. Existing code that writes to `$:/palette` will still change the palette. With the `$:/config/palette/enable-light-dark-detection` tiddler set to `yes` then legacy code writing to `$:/palette` won't have any visual effect.

**Comment by pmario** [comment]
>The part that is new is having to separately select two palettes, one for dark mode and one for light mode. Even if the user doesn't change the default, presenting it as two separate choices is unnecessary additional cognitive load on the user.

The user only has to change the setting if they want settings that are different to the default. 

As a user --

1. I want to use the current "switcher" setting as it is now, which overwrites `$:/palette`
2. I want to be able to Enable / Disable the detection
3. I want to define a light **and** a dark palette that is activated according to the browser UI setting

**Comment by pmario** [comment]
>I think the backwards compatibility situation is much simpler. Existing code that writes to $:/palette will still change the palette. 

Yes and that's a problem. If I define the new dark and light fields in my $:/palette to use them for auto-switching. 
Then I do install an "old" plugin which overwrites $:/palette -> My fields are gone. -> IMO that's a hard to find problem.

**Comment by pmario** [comment]
>I am not disputing the demand for automatic dark/light mode switching. The complexity I am talking about is having to manage two separate palette settings. Dark mode should be automatic, and users shouldn't have to configure it unless they've got unusual needs.

As I wrote. There are defaults, that can be changed if needed. 

If we **enable** auto detection by default -> No user intervention is needed.

**Comment by Jermolene** [comment]
Hi @pmario the UI here directly exposes your proposed arrangement of configuration tiddlers. That means that in order to see what palette they are using, or to change that palette, the user must understand the relationship between the two mutually exclusive sections of the user interface, and understand the significance of the checkbox. Compared to the present arrangement, this is enormously more complicated.

**Comment by Jermolene** [comment]
> Yes and that's a problem. If I define the new dark and light fields in my $:/palette to use them for auto-switching. Then I do install an "old" plugin which overwrites $:/palette -> My fields are gone. -> IMO that's a hard to find problem.

@pmario if we are trying to preserve the behaviour of the existing plugin then it is correct that $:/palette gets overwritten.

**Comment by pmario** [comment]
>I am not disputing the demand for automatic dark/light mode switching.

Does this mean, that the automatic dark/light mode switching should be ON by default?

**Comment by linonetwo** [comment]
> Dark mode should be automatic, and users shouldn't have to configure it unless they've got unusual needs.

The switching is automatic, but I want to switch to Nord theme by default automatically, someone might not. But we can preconfigure this in a Release like TidGi or TiddlywikiXP, so end-user don't need to config it.

**Comment by linonetwo** [comment]
> Existing code that writes to $:/palette will still change the palette.

I understand what you mean now. 

I have a proposal, When changing palette from UI, we set palette-light/dark together based on `color-scheme` field on the palette.

(I also agree to use a field for palette-light/dark!)

<img width="779" alt="截屏2023-09-28 13 35 16" src="https://github.com/Jermolene/TiddlyWiki5/assets/3746270/001bc3a4-77a8-4892-b7dd-5034e675eab3">

And we can leave palette-light empty in the core, because in the empty.html, the palette is light. And if it is empty, this config is fallback to use $:/palette 's text field.

If user is already using another light palette (or palette don't have a `color-scheme` field, default to light), this also works fine.

If user is using a dark palette, when auto switch, use Vanilla for light, and use text field of `$:/palette` for dark.

---

In conclusion:

| conditions                                      | $:/palette and $:/palette!!light or !!dark (the one currently using in env) mismatch | $:/palette === $:/palette!!light or !!dark (the one currently using in env) |
|-------------------------------------------------|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| [{$:/palette}get[color-scheme]] === current env | use $:/palette!!text (fallback to old configs)                                       | use $:/palette                                                              |
| [{$:/palette}get[color-scheme]] !== current env | use $:/palette!!light or !!dark (based on env)                                       | use $:/palette!!light or !!dark (based on env)                              |

```markdown
| conditions                                      | $:/palette and $:/palette!!light or !!dark (the one currently using in env) mismatch | $:/palette === $:/palette!!light or !!dark (the one currently using in env) |
|-------------------------------------------------|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| [{$:/palette}get[color-scheme]] === current env | use $:/palette!!text (fallback to old configs)                                       | use $:/palette                                                              |
| [{$:/palette}get[color-scheme]] !== current env | use $:/palette!!light or !!dark (based on env)                                       | use $:/palette!!light or !!dark (based on env)                              |
```

**Comment by Jermolene** [comment]
Thanks @pmario. I have two concerns about this PR:

* That the data model of having multiple conflicting configuration tiddlers is confusing and error prone, and will lead to behaviour that is hard to understand for end users
* That the proposed new control panel user interface is unwieldy and too complex to be universal

Earlier today @CrossEye came up with an [excellent reference](https://robertlambert.net/2014/09/a-field-guide-to-overloaded-data/) that covered "multipurpose fields". I think that we are facing a similarly venerable anti-pattern here.

**Comment by pmario** [comment]
Sorry for wasting everyone's time. I'll close this UI centric issue and the related PR.

I'll create a new proposal related to the core function that detects the browser ["preferes-color-scheme" setting](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by linonetwo** [comment]
Not wasting time, I didn't realize these issues until this discussion.

And I didn't realize vscode already have this feature too. It's this feature is off by default, and I was manually switching theme every time.
