### ISSUE TITLE
[BUG] Does this  `\procedure` definition conform to the expected behavior?

### ISSUE THREAD

**Issue by LinHQ1999** [Jermolene/TiddlyWiki5#7796]
### Describe the bug

![image](https://github.com/Jermolene/TiddlyWiki5/assets/50328516/39fbec85-2cb9-4ba9-ae7d-a25a335bc59e)

But the document says it should be written as follows:

![image](https://github.com/Jermolene/TiddlyWiki5/assets/50328516/77b1f575-0094-4433-95bf-ecc1b4fae51e)

### TiddlyWiki Configuration

It can be reproduced on the official documentation.

**Comment by Jermolene** [comment]
Hi @LinHQ1999 your example is interpreted as follows (note the quotes around the default value):

```
\procedure foo(bar:"{{$:/SiteTitle}}") <<bar>>
```

The string "{{$:/SiteTitle}}" is used as the literal default value. That works in this case because the `<<bar>>` construction will wikify the entire string. But it wouldn't work if you were, say, using the value of the parameter in a filter expression.

In the example in the docs, the the default value will be the actual text of the tiddler "$:/SiteTitle".

**Comment by LinHQ1999** [comment]
Got it, thanks!

**Comment by Jermolene** [comment]
Great thanks @LinHQ1999
