### ISSUE TITLE
[BUG] Tiddler .tid files don't end in a newline (POSIX conformance)

### ISSUE THREAD

**Issue by berney** [Jermolene/TiddlyWiki5#7807]
### Describe the bug

If I create a tiddler in node TiddlyWiki the `.tid` file doesn't end in a new line.

## `hexdump -C tiddler.tid | tail -n2`

```
000000b0  2f 24 6c 69 73 74 3e                              |/$list>|
000000b7
```

According to https://www.baeldung.com/linux/files-end-with-newlines#newlines-at-the-end-of-the-file
and https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html

### Expected behavior

The last line of a tiddler should end in a newline character to conform with the posix definition of a text file, which is a file consisting of lines ending in a newline character (0x0a, e.g `\n`).

### To Reproduce

1. Run TiddlyWiki on node
2. Create a new tiddler, with a line of text
3. View the `.tid` file on disk with `hexdump -C` and observe the last line does not end in `\n` (0x0a).

### TiddlyWiki Configuration

- Version 5.3.1
- Saving mechanism - Node.js

### Desktop (please complete the following information):

- OS: Alpine Linux 
- Browser: Chrome
- Version: 3.18.4

### Additional context

Other tools opening the file can make changes as a side effect, such as Vi/Vim. If you open the file and make not changes but save it, vim will automatically add a newline character at the end of the file to make it POSIX conformant.

Running pre-commit with the https://github.com/pre-commit/pre-commit-hooks end-of-file-fixer hook will want to change every tiddler `.tid` file to correct the end of file.

**Comment by pmario** [comment]
The TW repo uses the git default setting for `core.autocrlf` which is `false`. 

So we use LF only for line-feeds in Windows and for *x-like systems. We do **not** normalize LF on checkout on a Windows system.

For tiddlers the newline character has a meaning. So if tiddlers are used in templates that transclude other tiddlers, it must be possible to have tiddler files, that do **not** contain trailing newlines. 

Automatically adding such new-lines may break the TW UI.

-------

From my point of view an editor or any other system, should not automatically add or remove characters to arbitrary text files.

There is `.vimrc` which allows you to configure that behaviour. 
The same is true for git. 

For shell-files it's needed to have trailing newlines, since shell-files are mainly used to execute commands for command line interfaces (CLI)

In POSIX systems commands are only activated if they are terminated with a LF - **But** `.tid` files are **not** shell files. So from my point of view there is no need to make them POSIX conform.

**Comment by oeyoews** [comment]
For some shortcut config tiddler, adding newline will cause errors, tiddlywiki will not recognize it, and the corresponding shortcut keys will become invalid.

**Comment by rmunn** [comment]
Another case where adding final newlines would cause problems is in configuration tiddlers. There are many places throughout the TiddlyWiki code where true/false configuration values are saved in tiddlers with specific names (such as `$:/config/TimestampDisable`, among others) with the values "yes" or "no". If running TiddlyWiki under Node.js, the default setup is to save such tiddlers as `.tid` files. The TiddlyWiki code compares the value of those configuration tiddlers to the string "yes" (after converting them to lowercase, but NOT stripping any whitespace), so if the tiddler contains `yes\n` rather than `yes` then that check will fail, and the TW code will proceed as if it has the value `no`.

So enforcing final newlines in `.tid` files would actually break a lot of things, requiring a lot of work to change all the places in the TW code that assume there are no extra newlines inserted. And although `.tid` files *can* be treated as text files, there is actually very little benefit to doing so. For example, even if `.tid` files all had final newlines, they still could not be concatenated, because the syntax of a `.tid` file is a series of headers, a blank line, and then the tiddler body. If you concatenate two `.tid` files, the second one's headers would end up being considered part of the body of the concatenated file.

So for all these reasons, there is almost no benefit to enforcing final newlines in `.tid` files, and a lot of drawbacks to doing so. It's nice in theory to be POSIX-compliant, but in practice it doesn't matter and isn't worth the cost.

**Comment by berney** [comment]
Thanks for all the comments pointing out all the parts that rely on tiddlers not ending in a new line, and all the problems enforcing new lines would cause.

I'll close this issue as it seems clear it's either a WONTFIX or not a bug.
