### ISSUE TITLE
[BUG]  MathJax plugin broken on HTTPS

### ISSUE THREAD

**Issue by oricou** [Jermolene/TiddlyWiki5#7954]
### Describe the bug

Math display fine on local host (with desktop app or browser) but not anymore when I put the tiddlywiki on my server. 

I tried with or without MathJax plugin, the behaviour is the same.

### To Reproduce

See on https://ricou.eu.org/iren/notes_rn.html#Fonction%20d'activation

### TiddlyWiki Configuration

- Version 5.3.3
- Saving mechanism TiddlyDesktop

- OS: Linux, Android
- Browser Chromium, Firefox, Brave

### Additional context

Could it be related to having httpS on my server but not locally?

**Comment by Jermolene** [comment]
Hi @oricou the problem is that the MathJax plugin is disabled:

<img width="1034" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/39af085d-5202-40f4-91dc-314ba03b7780">

To fix it, click on the plugin to open it and reveal the "enable" button:

<img width="1028" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/32eda3ba-df5f-4b38-bbda-43b6c309d9fb">

Click the enable button, and then save changes and reload.

<img width="1036" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/154a75cc-5c57-41c1-b021-28a10a87071e">

(The images are broken in my illustration because I downloaded the HTML file alone to work on it).

**Comment by oricou** [comment]
As I said, if you download the HTML then it works but on my server it does not work.

Now I put on the server a version with MathJax activated, as you should see, it does not work.

**Comment by Jermolene** [comment]
Thank you @oricou I am seeing an error in the developer console which is saying that the problem is that the MathJax JavaScript is being referenced via an insecure `http` URI. That isn't allowed by browser because the page itself is served over `https` and is considered secure. Secure pages aren't allowed to load insecure content.

<img width="995" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/c1251b2d-6a42-4685-b352-50734a3be4b6">

As far as I can tell, the use of HTTP is embedded in the MathJax plugin. That's a community plugin, and is not part of the core, and so I can't help with fixing it. The KaTeX plugin is part of the core, if you are able to use that. It works offline, and doesn't require external JavaScript. If that is not possible I would suggest posting about the issue on talk.tiddlywiki.org to see if anyone in the community wants to step up and become a maintainer for the MathJax plugin.

**Comment by oricou** [comment]
I just add an s to have `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML` in my file and now it seems to work fine.

Can you make that change?

**Comment by oricou** [comment]
I could use Katex but I use a lot $ inside a line and $$ for a paragraph. I remember that was the reason I sticked to MathJax. Maybe there was another reason.

**Comment by Jermolene** [comment]
Hi @oricou the MathJax plugin isn't part of the official project, it is published independently. Therefore the core team cannot modify it; the original author needs to published an updated version.

In cases where a plugin has been abandoned we would need to find somebody else to take it on. I am not interested in taking the MathJax plugin for the core because it has a number of technical limitations compared to the official KaTeX plugin. (The MathJax plugin doesn't work under Node.js or for static HTML exports, and requires an internet connection).

**Comment by oricou** [comment]
Ok, it make sens. Thanks.

**Comment by oricou** [comment]
sure
