### ISSUE TITLE
[IDEA] procedure wikify mode

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#8072]
**Is your feature request related to a problem? Please describe.**

Content of procedure will left as-is when used in (Substituted) Attribute Values, make it necessary to use WikifyWidget, and cause confusion because I expect it to wikify by default, and it is difficlut to find a short workaround (not requiring too much boilerplate).

1. example 1 Attribute Values: https://github.com/Jermolene/TiddlyWiki5/pull/7821#issuecomment-1929572694
2. example 2:

Substituted Attribute Values

```
<!-- Omit other function and procedures here -->

\procedure series()
<$list filter="[range[0],[-3]]" variable="weekIndex">
{
  name: 'Email',
  type: 'line',
  stack: 'Total',
  areaStyle: {},
  emphasis: {
    focus: 'series'
  },
  data: [
    <$list filter="[range[7]]" variable="dayIndex">
      <<hoursToday>>,
    </$list>
  ]
},
</$list>
\end

<$echarts $text=`
  option = {
    series: [
      $(series)$
    ],
<!-- Omit -->
```

The result will be

```
option = { series: [ <$list filter="[range[0],[-3]]" variable="weekIndex"> // ...
```

We can see the `<$list` widget is left, instead taking effect.

I also tried

- `${[<series>]}$`
- `\function renderseries() [<series>]` and then `$(renderseries)$`
- `${[function[series]]}$`

**Describe the solution you'd like**

Add something to enable auto-wikify of procedure, like

```
\procedure series()
\autowikify yes
<$list filter="[range[0],[-3]]" variable="weekIndex">
{
  name: 'Email',
```

**Describe alternatives you've considered**

Add a `wikify` filter operator, so we can `${[<series>wikify[]]}$` and

```
<$button tooltip=`${ [<ariaLabel>wikify[]] }$` aria-label=`${ [<ariaLabel>wikify[]] }$` class="tc-btn-invisible">
```

**Additional context**

> why "when a procedure is used as an attribute value" is an exception to "not wikified"? @Jermolene in https://github.com/Jermolene/TiddlyWiki5/pull/7821#issuecomment-1929572694

**Comment by AnthonyMuscio** [comment]
If the content of the procedure is in a tiddler and instead transcluded, the transclusion process may result in the wikification you are after, depending on the circumstance.

I mention that here because;
* As this may point to a work around
* It may point to an approach to solve this, by implementing a form of transclusion.

> Content of procedure will left as-is when used in (Substituted) Attribute Values, make it necessary to use WikifyWidget, and cause confusion because I expect it to wikify by default.

* I do not expect it to wikify from experience with tiddlywiki, because neither do macro `\define` definitions.
* This has being a long standing area of confusion for new and experienced users because the problem is somewhat invisible.
  *  To understand why this is happening needs a deeper understanding of tiddlywikis rendering process, which occurs at the very end to generate the HTML we then see on screen. Only a small number of users seem to know about this.

Using wikify is discouraged, but I believe this is due to performance issues in some cases, but I believe not all. However wikification usually demands just in time wikification, eg
```
<$wikify name=result text="subject of wikifications>
Use <<result here>>
</$wikify>
```
* That is you use it where needed and close it right away
* At least it would be nice is we had a less verbose symbols to indicate wikification required.

There is now a partial resolution of the above issues by way of functions, they are "evaluated on the fly", rather than only at the end where wikification occurs in the final render. The new "back tick, and triple backtick attributes" feature also does this now.
* When a user is well versed in filters many of these apparent imitations can be bypassed.
* I would still welcome improvements in this area

I am researching this presently and will reply in this thread https://talk.tiddlywiki.org/t/how-to-apply-parsing-rules-to-the-output-of-the-wikify-widget/9325?u=tw_tones

**Comment by Jermolene** [comment]
Hi @linonetwo it can undoubtedly be confusing that using a double angle brackets as an attribute value (eg `<$text text=<<something>>/>`) appears to behave differently than `<<something>>` on its own.

I have considered an alternate syntax that would automatically wikify the transcluded variable. For example `<$text text=<<<something>>>/>`.

What holds me back is that wikifying an attribute in that way is inefficient. Wikifying is fundamentally computationally intensive: we have to parse the test, make the widget tree, extract the text, and then delete everything. With the current code, it is hard to see a way to cache the intermediate results.

In the meantime, the `<$wikify>` widget provides a workable workaround.

**Comment by linonetwo** [comment]
If I have to use `<$wikify>` widget, then I still have to pay for performance, so adding a short cut for it cost same CPU.



> and then delete everything

Do you mean `<<xxx>>` has cache? I didn't know that. So can we add cache to `<<<xxx>>>`?

**Comment by pmario** [comment]
>If I have to use <$wikify> widget, then I still have to pay for performance, so adding a short cut for it cost same CPU.

Yes using the wikify-widget **can be** a performance hog, **if used in a loop**, that gets **called very often**. So in combination with the list-widget it can be a performance problem. 

If you use it with user interaction like clicking a button or opening a tiddler should never be a problem. Even if you would render the whole wiki. Users allow a delay up to 1 second, if they click UI buttons.

As in your OP preparing a JSON structure and passing it to the echarts-widget **should be no problem**. I'm sure the echart-widget needs to run a 1000 times more code than preparing the data using wikify.

**Comment by pmario** [comment]
>What holds me back is that wikifying an attribute in that way is inefficient. Wikifying is fundamentally computationally intensive: we have to parse the test, make the widget tree, extract the text, and then delete everything. With the current code, it is hard to see a way to cache the intermediate results.

I think that's the right decision atm. If we would allow "rendered" parameters `<$text text=<<<something>>>/>` IMO users would use the carelessly and then complain about performance.

I think using the wikify widget as it is at the moment is the right balance between "user awareness" and "function"

**Comment by Jermolene** [comment]
> If I have to use `<$wikify>` widget, then I still have to pay for performance, so adding a short cut for it cost same CPU.

I still don't see the case for a shortcut syntax. Another factor is that almost every time we see somebody asking a question on the discussion forum about the use of the `<$wikify>` widget we find that it is not really necessary. That's not to say that there are not valid usages for the wikify widget, of course.

> Do you mean `<<xxx>>` has cache? I didn't know that. So can we add cache to `<<<xxx>>>`?

Sort of. When a variable is transcluded we can cache the parse tree in the variable itself in the widget tree.

**Comment by linonetwo** [comment]
Okay, let's left wikify as advanced usage, and the boilerplate is a discourage of the usage. (Syntactic Salt?)

**Comment by Jermolene** [comment]
> Syntactic Salt

That is an excellent term, thank you.

**Comment by linonetwo** [comment]
Every button tooltip needs wikify

```tid
\procedure repeat-complete-button()
  <$wikify name=tooltip text="<<lingo Button/CompleteRepeat/Description>>">
    <$button tooltip=<<tooltip>>>
      <$action-listops $field="tmo_repeatInterval" $filter="[all[current]get[tmo_repeatInterval]else[1]]"/>
      <$action-setfield tmo_taskState="Repetitive"/>
      <$action-listops $field="tmo_numberOfCompletions" $filter="[{!!tmo_numberOfCompletions}add{!!tmo_repeatInterval}]"/>
      <$action-setfield tmo_taskState="Repetitive"/>
      <<lingo Button/CompleteRepeat/Caption>>
      <span class="badge badge-light">
        {{!!tmo_numberOfCompletions}}
      </span>
    </$button>
  </$wikify>
\end

\procedure start-button()
  <$wikify name=tooltip text="<<lingo Button/Start/Description>>">
    <$button tooltip=<<tooltip>>>
      <$action-setfield tmo_taskState="Running"/>
      <<lingo Button/Start/Caption>>
    </$button>
  </$wikify>
\end

\procedure complete-button()
  <$wikify name=tooltip text="<<lingo Button/Complete/Description>>">
    <$button tooltip=<<tooltip>>>
      <$action-setfield tmo_taskState="Completed"/>
      <<lingo Button/Complete/Caption>>
    </$button>
  </$wikify>
\end
```

Paste here for future copy&paste.

**Comment by Jermolene** [comment]
> Every button tooltip needs wikify

Funnily enough, the reason that the wikify widget was created was because I was implementing the tooltips for the editor toolbar and I couldn't figure out any other way to make translatable tooltips.

**Comment by AnthonyMuscio** [comment]
Can we not now use a function and the lookup operator to avoid using wikify in translation tooltips?

**Comment by Jermolene** [comment]
> Can we not now use a function and the lookup operator to avoid using wikify in translation tooltips?

Hi @AnthonyMuscio the reason that wikification is needed for the tooltips is to allow translations of the tooltip to be transcluded, and to be able to add the keyboard shortcut to the end of the shortcut (which is dynamic, of course, because the keyboard shortcuts can be customised). Functions don't help with any of that.
