### ISSUE TITLE
[BUG] Unavoidable RSOD Caused by RegExp

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#8216]
This issue is a single stepped, deep dive and it's related to: https://github.com/Jermolene/TiddlyWiki5/issues/8213

As shown in #8213 there is a RSOD created by $:/core/modules/utils/linkedlist.js because it throws an error if it encounters "array elements" other than strings. -- IMO this behaviour is valid.

The problem now is that this RSOD is unavoidable with the current js implementation, even if every code element, wikitext and JS-code in itself is valid. 

#### Wikitext snippet from #8213 seems to be valid

```
\define re() (color)|(colour)ed
\define str() Something coloured
{{{ [<str>splitregexp<re>] }}}
```

- See TW docs: https://tiddlywiki.com/#splitregexp%20Operator - There are no documented limitations about the regexp.

#### JS code seems to be valid

- https://github.com/Jermolene/TiddlyWiki5/blob/dbe912ba5d6b51e542abd8a94db0d49cc7eee04e/core/modules/filters/strings.js#L220

- See MDN `string.split(regexp)`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#description -> Scroll down to 

>If separator is a regular expression with capturing groups, then each time separator matches, the captured groups (including any undefined results) are spliced into the output array. This behavior is specified by the regexp's [Symbol.split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/split) method.

In the quote it says: *the captured groups (**including** any **undefined** results) are spliced into the output array.*

#### How the problem happens

In the code the regexp `/(code)|(colour)ed/` contains 2 capturing groups, which will return at least 1 `undefined` with `Something coloured` given as "source text".

- In `strings.js` the `result` variable is an array and contains the `undefined` value.

```
result: (4) […]
​​0: "Something "
​​1: undefined
​​2: "colour"
​​3: ""
​​length: 4
```

- Then the `result` variable will be passed to: `LinkedList.js` to the `LinkedList.prototype.pushTop(value)`, where it will be `_assert`ed
- https://github.com/Jermolene/TiddlyWiki5/blob/dbe912ba5d6b51e542abd8a94db0d49cc7eee04e/core/modules/utils/linked-list.js#L58-L63 
- **So line 62 throws an error which is unavoidable** at the moment

### Conclusion

- As it stands atm, problems like this can happen any time. (remark: I did have some of them myself already, but I did not dig deeper)
- The RSOD can not be avoided with the implementation as it is atm

### Solution ??

I'm not sure. @Jermolene @flibbles ... what do you think?

**Comment by flibbles** [comment]
I'm not seeing in the documentation where it talks about capture groups, but I do see that the behavior you describe exists. Is this a new feature?

If this behavior is to be kept, it would seem to me that replacing the undefined values with an empty string is the solution. It's unlikely that empty strings would get mixed up with actual capture groups, since who ever captures empty strings? And it keeps the length of the output to a predicable size, unlike the strategy of removing the undefined values.

**Comment by pmario** [comment]
>If this behavior is to be kept, it would seem to me that replacing the undefined values with an empty string is the solution. 

I was experimenting with a possibility to ensure, that every element that is written to the list will be converted into a string. So there would be no need to throw exceptions at all. 

What was the reason, why you decided to throw exceptions instead of converting everything into strings? I did not see any discussion about that

**Comment by flibbles** [comment]
Again, it's been a while, but if I recall, it was the understanding that filters are only supposed to be passing around strings, and if undefined or null are floating around in there, something has already failed. Proceeding onward would only mask where the error was actually occurring.

Especially since `null` and `undefined` will toString into `"null"` and `"undefined"`. Not terribly useful for anyone.

**Comment by flibbles** [comment]
Oh. I didn't realize that filter operator was such a direct translation of a javascript function. I guess we've got to diverge from that method since filters have never allowed non-strings in the stream. Way I see it, there are two possible outcomes.

1. Remove `undefined` when it occurs
2. Change `undefined` to an empty string when it occurs

I go with solution 2. If an end user needs those empty strings gone, then they can always use `!is[empty]`, but if we already removed the undefines, then there's nothing they can do with it.

Any other solution I think would require parsing the regular expressions ourselves, I'd think.

**Comment by pmario** [comment]
uups: It's not possible to change `undefined` to empty-string.

See this: 

```
\define re() (color)|(colour)ed
\define str() Something coloured
{{{ [<str>splitregexp<re>join[, ]] }}
```

So for consistency reasons we should convert every incoming value into strings.

**Comment by pmario** [comment]
So it may be this:

```
// Sticks the given node onto the end of the list.
function _linkToEnd(list,value) {
	value = value + "";
```

**Comment by flibbles** [comment]
> That's right, but IMO they should not throw. I also think that number or booleans 5 or 'true' should not throw an error.

I would say that it absolutely should. Filters are meant to process strings, not numbers or other types. Putting stricter requirements on module developers leads to healthier code in the long run. Sort of like using `use strict`. If developers are free to drop numbers or booleans or null or whatever into filter streams, it could result in bad interactions with other filters or plugin developers who all assumed they're going to get strings.

It doesn't seem like a big ask to require all people developing filter operators just to put a `toString()` at the end if they were manipulating non-string list items.

>uups: It's not possible to change undefined to empty-string.

To me, this is an argument *against* converting to string in the Linked List. The reason undefined is still showing up in that case is because the output of splitregexp is getting fed directly into `join[]` instead of ever going near a linked list. `join[]` is expecting *only* strings.

Therefore, converting to string in Linked List isn't sufficient. Either every filter operator has to confirm that they're receiving strings before manipulating them, or the filter engine needs to confirm that at every intermediate step.

It seems easier to me to address the only known filter currently passing non-strings, splitregexp, and have it get in line with the other operators.

**Comment by pmario** [comment]
>It seems easier to me to address the only operator currently known to pass non-strings, splitregexp, and have it get in line with the other operators.

OK - I'll create a PR for this one. The fix should be straight forward.

**Comment by pmario** [comment]
@bluepenguindeveloper - You can close issues that you did create yourself, if it has been resolved.
