### ISSUE TITLE
The default value of $edit-text not effect to $set

### ISSUE THREAD

**Issue by lilixiong2018** [Jermolene/TiddlyWiki5#8259]
### Describe the bug

Create a new tiddler named "Test search with prefix" as:

```
<$edit-text field="search" default="Release" tiddler="$:/temp/search" placeholder="enter prefix string to search" size="30"/>

<$set field=search name=term tiddler="$:/temp/search" >
<$list filter="[!is[system]prefix<term>!sort[created]limit[200]]" template="$:/core/ui/ListItemTemplate" emptyMessage="Not found."/>
</$set>
```

then reload TW and open the new tiddler which  named "test search with prefix", it show word "Release" on editrbox, but the result of "search" tidders is ALL, not which that has prefix of "Release".

### Expected behavior

When open the "Test search with prefix" tiddler, return tidders which that has prefix of "Release".

### To Reproduce

1. Create a new tiddler named "Test search with prefix" as:

```
<$edit-text field="search" default="Release" tiddler="$:/temp/search" placeholder="enter prefix string to search" size="30"/>

<$set field=search name=term tiddler="$:/temp/search" >
<$list filter="[!is[system]prefix<term>!sort[created]limit[200]]" template="$:/core/ui/ListItemTemplate" emptyMessage="Not found."/>
</$set>
```

2. Reload TW.
3. open "Test search with prefix" tidder.
4. It should show tidders which has prefix "Release", not all the tidders.

### Screenshots

![image](https://github.com/Jermolene/TiddlyWiki5/assets/40269098/5355d92f-66f4-4820-9218-de1bc723dc69)

If we use backspace to delete some characters, or add some characters, it works as normal.

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
5.3.4-prerelease

- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
Open local tw file in chrome

### Desktop (please complete the following information):

Windows 10 64bits

Chrome 125.0.6422.142

5.3.4-prerelease

**Comment by Jermolene** [comment]
Hi @lilixiong2018 thanks for the report.

What is going on is that if the `<$edit-text>` widget is used with a target tiddler that does not exist then although the `default` attribute value is displayed in the control it is not actually saved back to the tiddler until the user makes a modification. So the result is that the target tiddler is not created unless the value is changed from the default value.

The underlying architectural reason that it works like this is because our architecture does not not permit widgets to modify the wiki store when are displayed or refreshed. Modifications can only be made within event handlers.

**Comment by lilixiong2018** [comment]
Thank you. I close this issue because of design constraint.
