### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#8326]
### Describe the bug

In v5.3.4 the core "colour" macro was changed from a macro to a procedure which broke constructions like `<div style.background=<<colour foreground>>>`. When used as an attribute value like this, macros using parameter/variable substitution work correctly while procedures relying on wikification will not function correctly. Thus they are not interchangeable

### To Reproduce

Create a new tiddler with the following content:

```
COLOUR MACRO:<br>
<<colour foreground>>

WIKIFY COLOUR MACRO WITH QUOTES:<br>
<$wikify name="fg" text="<<colour foreground>>">
<<fg>>
</$wikify>

WIKIFY COLOUR MACRO WITHOUT QUOTES:<br>
<$wikify name="fg" text=<<colour foreground>>>
<<fg>>
</$wikify>
```

In 5.3.3 all three produce the same results: `#333333`, but in v5.3.4, the third syntax dumps out the entire palette tiddler contents.

### TiddlyWiki Configuration

v5.3.4

**Comment by Jermolene** [comment]
@pmario @saqimtiaz I think this is a serious regression, and so am inclined towards a rapid v5.3.5 bug fix release.

**Comment by saqimtiaz** [comment]
I would have to agree that this needs a bug fix release. Suggest giving it another day or two in case any other bugs are reported.

**Comment by pmario** [comment]
But this means we will never be able to change any of the `\define` macros to `\procedures`, because they could have been used the way as you described it in the OP.

**Comment by ericshulman** [comment]
Even in v5.3.3, usage like
```
<div style.background=<<colour foreground>>>test this</div>
```
didn't work, because the `$colour` macro uses `$transclude` widgets, which still relies upon wikification to produce the desired result.  That is why the examples provided by me (and posted by jeremy) use `$wikify` to demonstrate the difference between v5.3.3 and v5.3.4.

However, there may be a more interesting modern solution that DOES permit "palette references" to work as desired when used as an attribute parameter...

In https://talk.tiddlywiki.org/t/how-to-use-the-colour-macro-as-an-attribute-value/10051, @bluepenguindeveloper suggests an alternative `<<getcolor>>` function that completely bypasses the reliance on wikification, and even supports recursion to handle nested use of `<<colour>>` within a palette definition:

```
\define colorRegexp() <<colou?r .*>>

\define removeRegex() <<colou?r |"|'|>>

\function getColor(c) [{$:/palette}getindex<c>!is[blank]] ~[[$:/palettes/Vanilla]getindex<c>!is[blank]] ~[[$:/config/DefaultColourMappings/]addsuffix<c>get[text]] :map[function[recolor],<currentTiddler>]

\function recolor(c) [<c>regexp<colorRegexp>] :then[<c>search-replace:g:regexp<removeRegex>,[]split[ ]!is[blank]first[]] :map[function[getColor],<currentTiddler>] :else[<c>]
```
Note that the filter syntax used in the above `getColor` function can be somewhat simplified by changing `getindex<c>!is[blank]` to just `getindex<c>`, as the `getindex<c>` operator already automatically excludes blank values.

Thus, a possible resolution for bug #8326 would be to:
A) revert the implementation of `<<colour>>` to it's v5.3.3 definition (i.e., using macro `\define` syntax instead of a `\procedure`).  This would resolve the backward-compatibility issue for existing TiddlyWiki instances.
and ALSO
B) add a new `<<getColor>>`/`<<getColour>>` `\function` as shown above to provide a modern "palette reference" implementation that would be a working replacement for `<<colour>>` as well as supporting the desirable `attr=<<getColour ...>>` usage that the old `attr=<<colour ...>>` does not.

**Comment by ericshulman** [comment]
In does appear that we CAN **replace** the existing `<<colour>>`/`<<color>>` macro and still retain backward compatibiity, by using the following code:
```
\define colorRegexp()	<<colou?r .*>>
\function color(c)	[{$:/palette}getindex<c>] ~[[$:/palettes/Vanilla]getindex<c>] ~[[$:/config/DefaultColourMappings/]addsuffix<c>get[text]] :map[function[recolor],<currentTiddler>]
\function colour(c)	[function[color],<c>]
\function recolor(c)	[<c>regexp<colorRegexp>] :then[<c>split[ ]last[]trim[']trim["]trim[>>]] :map[function[color],<currentTiddler>] :else[<c>]
```
This would resolve the `$wikify` bug I originally noted, while also permitting use of `<<colour ...>>` as a widget parameter value.

**Comment by pmario** [comment]
@ericshulman -- not quite -- I did test that one and there is a problem, that `#` is wikified as a OL-LI which is removed in text output.

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/611a5b02-fe0e-4742-913d-95c5d3598ca3)

**Comment by ericshulman** [comment]
I think we are **close** to a solution, though not quite there.

Here's the test I am now using:
```
\define colorRegexp()	<<(tf.)?colou?r .*>>
\function tf.color(c)	[{$:/palette}getindex<c>] ~[[$:/palettes/Vanilla]getindex<c>] ~[[$:/config/DefaultColourMappings/]addsuffix<c>get[text]] :map[function[tf.recolor],<currentTiddler>]
\function tf.colour(c)	[function[tf.color],<c>]
\function tf.recolor(c)	[<c>regexp<colorRegexp>] :then[<c>split[ ]last[]trim[']trim["]trim[>>]] :map[function[tf.color],<currentTiddler>] :else[<c>]

COLOUR MACRO:<br>
<<colour foreground>>

WIKIFY COLOUR MACRO WITH QUOTES:<br>
<$wikify name="fg" text="<<colour foreground>>">
<<fg>>
</$wikify>

WIKIFY COLOUR MACRO WITHOUT QUOTES:<br>
<$wikify name="fg" text=<<colour foreground>>>
<<fg>>
</$wikify>

TF.COLOUR FUNCTION:<br>
<<tf.colour foreground>>

WIKIFY TF.COLOUR FUNCTION WITH QUOTES:<br>
<$wikify name="fg" text="<<tf.colour foreground>>">
<<fg>>
</$wikify>

WIKIFY TF.COLOUR FUNCTION WITHOUT QUOTES:<br>
<$wikify name="fg" text=<<tf.colour foreground>>>
<<fg>>
</$wikify>
```

When run in v5.3.4, all the results are correctly "#333333" except for:
* "Wikify color macro without quotes" shows the entire palette contents (as originally reported)
* "Wikify tf.color function without quotes" shows the correct "foreground" palette entry, but with the leading "#" omitted (as you have shown)

When run in v5.3.3, all the results (including "wikify color macro without quotes") are correctly "#333333" except for:
* "Wikify tf.color function without quotes" shows the correct "foreground" palette entry, but with the leading "#" omitted (as you have shown)

So, if we can resolve this last test case (to retain the "#"), then we can successfully **replace** the old `<<colour>>` macro definition with functions.  Otherwise, I think that in v5.3.5 we should just revert to the old `<<colour>>` macro (to restore backward compatibility), and then wait on replacing `<<colour>>` with a function until we can solve this last problem.

**Comment by Jermolene** [comment]
I left a comment on [the Talk thread](https://talk.tiddlywiki.org/t/how-to-use-the-colour-macro-as-an-attribute-value/10051/9?u=jeremyruston):

TiddlyWiki actually allows arbitrary wikitext in a palette colour definition. So something like this should work as things stand:

```
page-background: <%if {{$:/Something}} %>red<%else%>green<%endif%>
```

In practice, the core palettes only use embedded <<colour>> macros, and so I would be surprised if there were any palettes out there that do anything more elaborate.

So, if we were to adopt the regex approach we would need to document the resulting restrictions.

My instinct, though, is that there are so many situations where wikified attributes would be useful that I think it would be worth looking at a way to implement them generically.

For example, using triple single quotes:

```
<$let a='''The colour is <<colour background>>'''>
```

Perhaps triple single quotes are a bit hard to read, but they would be unlikely to appear in existing wikis.

**Comment by Jermolene** [comment]
From my [post at Talk](https://talk.tiddlywiki.org/t/how-to-use-the-colour-macro-as-an-attribute-value/10051/13):

I just realised that we should be able to apply wikification to attributes that are specified as transclusions of variables or tiddlers (ie `attr=<<mything>>` or `attr={{anotherthing}}`.

So, rather then being triggered by a new type of quotation, it occurs to me that we might use a double equals sign to indicate wikification. For example:

```
<$let
   a=="The time is <<now>>"
   b==<<colour foreground>>
   c=={{MyToolTip}}
```

This approach would allow us to apply separate optimisations to each type of wikification, in particular we would be able to take advantage of the cached parse tree when transcoding variables or tiddlers.

**Comment by pmario** [comment]
>```
><$let
>   a=="The time is <<now>>"
>   b==<<colour foreground>>
>   c=={{MyToolTip}}
>```

I'm not so happy with the `==` sign used as an "assignment" indicator, because in many languages it is a "comparison" 

I think we should borrow the `:=` from Pascal as a new type of assignment. So it would not "clash" with C-like syntax definitions, as used by JavaScript. 

```
<$let
   a:="The time is <<now>>"
   b:=<<colour foreground>>
   c:={{MyToolTip}}
```
