### ISSUE TITLE
[IDEA] Make tagpicker respect sort order in its tagListFilter

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#8347]
The tagpicker features the `tagListFilter` parameter. This is great - but any user defined *sort order* in that filter is ignored and instead a hard coded alphabetical sorting is enforced (ref: https://github.com/Jermolene/TiddlyWiki5/issues/8346#issuecomment-2212395648 ). I wish user defined sort orders are accepted.

One example application that needs a custom sort order in the tagpicker dropdown is the [tag-categories](https://tag-categories.tiddlyhost.com/) plugin. Currently, "half" of this plugin does not function becuse of this problem. Another application I've always wanted is to make non-tag titles findable in the dropdown, but in a section separated from the tags.

**Describe alternatives you've considered**
I did test to make the tag-picker tags be flexbox items so their *order* can be set, but this messes up the navigation (which still follows the actual order), and it is not possible to show duplicates of a tag (which is desired in my application, because a tag can be assigned to multiple categories).

**Comment by twMat** [comment]
@pmario kindly gave a first [reply](https://github.com/Jermolene/TiddlyWiki5/issues/8346#issuecomment-2212398069) to this in another thread:

> The problem is, that at the moment that filter also bleeds into the keyboard handling. So there may be unknown side effects, if done poorly. So a lot more work will be needed.
> 
> https://github.com/Jermolene/TiddlyWiki5/blob/eeeb9f97a9b517f5ed76267bb50d4d141c72c251/core/wiki/macros/tag-picker.tid#L1-L6

**Comment by kookma** [comment]
Also see here: https://github.com/Jermolene/TiddlyWiki5/issues/8228

I like the idea by Jeremy here: https://github.com/Jermolene/TiddlyWiki5/issues/8228#issuecomment-2143756977

**Comment by pmario** [comment]
@twMat -- It seems `tagListFilter` sorting for the `tag-picker` macro can be done relatively straight forward -- Some more testing is needed.

@kookma -- Yours is a bit more complex. The tags.operator uses an Object to return results, for performance reasons. 

https://github.com/Jermolene/TiddlyWiki5/blob/eeeb9f97a9b517f5ed76267bb50d4d141c72c251/core/modules/filters/tags.js#L18-L28

The order of `Object,keys` can **not** be guaranteed with different browser vendors, depending on the EcmaScript version they support.

AND due to the spec of `Object.keys()` numbers will always be first. Eg: 
- If you add `a`, `c`, `b`,`10`, `1` in that order 
- `Object.keys()` will return `1`,`10`,`a`, `c`, `b`
- I'm not sure, what exactly happens, when we modify tags. eg: delete, add, add, delete and so on. 

On Stackoverflow there are some relevant posts about the exact JS-SPEC: [1](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) and [2](https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties) -- Where 2 is more important. 

Much more testing needed.

**Comment by pmario** [comment]
2 PRs are coming -- soon
