### ISSUE TITLE
Transclusion syntax for forcing block vs. inline mode

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#905]
The transclusion syntax `{{MyTiddler}}` results in a block mode transclusion when the syntax has been used in block mode, and an inline transclusion when the syntax has been used in inline mode. For example:

```
This transclusion will be in block mode:

{{MyTiddler}}

This transclusion will be in inline mode: {{MyTiddler}}
```

It is proposed to extend the syntax to allow the mode to be explicitly specified:

```
{block{MyTiddler}}

vs.

{inline{MyTiddler}}
```

**Comment by twMat** [comment]
```
{block{MyTiddler}}

vs.

{inline{MyTiddler}}
```

+1 but with the addition that *default* behaviour for `{{MyTiddler}}` should be what users and newcomers **likely expect**. It is reasonable to assume a user reasons like so:

*"the transclusion default behaviour should simply re-display MyTiddler as closely as possible"*.

This implies a *block* appearence even if I {{transclude}} in the line. Maybe this coudl be achieved using `inline-block`?

Thus, for MyTiddler including
```
foo

bar
```

...we get this {{MyTiddler}} appearence
```
...we get this foo

bar appearence
```

...but if you explicitly specify {inline{MyTiddler}} you get this appearence
```
...but if you specify foo bar you get this appearence
```

**Comment by Jermolene** [comment]
> Maybe this coudl be achieved using inline-block?

@twMat the inline vs. block issue is about whether or not the parser recognises block mode syntax like tables and headings. `inline-block` is about layout.

**Comment by pmario** [comment]
@Jermolene 
You are right: `inline-block` is also a CSS definition for `display` see: https://developer.mozilla.org/en-US/docs/Web/CSS/display

but that's probably not what @twMat meant??

**Comment by twMat** [comment]
>but that's probably not what @twMat meant??

You're of course right. The parser should recognize all the block mode syntax. But is my appendixed proposal above superflouos, i.e is it already implied in @Jermolene OP?

**Comment by tobibeer** [comment]
There could be the convention that while a default transclusion doesn't wrap content, defining classes does trigger that...

```
{.myclass block{foo}}
```

....not only force-interprets the content in block-mode but also wraps it in a `div` given "myclass" as a class.

Likewise...

```
{.myclass inline{foo}}
```
...would not only force-interpret content in inline-mode but also wrap it in a `span`  given "myclass" as a class.

These would not create any wrappers:

```
{block{foo}}
{inline{foo}}
```

**Comment by pmario** [comment]
What if `.myclass` defines `display:block` and the transclusion is defined that way`{.myclass inline{}}`. ... that's wrong. 

IMO there is a reason why CSS exists. It decouples the content from styling and we should not try to change that. 

So `{.myclass span{}}` may be ok for me. ... but `<span class="myclass">` is much clearer and not more to type. 

So in the end a new syntax would just create more complexity, for something that is already implemented, because we can use html syntax in wikitext if we really need to.

**Comment by tobibeer** [comment]
> What if .myclass defines display:block and the transclusion is defined that way{.myclass inline{}}. ... that's wrong.

As far as I can see, css and js allow to change containers dynamically from inline to block mode and back without replacing a presumably incorrect container. Otherwise, the browser would never allow to modify a block-level inline element to being inline or vice-versa.

**Comment by pmario** [comment]
@tobibeer 
You are right. My problem here is semantically and not technically here. 

Jeremy's OP was: 

```
{block{MyTiddler}}
vs.
{inline{MyTiddler}}
```

which is a shortcut for: 

```
<$transclude tiddler="MyTiddler" mode=block/>
vs
<$transclude tiddler="MyTiddler"/>
```

which creates this HTML

```
<p><p>test</p>
vs
test</p>
```

In my test case for the html `MyTiddler` contains the word `test` 
As you can see, for the `block` transclusion a `<p>` element was created. 
For the second `inline` transclusion __no covering element__ is created. So there is __no__ possibility to add a `class` because there is no wrapper element. So your proposal imo would create a very inconsistent behaviour. 

That's by intention, because we would get a hell lot of problems with the TW layout. (We actually had these problems in alpha and beta verrsion of TW.)

**Comment by tobibeer** [comment]
I don't understand, it would be quite clear that the syntax I proposed **does** create a wrapper. It would not create layout problems but help solve them where a wrapper is of need, as a user would specifically call for a wrapper to be applied.

You are well aware that I am **not** calling for transclusions to always be wrapped, right?

**Comment by pmario** [comment]
I didn't say, that I don't like the idea to have a wikitext version for "block mode transclusion". I want to have a consistent solution, that is easy to type and not error prone for the user. 

I think, we are not at this point yet. All suggestions we have imo are more complicated to understand, than just using html and the transclusion widget.

**Comment by pmario** [comment]
@Jermolene ... Did you consider the OP while developing #6666?

>It is proposed to extend the syntax to allow the mode to be explicitly specified:
>
>`{block{MyTiddler}}`
>
>vs.
>
>`{inline{MyTiddler}}`

**Comment by Jermolene** [comment]
Hi @Jermolene we added the `mode` attribute on the transclude widget in ecad2bf7a80784ab3c13b6294cb3b587c96c00f9 in February 2014. As it's turned out I don't think a shortcut syntax is warranted.

**Comment by pmario** [comment]
But not with the shortcut syntax eg: `{block{MyTiddler}}`

**Comment by Jermolene** [comment]
> But not with the shortcut syntax eg: `{block{MyTiddler}}`

Right, and the second part of the my post was to say that I don't think that a shortcut syntax is needed.
